### ISSUE TITLE
Why this package instead of react-native-splash-screen?

### ISSUE THREAD

**Issue by MoOx** [zoontek/react-native-bootsplash#1]
Real question that everybody is going to ask.
Exposing your motivation on why you created this module will probably answer this question :)

**Comment by zoontek** [comment]
@MoOx Good question! I added infos in the README: https://github.com/zoontek/react-native-bootsplash/blob/master/README.md#%EF%B8%8F%EF%B8%8F-comparaison-with-react-native-splash-screen 🙂

**Comment by youngjuning** [comment]
how to invoke show method in js
