### ISSUE TITLE
android.content.res.Resources$NotFoundException: Drawable org.package:drawable/bootsplash

### ISSUE THREAD

**Issue by giacomocerquone** [zoontek/react-native-bootsplash#10]
### 💻 My environment

- react-native-bootsplash version: 0.1.1
- react-native version: 0.60.4
- Platform: android
- OS version: 10
- Simulator: yes

### 🕵️‍♂️ Reproducing the issue

Trying to set up the module I obtain this error (found through logcat, the app won't even startup, it crash at the opening)
![image](https://user-images.githubusercontent.com/9303791/62425072-4302ed80-b6d7-11e9-96b3-1b50940afa0a.png)
But I do have the bootsplash.xml placed in the correct folder... what could it be?

And commenting this line in MainActivity.java:
`RNBootSplash.show(R.drawable.bootsplash, MainActivity.this);`

The app starts up but there is a white screen as splash.

PS: on ios it's working great

**Comment by giacomocerquone** [comment]
It is true that I renamed the android package (from org to com) but trust me, I've seen everywhere (and followed different guides), I even checked the R.java file and deleted and rebuilt the entire project, but nothing, can't understand why it doesn't find bootsplash.xml

**Comment by giacomocerquone** [comment]
JUst

**Comment by rarira** [comment]
exactly same error...
it works as expected right after I installed..
but suddenly the error happens.. and immediately crash.

- react-native-bootsplash version: 1.0.3
- react-native version: 0.61.5
- Platform: android
- OS version: 10
- Simulator: yes

**Comment by tmaly1980** [comment]
> Just for info, I influenced myself by the fact I had changed the package name, but actually it was throwing an error on the <bitmap tag.
> Don't know why but we cannot use the same mipmap resource that we use for the icon launcher! So I add to add another icon just for the splash

Can you clarify what you did? I'm running into this issue and not sure what to do.

**Comment by kbrandwijk** [comment]
I'm also running into the exact same error. What's the solution?

**Comment by MoOx** [comment]
If you get this issue with recent version of rn bootsplash, you probably forgot to replace .show by .init in your MainActivity java file :)
