### ISSUE TITLE
chalk@4.0.0 makes package require node v10

### ISSUE THREAD

**Issue by aserrabl** [zoontek/react-native-bootsplash#101]
### 💻 My environment

- react-native-bootsplash version: 2.2.3
- react-native version: 0.61.5
- Platform: both

### Reproducing the issue

Reinstalled dependencies in my project using node v8.17.0 and the last update of this package made made it incompatible. Is it really necessary to set the chalk dependency version to 4.0.0? 

Can be solved by fixing react-native-bootsplash to 2.1.1 though, but it would be nice to be able to update the package in the future.

**Comment by zoontek** [comment]
Which of your packages make the update impossible? Node 14.x juste came out, which means Node 10.x was 2 years ago.
