### ISSUE TITLE
Suggested features: choose different splash image on start and dispaly some text settled programatically

### ISSUE THREAD

**Issue by MykolaSauliak** [zoontek/react-native-bootsplash#102]
It will be cool if there is an opportunity to add some text, for example at the bottom of splash screen
Maybe it can be done through showing different images on start or just change view layout
I can try to make some pull requests

**Comment by zoontek** [comment]
@MykolaSauliak The CLI create a base, but you can edit your splash screen in Xcode / Android studio after that. I don't want the CLI generation to be complex and with a ton of options as the possibility are infinite.

**Comment by raajnadar** [comment]
But how can we add text drawable.xml does not allow text. I tried using layout file the app crashes on startup. @zoontek Can you provide an example for this?
