### ISSUE TITLE
White screen and deadlock warning.

### ISSUE THREAD

**Issue by micheilsgrey** [zoontek/react-native-bootsplash#103]
### 💻 My environment

- react-native-bootsplash version: ^2.2.3
- react-native version:~0.61.4
- Platform: iOS
- OS version: IOS 13.4
- Device: iPhone 11(13.4.1)
- Simulator: yes 
- Android Studio version: ?
- Android buildToolsVersion: ?
- Xcode version: 11.4.1

### 🕵️‍♂️ Reproducing the issue
I am not sure what i did wrong, but every time splash screen appears with white screen at the end. And. having warnings:
![Simulator Screen Shot - iPhone 11 - 2020-04-24 at 19 01 36](https://user-images.githubusercontent.com/8958040/80232789-22603680-865e-11ea-81c9-a652c26c4ca3.png)

My code 
in xcode:
```objectivec
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <UMCore/UMModuleRegistry.h>
#import <UMReactNativeAdapter/UMNativeModulesProxy.h>
#import <UMReactNativeAdapter/UMModuleRegistryAdapter.h>

#import "Orientation.h"

#import "RNBootSplash.h"

@implementation AppDelegate

@synthesize window = _window;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"lolApp" initialProperties:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];
  
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  NSArray<id<RCTBridgeModule>> *extraModules = [_moduleRegistryAdapter extraModulesForBridge:bridge];
  // You can inject any extra modules that you would like here, more information at:
  // https://facebook.github.io/react-native/docs/native-modules-ios.html#dependency-injection
  return extraModules;
}

- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
  return [Orientation getOrientation];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
#ifdef DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```
![Screenshot at Apr 24 19-47-16](https://user-images.githubusercontent.com/8958040/80236915-84bc3580-8664-11ea-880e-e0fff7ba0922.png)

react native:

```typescript
import 'react-native-gesture-handler'; // should be first import in App file
import React from 'react';
import MainNavigator from './src/screens/main/MainNavigator';
import { StatusBar } from 'react-native';
import { Provider } from 'react-redux';
import configureStore from './src/redux/store/store';
import { NavigationContainer } from '@react-navigation/native';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import RNBootSplash from "react-native-bootsplash";

const store = configureStore();

export default function App() {

//RNBootSplash.hide({ duration: 1000 });
RNBootSplash.hide();

  return (
    <Provider store={store}>
      <StatusBar backgroundColor='#133740' barStyle='light-content' />
      <SafeAreaProvider>
        <NavigationContainer>
          <MainNavigator />
        </NavigationContainer>
      </SafeAreaProvider>
    </Provider>
  );
}
```

gif with demo of white screen 
with duration: 
![2020-04-24 18 43 22](https://user-images.githubusercontent.com/8958040/80236082-4eca8180-8663-11ea-9b33-1cffc474b981.gif)
without duration: 
![2020-04-24 18 42 29](https://user-images.githubusercontent.com/8958040/80236126-60138e00-8663-11ea-9303-b01fe2f5692c.gif)

### 🤞Solution

I am noob in programming with react-native and javascript. Can anyone explain me what am i doing wrong?

**Comment by zoontek** [comment]
The white flash is related to this [race condition](https://stackoverflow.com/questions/28354756/presentviewcontroller-completion-block-called-too-soon).

I found a solution, but it creates a breaking change (the `hide` method should return a `Promise`)

**Comment by zoontek** [comment]
Try [2.2.4](https://github.com/zoontek/react-native-bootsplash/releases/tag/2.2.4)

**Comment by luancurti** [comment]
@micheilsgrey to fix the warning you need import `RCTDevLoadingView` on when you are in development mode and `RCT_DEV` is true try [this](https://github.com/facebook/react-native/issues/16376#issuecomment-350523177)

**Comment by micheilsgrey** [comment]
Right now i can not test new version on iOS but today i implement the android part and upadte to last version and this is what it looks like: 
![SplashAndroidtest2](https://user-images.githubusercontent.com/8958040/80273757-b1f8fa00-86dd-11ea-964c-f1625d3dc09c.gif)

I remove evrything from App.js thinking i just messed up something with my navigator( i am using `react-navigation` v5) or something else, code of app.js with this gif and android project code:

```typescript
import 'react-native-gesture-handler'; // should be first import in App file
import React from 'react';
import { View } from 'react-native';

import RNBootSplash from "react-native-bootsplash";

export default function App() {

  RNBootSplash.hide();
  
  return (
    <View style={{ flex: 1, backgroundColor: 'black' }}>
    </View>
  );
}

```

MainActivity: 

```java
package com.lolapp;

import android.os.Bundle; // <- add this necessary import
import com.facebook.react.ReactActivity;
import com.zoontek.rnbootsplash.RNBootSplash; // <- add this necessary import
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
import android.content.Intent; // <--- import
import android.content.res.Configuration; // <--- import

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "lolApp";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
    
    @Override
      public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        Intent intent = new Intent("onConfigurationChanged");
        intent.putExtra("newConfig", newConfig);
        this.sendBroadcast(intent);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        RNBootSplash.init(R.drawable.bootsplash, MainActivity.this); // <- display the generated bootsplash.xml drawable over our MainActivity
    }
}

```

styles: 

```xml
<resources>

    <!-- Base application theme -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Your base theme customization -->
    </style>

    <!-- Add the following lines -->
    <!-- BootTheme should inherit from AppTheme -->
    <style name="BootTheme" parent="AppTheme">
        <!-- set the generated bootsplash.xml drawable as activity background -->
        <item name="android:background">@drawable/bootsplash</item>
    </style>

</resources>
```

Manifest: 

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.lolapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <!-- OPTIONAL PERMISSIONS, REMOVE WHATEVER YOU DO NOT NEED -->
    <uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />
    <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.USE_FINGERPRINT" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

    <!-- These require runtime permissions on M -->
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />
    <!-- END OPTIONAL PERMISSIONS -->

    <application
        android:name=".MainApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:allowBackup="false"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustResize"
            android:screenOrientation="portrait"
            android:exported="true"
            tools:ignore="LockedOrientationActivity">
        </activity>

        <activity
            android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
            android:theme="@style/BootTheme"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

```

**Comment by zoontek** [comment]
@micheilsgrey Ohhhhhh I see it now. You have to run the `Bootsplash.hide` in a `useEffect` to ensure the App is mounted.

**Comment by zoontek** [comment]
Check the example: https://github.com/zoontek/react-native-bootsplash/blob/master/README.md#real-world-example

**Comment by micheilsgrey** [comment]
Since i am new to javascript and react, do i need change my whole class to function so i could use 'useEffect' ?

**Comment by zoontek** [comment]
It's not a class in example:

```js
export default function App() {
// …
}
```

If you use classes, `componentDidMount` is what you search.

**Comment by micheilsgrey** [comment]
> It's not a class in example:
> 
> ```js
> export default function App() {
> // …
> }
> ```
> 
> If you use classes, `componentDidMount` is what you search.

I see, thank you so much. I will try your advice soon.

**Comment by micheilsgrey** [comment]
@zoontek  thanks its actualy now working right with clear view without data. But if i use my navigation with redux i still having white screen so if i understand right i need somehow to detect when is actualy my navigation is ready to show on screen and i have no idea how can i listen to my navigation when its ready... I dont know do i messed up with `redux `or its just normal behavior of `react-navigation`. And one more question, how can i change the color of status bar during splash screen in ios and android ? I set status bar color in my App.js, did i do it in wrong place? Because color of status bar changes only when my navigation is ready to show on screen. I add 1 second timeout for splash screen, but this is terrible workaround. Here is demo gif: 
![splashTimeoutTest](https://user-images.githubusercontent.com/8958040/80308681-ef8e7d80-87d8-11ea-9606-bc7454e32b76.gif)

Here i set status bar : 

```typescript
const store = configureStore();

export default function App() {

React.useEffect(() => {
  setTimeout(() => {  
    RNBootSplash.hide();
 },1000);
  }, []);

  return (
    <Provider store={store}>
      <StatusBar backgroundColor='#133740' barStyle='light-content' />
      <SafeAreaProvider>
        <NavigationContainer>
          <MainNavigator />
        </NavigationContainer>
      </SafeAreaProvider>
    </Provider>
  );
}


```

**Comment by zoontek** [comment]
React Navigation emit events: https://reactnavigation.org/docs/navigation-events

**Comment by bashen1** [comment]
@zoontek 
App icon click
LaunchScreen(info.plist)
White screen                        <===== //the issue
didFinishLaunchingWithOptions(RNBootSplash)
LaunchScreen
hide LaunchScreen

**Comment by kashmiry** [comment]
> Check the example: https://github.com/zoontek/react-native-bootsplash/blob/master/README.md#real-world-example
> 
> ```js
> import 'react-native-gesture-handler'; // should be first import in App file
> import React from 'react';
> import { View } from 'react-native';
> 
> import RNBootSplash from "react-native-bootsplash";
> 
> export default function App() {
>   React.useEffect(() => {
>     RNBootSplash.hide();
>   }, []);
>   
>   return (
>     <View style={{ flex: 1, backgroundColor: 'black' }}>
>     </View>
>   );
> }
> ```
> 
> And the [React documentation](https://reactjs.org/docs/hooks-effect.html):
> 
> > What does useEffect do? By using this Hook, you tell React that your component needs to do something after render.
> 
> This is what you want to do: hiding the splash screen once the initial content has been rendered 🙂

I use React Navigation too, and what I did is this, in my App Navigator file (NavigationContainer functional component) added this.
```
        //Navigation Mounted
        React.useEffect(() => {
            //fade out splashscreen
            RNBootSplash.hide({ duration: 250 });
        }, []);
```
Now it will hide when the navigation have been mounted.

**Comment by micheilsgrey** [comment]
> > Check the example: https://github.com/zoontek/react-native-bootsplash/blob/master/README.md#real-world-example
> > ```js
> > import 'react-native-gesture-handler'; // should be first import in App file
> > import React from 'react';
> > import { View } from 'react-native';
> > 
> > import RNBootSplash from "react-native-bootsplash";
> > 
> > export default function App() {
> >   React.useEffect(() => {
> >     RNBootSplash.hide();
> >   }, []);
> >   
> >   return (
> >     <View style={{ flex: 1, backgroundColor: 'black' }}>
> >     </View>
> >   );
> > }
> > ```
> > 
> > 
> > And the [React documentation](https://reactjs.org/docs/hooks-effect.html):
> > > What does useEffect do? By using this Hook, you tell React that your component needs to do something after render.
> > 
> > 
> > This is what you want to do: hiding the splash screen once the initial content has been rendered 🙂
> 
> I use React Navigation too, and what I did is this, in my App Navigator file (NavigationContainer functional component) added this.
> 
> ```
>         //Navigation Mounted
>         React.useEffect(() => {
>             //fade out splashscreen
>             RNBootSplash.hide({ duration: 250 });
>         }, []);
> ```
> 
> Now it will hide when the navigation have been mounted.

Thanks, I will try this way, but for now, I was just delaying the screen for 1 sec, temporary hack.

```typescript
  React.useEffect(() => {
    setTimeout(() => {
      RNBootSplash.hide();
    }, 1000);
  }, []);
```

**Comment by drb1** [comment]
"react-native-bootsplash": "2.2.5",

still white screen appears when initially loading app

**Comment by anastely** [comment]
Hey @zoontek, the `duration` number it's in millie second or what?
because I set it `50` but it takes a too long time to hide?

**Comment by zoontek** [comment]
@anastely It's the duration of the fade animation, not of the hiding process.

**Comment by anastely** [comment]
Uh, But why it takes a long time to hide in android! unlike ios its work as expected!

**Comment by anastely** [comment]
@zoontek Uh well, But why it takes a long time to hide splash in android! unlike ios its work as expected!

**Comment by micheilsgrey** [comment]
> @zoontek Uh well, But why it takes a long time to hide splash in android! unlike ios its work as expected!

Overall I'm having all way too slow in android in thinking its the difference in systems and optimization issues.

**Comment by anastely** [comment]
> > @zoontek Uh well, But why it takes a long time to hide splash in android! unlike ios its work as expected!
> 
> Overall I'm having all way too slow in android in thinking its the difference in systems and optimization issues.

I do not mean to offend :) but I was using `react-native-splash-screen` in some of the projects before and its work well,  but I use this package it's so easy in installation, etc,  I guess there a something @zoontek miss!

**Comment by zoontek** [comment]
@anastely Android animations don't perform well, and `50ms` is way too low for any kind of animation in general. I recommend `220ms`, like Android `config_activityDefaultDur` value.
