### ISSUE TITLE
React logo on startup

### ISSUE THREAD

**Issue by amirmcs** [zoontek/react-native-bootsplash#105]
I just downloaded and followed the instructions the splash screen works great (thanks for making it so easy to addscreen.).  
I see react logo on startup breifly even though  I replaced all the files in "Assets" folder and in iOS images.xcassets folder.  Now when I load the app I see first react logo then it replaces with the logo I created.

Where is the image file for the very first react logo displayed on screen. I tried clearing build and starting again.

**Comment by zoontek** [comment]
@amirmcs Related issue: https://github.com/zoontek/react-native-bootsplash/issues/48
This is probably related to the Spotlight cache on device. Uninstall your app, restart your phone. Then clean your Xcode project, build it again.

https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update

**Comment by amirmcs** [comment]
It worked. Thanks for quick reply
