### ISSUE TITLE
[Android] shows blank screen for short time when opened from Linking

### ISSUE THREAD

**Issue by panda0603** [zoontek/react-native-bootsplash#108]
Hi, 

Splash screen shows/hides perfectly fine when opened normally from app drawer. 

However when app is opened(initially app is not running) using linking, 
(on android when you click on a link and didn't set default app to open, you get to choose which app to open the link with) 

splash screen shows -> blank white screen for short time(0.5 sec?) -> shows splash screen again -> then hides. 

Not sure if this is actually related to bootsplash, but since related to splash screen, I am posting the issue here. 

### 💻 My environment

- react-native-bootsplash version: 2.2.4
- react-native version: 0.61.5
- Platform:android
- OS version: 10.14
- Device: android pixel 2
- Simulator: simulator and real device

**Comment by zoontek** [comment]
@panda0603 Hi. Did you follow the guide? https://github.com/zoontek/react-native-bootsplash#handle-deep-linking-on-android

**Comment by panda0603** [comment]
@zoontek Thanks for the reply. 
```
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustPan"
        android:launchMode="singleTask"
        android:exported="true">
      </activity>

      <activity
      android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
      android:theme="@style/BootTheme"> 
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>

        <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="http" />
          <data android:scheme="https" />
        </intent-filter>
     </activity>
```
Yes, this is my manifest at the moment. Anything I am missing?

**Comment by panda0603** [comment]
adding android:launchMode="singleTask" solved the problem. Thanks
