### ISSUE TITLE
Cannot resolve symbol zoontek

### ISSUE THREAD

**Issue by andreiradoi** [zoontek/react-native-bootsplash#110]
**Versions:**
react-native: "0.62.2",
react-native-bootsplash: "^2.2.4"
Android studio 3.6.3
buildToolsVersion: 28.0.3

**Code** 
import com.zoontek.rnbootsplash.RNBootSplash;

**Error message**
Cannot resolve symbol zoontek

Tried the manual installation as well, without success.

**Comment by zoontek** [comment]
@andreiradoi Hi. Please provide **more** code. It's not enough context.

**Comment by andreiradoi** [comment]
Hi,

// MainActivity.java
`package com.appName;

import android.os.Bundle;
import com.facebook.react.ReactActivity;
import com.zoontek.rnbootsplash.RNBootSplash; -> this line throws error

public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "AppName";
  }

   @Override
    protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      RNBootSplash.init(R.drawable.launch, MainActivity.this);
    }
}
`

**Comment by zoontek** [comment]
Run `./gradlew clean` in your android directory.

**Comment by andreiradoi** [comment]
./gradlew clean along with Android Studio restart seems have fixed it.

Thank you!

**Comment by cecodor** [comment]
Having the same problem, gradlew clean did not worked for me :(

![image](https://user-images.githubusercontent.com/23288172/82843219-1c01ec00-9ea2-11ea-9a2d-a5d24659fb14.png)

**Comment by cecodor** [comment]
I finally solve it by updating the gradle plugin (Android Studio suggested this) and later I had to do this: https://stackoverflow.com/a/49645970/7090275, now its working
