### ISSUE TITLE
Release build stuck at splash screen but work fine in debug

### ISSUE THREAD

**Issue by imYashGupta** [zoontek/react-native-bootsplash#111]
Hi, so i was trying to add the splash screen in my app and follow the installation in debug it work as expected but when i release the signed APK the app stuck at splash screen , i was using codepush and react navigation i thought it was due code-push so i create the fresh installation  and try without it the same happen everything work on debug mode but when i create the release it stuck on splash.

i am using actual android device for testing but i tried in android emulator the release apps crash there. 

### 💻 My environment

- react-native-bootsplash version:"^2.2.4"
- react-native version: "0.62.2",
- Platform:  android 
- OS version: 10
- Device: oneplus 7 
- Simulator: no

### 🕵️‍♂️ Reproducing the issue

to create the build i was using: 
`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
`
and in android:
`./gradlew assembleRelease -x bundleReleaseJsAndAssets`

here is code https://github.com/imYashGupta/rn-splashscreen

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37147192/82090232-d2333c00-9712-11ea-8eeb-e888bf3374c0.gif)

**Comment by zoontek** [comment]
Thanks for the repository, I successfully reproduce your issue. But the state of your assets bugs me a little…

You have missing assets in mdpi size: https://github.com/imYashGupta/rn-splashscreen/tree/master/android/app/src/main/res/drawable-mdpi

**And less importantly, but:**
- A raw directory with your `app.json`: https://github.com/imYashGupta/rn-splashscreen/tree/master/android/app/src/main/res/raw ?
- You output your bundle manually: https://github.com/imYashGupta/rn-splashscreen/tree/master/android/app/src/main/assets
- You probably ran the CLI on an image which is too small: https://github.com/imYashGupta/rn-splashscreen/blob/master/android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png

I cleaned-up the `*.iml` files and all of these to keep:

<img width="297" alt="Screenshot 2020-05-16 at 12 15 19" src="https://user-images.githubusercontent.com/1902323/82117196-f7559800-976e-11ea-99f6-3c2c0b95ec29.png">

Then ran `./gradlew clean && ./gradlew installRelease`, and everything went back to order:

![20200516_120714](https://user-images.githubusercontent.com/1902323/82117455-45b76680-9770-11ea-8a7e-e7313db1f88c.gif)

**Comment by imYashGupta** [comment]
Thank you @zoontek , my app is back to track now and i've noticed that the raw directory in my app created when i run the cmd `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res` and this also added the drawable-x folders.

in my app i am also using react-navigation and other packages so deleting this folder crashes the app so this helped me there https://stackoverflow.com/questions/47084810/react-native-android-duplicate-file-error-when-generating-apk/52750886#52750886.

once again thank you!!
