### ISSUE TITLE
[ASK] How to create custom xml layout in Android?

### ISSUE THREAD

**Issue by rinoarmadiaz** [zoontek/react-native-bootsplash#112]
Hello, i've managed to setup the splash using the guide.

but my case are need to have 3 separate View (background, top image & text) 

i need to use my custom layout, how to use it? thanks!

**Comment by zoontek** [comment]
Hello. You can't use a custom layout, but `bootsplash.xml` is using a `layer-list`. I would recommend reading the Drawable resource documentation: https://developer.android.com/guide/topics/resources/drawable-resource#LayerList

**Comment by giacomocerquone** [comment]
ok here the reason why imageview won't work, right?

**Comment by r0b0t3d** [comment]
Poor me that my application can't use layer-list to build a splash screen. But I really love this library and want to use it. So I did some modification to allow this library accept a custom xml with this [patch](https://gist.github.com/r0b0t3d/1877de009cc2741900e67ded0b26d927)
So instead of calling
```
    RNBootSplash.init(R.drawable.bootsplash, MainActivity.this); // <- display the generated bootsplash.xml drawable over our MainActivity

```
You can call
```
RNBootSplash.initLayout(R.layout.splash_screen, MainActivity.this);
```
And remember to keep `MainActivity` as the entry point
```
        <activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

**Comment by zoontek** [comment]
@r0b0t3d I'm pretty sure a change like this will result in this regression: https://github.com/zoontek/react-native-bootsplash/pull/57#issuecomment-581170465

**Comment by r0b0t3d** [comment]
Sure, it will has a blank screen at start if using xml layout. It is a trade-off for anyone that can't use drawable like me. Again, this is just an option

**Comment by EhsanSarshar** [comment]
@zoontek react-native-splash-screen have a solution for it. so I should use this library for ios and use that for android

**Comment by zoontek** [comment]
@EhsanSarshar Splash screen can't have their own layout. See the regressions it creates: https://github.com/zoontek/react-native-bootsplash/pull/57 (same on react-native-splash-screen)

**Comment by EhsanSarshar** [comment]
@zoontek what's wrong for having a seperate screen for splash. 
ok no need to use react-native-splash the solution of @r0b0t3d worked for me. and it also don't have any white screen at startup

**Comment by zoontek** [comment]
@EhsanSarshar Cool, use that then 🙂
