### ISSUE TITLE
[ios] Launch screen jumps around

### ISSUE THREAD

**Issue by aiba** [zoontek/react-native-bootsplash#113]
Per the README, I added added `RNBootSplash.initWithStoryboard` to the suggested location:

```obj-c
self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
UIViewController *rootViewController = [UIViewController new];
rootViewController.view = rootView;
[RNBootSplash initWithStoryboard:@"SplashScreen" rootView:rootView];   // <---------- jumps around
self.window.rootViewController = rootViewController;
[self.window makeKeyAndVisible];
return YES;
```

But that resulted in the launch screen jumping around as the app opened.

When I moved the init call to the bottom of the function, it works perfectly:

```obj-c
self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
UIViewController *rootViewController = [UIViewController new];
rootViewController.view = rootView;
self.window.rootViewController = rootViewController;
[self.window makeKeyAndVisible];
[RNBootSplash initWithStoryboard:@"SplashScreen" rootView:rootView];   // <---------- works perfectly
return YES;
```

Is this expected?  I'm just wondering if we should update the README so others can avoid the jumping launch screen as well.

### 💻 My environment

- react-native-bootsplash version: 2.2.4
- react-native version: 0.62.2
- Platform: ios
- OS version: macos 10.15.4
- Device: all
- Simulator: yes
- Xcode version: 11.5

**Comment by zoontek** [comment]
That's not supposed to make a difference, and I personally never see a jump.

Could you create a video capture?

**Comment by Fan** [comment]
Was having the same issue. Moving to the bottom solved it for me too!

**Comment by zoontek** [comment]
@Fan Good to know. We could move it in the documentation / example.
The current implementation rely on rootView loadingView, so it's without consequences.

**Comment by zoontek** [comment]
Closed by https://github.com/zoontek/react-native-bootsplash/pull/114
Thanks, @Fan

**Comment by Magudeshwaran** [comment]
> Was having the same issue. Moving to the bottom solved it for me too!

Can you explain bro ?
