### ISSUE TITLE
npx generate-bootsplash gives 404

### ISSUE THREAD

**Issue by giacomocerquone** [zoontek/react-native-bootsplash#115]
Hi, npx generate-bootsplash gives 404.
Should the README be updated with some other package name or what?

Thanks for the awesome work!

**Comment by zoontek** [comment]
@giacomocerquone Do you have installed the package before?

**Comment by giacomocerquone** [comment]
absolutely yes, the package is installed and I lastly ended up creating the splash myself!
I'll paste npm, node and react native info

**Comment by zoontek** [comment]
Which version of npx do you use?

**Comment by giacomocerquone** [comment]
yes, I'm truly sorry and very happy and grateful to see such a fast response!
I was using an old version of the package, damn... I've never found an npm command that shows me the outdated packages, do you know one? Specifically, it should look for major version changes too

**Comment by zoontek** [comment]
`npm / yarn outdated` does that (including major versions)

**Comment by giacomocerquone** [comment]
Yeah I knew that command, but most of the times it misses results in windows... should dig into it!

Thanks so much, are you on some site I can donate just once instead of a subscription? Something like buy me a coffee

**Comment by zoontek** [comment]
@giacomocerquone Not really, but if you want to send a one time shot, I have a Paypal, this could do the trick: zoontek[at]gmail[dot]com 🙂

**Comment by giacomocerquone** [comment]
Done, thank you again!
