### ISSUE TITLE
Feature request: Do not show splashscreen through a flag on particular variants/flavors

### ISSUE THREAD

**Issue by afilp** [zoontek/react-native-bootsplash#118]
Our app has many flavors (Android) and schemes (iOS).

Not all flavors should have a splash screen. How can we not show the splash screen on some of them?

For example, I manage to do this on the react-native side through this flag:
`buildConfigField 'boolean', 'HAS_SPLASHSCREEN', 'true'`

And then in JS:
```
import BuildConfig from 'react-native-build-config';

if (BuildConfig.HAS_SPLASHSCREEN) {
      // do stuff while splash screen is shown
      // After having done stuff (such as async tasks) hide the splash screen
      const SplashScreen = require('react-native-bootsplash').default;
      setTimeout(() => {
        SplashScreen.hide({ duration: 200 });
      }, 1400);
    }
```

But this only works in the JS side, splash screen images are still needed for the Android side. I had to use "transparent" images for this, since there is code in the Android side that I do not know how to make it conditional.

I tried to use an `IF` here but it did not work:
```
public class MainActivity extends ReactActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    if (BuildConfig.HAS_SPLASHSCREEN) {
      RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
    }
  }
```

Is there any way to do this?

Thank you!

**Comment by zoontek** [comment]
- Only set the BootTheme on wanted flavors (`android/app/src/FLAVOR/res/values/styles.xml`).
- Test in Java the value of `BuildConfig.FLAVOR`

Sorry, I'm closing this. This is not really an issue with the library, more a question about Android development in general.
