### ISSUE TITLE
Does this support react-native-navigation's way ?

### ISSUE THREAD

**Issue by Tracklous** [zoontek/react-native-bootsplash#12]
### 💻 My environment

- react-native-bootsplash version: 0.1.1
- react-native version: 0.60.4
- Platform: both
- OS version: Mojave
- Device: iphone 8 simulator
- Simulator: yes 
- Android Studio version: 3.4.x
- Xcode version: 10.3
- React-native-navigation: v3 Alpha 11

### 🕵️‍♂️ Issue is splash screen fluctuates once when JS screen gets mounted
I followed all the steps you have mentioned but i'm not be able to achieve the smooth splash experience. I'm using react-native-navigation is this creating the problem? Whats happening right now is  whenever i do load my app native splash shows on the screen but fluctuates once when javascript screen mounted. Please guide me further.

I'm guessing this is something to do with react native navigation. If yes then how can i achieve same results. Looking forward for your response. Thanks!

**Comment by zabojad** [comment]
@Tracklous have you found a solution?
