### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by Faisal-Manzer** [zoontek/react-native-bootsplash#120]
### 💻 My environment

- react-native-bootsplash version: 2.2.4
- react-native version: 0.62.2
- Platform: MacOS
- OS version: MacOs Catalina 10.15.3
- Device: Apple MacbookAir
- Simulator: no
- Android Studio version: ?
- Android buildToolsVersion: ?
- Xcode version: ?

### 🕵️‍♂️ Reproducing the issue
```bash
git clone https://github.com/zoontek/react-native-bootsplash
cd react-native-bootsplash
cd example
yarn install
cd ios && pod install && cd -
```
Try starting MacOS project with https://microsoft.github.io/react-native-windows/docs/rnm-getting-started

```bash
npx react-native-macos-init
```

### Error
```
[!] The platform of the target `react-native-bootsplash-example-macOS` (macOS 10.14) is not compatible with `RNBootSplash (2.2.4)`, which does not support `macOS`.

```

### Feature request
macOS support for react-native is in beta. It would be great if this library can support macOS also in conjunction with iOS and Android.

**Comment by zoontek** [comment]
I don't know a lot of desktop apps which use splash screens. I'm not sure I'll add windows / macOS support anytime soon, but I will accept pull requests 🙂

**Comment by Faisal-Manzer** [comment]
The problem is actually not `macOS` support. Problem is that 100% production applications on Android or iOS will need a splash screen. If anyone wants to port their app to `macOS` the package will break that just like above. I haven't tried windows so I can't speak on that.

**Comment by zoontek** [comment]
React Native CLI allows you to avoid linking on unsupported platforms:

```
// react-native.config.js
module.exports = {
  dependencies: {
    "react-native-bootsplash": {
      platforms: {
        macos: null,
        windows: null,
      },
    },
  },
};
```
