### ISSUE TITLE
RNBootSplash.hide() stuck ISSUE

### ISSUE THREAD

**Issue by David-moonsite** [zoontek/react-native-bootsplash#122]
👋 Hello!

### 💻 My environment

- react-native-bootsplash version:^2.2.4
- react-native version:0.60.5
- Platform: both
- OS version: macOS Catalina 10.15.5
- Device: both
- Simulator: both
- Android Studio version: 3.1
- Android buildToolsVersion: 28.0.3
- Xcode version: 11.4.1

### 🕵️‍♂️ Reproducing the issue

When I run in a physical device or on simulator ,there's a problem. The app launches and gets stuck on the React Native splash screen. What's the cause of this and how can I prevent it?
i did exactly step by step in README.md

**Comment by zoontek** [comment]
Where did you call the `hide()` method? Please copy JS code her.

**Comment by David-moonsite** [comment]
<img width="538" alt="Screen Shot 2020-06-15 at 11 27 17" src="https://user-images.githubusercontent.com/58983212/84635027-512ab880-aefb-11ea-99cd-67ef90e4b92b.png">

**Comment by zoontek** [comment]
Check the exception in Xcode: The file Bootsplash.storyboard simply doesn't exist in your project.

**Comment by zoontek** [comment]
Check the part where you have to drag and drop the file: https://github.com/zoontek/react-native-bootsplash/blob/master/README.md#ios-1 (with the 3 screenshots)

**Comment by David-moonsite** [comment]
Thanks !
