### ISSUE TITLE
Feature Request: Store whether the Splashscreen is hidden or not

### ISSUE THREAD

**Issue by maitham** [zoontek/react-native-bootsplash#124]
hey thanks for the awesome work with this library. I was wondering if there were plans to support storing the visible state within the RNBootSplash component? This way we can query whether the bootsplash is open or not. Currently doing this via usestate and react context. It would be handy if this was already part of the library. Any thoughts on this?

**Comment by zoontek** [comment]
It's planned, I need to find some time to polish the next version and release it 🙂

**Comment by zoontek** [comment]
@maitham This is available on the 3.0.0 alpha! Please give it a try: https://github.com/zoontek/react-native-bootsplash/tree/3.0.0
