### ISSUE TITLE
Show View as overlay of Bootsplash

### ISSUE THREAD

**Issue by radeno** [zoontek/react-native-bootsplash#126]
Hi,

At first, thank you for great work that you are doing for this package!

I have a question about showing RN component on top of Bootsplash.
Is there any possibility of how to do that?

For example, sometimes it takes much time until the app is completely loaded (because actions on background/foreground), and this time should be multiplicated on older devices. And the good user experience is to show "loader" (ActivityIndicator) as a simple component above splashscreen.

Of course, I have multiple ways how to do that:
- Create RN splashscreen component and then add ActivityIndicator. Disadvantage of this solution is duplicate whole iOS/Android Splashsreen on RN side.
- Add "activity indicator" into ios storyboard / android drawable. Disadvantage is that indicator is visible from the first moment, but it takes some time until is animated(rotated)

Any hint how to do that?

Regards!

**Comment by zoontek** [comment]
@radeno Hi.

> Create RN splashscreen component and then add ActivityIndicator. Disadvantage of this solution is duplicate whole iOS/Android Splashsreen on RN side.

Is the recommended solution. It's even the one used for the example (with the Animated React logo): https://github.com/zoontek/react-native-bootsplash/blob/master/example/App.js

The other one will not be implemented because it would make it too difficult to create identical splash screen across platforms.

**Comment by radeno** [comment]
@zoontek thanks for your reply.
I thought that I must duplicate splashscreen functionality into RN side. Sadly there must be implemented 3 same things.
Anyway thanks!

**Comment by zoontek** [comment]
That's not really an issue for me since the CLI takes care of Android and iOS for you. If your splash screen has a very complex layout, I encourage you to keep it simple, animate details in on load.
