### ISSUE TITLE
Unexpected files included in npmjs distribution

### ISSUE THREAD

**Issue by mikehardy** [zoontek/react-native-bootsplash#127]
When you look at the files included in the distribution on npmjs it is clear some are development files and shouldn't be there

./android/idea
./android/**/*iml
./android/.gradle
yarn-error.log

I had a similar problem - because it's really confusing to get correct! https://github.com/react-native-community/react-native-device-info/pull/872

Once it is understood though, it's not hard to fix, for example: https://github.com/th3rdwave/react-native-safe-area-context/pull/41/files

Interested in a fix up here?

**Comment by zoontek** [comment]
An easy fix is indeed to move to a whitelist instead of npmignore: https://github.com/react-native-community/react-native-permissions/blob/master/package.json#L21

Totally interested!

**Comment by mikehardy** [comment]
PR posted, took me way less time to post that then you saved me in the .xib -> storyboard migration even though I had to de-integrate react-native-splash-screen first, sincere thanks @zoontek
