### ISSUE TITLE
Question about naming conventions

### ISSUE THREAD

**Issue by TheWirv** [zoontek/react-native-bootsplash#129]
### 💻 My environment

- react-native-bootsplash version: none
- react-native version: v0.63.0-rc.1
- Platform: both
- OS version: irrelevant
- Device: none
- Simulator: irrelevant
- Android Studio version: irrelevant
- Android buildToolsVersion: irrelevant
- Xcode version: 11.5

Hi, I was just curious. Do I understand it correctly that it is required to name the storyboard file `BootSplash.storyboard`? Because I am currently using [React Native Splash Screen](https://github.com/crazycodeboy/react-native-splash-screen)  (I even had to switch to the `master` branch because the package hasn't seen an npm release in almost 1.5 years) and I am thinking about using this package instead. My only problem is: I am basically building multiple almost identical apps using one single code base. The differences I manage using [React Native Ultimate Config](https://github.com/search?q=react-native-ultimate-config) and of course every app has its own splash screen. And that means that I provide the launch screen parameter like this:
```
<key>UILaunchStoryboardName</key>
<string>LaunchScreen$(BUNDLE_ID_SUFFIX).storyboard</string>
```
Then, obviously I have multiple storyboards, one for each individual app.

Would this, or a similar, configuration work with this package?

**Comment by zoontek** [comment]
Hi. No, it's just the default name when you generate the file from the CLI.
If you want to name `LaunchScreenXXX.storyboard` and keep your config, it's totally OK.

The next version will probably switch to `LaunchScreen.storyboard` by default anyway, since RN 0.63 will ship with this file. It will avoid some Xcode configuration when you add this package to your project.

**Comment by TheWirv** [comment]
Sounds awesome, thanks for the quick reply!
