### ISSUE TITLE
Feature request: react-native-navigation support

### ISSUE THREAD

**Issue by Tracklous** [zoontek/react-native-bootsplash#13]
### 💻 My environment

- react-native-bootsplash version: 0.1.1
- react-native version: 0.60.4
- Platform:  Both
- OS version: IOS 12.3 / Android Pie
- Device: Iphone 8 simulator
- Simulator: yes 
- Android Studio version: 3.4.x
- Xcode version: 10.3
- React-Native-Navigation: V3 Alpha 11

### 🕵️‍♂️ Issue is splash screen fluctuates once when JS screen gets mounted..
I followed all your steps but its still happening. Please let me know what to do. I'm using react native navigation. I'm guessing due to react-native-navigation this is happening. Please let me know how to deal with it. Looking forward for your response. Thanks!

**Comment by MoOx** [comment]
Seems to be a dup of #12

**Comment by zoontek** [comment]
No, it does not. `react-native-navigation` system is too complex and too different from classic RN native view handling.

**Comment by Tracklous** [comment]
Yah! but then how react-native-splash-screen works well with RNN also ?? Is your lib way diff. than react-native-splash-screen implementation ??

**Comment by zoontek** [comment]
@Tracklous Yes, the implementation is different. I'll take a look at react-native-navigation and see if I can create instructions for it.

**Comment by vorasudh** [comment]
I have same problem. I am using React Native Router Flux which is based on React-Navigation.

**Comment by zoontek** [comment]
@maxKimoby If it's happen with react-navigation (only JS lib), you surely missed a step in the install guide

**Comment by rabanos-rvc** [comment]
up

**Comment by vorasudh** [comment]
> @maxKimoby If it's happen with react-navigation (only JS lib), you surely missed a step in the install guide

Which step do you think is missed?

**Comment by vinurs** [comment]
is there any solution for this

**Comment by zoontek** [comment]
@vinurs Didn't have the time to check, as I'm not using `react-native-navigation`. I would be happy if someone can help on this.

**Comment by kevinranks** [comment]
Hope someone can help with this!

**Comment by MatthewPattell** [comment]
Hello everyone.
[Try my hot fix](https://github.com/MatthewPattell/react-native-bootsplash/tree/independent-splash)

See README.md for details.

**Comment by rtman** [comment]
@MatthewPattell @zoontek any chance we can get a fix for this?

**Comment by ninjz** [comment]
@MatthewPattell Thanks, this hotfix worked for me. Please submit a PR!

**Comment by zoontek** [comment]
I studied the case a bit and the solution provided in https://github.com/zoontek/react-native-bootsplash/pull/49 does not suit me: it creates a bunch of usages issues.
I'm closing this and added a warning in the `README`: https://github.com/zoontek/react-native-bootsplash/commit/35cdf62cf2c4cf9cee73d1a8cad457fbf8d31c68

**Comment by zoontek** [comment]
I have not tested it yet, but version `2.0.2` should supports `react-native-navigation` just fine: https://github.com/zoontek/react-native-bootsplash/releases/tag/2.0.2

**Comment by olegdev** [comment]
Please provide some instructions of how to.. thnx

**Comment by arun057** [comment]
Any updates here?

**Comment by thobiasn** [comment]
Can you provide an updated example of how to configure `AppDelegate.m` while using `react-native-navigation`?

**Comment by DovletAmanov** [comment]
Is there any instructions to implement this lib alongside with `react-native-navigation`? Thanks in advance.

**Comment by mikepaszkiewicz** [comment]
@zoontek Is there a guide for how to do this in version 2.0.2? Thanks in advance!

**Comment by kiran-kumar011** [comment]
@zoontek does it supports [@react-navigation/native](https://www.npmjs.com/package/@react-navigation/native) and [@react-navigation/stack](https://www.npmjs.com/package/@react-navigation/stack).

let me know how to make this work with the above packages because i'm not using react-native-navigation.

**Comment by MoOx** [comment]
@kiran-kumar011 it just work with react-navigation without any particular setup (just follow the readme).

**Comment by todorone** [comment]
> I have not tested it yet, but version 2.0.2 should supports react-native-navigation just fine: https://github.com/zoontek/react-native-bootsplash/releases/tag/2.0.2

Hi @zoontek 

It's not clear how to initialize RNBootsplash. When using RNN, we don't have access to `rootView`, so we can't call:
`[RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];`

Can we make somehow `rootView` parameter optional to make it work with RNN?

Thanks.

**Comment by ghiculescualexandru** [comment]
@todorone Have you managed to initialize it?

**Comment by todorone** [comment]
@ghiculescualexandru Unfortunately, no. Seems it does not work well with RNN.

**Comment by zoontek** [comment]
@todorone @ghiculescualexandru Unfortunately `react-native-navigation` is not "standard" `react-native`. They don't expose their created `RCTRootView`.

There's an issue on their side: https://github.com/wix/react-native-navigation/issues/6535
And also an open discussion about Android SplashsScreen API: https://github.com/wix/react-native-navigation/discussions/7363

It seems they have an (undocumented) splash screen implem on iOS:
- https://github.com/wix/react-native-navigation/blob/master/lib/ios/RNNSplashScreen.m
- https://github.com/wix/react-native-navigation/blob/master/lib/ios/ReactNativeNavigation.m#L65

```objc
RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
[ReactNativeNavigation bootstrapWithBridge:bridge]; // <- should show their RNNSplashScreen
```

I personally recommend switching to `react-navigation` v6 + `@react-navigation/native-stack` (using `react-native-screens`). Native navigation without the clunkyness.
