### ISSUE TITLE
New feature android 

### ISSUE THREAD

**Issue by maystrenkoYurii** [zoontek/react-native-bootsplash#130]
👋 Hello!

Add please new feature only initDrawable method  and  method show() set as public. My fix Xaiomi jumping image))
<img width="973" alt="Снимок экрана 2020-07-08 в 14 02 33" src="https://user-images.githubusercontent.com/23016311/86911418-f5330880-c123-11ea-8b0a-f5764fba22fc.png">

**Comment by zoontek** [comment]
This does not work like this. Check https://github.com/zoontek/react-native-bootsplash/issues/52#issuecomment-580366701 for a fix.

**Comment by maystrenkoYurii** [comment]
@zoontek work my solution. I not show image in preview. I have animate images after show
<img width="548" alt="Снимок экрана 2020-07-08 в 15 32 52" src="https://user-images.githubusercontent.com/23016311/86919096-5a8cf680-c130-11ea-8f9a-51ef18f3f2a2.png">
![animation](https://user-images.githubusercontent.com/23016311/86919182-814b2d00-c130-11ea-81ce-3a7e0645a22c.gif)
