### ISSUE TITLE
Invalid 'android:scaleType' in modified bootsplash.xml , Always fitCenter.

### ISSUE THREAD

**Issue by Miluaaa** [zoontek/react-native-bootsplash#136]
### 💻 My environment

- react-native-bootsplash version:^2.2.4
- react-native version:0.62.2
- Platform:android
- OS version: android 9
- Device: vivo Z1i
- Simulator: on
- Android Studio version: 3.6.3

### 🕵️‍♂️ Reproducing the issue

expected :
![WechatIMG7](https://user-images.githubusercontent.com/49137179/87898696-80e05980-ca81-11ea-8afd-09576aba5d82.jpeg)

result：
![WechatIMG8](https://user-images.githubusercontent.com/49137179/87898715-8e95df00-ca81-11ea-9cac-5d5b6859964c.jpeg)

 I do n’t have enough basic knowledge of IOS and Android development.Ask for help

**Comment by Miluaaa** [comment]
res-drawable-bootsplash.xml



`<?xml version="1.0" encoding="utf-8"?>

<layer-list 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:opacity="opaque"
 >
    <item android:drawable="@color/bootsplash_background" />

    <item>
        <bitmap
            android:src="@mipmap/bootsplash_logo"
            android:scaleType="centerCrop" />
    </item>
</layer-list>
`

**Comment by Miluaaa** [comment]
res-drawable-bootsplash.xml



`<?xml version="1.0" encoding="utf-8"?>

<layer-list 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:opacity="opaque"
 >
    <item android:drawable="@color/bootsplash_background" />

    <item>
        <bitmap
            android:src="@mipmap/bootsplash_logo"
            android:scaleType="centerCrop" />
    </item>
</layer-list>`

**Comment by Miluaaa** [comment]
res-drawable-bootsplash.xml


`<layer-list 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:opacity="opaque"
 >
    <item android:drawable="@color/bootsplash_background" />

    <item>
        <bitmap
            android:src="@mipmap/bootsplash_logo"
            android:scaleType="centerCrop" />
    </item>
</layer-list>`

**Comment by zoontek** [comment]
I'm pretty sure Android drawables do not support `centerCrop` for background image, only ImageView
