### ISSUE TITLE
Side effects of PermissionsAndroid.request evaluating to 'never_ask_again' hiding the splash screen.

### ISSUE THREAD

**Issue by mafortier-nexapp** [zoontek/react-native-bootsplash#138]
### 💻 My environment

- react-native-bootsplash version: 2.2.5
- react-native version: 0.61.5
- Platform: Android
- OS version: 10
- Device: any (it happens on my real Pixel 3a)
- Simulator: any (it happens on a Pixel 3a simulator as well)

### 🕵️‍♂️ Reproducing the issue

During my application initialization, I'm displaying the boot splash screen while performing some checks. One of these check is some Android permissions I need the user to allow.

So the application boots, the splash screen is there. Some logic makes the permission prompt appears where there are three choices:

- Allow
- Deny
- Deny and never ask again (present only if it's not the first time shown)

Here's the flow:
If "Allow" is chosen, the splash screen is instructed to hide itself. -> works
If "Deny" is chosen, the splash screen stays and a rationale alert message explains why we need these permissions and then re-prompt the user again for the permissions. -> works
if "Deny and never ask again" is chosen, it chose a rationale alert message too, but the outcome is we close the application. -> works.

Then, if the application is booted whilst we previously had chosen "Allow" or "Deny", the previously described flow works just fine. But, if the user had previously chosen "Deny and never ask again", on boot, the splash screen disappears (hides itself) **without having invoked** the hide method, right after the permission check (which resolve in "never_ask_again") and triggers the third option of the flow. But, for some weird reason, we see the application content underneath the rationale alert message instead of the splash screen.

It seems to be some side effects going on with the hiding of the boot splash screen from within the library when evaluating a permission (PermissionsAndroid.request) to 'never_ask_again'.

### 🤞Solution

None so far. Any takes ?

**Comment by zoontek** [comment]
Hi. I understand checking the permissions when the splash screen is visible, but why using `request()` for that?

**Comment by WhippetsAintDogs** [comment]
Hi, `check()` only returns a boolean whether the permission has been allowed or not. If its `false`, you cannot distinguish if you can (and have to) ask again or not. Moreover, `request()` won't do anything if it was previously set to `never_ask_again`. Does that make sense ?

**Comment by zoontek** [comment]
@WhippetsAintDogs Yes, totally. I forgot `PermissionsAndroid` was a thing since I'm also a maintainer on `react-native-permissions` 😅. The `check` method on this lib return a proper status: https://github.com/react-native-community/react-native-permissions#check

**Comment by mafortier-nexapp** [comment]
I'll try to get around the issue with your library (`react-native-permissions`) tomorrow. I'll let you know if it solves the issue.

Thanks @zoontek !

**Comment by mafortier-nexapp** [comment]
@zoontek sorry for the delays, but you were right. `react-native-permissions` over PermissionAndroid (`react-native`) indeed fixed the issue.

Thanks !
