### ISSUE TITLE
Use of undeclared identifier 'RNBootSplash' - Fastlane

### ISSUE THREAD

**Issue by draggie** [zoontek/react-native-bootsplash#139]
Update: Apparently i can build for iOS debug but the release with target "Generic iOS Device" is the moment it happens.
### 💻 My environment

- react-native-bootsplash version: 2.2.5
- react-native version: 0.63.2
- Platform: ios 
- OS version: 10.15.5
- Device: MacBook Pro (Retina, 13-inch, Late 2012)
- Simulator: n/a
- Xcode version: 11.5

### 🕵️‍♂️ Reproducing the issue

Properly configured library - added the SplashScreen, installed pods, configured hide function.
While building using Xcode or react-native CLI it works just fine.
However, when built on clear ground with CI pipe using fastlane - it throws this error every time:
`../ios/supplier/AppDelegate.m:56:4: use of undeclared identifier 'RNBootSplash'
`
When I inspect this file in the Xcode it normally is able to find the RNBootSplash type, navigate to source header, I did not forgot to add the header.

Part of the file: 
```objective-c
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import "RNBootSplash.h"

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper =
      [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc]
                            initWithRootNode:application
                        withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc]
                        initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self
                                            launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"supplier"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f
                                                    green:1.0f
                                                     blue:1.0f
                                                    alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [RNBootSplash initWithStoryboard:@"LaunchScreen" rootView:rootView];
  return YES;
}
```

**Comment by zoontek** [comment]
You set the import between ˋ#ifdef FB_SONARKIT_ENABLED` and ˋ#endif`

Which means RNBootsplash.h is not imported on production builds.

**Comment by fatihkan** [comment]
The problem actually stems from incorrect positioning. Solution to similar problem [https://github.com/facebook/react-native/issues/28910](url)

#import "RNBootSplash.h"

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
