### ISSUE TITLE
"jump" during transition in Redmi Note 4

### ISSUE THREAD

**Issue by Magudeshwaran** [zoontek/react-native-bootsplash#143]
### 💻 My environment

- react-native-bootsplash version:
- react-native version:
- Platform: android 
- OS version: MIUI 11.0.2
- Device: MI /  Redmi Note 4
- Simulator: no
- Android Studio version: 4.0
- Android buildToolsVersion: ?
- Xcode version: ?

### 🕵️‍♂️ Reproducing the issue
There is a  vertical "jump" during transitionas like the android gravity params did not match perfectly.

### 🤞Solution

Need a solution

**Comment by zoontek** [comment]
@Magudeshwaran Please submit some code (styles.xml), bootsplash.xml)

**Comment by Magudeshwaran** [comment]
bootsplash.xml
`<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android"
    android:opacity="opaque">
    <item android:drawable="@color/bootsplash_background" />

    <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/bootsplash_logo" />
    </item>
</layer-list>
`
styles.xml

`<?xml version="1.0" encoding="utf-8"?>
<resources>

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">

    </style>


     <style name="BootTheme" parent="AppTheme">
    
    <item name="android:background">@drawable/bootsplash</item>

  </style>
</resources>
`

**Comment by Magudeshwaran** [comment]
[styles.txt](https://github.com/zoontek/react-native-bootsplash/files/5095063/styles.txt)

[bootsplash.txt](https://github.com/zoontek/react-native-bootsplash/files/5095059/bootsplash.txt)
`

**Comment by zoontek** [comment]
@Magudeshwaran MIUI is known to be terrible. Check this workaround: https://github.com/crazycodeboy/react-native-splash-screen/issues/241#issuecomment-662802070

**Comment by Magudeshwaran** [comment]
> @Magudeshwaran MIUI is known to be terrible. Check this workaround: [crazycodeboy/react-native-splash-screen#241 (comment)](https://github.com/crazycodeboy/react-native-splash-screen/issues/241#issuecomment-662802070)

Can you help me with react-native-bootsplash npm ? It does not getting themeResourceId as a parameter as in react-native-splash-screen. Reply with code will be very helpful.  Thanks( i'm new to react-native)

**Comment by r0b0t3d** [comment]
You are setting translucent status for MainActivity, so you should set it to BootTheme too.

Try this
```
<style name="BootTheme" parent="AppTheme">
        <!-- set the generated bootsplash.xml drawable as activity background -->
        <item name="android:background">@drawable/boot_splash</item>
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowTranslucentNavigation">true</item>
    </style>
```

**Comment by Magudeshwaran** [comment]
I almost solved my issue, with these code. Correct me if possible and suggest me a better solution if you have. Thanks
 ( IT WORKS GOOD ON REDMI NOTE 4 )
styles.xml
`<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:textColor">#000000</item>
        <item name="android:windowLightStatusBar">false</item>
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>

    </style>
    <style name="BootTheme" parent="AppTheme">
        
        <item name="android:background">@drawable/bootsplash</item>
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowLightStatusBar">true</item>
    </style>
</resources>
`
App.js

`<View style={{ height: 29, backgroundColor: "gray", width: "100%" }} />`
