### ISSUE TITLE
Showing a native iOS alert before bootsplash hides prevents future "hide"s from working

### ISSUE THREAD

**Issue by cwhenderson20** [zoontek/react-native-bootsplash#149]
### 💻 My environment

- react-native-bootsplash version: 2.2.4
- react-native version: 0.61.5
- Platform: iOS
- OS version: 13.x
- Device: iPhone (any)
- Simulator: yes + actual device
- Xcode version: 11.6

### 🕵️‍♂️ Reproducing the issue

First, thank you so much for this library! It's really been great to use.

I've just run into an issue where showing a native iOS alert (react-native's `Alert.alert`) _before_ hiding bootsplash (`BootSplash.hide()`) prevents the splash from hiding correctly in the future (and also dismisses the Alert in the process). 

Here are some screen recordings to illustrate the problem:

**Showing an alert before the splash is hidden:**
![splash-with-alert](https://user-images.githubusercontent.com/5496110/91484372-1a680b80-e877-11ea-827f-6311fa113bed.gif)

**Removing the alert completely:**
![splash-without-alert](https://user-images.githubusercontent.com/5496110/91484423-2f449f00-e877-11ea-9f78-5eb262c82d9d.gif)

**Delaying the alert until after the splash is hidden:**
![splash-with-delayed-alert](https://user-images.githubusercontent.com/5496110/91484451-39669d80-e877-11ea-8d97-bb0ace432ac3.gif)

I haven't yet verified behavior on Android.

It seems like this could be vaguely related to #100 and taken care of by the rewrite in 3.0, but I'm just speculating.  

Here are the gifs attached as .mov files in case the gifs don't come through properly: [splash_recordings.zip](https://github.com/zoontek/react-native-bootsplash/files/5138310/splash_recordings.zip)

**Comment by zoontek** [comment]
@cwhenderson20 Could you try the @next version to see if the issue is still present?

**Comment by cwhenderson20** [comment]
@zoontek I will give it a try this week and let you know.

**Comment by michaelgmcd** [comment]
We're seeing this as well with react-native-bootsplash@3.0.0-alpha.2

**Comment by zoontek** [comment]
I updated the `next` version. This issue did not get solved, but the async API should help you **not** displaying an alert before the Bootsplash is properly hidden.

**Comment by sameterdem** [comment]
@zoontek I need something like this. Does this problem continue?

**Comment by zoontek** [comment]
@sameterdem You need something like what?

**Comment by sameterdem** [comment]
@zoontek  Before I turn off the splash screen, I want to show some notifications on the screen. Like location permissions or an alert.

**Comment by zoontek** [comment]
@sameterdem The current implementation correctly dismiss the splash screen `UIViewController` instance: https://github.com/zoontek/react-native-bootsplash/blob/3.0.0/ios/RNBootSplash.m#L180

This issue seems related to the `Alert` module itself: https://github.com/facebook/react-native/commit/f319ff321c4b7c0929b99e3ebe7e1ce1fa50b34c#diff-56beca6ee071cdd162c269ce765ab12d5af8c8c0ca840bca1e9d1f59e9fab790 (read the commit description)

It is not shipped yet, but will probably be in the `0.64`

**Comment by a-eid** [comment]
@zoontek is there a possibility to hook into the splash screen events, 'hide', 'hide-complete', 'show', 'show-complete' or something similar ?

**Comment by zoontek** [comment]
> @zoontek is there a possibility to hook into the splash screen events, 'hide', 'hide-complete', 'show', 'show-complete' or something similar ?

v3 has an async API. You can await show / hide methods.

**Comment by a-eid** [comment]
@zoontek great thanks.

**Comment by zoontek** [comment]
@a-eid It is. I released it this afternoon.

**Comment by a-eid** [comment]
@zoontek thank you.
