### ISSUE TITLE
how to edit LaunchScreen.xib to set a full screen image in iOS?

### ISSUE THREAD

**Issue by KingAmo** [zoontek/react-native-bootsplash#15]
### 💻 My environment

- react-native-bootsplash version:  0.1.1
```System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.25 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 21, 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 28.0.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

### 🕵️‍♂️ Reproducing the issue

i am an Android developer，not familiar with iOS,  could you please give a brief guide on how to set the `LauchScreen.xib` to display a full screen image?

**Comment by MoOx** [comment]
React Native should have a launch screen by default. To use a full screen image, you should refer to  official documentation of apple xib stuff.

But since you didn't look their first, let me share one of my splashcreen I have under the hand :)

My splash `screenscreen.png`, once added to the iOS project, has been added in Xcode by using the Interface Builder.
To add the image, just hit the button that look like an iPhone home button  (sort of `([ ])`) in the top right corner of xcode 

<img width="122" alt="image" src="https://user-images.githubusercontent.com/157534/63495112-81fab680-c4bf-11e9-85f7-25eb78b5aa7d.png">

Then choose an image.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/157534/63495088-75765e00-c4bf-11e9-9572-0f0cb6b25a56.png">

And apply the following constraints

<img width="378" alt="image" src="https://user-images.githubusercontent.com/157534/63491691-2c6edb80-c4b8-11e9-85cb-8c0139a50785.png">

(You can use the buttons in the bottom right corner)

<img width="389" alt="image" src="https://user-images.githubusercontent.com/157534/63495259-cede8d00-c4bf-11e9-8747-1c19a513d00e.png">

Alternatively, you can adapt this .xib (xml) file :)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.XIB" version="3.0" toolsVersion="14490.70" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" launchScreen="YES" useTraitCollections="YES" colorMatched="YES">
    <device id="retina6_1" orientation="portrait">
        <adaptation id="fullscreen"/>
    </device>
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="14490.49"/>
        <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
    </dependencies>
    <objects>
        <placeholder placeholderIdentifier="IBFilesOwner" id="-1" userLabel="File's Owner"/>
        <placeholder placeholderIdentifier="IBFirstResponder" id="-2" customClass="UIResponder"/>
        <view clipsSubviews="YES" contentMode="scaleToFill" id="mQO-OZ-GhJ">
            <rect key="frame" x="0.0" y="0.0" width="414" height="896"/>
            <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>
            <subviews>
                <imageView userInteractionEnabled="NO" contentMode="scaleToFill" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="splashscreen.png" adjustsImageSizeForAccessibilityContentSizeCategory="YES" translatesAutoresizingMaskIntoConstraints="NO" id="5gn-MB-2H7">
                    <rect key="frame" x="-241" y="0.0" width="896" height="896"/>
                    <constraints>
                        <constraint firstAttribute="width" secondItem="5gn-MB-2H7" secondAttribute="height" multiplier="1:1" id="tBu-Bh-JPi"/>
                    </constraints>
                </imageView>
            </subviews>
            <color key="backgroundColor" white="1" alpha="1" colorSpace="custom" customColorSpace="genericGamma22GrayColorSpace"/>
            <constraints>
                <constraint firstItem="5gn-MB-2H7" firstAttribute="firstBaseline" secondItem="mQO-OZ-GhJ" secondAttribute="firstBaseline" id="9CM-2N-kwV"/>
                <constraint firstItem="5gn-MB-2H7" firstAttribute="centerY" secondItem="mQO-OZ-GhJ" secondAttribute="centerY" id="UIg-jf-rVl"/>
                <constraint firstItem="5gn-MB-2H7" firstAttribute="centerX" secondItem="mQO-OZ-GhJ" secondAttribute="centerX" id="VqM-5Z-wCO"/>
                <constraint firstAttribute="baseline" secondItem="5gn-MB-2H7" secondAttribute="baseline" id="g37-ya-jJo"/>
            </constraints>
            <point key="canvasLocation" x="137.68115942028987" y="142.63392857142856"/>
        </view>
    </objects>
    <resources>
        <image name="splashscreen.png" width="2048" height="2048"/>
    </resources>
</document>
```

Hope this helped (I should write a blog post about that & add link to it in the readme...)

**Comment by KingAmo** [comment]
@MoOx  thanks a lot~  but it seems that your code displays an icon in the center of the screen. anyway，i got it how to set a full screen image in `LaunchScreen.xib` file , thanks

**Comment by MoOx** [comment]
@KingAmo what was the size of your png? In my example, my image was 2048 x 2048 (so a big splash screen)

**Comment by KingAmo** [comment]
![image](https://user-images.githubusercontent.com/29938227/63572444-7a1d3e00-c5b5-11e9-8ced-376b9e8cb25e.png)
@MoOx  here it is ,there are three different size which is in `Images.xcassets`,  not a square image

**Comment by MoOx** [comment]
Oh yeah so that's not a square single PNG. Yeah so constraints must be different I guess.

**Comment by zoontek** [comment]
@KingAmo  I suggest to uses transparent PNG. If you do that, no need to update the images if you want to change the splash screen background color! :)

For the guys you want a small tuto:

1. Add an ImageView inside the .xib UIView using drag'n'drop

<img width="739" alt="Screenshot 2019-08-23 at 14 50 04" src="https://user-images.githubusercontent.com/1902323/63594220-2fe88c80-c5b6-11e9-9409-910e094bacbe.png">

<img width="790" alt="Screenshot 2019-08-23 at 14 50 38" src="https://user-images.githubusercontent.com/1902323/63594552-03814000-c5b7-11e9-8fda-4ed70bbbc108.png">

2. Add constraints _left: 0, right: 0, top: 0, bottom: 0_ (you can include notch safe insets automatically)

<img width="917" alt="Screenshot 2019-08-23 at 14 54 42" src="https://user-images.githubusercontent.com/1902323/63594634-45aa8180-c5b7-11e9-8dbb-e3bd1fee9ab7.png">

3. Enjoy image scaling setting 🤙

![Screenshot 2019-08-23 at 14 55 02](https://user-images.githubusercontent.com/1902323/63594869-e00ac500-c5b7-11e9-95a6-b81d87221f8f.png)

**Comment by paras-kc** [comment]
how can i do it for android??

**Comment by gatspy** [comment]
@zoontek your solution perfect!

**Comment by Malik-Usman17** [comment]
> 

Thanks, this really helpful
