### ISSUE TITLE
Android: splash screen background flashes when keyboard is opened / closed

### ISSUE THREAD

**Issue by sanjaypojo** [zoontek/react-native-bootsplash#150]
@zoontek thanks a ton for the library, it's great. Excited to use the new release but found this issue!

### 💻 My environment

- react-native-bootsplash version: 3.0.0-alpha.2
- react-native version: 0.61.5
- Platform: android
- OS version: Android 9
- Device: Samsung S8
- Simulator: no

### 🕵️‍♂️ Reproducing the issue

- Install new version using the migration guide. Our splash screen has a purple background image + white logo.
- Launch the app, everything works as expected.
- Click on input to open the android keyboard.

The purple image + logo flash during the keyboard open animation, only within the keyboard area. Video here:

![bootsplash_flash](https://user-images.githubusercontent.com/4957294/91916020-e6268d80-ec70-11ea-9eb4-6f8cd0f58202.gif)

### 🤞Solution

Unsure, but might be because of the new style of using the splash screen as the app background. Maybe an additional line is needed to layer another background on top of it to prevent the flash?

**Comment by zoontek** [comment]
@sanjaypojo Could you post your AndroidManifest.xml?

**Comment by sanjaypojo** [comment]
@zoontek sure, here are the relevant parts of `AndroidManifest.xml`:

```xml
  <application
      android:name="***.MainApplication"
      android:label="***"
      android:icon="***"
      android:roundIcon="***"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:networkSecurityConfig="@xml/network_security_config"
      tools:replace="android:allowBackup">
      <activity
        android:name=".MainActivity"
        android:label="***"
        android:launchMode="singleTask"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="sensorPortrait"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
            <intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <!-- Branch URI Scheme -->
            <intent-filter>
                <data android:scheme="***" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
      </activity>
  </application>
```

Here's `styles.xml`:

```xml
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#cccccc</item>
        <item name="android:statusBarColor">@color/purple</item>
        <item name="android:android:fitsSystemWindows">true</item>
        <!-- Needed for RNBootSplash -->
        <!-- set the generated bootsplash.xml drawable as activity background -->
        <item name="android:background">@drawable/bootsplash</item>
    </style>

</resources>
```

And here's the drawable (`bootsplash.xml`):

```xml
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
    <item android:drawable="@color/bootsplash_background" />

    <item>
        <bitmap android:gravity="top | center_horizontal" android:src="@mipmap/splash_screen_bg" />
    </item>

    <item>
        <bitmap android:src="@mipmap/bootsplash_logo" android:gravity="center" />
    </item>
</layer-list>
```

**Comment by zoontek** [comment]
I tried giving it a try, couldn't reproduce it. The only issue was `<item name="android:android:fitsSystemWindows">true</item>` (`android:android:` prefix does not exists).

Are you sure `RNBootSplash.init(this, R.style.AppTheme);` came before `super.onCreate(savedInstanceState);`?
See https://github.com/zoontek/react-native-bootsplash/blob/3.0.0/MIGRATION.md

**Comment by sanjaypojo** [comment]
@zoontek I've added it before as described in the guide:

```java
    // Override onCreate for RNBootSplash
    @Override
    protected void onCreate(Bundle savedInstanceState) {
      // Use RNBootSplash
      RNBootSplash.init(this, R.style.AppTheme);
      super.onCreate(savedInstanceState);
    }
```

Do you think it's related to the custom drawable styling in `bootsplash.xml`? I can't really think of anything else that might cause it. The branch only contains this one bootsplash update and nothing else, so it definitely seems to be caused by this change :)

**Comment by zoontek** [comment]
@sanjaypojo Currently, the `init` method set the `AppTheme` back to `@null` when a custom `Dialog` is created.

- https://github.com/zoontek/react-native-bootsplash/blob/3.0.0/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java#L52
- https://github.com/zoontek/react-native-bootsplash/blob/3.0.0/android/src/main/res/values/styles.xml#L2

It might be an issue with Samsung horrible custom UI.

**Comment by sanjaypojo** [comment]
Thanks @zoontek -- I'll try and look into the source code to see if I can identify what's happening.

I haven't read the source, but here's what I was thinking: Since I'm directly setting the background inside AppTheme in `styles.xml`, would this mean that `bootsplash.xml` is always set as the background? Should I make some changes in `styles.xml` so that `bootsplash.xml` is only set as the background when it is not hidden? This part was unclear to me. Thanks!

**Comment by zoontek** [comment]
@sanjaypojo How it works:

- The splash screen is set as your `AppTheme` background
- When you call `init`, a `Dialog` is shown over your `Activity` using the exact same `AppTheme`
- Once shown, the `Activity` background is cleared using `BootSplashNullBackgroundTheme`, which set background to `@null` <- that's where the issue happen
- You hide the `Dialog` when you want via JS

I don't have a Samsung phone to reproduce the issue (only a Nexus and a phone with Android One: no issues with stock Android, damn manufacturer and their custom UIs), but I can create a branch on which I will try to apply some patches until you confirm that one of them works. Would you be OK with this?

I'm thinking about setting the background first to `@android:color/transparent`, then to `@null`

**Comment by sanjaypojo** [comment]
Thanks a ton for the explanation @zoontek, that makes sense!

> I don't have a Samsung phone to reproduce the issue (only a Nexus and a phone with Android One: no issues with stock Android, damn manufacturer and their custom UIs)

So many issues with android development caused by these random manufacturer decisions 😓 

> I can create a branch on which I will try to apply some patches until you confirm that one of them works. Would you be OK with this?

That sounds amazing, I'm happy to try them out and report back to you!

**Comment by zoontek** [comment]
@sanjaypojo Sorry for the huge delay. As the new implementation broke Detox tests for a lot of users, I decided to rollback the original implementation. Which mean this issue should disappear too :)

https://github.com/zoontek/react-native-bootsplash/tree/3.0.0

The migration guide is now ultra short: https://github.com/zoontek/react-native-bootsplash/blob/3.0.0/MIGRATION.md

**Comment by sanjaypojo** [comment]
Thanks @zoontek will try it out soon!

**Comment by Jevon-Rhino** [comment]
Hey @zoontek @sanjaypojo changing `android:windowSoftInputMode="adjustResize"` to `android:windowSoftInputMode="adjustPan"` seems to fix it for me.

**Comment by cristianoccazinsp** [comment]
@Jevon-Rhino but `android:windowSoftInputMode="adjustPan"` does no work in modals. How do you solve the issue if you also have text inputs within a RN `Modal` ?

**Comment by Ghabriel-elias** [comment]
> @Jevon-Rhino but `android:windowSoftInputMode="adjustPan"` does no work in modals. How do you solve the issue if you also have text inputs within a RN `Modal` ?

iam using native 74 and that its, thansk man

**Comment by MrFarhan** [comment]
> Hey @zoontek @sanjaypojo changing `android:windowSoftInputMode="adjustResize"` to `android:windowSoftInputMode="adjustPan"` fixed it for me.

It worked for me but i am also using react native gifted chat which has the requirement of this `android:windowSoftInputMode="adjustResize"` so again i am stucked.

![Screenshot 2024-09-25 at 3 49 20 PM](https://github.com/user-attachments/assets/346a088e-9267-45a0-99e4-ba4f83da059b)

**Comment by RyanMurphyMobi** [comment]
> > Hey [@zoontek](https://github.com/zoontek) [@sanjaypojo](https://github.com/sanjaypojo) changing `android:windowSoftInputMode="adjustResize"` to `android:windowSoftInputMode="adjustPan"` fixed it for me.
> 
> It worked for me but i am also using react native gifted chat which has the requirement of this `android:windowSoftInputMode="adjustResize"` so again i am stucked.
> 
> ![Screenshot 2024-09-25 at 3 49 20 PM](https://github.com/user-attachments/assets/346a088e-9267-45a0-99e4-ba4f83da059b)

Did you ever fix this?
