### ISSUE TITLE
Fullscreen image with maintained aspect ratio not possible in version 3+ on Android

### ISSUE THREAD

**Issue by fgeorgsson** [zoontek/react-native-bootsplash#153]
### 💻 My environment

- react-native-bootsplash version: 3.0.0-alpha.2
- react-native version:0.63.2
- Platform: android
- OS version: 9
- Device: LG G6
- Simulator: either
- Android Studio version: 4.0.1
- Android buildToolsVersion: any

### 🕵️‍♂️ Reproducing the issue

I want a fullscreen image with maintained aspect ratio that is minimally scaled to cover the screen.

There seems to be no way to make a fullscreen splash in version 3+. The problem stems from the bootsplash drawable now being a background for the MainActivity instead of using a separate activity. The background must be a plain drawable and as such cannot use "centerCrop" to cover the screen with aspect ratio kept intact.

- Using the available forms of fill the image aspect ratio will become distorted.
- Using just "center" the image may become too large/too small to match up in the screen since there will be no scaling involved. Too much of the image might be cropped of, or there might be gaps if the screen is larger than the image.

Any ideas?

**Comment by zoontek** [comment]
@fgeorgsson Please share your splash screen config (bootsplash.xml)

**Comment by zoontek** [comment]
Yeah, it's laughable. Don't overthinking it too much, Slack, Airbnb etc just display a centered logo on Android 🙂

**Comment by nvojnovic** [comment]
Actually I have managed to make it work but I'm not sure it will work for everybody.
At the end I just replaced:
https://github.com/zoontek/react-native-bootsplash/blob/a3140e40962c44e0a5bab6ad9b41e4d30447a518/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java#L67-L69
with https://github.com/nvojnovic/react-native-bootsplash/commit/d35a28efc1ff784b7d65da7ed83996a9f6264946#diff-f60ed56a9c8275894022fe5a7a1625c33bdb55b729bb4e38962af4d1613eda25
```
ImageView view = new ImageView(context);

view.setImageResource(mDrawableResId);
view.setScaleType(ImageView.ScaleType.CENTER_CROP);
```

So using ImageView instead of View and setScaleType did the trick for me.

**Comment by chesovnik** [comment]
> Actually I have managed to make it work but I'm not sure it will work for everybody.
> At the end I just replaced:
> 
> https://github.com/zoontek/react-native-bootsplash/blob/a3140e40962c44e0a5bab6ad9b41e4d30447a518/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java#L67-L69
> 
> 
> with [nvojnovic@d35a28e#diff-f60ed56a9c8275894022fe5a7a1625c33bdb55b729bb4e38962af4d1613eda25](https://github.com/nvojnovic/react-native-bootsplash/commit/d35a28efc1ff784b7d65da7ed83996a9f6264946#diff-f60ed56a9c8275894022fe5a7a1625c33bdb55b729bb4e38962af4d1613eda25)
> ```
> ImageView view = new ImageView(context);
> 
> view.setImageResource(mDrawableResId);
> view.setScaleType(ImageView.ScaleType.CENTER_CROP);
> ```
> 
> So using ImageView instead of View and setScaleType did the trick for me.

Hi! I have just used your trick and it works! But the first 2 seconds I see distorted image and only then nice fullscreen cover. How did you solve it? Thanks!

**Comment by chaimPaneth** [comment]
Hi @chesovnik 

In addition to the changes you mentioned [above](https://github.com/zoontek/react-native-bootsplash/issues/153#issuecomment-769216131)

I also changed the `drawable.xml` and added `android:scaleType="centerCrop"` to the `<item/>` so it looks like this

```
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">

    <item>
        <bitmap android:src="@mipmap/splash_screen" android:scaleType="centerCrop" />
    </item>

</layer-list>

```

And now it's working fine.

**Comment by federazionekoinonie** [comment]
> Hi @chesovnik
> 
> In addition to the changes you mentioned [above](https://github.com/zoontek/react-native-bootsplash/issues/153#issuecomment-769216131)
> 
> I also changed the `drawable.xml` and added `android:scaleType="centerCrop"` to the `<item/>` so it looks like this
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> 
> <layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
> 
>     <item>
>         <bitmap android:src="@mipmap/splash_screen" android:scaleType="centerCrop" />
>     </item>
> 
> </layer-list>
> ```
> 
> And now it's working fine.

Thank you so much, it worked! The only trouble: when I run first-time the app (react-native run-android) the image is rendered fullscreen with the correct aspect ratio, instead, since I closed the app, whenever I re-open it I see first the image wrongly stretched for a moment, and almost immediately it changes to the right aspect ratio... Any suggestions? Thanks!

**Comment by IlanZ93** [comment]
Hi @chaimPaneth , i dont have any drawable.xml file here what i have and i have the same issue @fondakogb got, first a distored image and then a centerCroped image : 

AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.xxxxxxx">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:windowSoftInputMode="adjustResize"
        android:exported="true"
        android:launchMode="singleTask">     
      </activity>

      <activity
        android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
        android:theme="@style/BootTheme"
        android:launchMode="singleTask">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
    </application>
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https"/>
        </intent>
    </queries>
</manifest>
```

styles.xml
```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
    </style>

  <!-- Add the following lines (BootTheme should inherit from AppTheme) -->
  <style name="BootTheme" parent="AppTheme">
    <!-- set the generated bootsplash.xml drawable as activity background -->
    <item name="android:background">@drawable/launch_screen</item>
  </style>
</resources>
```

bootsplash.xml
```
<?xml version="1.0" encoding="utf-8"?>

<!-- used only for visual debugging in Android Studio -->
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:background="@drawable/launch_screen"
  android:orientation="vertical"
  android:scaleType="centerCrop" />
```

launch_screen.xml
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">
    <ImageView  android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@drawable/launch_screen"
        android:orientation="vertical"
        android:scaleType="centerCrop" />
</RelativeLayout>
```

Do you know how to fix this ? it seems that both scaleType in 2 last file are not use, because even if i change for another scaletype, nothing change.

I have multiple App with this project, and all have fullscreen SplashScreen.

Thank you
