### ISSUE TITLE
Splash screen jumping up on android

### ISSUE THREAD

**Issue by David-moonsite** [zoontek/react-native-bootsplash#154]
### 💻 My environment

- react-native-bootsplash version:2.2.4
- react-native version: 0.60.5
- Platform: android 

- OS version: ?
- Device: all android device
- Simulator: yes
- Android Studio version: ?
- Android buildToolsVersion: ?
- Xcode version: ?

### 🕵️‍♂️ Reproducing the issue

When following the instructions, I get a good working result on iOS. 
On android, there is a small jump up (approx. the height of the status bar, so I suspect it has to do with that) a split second after opening the app.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/58983212/92614722-0b487b00-f2c5-11ea-8e07-349a830f413e.gif)

styles.xml

```
<resources>
  <!-- Base application theme. -->
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:windowDisablePreview">true</item>
  </style>
  <!-- BootTheme should inherit from AppTheme -->
  <style name="BootTheme" parent="AppTheme">
    <item name="android:windowBackground">@drawable/splash_screen</item>
  </style>
</resources>
```
bootsplash.xml
```
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
    <item android:drawable="@color/bootsplash_background" />

    <item>
        <bitmap android:src="@mipmap/icon" android:gravity="fill" />
    </item>
</layer-list>
```

### 🤞Solution

<StatusBar
            backgroundColor="rgba(0,0,0,.3)"
             **translucent={true}**-----> it should be true only when splash screen done
            hidden={false}
            barStyle="light-content"
          />

**Comment by zoontek** [comment]
@David-moonsite Do you use custom Java code to hide the status bar or else?

**Comment by David-moonsite** [comment]
@zoontek  no

**Comment by zoontek** [comment]
windowBackground -> background

**Comment by David-moonsite** [comment]
styles.xml
```
<resources>
  <!-- Base application theme. -->
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:windowDisablePreview">true</item>
  </style>
  <!-- BootTheme should inherit from AppTheme -->
  <style name="BootTheme" parent="AppTheme">
    <item name="android:background">@drawable/splash_screen</item>
  </style>
</resources>
```
same issue :(

**Comment by zoontek** [comment]
Replace android:gravity="fill" with android:gravity="center"

**Comment by David-moonsite** [comment]
find the problem 👍 
```
<StatusBar
            backgroundColor="rgba(0,0,0,.3)"
             **translucent={true}**-----> it should be true only when splash screen done
            hidden={false}
            barStyle="light-content"
          />
```

**Comment by zoontek** [comment]
Ah indeed! Or set your status bar as transparent at start in your styles.xml, it will solves it too.
