### ISSUE TITLE
When starting app, the splash screen is showing as a white screen

### ISSUE THREAD

**Issue by PriorM** [zoontek/react-native-bootsplash#156]
### 💻 My environment

- react-native-bootsplash version: react-native-bootsplash@3.0.0-alpha.2
- react-native version: react-native@0.62.2
- Platform: android 
- OS version: 10
- Device: Google Pixel 2
- Simulator: yes
- Android Studio version: 4
- Android buildToolsVersion: 30.02
- Xcode version: n/a

### 🕵️‍♂️ Reproducing the issue

I followed the setup steps in the readme and the migration steps in MIGRATION.md as I was previously attempting to use the current version of the module. Below is the code where I'm calling RNBootSplash at the start of my App function.

![image](https://user-images.githubusercontent.com/37394046/92892871-809a8400-f45c-11ea-9bd6-56f18547bb50.png)

**Comment by zoontek** [comment]
@PriorM Submit all your modified files (styles.xml, bootsplash.xml, MainActivity.java) + a video if possible.

**Comment by PriorM** [comment]
Hi, here are the files that you requested. Thank you for your quick reply

[Requested Files.zip](https://github.com/zoontek/react-native-bootsplash/files/5212274/Requested.Files.zip)

**Comment by zoontek** [comment]
<img width="684" alt="Screenshot 2020-09-12 at 10 51 05" src="https://user-images.githubusercontent.com/1902323/92991681-eed75900-f4e5-11ea-8323-15389c3deba8.png">

You didn't install the package correctly. If you did, clean your project. https://github.com/pmadruga/react-native-clean-project

**Comment by PriorM** [comment]
@zoontek I've cleaned the project as you suggested and reinstalled the package using npm install --save react-native-bootsplash but it has not solved this issue
