### ISSUE TITLE
Set AppCompatDelegate.setDefaultNightMode doesn't work properly

### ISSUE THREAD

**Issue by irekrog** [zoontek/react-native-bootsplash#157]
### 💻 My environment

- react-native-bootsplash version: 3.0.0-alpha.2
- react-native version:0.62.2
- Platform: android
- OS version: 10
- Device: Huawei P30 Pro
- Simulator: no (but on Pixel with Android 11 simulator is same)
- Android Studio version: Android Studio 4.1 RC 2

### 🕵️‍♂️ Reproducing the issue
System theme is Dark, but I want to change to Light theme for app so then I set    `AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);` in `MainApplication.java` in `onCreate` method. But on the start for a moment **is still black background** and about 500ms after is white. 

(Of course in case when system default theme is Light and I change to MODE_NIGHT_YES then first is white background and in a moment black)

**MainActivity.java**
```
protected void onCreate(Bundle savedInstanceState) {
  RNBootSplash.init(this, R.style.AppTheme);
  super.onCreate(savedInstanceState);
}
```
**MainApplication.java**
```
public void onCreate() {
    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }
```
**bootsplash.xml**
```
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
    <item android:drawable="@color/bootsplash_background" />

    <item>
        <bitmap android:src="@mipmap/bootsplash_logo" android:gravity="center" />
    </item>
</layer-list>
```
**bootsplash_dark.xml**
```
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
    <item android:drawable="@color/bootsplash_background_dark" />

    <item>
        <bitmap android:src="@mipmap/bootsplash_logo" android:gravity="center" />
    </item>
</layer-list>
```
**colors.xml**
```
<resources>
    <color name="bootsplash_background">#FFFFFF</color>
    <color name="bootsplash_background_dark">#000000</color>
</resources>
```
**values/styles.xml**
```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
        <item name="android:background">@drawable/bootsplash</item>
    </style>

</resources>
```
**values-night/styles.xml**
```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
        <item name="android:background">@drawable/bootsplash_dark</item>
    </style>

</resources>
```
### 🤞Solution

**Temporary workaround for me** is change in `values-night/styles.xml` style name from AppTheme to AppThemeDark (keep AppTheme name in `values/styles.xml`), checking current theme and call properly style in init
```
int currentNightMode = configuration.uiMode & Configuration.UI_MODE_NIGHT_MASK;
switch (currentNightMode) {
    case Configuration.UI_MODE_NIGHT_NO:
        RNBootSplash.init(this, R.style.AppTheme);
        break;
    case Configuration.UI_MODE_NIGHT_YES:
        RNBootSplash.init(this, R.style.AppThemeDark);
        break;
}
```

**Comment by zoontek** [comment]
@irekrog Did it worked in version `2.2.5`?

**Comment by irekrog** [comment]
@zoontek I didn't try in any `2.x.x` version. Only in `3.0.0-alpha.2`

**Comment by zoontek** [comment]
I'm closing this since the theme handling has been rollbacked in the `next` version (which is no longer an alpha).
If someone encounter the same issue, please post a message and I will re-open it.
