### ISSUE TITLE
How to set a Layout as Splash screen

### ISSUE THREAD

**Issue by EhsanSarshar** [zoontek/react-native-bootsplash#158]
There are too much limitation with Drawable. I have my own layout with RelativeLayout how to use that as Splash screen.
can Any one shows a sample

**Comment by Youn-ha** [comment]
https://github.com/zoontek/react-native-bootsplash/issues/112#issuecomment-678234696

You cannot use your own RelativeLayout. Check this out.

**Comment by EhsanSarshar** [comment]
@Youn-ha yes I can
check [this](https://github.com/zoontek/react-native-bootsplash/issues/112#issuecomment-676495403) out
