### ISSUE TITLE
generate-bootsplash not found in mac

### ISSUE THREAD

**Issue by SergiOnGit** [zoontek/react-native-bootsplash#159]
# Bug report

## Summary

Hi, i'm trying to install this package in mac but when i run npx generate-bootsplash it says package is not found. Same when i run it with yarn.

Error log:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/generate-bootsplash - Not found
npm ERR! 404 
npm ERR! 404  'generate-bootsplash@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 23.62 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - /var/folders/2t/zyqjc4bs5553jb4p0npvrp8h0000gn/T/yarn--1601219868909-0.7521229414003985/node
    Yarn: 1.22.5 - /var/folders/2t/zyqjc4bs5553jb4p0npvrp8h0000gn/T/yarn--1601219868909-0.7521229414003985/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.0-alpha.2

**Comment by jhoanborges** [comment]
+1

**Comment by zoontek** [comment]
@SergiOnGit @jhoanborges Did you installed it first (`npm install react-native-bootsplash && npx generate-bootsplash`)? By default, `npx` will search in your local executables.

**Comment by SergiOnGit** [comment]
@zoontek you are right. Thanks.
