### ISSUE TITLE
Making the status bar transparent on Android

### ISSUE THREAD

**Issue by yanisdb** [zoontek/react-native-bootsplash#164]
# Feature request
Hi,

The idea is to make the status bar transparent on Android, as it is on IOS. I would be happy to look further into it if you can confirm me that it is not possible already with the plugin

Have a great day

**Comment by zoontek** [comment]
This has nothing to do with this library.

**Comment by yanisdb** [comment]
I want the status bar transparent during the splash screen (it is already transparent for the application itself).
I think I need to modify either RNBootSplashActivity.java or the generated BootTheme in the style.xml. 
I tried to modify the style.xml but it didn't yield any result. I couldn't find or understand where and how this BootTheme is being used.

**Comment by yanisdb** [comment]
I managed to do it by adding these two lines to RNBootSplash.java :
```        
activity.getWindow().setStatusBarColor(Color.argb(0,0,0,0));
activity.getWindow().setFlags(
                WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
                WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
```

**Comment by zoontek** [comment]
@yanisdb Yes https://github.com/zoontek/react-native-bootsplash/issues/52#issuecomment-580366701

**Comment by yanisdb** [comment]
Sorry to bother you so much, it did indeed work as in the comment you pointed out but I now get the same problem as the last comment of the thread: https://github.com/zoontek/react-native-bootsplash/issues/52#issuecomment-674251421. Did I miss something ?

**Comment by zoontek** [comment]
No, this is indeed how Android display translucent status bar. As 100% transparent status bar are not possible using only `style.xml`, you'll always have this one second glitch at start, before the Java custom code kicks in (in SplashScreenActivity, or even in MainActivity: the limitation is similar).

I would recommend sticks to translucentStatusBar only, not applying `FLAG_LAYOUT_NO_LIMITS`.

**Comment by GabrielVBusato** [comment]
Still jumping the screen when settings flags to main activity? Or anyone did found a way to fix this?
