### ISSUE TITLE
iOS background color is not icon color

### ISSUE THREAD

**Issue by arnaudambro** [zoontek/react-native-bootsplash#166]
Hi there, 

The color of my icon and the background don't match, and I'm trying for one hour to make them match with no success...

What is the magic recipe ?

The target color is the icon color `#fedf1e`, it's also the one I entered with `yarn generate-bootsplash`. But it doesn't match...

![image](https://user-images.githubusercontent.com/31724752/95610479-b1240c80-0a60-11eb-9c66-5ac44c756058.png)

**Comment by zoontek** [comment]
@arnaudambro Hi. This is probably a duplicate of https://github.com/zoontek/react-native-bootsplash/issues/71

**Comment by arnaudambro** [comment]
Good advise for the transparent PNG, I will follow it.

But still, even with the `Display P3` color profile, the color of the background is not the one expected.
So when I give `#fedf1e` when asked using `yarn generate-bootsplash` (great tool by the way), the color is not the one expected.
Is there a trick to get the proper color ?

**Comment by zoontek** [comment]
@arnaudambro It might depends of the image, the screen, or the `jimp` treatment. I would **really** recommend the transparent PNG here 😅

**Comment by arnaudambro** [comment]
Haha OK well noted ! Indeed it works perfectly. Thanks !
