### ISSUE TITLE
[Enhancement] Support hiding from native iOS code

### ISSUE THREAD

**Issue by michaelgmcd** [zoontek/react-native-bootsplash#168]
# Feature request

In order to support the use case of showing the splash screen when the app is put in the background (via `applicationWillResignActive`), we'd need a way to hide the splash screen from the native side.

We can use this to show the splash screen from the native side, but we don't have a way to hide it.
```
[RNBootSplash initWithStoryboard:@"LaunchScreen" rootView:self.window.rootViewController.view];
```

Thank you for your work on react-native-bootsplash. We've recently migrated from react-native-splash-screen and this is the only use case we have that this library doesn't support.

**Comment by zoontek** [comment]
Hi. Why not using AppState to achieve the same?

**Comment by michaelgmcd** [comment]
This would be the preferred approach, but it doesn't seem to work. I believe this is because it's considered a background task. The JS code is notified too late in the cycle to make any UI changes. I could be wrong here, but trying to call `bootSplash.show()` on app status change (when nextAppStatus is "background") does nothing.

**Comment by zoontek** [comment]
Did you tried with the inactive status instead of background?

**Comment by zoontek** [comment]
I confirm that `inactive` is triggered on `UIApplicationWillResignActiveNotification `: https://github.com/facebook/react-native/blob/0.63-stable/React/CoreModules/RCTAppState.mm#L115
