### ISSUE TITLE
Splash Screen on Android

### ISSUE THREAD

**Issue by rkocur** [zoontek/react-native-bootsplash#169]
As you can see in the attachment, I made the logo image in the middle and the version text at the bottom on iOS. But I couldn't do this on android. Can you help?

```
<?xml version="1.0" encoding="utf-8"?>
<!-- used only for visual debugging in Android Studio -->
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:background="@drawable/bootsplash"
  android:orientation="vertical" >
    <TextView
        android:id="@+id/textView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Version 3.1" />
</LinearLayout>
```

<img width="565" alt="Screen Shot 2020-10-14 at 12 16 12" src="https://user-images.githubusercontent.com/53087530/95969908-fc9b3980-0e17-11eb-9c7b-9257ca0c48e3.png">

<img width="869" alt="Screen Shot 2020-10-14 at 12 24 04" src="https://user-images.githubusercontent.com/53087530/95970559-c5795800-0e18-11eb-93e0-0628d467099d.png">

**Comment by zoontek** [comment]
This is not possible. You can't design a splash screen using a Layout (check for other issues that already answer #duplicate)

Please, understand too that issues are for real issues in the library, not getting help about your project.

**Comment by rkocur** [comment]
Thank you for your interest. Actually not with help. We opened your project for feature request. There is no problem in iOS. I think your project will be useful if we solve it for Android. The start screen looks good on Facebook and Instagram apps.

**Comment by zoontek** [comment]
This is not a feature request either.
You are looking for https://developer.android.com/guide/topics/resources/drawable-resource
