### ISSUE TITLE
Splash screen from @drawable/launch_screen

### ISSUE THREAD

**Issue by zyxel648** [zoontek/react-native-bootsplash#17]
### 💻 My environment

- react-native-bootsplash version: 0.1.1
- react-native version: 0.60.5

In the example of the boot screen, you've used the icon from `@mipmap/ic_launcher`. But often icon and splash are different. What is the proper way to setup splash screen with images from `@drawable/launch_screen`? 
Is that correct?
```
    <item android:gravity="center">
        <bitmap android:src="@drawable/launch_screen" />
    </item>
```
The images from `@drawable/launch_screen` are in the folders `drawable-hdpi`, `drawable-mdpi`, `drawable-mdpi` etc.
![image](https://user-images.githubusercontent.com/2689644/63573527-3c58ef00-c58e-11e9-8a83-9f20f5bd0b7e.png)

This works for the first app launch, but when I click "Reload" in the emulator, a white screen appears without an image.

**Comment by MoOx** [comment]
You can't have the splash screen during reload atm with my knowledge.

@zoontek can we listen to reload to show it? I think you are familiar with dev menus, maybe enough to know :D

**Comment by zoontek** [comment]
@zyxel648 Your approach is good. It's perfectly normal to not displaying the splash screen on reload as we want to see the download progression info and as it has no impact on the production build.

**Comment by zyxel648** [comment]
@zoontek, @MoOx thank you for the responses! I have no questions anymore 👍
