### ISSUE TITLE
yarn generate-bootsplash icon generator tool fails at the first step

### ISSUE THREAD

**Issue by jcohenho** [zoontek/react-native-bootsplash#172]
# Bug report

## Summary

When trying to run `yarn generate-bootsplash` from my RN project root folder, I get the following error:
```bash
? The path to the root of your React Native project › .
› Invalid React Native project. A valid app.json file could not be found.
```
No matter what I try, the cli cannot find my react-native app. 

## Environment info

`react-native info` output:

```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 193.86 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.4 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

```bash
# paste it here
```

Library version: ^2.2.7

## Steps to reproduce

1. `yarn add react-native-bootsplash`
2. `yarn generate-bootsplash`

Describe what you expected to happen:

1. I expect the CLI asset generator to work

**Comment by zoontek** [comment]
Hi! What's in your app.json file?

**Comment by jcohenho** [comment]
@zoontek 
```
{
  "expo": {
    "name": "MyApp",
    "slug": "myapp",
    "runtimeVersion": "37.0.0",
    "privacy": "unlisted",
    "version": "1.0.0"
  }
}
```

**Comment by zoontek** [comment]
@jcohenho This module is not compatible with Expo. Follow their documentation: https://docs.expo.io/guides/splash-screens/

**Comment by jcohenho** [comment]
I’m using an ejected expo app, so I’m just working with pure react native.

**Comment by zoontek** [comment]
Pure react-native `app.json` files looks like this: https://github.com/zoontek/react-native-bootsplash/blob/master/example/app.json

I guess updating the file to this **might** work, but I am not familiar with Expo bare workflow:

```
{
  "name": "MyApp",
  "displayName": "MyApp"
  "expo": {
    "name": "MyApp",
    "slug": "myapp",
    "runtimeVersion": "37.0.0",
    "privacy": "unlisted",
    "version": "1.0.0"
  }
}
```
