### ISSUE TITLE
Is there a way to pass text to the Splash screen?

### ISSUE THREAD

**Issue by Onibenjo** [zoontek/react-native-bootsplash#174]
# Feature request

## Why it is needed
I would love to add text to the bottom of the splash screen like the "from Facebook" whtatsapp has. I dont know if there is a workaround for that, I dont have experience with Java files and editing xmls and all that

**Comment by zoontek** [comment]
@Onibenjo Check the Android documentation: https://developer.android.com/guide/topics/resources/drawable-resource
