### ISSUE TITLE
Remove duplicate call to instantiateInitialViewController in RNBootSplash.m

### ISSUE THREAD

**Issue by boliveira** [zoontek/react-native-bootsplash#175]
Is it necessary to have two calls to instantiateInitialViewController in RNBootSplash.m?

```
UIStoryboard *storyboard = [UIStoryboard storyboardWithName:storyboardName bundle:nil];
  UIView *loadingView = [[storyboard instantiateInitialViewController] view]; <--- Can't this be _splashViewController = [storyboard instantiateInitialViewController]; and then UIView *loadingView = [_splashViewController view];

  [rootView setLoadingView:loadingView];
  rootView.loadingViewFadeDelay = 0.1;
  rootView.loadingViewFadeDuration = 0;

  _splashViewController = [storyboard instantiateInitialViewController]; <--- Then this one can be removed
  [_splashViewController setModalPresentationStyle:UIModalPresentationOverFullScreen];
```

**Comment by zoontek** [comment]
@boliveira Yes. The first one is only used to have an instance of `UIView` and set it as `loadingView`.
Once the JS has loaded, this view instance is destroyed.

The second one is used for the splash screen, which can persist after the JS load.

**Comment by boliveira** [comment]
@zoontek , sorry for bothering again but I changed my code to the following and everything still worked correctly. I am not sure there is any need to have 2 calls to instantiateInitialViewController. Can't it be like the following?

 ```
UIStoryboard *storyboard = [UIStoryboard storyboardWithName:storyboardName bundle:nil];

 _splashViewController = [storyboard instantiateInitialViewController];

  UIView *loadingView = [_splashViewController view];
  [rootView setLoadingView:loadingView];
  rootView.loadingViewFadeDelay = 0.1;
  rootView.loadingViewFadeDuration = 0;

  [_splashViewController setModalPresentationStyle:UIModalPresentationOverFullScreen];
```

**Comment by zoontek** [comment]
@boliveira The first `UIView` instance is manipulated by React Native `RCTRootView`, the second by this lib. I'm not confident enough to share instances across projects (even more if ARC is enabled). As the first instance is destroyed at app start, I'm not sure the performance gain is significant anyway.
