### ISSUE TITLE
Resize Image?

### ISSUE THREAD

**Issue by traingethermarc** [zoontek/react-native-bootsplash#176]
Hi!
```
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-bootsplash": "^2.2.7",
    iOS: 14
```

I created a Storyboard with `npx generate-bootsplash` with a dp of 200, because I have a horizontal logo/text which should be a little bit bigger. When the app launches it's first around 100 dp probably and then scales up/replaces with a bigger one. Any help? Thank you so much :)

**Comment by zoontek** [comment]
@traingethermarc Please provide the full command line / a screenshot of the generation

**Comment by traingethermarc** [comment]
Hi @zoontek - thanks for your reply!

MacBook-Pro:MyApp marc$ npx generate-bootsplash
✔ The path to the root of your React Native project … .
✔ The path to your static assets directory … assets
✔ Your original icon file … assets/logohq.png
✔ The bootsplash background color (in hexadecimal) … #FFF
✔ The desired icon width (in dp - we recommend approximately ~100) … 200
✔ Are you sure? All the existing bootsplash images will be overwritten! … yes
👍  Looking good! Generating files…

✨  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png (200x45)
✨  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png (300x67)
✨  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png (400x89)
✨  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png (600x134)
✨  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png (800x178)
✨  ios/MyApp/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png (200x45)
✨  ios/MyApp/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png (400x89)
✨  ios/MyApp/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png (600x134)
✨  assets/bootsplash_logo.png (200x45)
✨  assets/bootsplash_logo@1,5x.png (300x67)
✨  assets/bootsplash_logo@2x.png (400x89)
✨  assets/bootsplash_logo@3x.png (600x134)
✨  assets/bootsplash_logo@4x.png (800x178)
✨  ios/MyApp/BootSplash.storyboard
✨  android/app/src/main/res/drawable/bootsplash.xml
✏️   Editing android/app/src/main/res/values/colors.xml
✅  Done! Thanks for using react-native-bootsplash.

**Comment by zoontek** [comment]
It should be enough. It might the iOS cache.
Did you clean your project after switching to 200dp? (and uninstall your app)

**Comment by traingethermarc** [comment]
I will try that once more and if not build it only my own :) - thank you very much and keep up the great work! 👍

**Comment by zoontek** [comment]
Don't forget to open the ˋBootSplash.storyboard` on Xcode to check if your logo is indeed 200dp wide.

If it is, clean hard 🧼 😄

**Comment by traingethermarc** [comment]
So I opened ˋBootSplash.storyboard and it has the dpi. It still loads in approx. 100 dp I guess. And then scales up to the new size once the js loads. Cleaned the project, uninstalled app.

**Comment by traingethermarc** [comment]
For around 1 second it has the small size and then once the bundle loads it scales up

**Comment by zoontek** [comment]
@traingethermarc Try to follow these steps: https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update/35783070#35783070

**Comment by zoontek** [comment]
@traingethermarc Did it solves it?
