### ISSUE TITLE
Optimizing docs

### ISSUE THREAD

**Issue by SergiOnGit** [zoontek/react-native-bootsplash#177]
@zoontek Can you add changelogs and upgrade guides for version 3 future releases?

**Comment by zoontek** [comment]
Hi 🙋‍♂️ 
I indeed not wrote release notes for the beta / RC, but a migration guide is available: https://github.com/zoontek/react-native-bootsplash/blob/3.0.0/MIGRATION.md

**Comment by SergiOnGit** [comment]
Hi,
i mean from version 3.0 to 3.1 for example.

**Comment by zoontek** [comment]
@SergiOnGit You mean releases notes? 😅 https://github.com/zoontek/react-native-bootsplash/releases

**Comment by SergiOnGit** [comment]
Yes but for version 3. Those are for version 2.

**Comment by zoontek** [comment]
@SergiOnGit I will add releases notes for the version 3.0.0 when the stable version will land 🙂

Until then, I would rather encourage to try `@next` version, but not release them like it's the latest (production) version available.

**Comment by SergiOnGit** [comment]
Oh sorry, I have read your words incorrectly "I indeed not wrote release notes for the beta" :D I haven't noticed "not" :D  
I noticed that @next version have one problem. Splash image moves and you had fixed it before in v3.0.0-alpha.2. Would be great if you fix it in @next too.

You need to add this lines in doc:

```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:windowDrawsSystemBarBackgrounds">true</item> <!-- add this -->
        <item name="android:windowTranslucentStatus">true</item> <!-- add this -->
    </style>
```

**Comment by zoontek** [comment]
@SergiOnGit Alpha version tried to use a new splash screen technique, but it breaks too much things: Detox tests, loading bundle indicator, small jumps like this. Beta and now RC rolled back to the good old system, but kept the Promise API.

I encourage you to update to the latest `@next` version, it should solve your issue 🙂

**Comment by SergiOnGit** [comment]
I have updated and that's why i say, you need to add those lines. Without them, splash moves.

**Comment by zoontek** [comment]
@SergiOnGit Are you testing on proper Android stock UI, or manufacturers custom UI? (like Xiaomi MIUI, Huawei EMUI, Samsung One UI…)

**Comment by SergiOnGit** [comment]
I have tested it on android emulator. Google pixel 2, api level 29.

Here is my styles.xml

```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
        <item name="colorAccent">#2273C8</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowTranslucentStatus">true</item>
    </style>

    <!-- Add the following lines (BootTheme should inherit from AppTheme) -->
    <style name="BootTheme" parent="AppTheme">
        <!-- set the generated bootsplash.xml drawable as activity background -->
        <item name="android:background">@drawable/bootsplash</item>
    </style>

</resources>
```

Last I remember, splash was moving only on Xiaomi, but now it happens on google pixel too. Looks like windowDrawsSystemBarBackgrounds and windowTranslucentStatus is fixing it.

**Comment by zoontek** [comment]
@SergiOnGit I think `<item name="android:windowTranslucentStatus">true</item>` is enough. If you confirm, I will add a warning in the `README`.

PS: No issue on a physical Pixel (Android 10).

**Comment by SergiOnGit** [comment]
@zoontek I have checked and I can confirm that only `<item name="android:windowTranslucentStatus">true</item>` is enough.
