### ISSUE TITLE
[iOS] Wrong image appearing for a few seconds after changing it

### ISSUE THREAD

**Issue by mCodex** [zoontek/react-native-bootsplash#178]
Hello, first of all thanks for this awesome library.

I've been using it for awhile, however I just found something that is a little strange. 

Today, I installed this library in a fresh new project. Everything went fine, I generated a new splashscreen using `yarn generate-bootsplash` then I saw the image that I chosen wasn't good then I regenerated again with `yarn generate-bootsplash` using another image. However, on iOS something strange started happening which is in the first few seconds the old image was appearing and then it automatically changed to the most recent one.

After that I thought it could be my image which may be wrong.

Despite of that, I had to change the splash screen in another project which has been using this library for awhile. So, this project had a previous splash screen then I changed the image to the new one, but happened the same above again. For a few seconds the old image shows for a little while and then it switch to the most recent one.

After that, I checked another project that I successfully changed the image a month ago and saw that project was using the v2.2.5 then I tried changing the splash screen from the project above using v2.2.5 and it worked as expected.

I've tested all scenarios using:

- React-Native 0.63.3
- React-Native-Bootsplash 2.2.8 and 2.2.5
- iOS Emulator - iPhone 11 with iOS 14

**Comment by zoontek** [comment]
Hello @mCodex 👋

This is probably a duplicate of https://github.com/zoontek/react-native-bootsplash/issues/105

**Comment by mCodex** [comment]
Hi, thanks for the quick response. Sorry, I searched here but couldn't find anything related.

Yeah, could be related! I'll try to do the steps that you wrote there in another project and closing this issue for now.

Many thanks!

Have a nice day!
