### ISSUE TITLE
Can not hide the splash screen in the latest version 3.0.1

### ISSUE THREAD

**Issue by massoprod** [zoontek/react-native-bootsplash#183]
# Can not hide the splash screen

Library version: 3.0.1

Hi.

I tried to install the latest package version, but I was not able to hide the splash screen in JS code.
Splash screen was initialized correctly so it was shown, but RNBootSplash.hide() function seems to be not working.

I hade to downgrade package to older version.

**Comment by zoontek** [comment]
@massoprod Please respect the issue template.

**Comment by kbrandwijk** [comment]
I have the same issue after upgrading to 3.0.2. Works on Android, but doesn't hide on iOS.

```
Possible Unhandled Promise Rejection (id: 0):
Error: A bootsplash task is already pending
```

**Comment by zoontek** [comment]
@kbrandwijk Same as @massoprod. Please provide additional informations. They are requested when you create an issue, see https://raw.githubusercontent.com/zoontek/react-native-bootsplash/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by nkaramarko** [comment]
i am having same error :
Error: A bootsplash task is already pending

If app is in background for a while, when it comes to foreground it keeps reloading the splash screen and i get this error. App shows splash screen, then it hides, then 1 second later again shows the splash screen then hides it.. and it keeps going like this forever. app needs to be restarted completely for this to disappear. and every time it reloads it shows this same error.

package version 3.0.1

**Comment by zoontek** [comment]
@nkaramarko Could you please share some JS code?

**Comment by zoontek** [comment]
Closed in favor of https://github.com/zoontek/react-native-bootsplash/issues/183

**Comment by zoontek** [comment]
I recommend everyone to update to the latest version https://github.com/zoontek/react-native-bootsplash/releases/tag/3.1.0
