### ISSUE TITLE
Colored Status Bar and Navigation on Android

### ISSUE THREAD

**Issue by jawil003** [zoontek/react-native-bootsplash#186]
# Feature request

## Why it is needed

My App is coloring every View Background Color with the correct Status Bar Color so they matching. So I would like to do this too on the SplashScreen for a consistent User Experience.

## Possible implementation

I guess when the App theme defines the "colorPrimaryDark" it should color the STtausBar in that Color but somehow it is not working maybe there is another theme Property which I could try idk.

### Code sample

styles.xml:
```
<resources>

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/primaryColor</item>
        <item name="colorPrimaryDark">@color/primaryDarkColor</item>
        <item name="android:textColor">@color/primaryTextColor</item>
        <item name="android:strokeColor">@color/primaryTextColor</item>
    </style>

    <!-- Add the following lines (BootTheme should inherit from AppTheme) -->
    <style name="BootTheme" parent="AppTheme">
        <!-- set the generated bootsplash.xml drawable as activity background -->
        <item name="android:background">@drawable/bootsplash</item>
    </style>

</resources>
```

AndroidManifest.xml:
```
<manifest...>
  ...
  <application>
      <activity
            android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
            android:launchMode="singleTask"
            android:theme="@style/BootTheme">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
  </application>
</manifest>
```

**Comment by zoontek** [comment]
@jawil003 What your are looking for is `android:statusBarColor` & `android:navigationBarColor`

```xml
<resources>

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:statusBarColor">@android:color/white</item>
        <item name="android:navigationBarColor">@android:color/white</item>
    </style>

    <style name="BootTheme" parent="AppTheme">
        <!-- will inherit from your AppTheme -->
        <item name="android:background">@drawable/bootsplash</item>
    </style>

</resources>
```

**Comment by jawil003** [comment]
> @jawil003 What your are looking for is `android:statusBarColor` & `android:navigationBarColor`
> 
> ```xml
> <resources>
> 
>     <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>         <item name="android:statusBarColor">@android:color/white</item>
>         <item name="android:navigationBarColor">@android:color/white</item>
>     </style>
> 
>     <style name="BootTheme" parent="AppTheme">
>         
>         <item name="android:background">@drawable/bootsplash</item>
>     </style>
> 
> </resources>
> ```

Thank you for the fast answer I know it is not really something about this Library, but I couldn't find a good ressource about the style properties on Android Developers.

**Comment by zoontek** [comment]
Indeed, this is not related to this library at all.
