### ISSUE TITLE
Background Image Support (Specificly for IOS)

### ISSUE THREAD

**Issue by Yashpk789987** [zoontek/react-native-bootsplash#188]
I want to show background Image in splash screen for my project

for android i achieved  this by editing bootsplash.xml file like this

```
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
    <item android:drawable="@drawable/bg" />   <-- By adding this line
    <item>
        <bitmap android:src="@mipmap/bootsplash_logo" android:gravity="center" />
    </item>
</layer-list>
```

![WhatsApp Image 2020-12-09 at 10 46 29 PM](https://user-images.githubusercontent.com/43312758/101663892-1021e580-3a00-11eb-9f2a-ae6e0d6d1142.jpeg)

but i am unable to do so in IOS
please can anyone help me ??

**Comment by zoontek** [comment]
Sorry, this is not related to this library and not an issue / a feature request. You can post on StackOverflow for help if you want 🙂
