### ISSUE TITLE
Image fades in on launch?

### ISSUE THREAD

**Issue by kg-currenxie** [zoontek/react-native-bootsplash#189]
# Feature request

Any ideas why the image is fading in _after_ the animation to fullscreen finishes? 
It should appear immediately.

Gif:

![Kapture 2020-12-10 at 14 43 25](https://user-images.githubusercontent.com/48229166/101732546-58243380-3af8-11eb-9a20-a3383878f166.gif)

I just followed the readme steps.

## Why it is needed

Ugly with a completely black screen. It's unlike the "normal" iOS behavior.
It also worked fine with react-native-splashscreen

## Misc

- RNBootSplash 3.1.2
- RN 61.5
- XCode 12.2
- iPhone 11 Pro

Generated storyboard with
```
yarn react-native generate-bootsplash ios/CurrenxieMobileReactNative/Images.xcassets/SplashImage.imageset/Logo_WhiteOnBlack.png \
  --background-color=000000 \
  --logo-width=180 \
  --assets-path=assets
```

**Comment by kg-currenxie** [comment]
Seemed I could solve it like this: https://stackoverflow.com/questions/63978396/launch-screen-not-working-on-ios-14-with-xcode-12

- Delete app
- Reboot simulator
- Install app again

lol Apple

**Comment by zoontek** [comment]
@kg-currenxie Yeah, it's an issue related to the device app icons & splash screens cache 😅
