### ISSUE TITLE
I cannot see any splash screen in IOS device, only react native app name screen is visible ,what is .xib support ?

### ISSUE THREAD

**Issue by hussainhspl** [zoontek/react-native-bootsplash#19]
### 💻 My environment

- react-native-bootsplash version:
- react-native version:
- Platform: ios / android / both
- OS version: ?
- Device: brand + model
- Simulator: yes / no
- Android Studio version: ?
- Android buildToolsVersion: ?
- Xcode version: ?

### 🕵️‍♂️ Reproducing the issue

Explain what you did, what you expected to happen, and what actually happens.
Provide some code or screenshots if needed.

### 🤞Solution

Do you know what needs to be done to address this issue?
Ideally, provide a pull request with a fix.

**Comment by zoontek** [comment]
The react native app name screen is named Launchscreen.xib (it's the format supported).
You can edit it directly in Xcode
