### ISSUE TITLE
Splash disappeared where I'm not hide it, on Android

### ISSUE THREAD

**Issue by srgrbth** [zoontek/react-native-bootsplash#192]
# Bug report

## Summary

Sorry, I'm poor in english.
On Android, I'm not hide splash.
But, splash disappeared.
Is this expected behavior?

I want hide splash in another activity(later time and another scene).
Is this possible?

Thanks a lot!

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
(node:41353) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 564.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_272 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: react-native-bootsplash@3.1.2

## Steps to reproduce

1.
react-native init AAA
yarn add styled-components
yarn add typescript @types/react @types/react-native @types/styled-components babel-plugin-root-import --dev
yarn add @react-navigation/native
yarn add react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
yarn add @react-navigation/stack
yarn add react-native-bootsplash
yarn react-native generate-bootsplash src/Assets/Images/app_splash.png \
--background-color=c6d9e9 \
--logo-width=100 \
--assets-path=assets

2.
pod install

3.
write code in Installation

Describe what you expected to happen:

1.
Splash remain on both OS.
But, in Android, splash disappeared.

**Comment by zoontek** [comment]
Please respect the setup entirely.
