### ISSUE TITLE
Cannot generate assets, error Unrecognized command "generate-bootsplash".

### ISSUE THREAD

**Issue by alex-vasylchenko** [zoontek/react-native-bootsplash#197]
# Bug report
## Summary

Get an error trying to generate assets:
Run this in terminal:

```bash
npx react-native generate-bootsplash ./src/assets/images/app/logo.png --background-color=000 --logo-width=200 --assets-path=./src/assets/images/bootsplash
```

```bash
warn Package react-native-bootsplash has been ignored because it contains invalid configuration. Reason: Unexpected token {
error Unrecognized command "generate-bootsplash".
info Run "react-native --help" to see a list of all available commands.
```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 1.18 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.17.0 - ~/.nvm/versions/node/v8.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v8.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.1.2

**Comment by zoontek** [comment]
Hi. Try upgrading to **at least** node 10. One of the dependencies, `chalk`, require it: https://github.com/chalk/chalk/releases/tag/v4.0.0 (even `@react-native-community/cli` require >= 8.3)

Latest LTS is v14: https://nodejs.org/en/

If you have to use multiple node versions, I recommend `fnm`: https://github.com/Schniz/fnm

**Comment by zoontek** [comment]
<img width="1264" alt="Screenshot 2020-12-24 at 00 07 08" src="https://user-images.githubusercontent.com/1902323/103043124-15447000-457c-11eb-951c-2ca4a632ea58.png">

Confirmed, just update `node`.

**Comment by Gabsys** [comment]
![image](https://user-images.githubusercontent.com/23636171/103476885-66622880-4df4-11eb-8ae8-747d4fbe47d2.png)

I am using node 10 but still facing the same issue
React Native version: 0.59.10

**Comment by zoontek** [comment]
@Gabsys No, that's a different one. Your react-native version (and the react-native CLI) is too old. Just check the support at the top of the README: https://github.com/zoontek/react-native-bootsplash#support

**Comment by Gabsys** [comment]
My bad. Issue solved after upgrading my react native to 0.63. Sorry & thanks!

**Comment by uadapps** [comment]
I have the same issue with node 12 and react-native 0.64.0

**Comment by amitsharma-007** [comment]
Any Solution? I am too facing the same issue with the latest react-native and node versions.

**Comment by yusufbadurohman** [comment]
Please run this in terminal:

`npx generate-bootsplash --help` or `yarn generate-bootsplash --help`

**Comment by lockykeaney** [comment]
> 

This returns and error saying the package does not exist.
```
❯ npx generate-bootsplash --help
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/generate-bootsplash - Not found
npm ERR! 404 
npm ERR! 404  'generate-bootsplash@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Has this ever been updated or fixed? Node version is 16.15.0 and RN is 0.67.0, but I just keep getting command is not found.

**Comment by zoontek** [comment]
@lockykeaney You have to install the package first

**Comment by lockykeaney** [comment]
@zoontek What package do I install? The command `generate-bootplash` does not exist, and when prefaced by `react-native` it still can't be found. 

`npx react-native generate-bootsplash --help` and `yarn react-native generate-bootsplash --help` don't return any mention of the `generate-bootsplash` command either. I've run that in the project root where RN is installed, and just in the home directory with a global install as well. The docs don't have any reference to installing a package to create the assets.

**Comment by zoontek** [comment]
@lockykeaney https://github.com/zoontek/react-native-bootsplash#setup

**Comment by fondue-tech** [comment]
This is still issue, Im using node 18.1.0.

**Comment by zoontek** [comment]
@fondue-tech No. I'm using Node 18 too.

Just be sure that:
- The package is installed
- You are using `yarn react-native generate-bootsplash` or `npx react-native generate-bootsplash`

**Comment by fondue-tech** [comment]
@zoontek I do. Package is installed.
![Screenshot 2022-09-10 at 16 15 18](https://user-images.githubusercontent.com/74980407/189477118-f982cf99-8eb9-4a71-975e-b7895429f53e.png)

I try using npx and yarn 
![Screenshot 2022-09-10 at 16 18 07](https://user-images.githubusercontent.com/74980407/189477145-37f936e7-1d5e-4c81-be46-6fd70c4781ae.png)

**Comment by zoontek** [comment]
@fondue-tech I see "monorepo" in your path, you correctly disabled hoisting for react-native and react-native-* packaged?

**Comment by fondue-tech** [comment]
@zoontek This is currently just a folder name, its just pure react native application, without expo.
I run yarn info got following as well
![Screenshot 2022-09-10 at 16 22 25](https://user-images.githubusercontent.com/74980407/189477285-bf7a461f-a32e-4eab-b156-0d9279a4281b.png)

**Comment by zoontek** [comment]
@fondue-tech react-native version? OS?

**Comment by fondue-tech** [comment]
@zoontek
Here ! 
`System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 20.88 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
    Watchman: 2021.09.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.1 => 0.68.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

**Comment by zoontek** [comment]
@fondue-tech There is an issue with your setup here:

> @react-native-community/cli: Not Found

If you try to run `yarn react-native --help` alone, does it works? Anyway, it's not related to this package plugin. I asked because I didn't tried yet with RN 0.70, but it fully works with RN 0.68.

**Comment by fondue-tech** [comment]
@zoontek Somehow I manage to fix the issue, i removed the lock files and node_packages and reinstalling again. Now the command is reconegnized.
Thank for blazingly fast response to my issue.
