### ISSUE TITLE
null is not an object (evaluating 'NativeModule.hide')

### ISSUE THREAD

**Issue by AlaaElden98** [zoontek/react-native-bootsplash#202]
# Bug report

## Summary
I have installed the package successfully and followed the instructions as it says, but it's not working and giving me a warning that the "NativeModule is null".

## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 834.94 MB / 7.90 GB
  Binaries:
    Node: 15.5.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.3.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 24, 28, 29, 30
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.2
      System Images: android-28 | Android TV Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 1.7.0 - C:\Program Files (x86)\Java\jdk1.7.0\bin\javac.EXE
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.1.2

## Steps to reproduce

There is no much work actually, just
- install the package and follow the instructions
- the issue is on Android, I didn't test it on IOS
- I run the app on a simulator

## Reproducible sample code

The warning I get
![Screenshot 2021-02-06 082451](https://user-images.githubusercontent.com/34111697/107111038-53a89c80-6855-11eb-8c9a-51a2d58d1ade.png)

The code I use
![Screenshot 2021-02-06 082611](https://user-images.githubusercontent.com/34111697/107111054-75a21f00-6855-11eb-813f-66584703aa3d.png)

**Comment by zoontek** [comment]
@AlaaElden98 The package is not correctly linked. Did you ran a ˋpod install`?

**Comment by AlaaElden98** [comment]
> @AlaaElden98 The package is not correctly linked. Did you ran a `pod install`?
@zoontek  I'm working on windows, so I'm only working with android, I cannot run `pod install`, is that seems right or what?

**Comment by AlaaElden98** [comment]
### okay, I found out what was wrong.
**inside `AndroidManifest.xml` there were two attributes with the same values and names in different activities.
in the instructions the AndroidManifest.xml file is like that:**
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.rnbootsplashexample">

  

  <application
    android:name=".MainApplication"
    android:label="@string/app_name"
    android:icon="@mipmap/ic_launcher"
    android:roundIcon="@mipmap/ic_launcher_round"
    android:allowBackup="false"
    android:theme="@style/AppTheme">

    <activity
      android:name=".MainActivity"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
      android:label="@string/app_name"
      android:windowSoftInputMode="adjustResize"
      android:exported="true"
      android:launchMode="singleTask">
    </activity>

    
    <activity
      android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
      android:theme="@style/BootTheme"
      android:launchMode="singleTask">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>

    

  </application>

</manifest>

**My approach is to delete that line `android:launchMode="singleTask" ` from the first activity, so the file will look like this :**
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.rnbootsplashexample">

  

  <application
    android:name=".MainApplication"
    android:label="@string/app_name"
    android:icon="@mipmap/ic_launcher"
    android:roundIcon="@mipmap/ic_launcher_round"
    android:allowBackup="false"
    android:theme="@style/AppTheme">

    <activity
      android:name=".MainActivity"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
      android:label="@string/app_name"
      android:windowSoftInputMode="adjustResize"
      android:exported="true"
    >
    </activity>

    
    <activity
      android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
      android:theme="@style/BootTheme"
      android:launchMode="singleTask">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>

    

  </application>

</manifest>

**That's it, I don't know why,but it worked!**

**Comment by boobzzz** [comment]
Didn't work for me.
@zoontek can you provide solution for this issue?
