### ISSUE TITLE
[iOS] App launches after 2-3 minutes on second launch

### ISSUE THREAD

**Issue by DovletAmanov** [zoontek/react-native-bootsplash#206]
# Bug report

## Summary
Hi, I successfully did setup without problem and had successful build. When launching app for the first time, there is no problem, Splash Screen hides in 2-3 seconds. But after killing app and relaunching, Splash Screen get stuck for 2-3 minutes and if on real device then it calls package manager to build js bundle and run initial render function of app, if on simulator, it calls it calls package manager to build js bundle and runs initial render function of app but app is still stuck on SplashScreen. I think it is related to native thing, not js side. 
Any help/suggestion appreciated. Thanks in advance.

## Environment info

```bash

System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1007.82 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.1.4

## Steps to reproduce
1. build and run app
2. kill app
3. launch again

Describe what you expected to happen:

1. Not to wait that much time(2-3 minutes)  on second launch

## Reproducible sample code

AppDelegate.m
```
#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>
#import "AppDelegate.h"

#import "RNFBMessagingModule.h"

#import <FirebaseMessaging.h>
#import <React/RCTLog.h>

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <React/RCTLinkingManager.h>
#import "RNBootSplash.h" // <- add the header import


#if DEBUG
#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif
#endif


@import UIKit;
@import Firebase;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  // Disabling notification badge from init ~ Dovik
  application.applicationIconBadgeNumber = 0;

  
  if ([FIRApp defaultApp] == nil) {
     [FIRApp configure];
   }



  #if DEBUG
      #ifdef FB_SONARKIT_ENABLED
        InitializeFlipper(application);
      #endif
  #endif


  NSDictionary *appProperties = [RNFBMessagingModule addCustomPropsToUserProps:nil withLaunchOptions:launchOptions];

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"myapp"
                                            initialProperties:appProperties];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:255.0f green:255.0f blue:255.0f alpha:1];
  

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];


  

 // Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;
   

  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // <- initialization using the storyboard file name

  return YES;
}

// Called when a notification is delivered to a foreground app.
-(void)userNotificationCenter:(UNUserNotificationCenter *)center
      willPresentNotification:(UNNotification *)notification
        withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  // Still call the JS onNotification handler so it can display the new message right away
  NSDictionary *userInfo = notification.request.content.userInfo;
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo
                                fetchCompletionHandler:^void (UIBackgroundFetchResult result){}];

  // hide push notification
  completionHandler(UNNotificationPresentationOptionAlert);
}

////Called when a notification is delivered to a foreground app.
//- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler{
//
//    NSDictionary *userInfo = notification.request.content.userInfo;
//    //Foreground
//    NSLog(@"APP_PUSH from foreground %@", userInfo);
//
//   [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo
//   fetchCompletionHandler:^void (UIBackgroundFetchResult result){}];
//   completionHandler(UNNotificationPresentationOptionAlert);
//}








- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// Add this above `@end`:
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

// Add this above `@end`:
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}



// Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
 [RNCPushNotificationIOS didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
  [FIRMessaging messaging].APNSToken = deviceToken;
}
// Required for the notification event. You must call the completion handler after handling the remote notification.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];

}
// Required for the registrationError event.
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
 [RNCPushNotificationIOS didFailToRegisterForRemoteNotificationsWithError:error];
}
// Required for localNotification event
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  [RNCPushNotificationIOS didReceiveNotificationResponse:response];
}




@end
```

**Comment by zoontek** [comment]
I never saw a similar behavior before. Are you sure it happens because of this lib? Did you tried to disable it to see if it continues to happen (just remove the `[RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];` and don't call `BootSplash.hide()` in your JS.

**Comment by gayathri-aarvm** [comment]
In my case, the crash happened immediately after the app launch

**Comment by gayathri-aarvm** [comment]
> I never saw a similar behavior before. Are you sure it happens because of this lib? Did you tried to disable it to see if it continues to happen (just remove the `[RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];` and don't call `BootSplash.hide()` in your JS.

I have tried this. After removing the mentioned line above the app is not crashing. 

I got a error like this.

`Use of undeclared identifier 'RNBootSplash'`

**Comment by DovletAmanov** [comment]
> I never saw a similar behavior before. Are you sure it happens because of this lib? Did you tried to disable it to see if it continues to happen (just remove the `[RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];` and don't call `BootSplash.hide()` in your JS.

I tried like you said, simulator started to work as a expected but real device still stucks for 2-3 minutes. As you said, it might not be related to this lib but, before installing this module, I used to use react-native-splash-screen and there was no 'stuck' issue at the launch. Do you have any idea what could cause this issue?

**Comment by DovletAmanov** [comment]
Btw, now I realized that when running on real device as `release` mode, app not getting stuck, but on `debug` mode, it gets stuck. Also `[RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]` and `BootSplash.hide()` are both removed right now

**Comment by zoontek** [comment]
@DovletAmanov Did you correctly clean react-native-splash-screen optcode?

- Use https://github.com/pmadruga/react-native-clean-project to nuke all caches.
- Delete Xcode DerivedData folder
- Uninstall the app from you phone
- Restart you phone (to reset the on device spotlight cache)
- Rebuild and reinstall the app then

**Comment by DovletAmanov** [comment]
Yes, I read about it and cleaned as you mentioned

**Comment by zoontek** [comment]
@DovletAmanov Did you ran correctly all steps? If it only fail release, connect a device and run the release mode with debug enabled to see what it say.

**Comment by DovletAmanov** [comment]
Ok, I will try and inform you. Thanks a lot

**Comment by Gyeop** [comment]
I'm in the same situation as th author(react-native-splash-scrren migration) , this should only occur in debug mode.

If you are writing the code below, pleasse try to remove it.
```js
NativeModules.DevSettings.setIsDebuggingRemotely(true);
```

**Comment by zoontek** [comment]
It might be related: https://github.com/crazycodeboy/react-native-splash-screen/issues/512

**Comment by zoontek** [comment]
@DovletAmanov Did you tried with a fresh project?

**Comment by DovletAmanov** [comment]
No, I didn't try with fresh project but I tried again with cleaning `react-native-clean-project` and nothing new, same result as it was before cleaning.

**Comment by zoontek** [comment]
@DovletAmanov You can use the /example project from the repo to try.

**Comment by DovletAmanov** [comment]
Ok

**Comment by zoontek** [comment]
@DovletAmanov Did you tried it? If you say there is no issue on a fresh project, I will advise opening an issue on the [react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen/).

I cannot help debugging other libs if this one isn't responsible for the issue 😕

**Comment by A-Yatsyk** [comment]
[IOS] I have had the similar issues. BootSplash.storyboard doesn't hide on second launch 😔

**Environment**

System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 218.18 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /var/folders/ts/9bfpymvx7h1d_250rt6j61n80000gn/T/yarn--1617392544218-0.8045717743643996/node
    Yarn: 1.22.4 - /var/folders/ts/9bfpymvx7h1d_250rt6j61n80000gn/T/yarn--1617392544218-0.8045717743643996/yarn
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.2, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.3, 31.0.0
      System Images: android-24 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by zoontek** [comment]
I'm closing this since it's impossible do reproduce this and probably not related to this library.
