### ISSUE TITLE
Cannot find module '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by Zestpond** [zoontek/react-native-bootsplash#208]
Hi, I have issue when run `yarn start` and can not start
react-native-bootsplash has been ignored because it contains invalid configuration. Reason: Cannot find module '@babel/runtime/helpers/interopRequireDefault'

I using react-native-bootsplash@3.1.5

**Comment by zoontek** [comment]
@Zestpond Please fill the issue template or this will be closed
