### ISSUE TITLE
There is a native module RNBootSplash error

### ISSUE THREAD

**Issue by cx5168** [zoontek/react-native-bootsplash#21]
Follow the steps to configure it and get an error.
react-native: 0.60.4
react-native-bootsplash: 1.0.0

![img_20190902](https://user-images.githubusercontent.com/29448456/64094962-67b2b980-cd98-11e9-85d0-3f85ab156c88.png)

**Comment by cx5168** [comment]
I solved it.
The steps to update MainApplication.java are not required, you should delete the import.

**Comment by zoontek** [comment]
Manual linking is not mandatory for RN 0.60+. It's in the README 🙂
