### ISSUE TITLE
react-navigation example

### ISSUE THREAD

**Issue by charbelsako** [zoontek/react-native-bootsplash#210]
Can you provide an example on how to add the animation while using `react-navigation`

**Comment by zoontek** [comment]
@charbelsako There is nothing specific about `react-navigation`. You can check the "Used by" list to find a few examples:

- https://github.com/echobind/react-native-template/blob/master/template/src/App.tsx
- https://github.com/berty/berty/blob/master/js/packages/messenger-app/App.tsx
- https://github.com/NewBieBR/typescript-react-native-starter/blob/master/src/App.tsx
- https://github.com/azhavrid/movie-swiper/blob/master/src/Application.tsx
