### ISSUE TITLE
Splash Screen gets stuck when using multiple bundles

### ISSUE THREAD

**Issue by teuscm** [zoontek/react-native-bootsplash#217]
# Bug report

## Summary

When using another library like [react-native-threads](https://github.com/joltup/react-native-threads), the splash screen will show up (and get stuck) every time a new worker is spawned.

I assume this is happening because the worker is actually a new bundle instance being created in the background, and perhaps the code that checks for development reload is thinking that the worker is actually a reload.

I assume this is a problem with **both iOS and Android**, however, I'm only able to use the first platform at the moment.

## Environment info

`react-native info` output:

```bash
 BUNDLE  ./index.js <--- splash screen hides normally

 LOG  Arguments [49, [49, 54, 49, 54, 57, 57, 51, 54, 57, 56, 48, 56, 49]]
 LOG  Running "myapp" with {"rootTag":1,"initialProps":{}}
 BUNDLE  ./worker.js <-- splash screen comes back as soon as a worker is spawned.
 
 BUNDLE  ./worker.js 

 BUNDLE  ./worker.js 

 BUNDLE  ./worker.js 
```

Library version: 3.2.0

## Steps to reproduce

1. Use any library that spawns multiple bundles for multiprocessing (like [the one I'm using](https://github.com/joltup/react-native-threads)).
2. The splash screen will hide for a quick second and will immediately come back after the worker has been spawned (and it will be stuck).  

Describe what you expected to happen:

1. The splash screen should come up and hide only in the root bundle (eg. BUNDLE ./index.js).
2. The splash screen should not interact with different bundle names (that is: BUNDLE ./index.js != BUNDLE ./worker.js).

## Reproducible sample code

Just run the [usage code](https://github.com/joltup/react-native-threads#usage) after installing react-native-threads and hiding the splash screen for the first time (a setTimeout helps in making sure you see the hiding animation, but not necessary).

**Comment by zoontek** [comment]
@teuscm Hi 👋 I not tested it, but I assume that it is due to splash screen reload on development.
Currently when you reload the JS bundle, the splash screen is displayed again to ensure the normal flow is respected.

This will not be removed since it's an useful feature for a lot of people. But you can use [patch-package](https://github.com/ds300/patch-package) to comment it.

https://github.com/zoontek/react-native-bootsplash/blob/3.2.0/ios/RNBootSplash.m#L69
https://github.com/zoontek/react-native-bootsplash/blob/3.2.0/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java#L99 (You have to return early here)

**Comment by teuscm** [comment]
> @teuscm Hi 👋 I didn't test it, but I assume that it is due to splash screen reload on development.
> Currently when you reload the JS bundle, the splash screen is displayed again to ensure the normal flow is respected.
> 
> This will not be removed since it's an useful feature for a lot of people. But you can use [patch-package](https://github.com/ds300/patch-package) to comment it.
> 
> https://github.com/zoontek/react-native-bootsplash/blob/3.2.0/ios/RNBootSplash.m#L69
> https://github.com/zoontek/react-native-bootsplash/blob/3.2.0/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java#L99 (You have to return early here)

Thanks for directing me into where that part of the code lies on android. I've found it on iOS before but I guess I didn't really know how many lines to comment out since I'm not familiar with the language.

I also think that reloading is a good feature, but I'd consider spawning a new worker different from reloading:

The bundle index.js never reloads in this exemple, but new bundles (named worker.js) are created in the background for cpu intensive tasks and they are just javascript instances of the "worker.js" file, not the "index.js/App".

I think a possible fix would be perhaps to check if the bundle being created has the same name of the root bundle, that is:

```bash
BUNDLE  ./index.js <--- this is the app bundle
[...]
BUNDLE  ./worker.js <--- this is the worker bundle (not a restart)
BUNDLE  ./index.js <--- this is the app bundle once again (aka. restart)
```

**Comment by teuscm** [comment]
![image](https://user-images.githubusercontent.com/30584910/112844095-b52d0080-9079-11eb-9939-c1b274465d15.png)

@zoontek Even after commenting these lines out and reseting the metro cache, I still face the same problems, which perhaps indicates that the issue lies somewhere else?

**Comment by zoontek** [comment]
Reset the Xcode cache too (`DerivedData`)

**Comment by abelyeupear** [comment]
@teuscm We had to downgrade to 2.2.8 to resolve this issue. We're not using `react-native-threads`, but we are swapping bundles so the problem is likely the same. Did commenting those line + removing `DerivedData` solve the issue for you?

**Comment by teuscm** [comment]
> @teuscm We had to downgrade to 2.2.8 to resolve this issue. We're not using `react-native-threads`, but we are swapping bundles so the problem is likely the same. Did commenting those line + removing `DerivedData` solve the issue for you?

Hello!

I couldn't really test removing derived data because I was in a hurry, but I've cleaned my build folder before resetting metro cache.

For the time being we've revert our splashscreen back to `react-native-splah-screen`, but I'm looking forward to use bootsplash once this issue gets handled.

**Comment by vrazn** [comment]
@zoontek Updating to the latest version makes the app get stuck on the splash screen (ios) simulator. Rolled back to 3.2.0 for now
We're using react-native-code-push, which probably does the same thing with swapping the bundles, but I'm not 100% sure

**Comment by zoontek** [comment]
@vrazn I can't reproduce that. Try cleaning your build in Xcode (DerivedData etc)?

https://user-images.githubusercontent.com/1902323/117258811-a8a48080-ae4d-11eb-906b-3f62945923db.mov

**Comment by vrazn** [comment]
Solved the problem.

For some reason had the ```[RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];``` line before the ```[self.window makeKeyAndVisible];``` and it somehow worked on the 3.2.0 version.
Sorry for misleading you @zoontek!

Followed the docs now
![image](https://user-images.githubusercontent.com/8733843/117272918-399b4c00-ae8e-11eb-9c59-264ab5512ec6.png)

**Comment by abelyeupear** [comment]
I can confirm that 3.2.3 fixes this! Also, @vrazn I think that the docs might have changed that recently because we had the same situation with the order of operations as you did.

So, to anybody reading this in the future:
1. Upgrade to 3.2.3+.
2. Make sure the order of your `AppDelegate.m` code is the same as @vrazn 's suggestion.
