### ISSUE TITLE
react-native run-android  two applications appear?

### ISSUE THREAD

**Issue by sharingjingang050241** [zoontek/react-native-bootsplash#22]
### 💻 My environment

- react-native-bootsplash version:1.0.0
- react-native version:0.60.5
- Platform: android 
- OS version: 7.1

### 🕵️‍♂️ Reproducing the issue
react-native run-android  two applications appear?
![image](https://user-images.githubusercontent.com/20335157/64095196-b78d8280-cd90-11e9-9d8b-36955b854422.png)

```
"react": "16.8.6",
"react-native": "0.60.5",
"react-native-bootsplash": "^1.0.0",
```
AndroidManifest.xml

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      
      <activity
        android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
        android:theme="@style/BootTheme"> 
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
    </application>

MainActivity.java
```Java
public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "wywdrgapp";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        RNBootSplash.show(R.drawable.bootsplash, MainActivity.this); // <- display the "bootsplash" xml view over our MainActivity
    }
}
`

how to solve this. thanks

**Comment by sharingjingang050241** [comment]
emmmmmmmmmmm, This is my problem，sorry
please close this .

**Comment by albert-carreras** [comment]
Can you explain what was wrong... Instead of just closing this? I'm facing the same issue

**Comment by rodolphefauquez** [comment]
@albert-carreras 
I had the problem too, but the solution is on the readme x).

In your manifest, you probably forgot to remove the default `<intent-filter>` lines from your original activity (.MainActivity)

Keep only the `<intent-filter>` of the 2nd activity ('com.zoontek.rnbootsplash.RNBootSplashActivity') :
```
<intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
```


So your manifest should be like something like that:

```
<application
    android:name=".MainApplication"
    ...
>

    <activity
      android:name=".MainActivity"
      android:exported="true"
      ...
      >
    </activity>

    <activity
      android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
      android:theme="@style/BootTheme">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>

    <!-- … -->
  </application>
```

**Comment by kylanhurt** [comment]
Thank you for the heads up. Fixed it for me as well.
