### ISSUE TITLE
No native splash screen registered warning on an expo ejected app, splash screen never hides.

### ISSUE THREAD

**Issue by luklew** [zoontek/react-native-bootsplash#220]
# Bug report

## Summary

This is an iOS only problem. Works as expected on Android.
When adding RNBootSplash to an expo ejected app, it throws an error on startup saying :
No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.

This is with Expo Splash screen code commented out inside AppDelegate.m

## Environment info

`react-native info` output:
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 104.18 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 3.2.0

## Steps to reproduce

1. Install RN BootSplash for iOS as specified in the instructions. As this is an expo ejected app, for iOS I have added the lines needed in AppDelegate.m into the initializeReactNativeApp function and commented out EXSplashScreenService lines.
2. Launch the app on iOS emulator or device (behaves the same on both)
3. App launches but throws  a warning : No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.
4. The splash screen on the device never hides.

Describe what you expected to happen:

1. The splash screens to hide when the hide() function is called.

## Reproducible sample code

Any ejected expo app using expo sdk 40.

**Comment by zoontek** [comment]
This package does not support Expo SDK. Please uses their API instead: https://docs.expo.io/versions/latest/sdk/splash-screen/

**Comment by luklew** [comment]
@zoontek is there no work around to get it work on iOS expo ejected react native app that you know of? Managed to get it working correctly on Android, and it works in DEBUG on iOS, only when I build 'release' the splash doesn't show. Wondering if you know any way just to get that last bit working?

**Comment by zoontek** [comment]
I don't know a lot about Expo fork since I don't use it. I suggest asking them directly, it's a commercial product and their support is on point 🙂

**Comment by luklew** [comment]
ok thanks! I'll tinker around and check with expo support to see if I can get it running.

**Comment by luklew** [comment]
ok thanks! I'll tinker around and check with expo support to see if I can get it running.

**Comment by stevenpersia** [comment]
Hi @luklew !
Did you found a solution ? Because this package works better than expo splash screen on Android. It could be great if it works same on iOS :)

**Comment by luklew** [comment]
> Hi @luklew !
> Did you found a solution ? Because this package works better than expo splash screen on Android. It could be great if it works same on iOS :)

Hi, I did not. For iOS I just replaced the expo splash image with my own and left it as it was.
