### ISSUE TITLE
Multiple/Dynamic Splash Screens

### ISSUE THREAD

**Issue by ReyhanFabianto** [zoontek/react-native-bootsplash#221]
# Feature request

Hi,
Thanks for the amazing library ! I was wondering if it's possible to have multiple splash/storyboards and display according to some JS logic.

## Why it is needed

If an app has dark-mode functionality, in which the value is stored JS side, we could display the appropriate splash screen matching the color scheme that of the current theme.

## Possible implementation

I'm not sure how it would work in the Java/Swift side since I have minimal experience with the both platforms.

### Code sample

So for example, we would be able to call `RNBootSplash.show({ splashScreen: 'darkSplashScreen', fade: true });`

**Comment by zoontek** [comment]
Hi! There nothing specific about this library to add dark mode splash screen support. You can follow this tutorial: https://brainsandbeards.com/blog/how-to-add-a-dark-mode-splash-screen-to-a-react-native-app (or anything you will find about dark theme)
