### ISSUE TITLE
Ability to hide status bar when splashscreen is visible

### ISSUE THREAD

**Issue by naishe** [zoontek/react-native-bootsplash#222]
# Feature request

Thanks for this library. I migrated away from [react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen) for my new project. This project requires me to hide the status bar during the splash screen display. I was [able to achieve this with the aforementioned library](https://github.com/crazycodeboy/react-native-splash-screen/issues/105#issuecomment-401966983). However, there seem to be no documentation about it in the readme. So, I am assuming it is a feature request at this point.

## Why it is needed

The UX people say it does not give immersive experience to the user with mismatching status bar with little notifications on it. It is purely cosmetic thing for me. But I have to agree it would be good if at least status bar could be set to the same color as splash screen background if it too difficult to hide it.

## Possible implementation

React-Native-Spash-Screen offers this setting when we initialize the library in Java. Please see here: https://github.com/crazycodeboy/react-native-splash-screen/issues/105#issuecomment-401966983 I am hoping that something similar should be possible here too.

### Code sample

I do not have a code sample at the moment. I may give it a go and see if I could come with up something.

Thanks again!

**Comment by zoontek** [comment]
@naishe Hi! This is not related to this library. Make your status bar translucent in your styles.xml (see https://github.com/zoontek/react-native-bootsplash/issues/52#issuecomment-580366701 - so you can draw under it)

**Comment by zoontek** [comment]
If you want to copy ˋreact-native-splash-screen` behavior (going totally fullscreen - which is not the same as hiding the status bar!) you just have to add this line to your `AppTheme`:
https://github.com/crazycodeboy/react-native-splash-screen/blob/master/android/src/main/res/values/styles.xml#L9

As you can see, this method only apply this theme:
https://github.com/crazycodeboy/react-native-splash-screen/blob/master/android/src/main/java/org/devio/rn/splashscreen/SplashScreen.java#L46

And as your `BootTheme` already inherit from you ˋAppTheme`, setting one single line in it will apply on both, immediately at app start

**Comment by naishe** [comment]
That's great. I really appreciate quick response. Thanks
