### ISSUE TITLE
RNBootSplash.show - cannot find symbol

### ISSUE THREAD

**Issue by zuberpalekar** [zoontek/react-native-bootsplash#229]
# Bug report

## Summary

```
MainActivity.java:13: error: cannot find symbol
      RNBootSplash.show(R.drawable.bootsplash, MainActivity.this);
                              ^
  symbol:   method show(int,MainActivity)
  location: class RNBootSplash
```

Set it up as mentioned in the documents.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.27 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /var/folders/g7/j7y621rd591dfkht5yhmpt3w0000gn/T/yarn--1619225897863-0.11830735118090141/node
    Yarn: 1.22.10 - /var/folders/g7/j7y621rd591dfkht5yhmpt3w0000gn/T/yarn--1619225897863-0.11830735118090141/yarn
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
```

Library version: 3.2.1

## Steps to reproduce

Application fails to build.

Describe what you expected to happen:

Expected it to build and run successfully.

## Reproducible sample code

`package com.company.dev.finche;
import android.os.Bundle; // Added for SplashScreen

import com.facebook.react.ReactActivity;
import com.zoontek.rnbootsplash.RNBootSplash; // Added for SplashScreen

public class MainActivity extends ReactActivity {

  // Added for Splash screen [Ref: https://medium.com/@appstud/add-a-splash-screen-to-a-react-native-app-810492e773f9]
  @Override
  protected void onCreate(Bundle savedInstanceState) {
      //SplashScreen.show(this);
      RNBootSplash.show(R.drawable.bootsplash, MainActivity.this);
      super.onCreate(savedInstanceState);
  }

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "mobile";
  }
}
`

**Comment by zoontek** [comment]
This is not an issue with the library.

1. Did you generate the bootsplash.xml drawable?
2. Is it in the correct directory?
3. Are you sure your imports are corrects?
4. Did you clean you Gradle cache / artifacts before building your app again?
