### ISSUE TITLE
Splash screen not hiding iOS; handleJavaScriptDidFailToLoad

### ISSUE THREAD

**Issue by rnnyrk** [zoontek/react-native-bootsplash#23]
👋 Hello!

First of all thanks for making this product. Seems there was need for a new splash screen package next to react-native-splash-screen. I've installed it yesterday and it seems to work on Android, but on iOS I'm getting the following error in xcode:

```
2019-09-04 09:55:44.408609+0200 Jobner[6735:2992237] +[RNBootSplash handleJavaScriptDidFailToLoad:]: unrecognized selector sent to class 0x104997c80
2019-09-04 09:55:44.409344+0200 Jobner[6735:2992237] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[RNBootSplash handleJavaScriptDidFailToLoad:]: unrecognized selector sent to class 0x104997c80'
*** First throw call stack:
```

The app is opening and the splash screen is show. But - as the error suggests with `handleJavaScriptDidFailToLoad` - it never disappears and the app doesn't continue to load. 

Any idea? 

### 💻 My environment

- react-native-bootsplash version: 1.0.0
- react-native version: 0.60.5
- Platform: iOS
- OS version: 12.1.4
- Device: iPhone X
- Simulator: No
- Xcode version: Version 10.3 (10G8)

### 🕵️‍♂️ Reproducing the issue

I've installed it following the README. Just after I've updated my project from 0.59.9 to 0.60.5, since `react-native-splash-screen` gave a lot of error and didn't seem to be supported anymore. So I tried this one. 

Then I'd run the project via xcode with an iPhone X connected. The project builds without issues (message build succeeded is shown), but the issue appears when opening  the app. 

<img width="1179" alt="Screenshot 2019-09-04 at 10 34 18" src="https://user-images.githubusercontent.com/4519142/64238957-9c8d5080-ceff-11e9-88c3-b81894929e34.png">

**Comment by zoontek** [comment]
@rnnyrk Hi 👋
I made a release which might fix the issue: https://github.com/zoontek/react-native-bootsplash/releases/tag/1.0.1 Can you give it a try?

**Comment by rnnyrk** [comment]
@zoontek Thanks for the fast fix. Update seems to work!
