### ISSUE TITLE
BootSplash automatically hides in React Native 0.64.0 

### ISSUE THREAD

**Issue by StampixSMO** [zoontek/react-native-bootsplash#230]
# Bug report

## Summary

Just upgraded to RN 0.64.0 from 0.64.4 and the splash activity hides automatically after the bundle is loaded. I had the splashscreen replicated in RN, to do some animation on the splashscreen logo. However, with this automatic hiding, it causes a weird flicker before my own replica component is rendered (instead of fading out when manually calling `hide()`).

## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.11 GB / 15.86 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 15.5.27130.2036 (Visual Studio Community 2017)
  Languages:
    Java: 15.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.2
    react-native: ^0.64.0 => 0.64.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 3.2.1

## Steps to reproduce

1. This issue is appearing on Android for me
2. Bootstrap a repo with RN 0.63.4 and react-native-bootsplash
3. Hide the bootsplash on your first app open
4. Test the functionality to work as expected (i.e. not hide when `hide()` is not called)
5. Upgrade to RN 0.64.0 using the upgrade helper from RN
6. Notice that the hiding is now implicit & automatic and that the `hide()` call never returns anymore.

Describe what you expected to happen:

1. After upgrading, to have the exact same behaviour (i.e. hiding the bootsplash manually)

**Comment by zoontek** [comment]
This is probably not related, I updated our app to RN 0.64 and it doesn't do that.

**Comment by StampixSMO** [comment]
Thanks for the prompt response @zoontek, apart from the `inlineRequires` metro config change, I have not missed anything (double-checked just now).

**Comment by zoontek** [comment]
Could you create a small repo with the minimum amount of code to reproduce the issue?
Thanks for the info, it was requested indeed (you set `Library version: x.x.x`)

**Comment by StampixSMO** [comment]
I don't succeed in a fresh repo to reproduce this issue @zoontek 
Feel free to close, I'll need to investigate deeper what is causing this issue in a bigger repo

**Comment by Emehado** [comment]
I had a similar case where I thought the splash screen hiding automatically... That wasn't the case at all. Modals are displayed on top of the splash screen. So if you're rendering a modal when your app launches, the splash screen is gonna be beneath it. Am not sure if that's the correct behavior.

**Comment by StampixSMO** [comment]
> I had a similar case where I thought the splash screen hiding automatically... That wasn't the case at all. Modals are displayed on top of the splash screen. So if you're rendering a modal when your app launches, the splash screen is gonna be beneath it. Am not sure if that's the correct behavior.

I wasn't rendering a modal :)

**Comment by fredikey** [comment]
I had a similar issue too, but in my case, it was caused by blocking the js thread (fetching and processing a lot of data). Try to  move all heavy operations after hide method

<img width="446" alt="image" src="https://user-images.githubusercontent.com/44212097/132553625-3662273c-7830-464e-9ca4-a7bf5c4cfe9f.png">
