### ISSUE TITLE
Make the image an optional parameter

### ISSUE THREAD

**Issue by warrier-97** [zoontek/react-native-bootsplash#233]
# Feature request

Currently, it is necessary to pass in an asset for this package to work and generate splash screens for me. Can this be made optional so as to make plainly colored splash screens?

## Why it is needed

This would enable us to generate plainly colored splash screens for use cases such as playing a lottie animation or some kind of a video from the JS side as soon as the app is launched.

**Comment by zoontek** [comment]
@warrier-97 That's a good idea. Can you make a pull request?
