### ISSUE TITLE
SplashScreen does not work in release for iOS, Android is OK

### ISSUE THREAD

**Issue by endlesstech** [zoontek/react-native-bootsplash#238]
# No Template

👉 Please follow one of the issue templates provided by the repo - if you are seeing this message, it means you haven't.

If you don't follow the issue template, we may immediately close it.

**Comment by endlesstech** [comment]
In Local dev, both platforms are working fine. But in release, for iOS is not working.

**Comment by sawariz0r** [comment]
@endlesstech What kind of behavior are you experiencing? 
I have some iOS users who report that they're just getting a black screen when launching the app

**Comment by sawariz0r** [comment]
@endlesstech Any changes?

**Comment by zoontek** [comment]
I could not reproduce this + no issue template.

**Comment by webraptor** [comment]
We're also getting production reports with this issue. Works perfectly on development, release on iOS has issues. Android is perfectly fine. Unfortunately we do not have reproduction steps other than upgrading from 3.1.5 to 3.2.3

**Comment by webraptor** [comment]
@zoontek https://github.com/zoontek/react-native-bootsplash/commit/a7908b71213cdaeb95cae1072b7a509065859592 this commit seems to be the culprit

**Comment by webraptor** [comment]
@zoontek we've just validated that all's okay on 3.2.2 as opposed to 3.2.3. Since 3.2.3 is supposed to improve development, but affects production builds on iOS, the best bet would be to revert that if the fix is not easy and straightforward.

**Comment by zoontek** [comment]
@webraptor Are you sure you call `initWithStoryboard` at the right place? https://github.com/zoontek/react-native-bootsplash#ios-1 (Just  before the `return`)

**Comment by webraptor** [comment]
> @webraptor Are you sure you call `initWithStoryboard` at the right place? https://github.com/zoontek/react-native-bootsplash#ios-1 (Just before the `return`)

Initially it was but then a `[FIRApp configure];` line was added in between. If it is critical that the `initWithStoryboard` be just before the return and nothing else, the readme should be updates so that this is emphasised, as it's not clear right now.

I'll update the code and reply later on after we have feedback from QA / users
