### ISSUE TITLE
[IOS] Splash disappears when modal becomes invisible

### ISSUE THREAD

**Issue by denis-tsmokalyuk** [zoontek/react-native-bootsplash#239]
# Bug report

## Summary
Splash disappears when modal (from react-native, react-native-modal, etc) becomes invisible.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 28.69 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1
    react-native: 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.2.3

## Steps to reproduce

1. Show Modal
2. Run RNBootSplash.show()
3. Hide Modal
4. Splash appears for a split second and disappears. splash visibility status === true

Describe what you expected to happen:

1. Set modal visibility to true
2. Run RNBootSplash.show()
3. Set modal visibility to false
4. Splash appears and does't disappear. splash visibility status === true

This issue was found in iOS Simulator.

https://user-images.githubusercontent.com/60439444/119676405-80091880-be46-11eb-89b1-ba3cfbaad012.mov

**Comment by zoontek** [comment]
This is tied to the fact that both (splash screen and modal) are implement using `UIViewController`.
Related: https://github.com/zoontek/react-native-bootsplash/issues/119
