### ISSUE TITLE
Issue with React Native Firebase.

### ISSUE THREAD

**Issue by rkaartikeyan** [zoontek/react-native-bootsplash#24]
### 💻 My environment

```
"dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-bootsplash": "^1.0.0",
    "react-native-firebase": "^5.5.6",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-reanimated": "^1.2.0",
    "react-navigation": "^3.12.0"
  },
```
- Platform: android
- OS version: 8.1
- Device: All
- Simulator: no
- Android buildToolsVersion: 3.4.1

### 🕵️‍♂️ Reproducing the issue

I have used React native firebase for push notifications. When I have opened the app and if I am getting a push notification, I can get the _body & title details in the .onNotification() callback of firebase.

But, in this callback function .onNotificationOpened(), _body & title are null, please check below screenshot.

![image](https://user-images.githubusercontent.com/3778591/64928854-5c04cf80-d83b-11e9-8493-0b7486658aba.png)

### 🤞Solution

I think its because of the bootsplash, I am getting that error. So please give me a solution.

**Comment by MoOx** [comment]
I guess if you remove totally react-native-bootsplash you don't have this issue anymore?

**Comment by zoontek** [comment]
@rkaartikeyan This looks similar to the issue treated by this PR https://github.com/zoontek/react-native-bootsplash/pull/11. Maybe it wasn't enough.

Could you provides your `AndroidManifest.xml`?

**Comment by rkaartikeyan** [comment]
Dear Friends,

as mentioned in the document, we have to pass the notification message in data attribute, and its resolved.
