### ISSUE TITLE
Support 'transparent' as a acceptable color.

### ISSUE THREAD

**Issue by kuasha420** [zoontek/react-native-bootsplash#242]
# Feature request

Support passing color transparent when generating assets. It can be replaced as @android/transparent color on android. Not sure about IOS.

## Why it is needed

It can greatly help with automatic light/dark mode situation. 

## Possible implementation

when transparent is supplied. Replace it with 

```xml
<resources>
    <color name="bootsplash_background">@android:color/transparent</color>
</resources>
```

NOT SURE ABOUT IOS.

**Comment by zoontek** [comment]
@kuasha420 Hi. This doesn't seems useful. What is the use-case?

**Comment by kuasha420** [comment]
@zoontek Hi,

This is useful in with Theme.AppCompat.DayNight.NoActionBar, where the system background changes automatically based on the System Theme. If the bootsplash background is transparent. then it will be white on light theme and a darkish color on dark theme. I can send in a gif once I am home. 

Cheers.

**Comment by zoontek** [comment]
This is a rather specific use case, I prefer not to implement such edge cases (and document them!) and let the developer update its `styles.xml` after bootstraping.

**Comment by kuasha420** [comment]
Understood. Would you consider accepting a PR for it? 

Cheers

**Comment by zoontek** [comment]
I don't think I would, sorry!

**Comment by AlfieJones** [comment]
I wouldn't consider it an edge case either, I think this would be worth adding in the future
