### ISSUE TITLE
Splash screen is not shown on app launch on android

### ISSUE THREAD

**Issue by badsyntax** [zoontek/react-native-bootsplash#244]
# Bug report

## Summary

When launching the app on android, the splash screen is not immediately displayed. It is only displayed after the JS has loaded. I see a blank background for a short time, then I see the splash screen. Is this the expected behaviour? 

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
    Memory: 75.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: Not Found
    npm: 7.12.1 - ~/.nvm/versions/node/v16.1.0/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.2.3

## Steps to reproduce

- Creat a new RN project with `npx react-native init SplashApp --template react-native-template-typescript`
- Follow the instructions in this repo README to install react-native-bootsplash
- Run the app on android with `npm run android`
- Notice when the app starts there is no splashscreen. The splash screen is only displayed after the app has loaded the javascript.

Describe what you expected to happen:

1. When the app launches I expect to immediately see a splashscreen

**Comment by badsyntax** [comment]
Hmm, actually, this seems to only be the case when launching the app using `react-native run-android`. If I install the app with `react-native run-android`, then close the app, then launch the installed app from the device, i don't see this behaviour.

**Comment by zoontek** [comment]
Clean your caches using `react-native-clean-project`.

**Comment by badsyntax** [comment]
I'm not sure it's related to caches as I installed it on a fresh RN project. Either way, it's working as expect. 

I want to say thanks for creating this project. It's the only splash library that works without any UI glitches. 

- https://github.com/crazycodeboy/react-native-splash-screen throws build errors when compiling android tests due to SDK version incompatibility
- expo-splash-screen has some weird UI glitches on android, see: https://github.com/expo/expo/tree/master/packages/expo-splash-screen#native-mode-pushes-splash-image-up-a-little-bit
