### ISSUE TITLE
AppDelegate.swift setup guide

### ISSUE THREAD

**Issue by M1chaelChen** [zoontek/react-native-bootsplash#245]
# Feature request

## Why it is needed
I'm using Swift which has AppDelegate.swift instead of AppDelegate.m. Does it work with swift? If so, can you please add a setup guide? Thanks!

## Possible implementation
Support for Swift

**Comment by zoontek** [comment]
@M1chaelChen I don't use Swift either, but it shouldn't be a problem?

**Comment by M1chaelChen** [comment]
@zoontek Thanks for the reply! I've got it working by doing the following:
1. Create a bridging header https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift
2. Add `#import "RNBootSplash.h"` in the bridging header file
3. Add `RNBootSplash.initWithStoryboard("LaunchScreen", rootView: rootView);` in `AppDelegate.swift`

Hope this helps if anyone has a similar question.

**Comment by M1chaelChen** [comment]
Closing the issue.

**Comment by mefjuu** [comment]
I think it's worth mentioning @M1chaelChen's Swift integration info in README.md

**Comment by zoontek** [comment]
@mefjuu React Native `AppDelegate` file is not written Swift, but Objective-C. If you mind doing the change by yourself (for what?), I assume you know what you are doing, and know Swift a bit.

**Comment by akuul** [comment]
@zoontek Could we please have a Swift example since React Native 0.77 moved AppDelegate to Swift ?
