### ISSUE TITLE
Is possible to make a full background image in the display?

### ISSUE THREAD

**Issue by fernando143** [zoontek/react-native-bootsplash#253]
Like I say in the title. Is possible to do a splash screen that fill the entire display? How can I do that?

Thanks!

**Comment by zoontek** [comment]
Hi! This is:

1) Not an issue with library itself, but more a question about Android drawable (check their doc)
2) A previously asked question, search for duplicates
3) If you don't find the answer, you can ask on [StackOverflow](https://stackoverflow.com)
