### ISSUE TITLE
Add support for multiple splash screens per Target ( ios )  / Flavor (android)

### ISSUE THREAD

**Issue by 29er** [zoontek/react-native-bootsplash#255]
maybe this can already be achieved with this library, but I would love to be able to create different Splash screens based on the IOS target, Android Build variant ( flavor )  that I choose. 
Has anyone done this using this library ?

**Comment by zoontek** [comment]
Hi, this can be done using standard android / iOS techniques (and this library, which is agnostic about them). I let you ask for help on StackOverflow or another website as this is an issues board.
