### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by grifotv** [zoontek/react-native-bootsplash#26]
Fantastic work! I'm currently using `react-native-splash-screen` but I'm considering switching to `react-native-bootsplash` based on this [comparison](https://github.com/zoontek/react-native-bootsplash#%EF%B8%8F%EF%B8%8F-comparison-with-react-native-splash-screen).

One clear advantage of `react-native-splash-screen` is the MIT license, so I was wondering which license this project will have.

**Comment by MoOx** [comment]
MIT https://github.com/zoontek/react-native-bootsplash/blob/3820bf0bd7d259c7e307b6c85f2ccd9d73fc8fb7/package.json#L4

@zoontek you really need to think about this for your packages :D

**Comment by grifotv** [comment]
@MoOx thanks. It should be ok to add a `LICENSE` file

**Comment by zoontek** [comment]
@grifotv Can you make a PR with it?

**Comment by zoontek** [comment]
Nevermind, I've done it: https://github.com/zoontek/react-native-bootsplash/commit/fea851cbc4d59a3a0796178dff9efb593ce8e34a
