### ISSUE TITLE
After Following all process, My App stops Displaying 

### ISSUE THREAD

**Issue by sheggietyn** [zoontek/react-native-bootsplash#263]
i Followed all the setup process and my App stops displaying on the Emulator then I later discovered that there are 2 
 @Override
protected void onCreate(Bundle savedInstanceState) {} in my MainActivity.java, one for my React navigation and the other one for bootsplash screen which is causing conflicts to the application on the emulator

please I would like to know how else I can do this in the mainactivity.java file

**Comment by zoontek** [comment]
@sheggietyn Please respect the issue template or this issue will be deleted soon

**Comment by ddikodroid** [comment]
> i Followed all the setup process and my App stops displaying on the Emulator then I later discovered that there are 2 @OverRide protected void onCreate(Bundle savedInstanceState) {} in my MainActivity.java, one for my React navigation and the other one for bootsplash screen which is causing conflicts to the application on the emulator
> 
> please I would like to know how else I can do this in the mainactivity.java file

how do you solve this issue?
