### ISSUE TITLE
Make splash screen for one platform only

### ISSUE THREAD

**Issue by mehdi-developer** [zoontek/react-native-bootsplash#272]
### Why it is needed?

I make the splash screen for iOS with xCode pretty much and it's very easy and simple with a drag and drop however I just need to use this awesome library just for android only . I wish it had some command to generate for both platforms or just one single platform ( iOS / Android ) . Thanks in advance .

### Possible implementation

Right now I delete all the files generated in the ios folder which are :

ios/YourProjectName/BootSplash.storyboard
ios/YourProjectName/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
ios/YourProjectName/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
ios/YourProjectName/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png

Then in the root of the project react-native.config.js I have to add these code lines so it doesn't install on ios when running `npm run ios` and don't throw a warning about `pod install` : 

`module.exports = {`
  `dependencies: {`
    `'react-native-bootsplash': {`
      `platforms: {`
        `ios: null,`
      `},`
    `},`
  `},`
`};`

**Comment by zoontek** [comment]
The generator already ignore `ios` creation if the directory doesn't exists.
You can safely delete the files generated on iOS, it has no impact at all.
