### ISSUE TITLE
4.x support for android api21?

### ISSUE THREAD

**Issue by mikehardy** [zoontek/react-native-bootsplash#275]
### Why it is needed?

Not a "need" per se but a desire, to match up with current react-native minSdkVersion on Android (which is 21)

It appears that between alpha01 and alpha02 of the new splashscreen API they added backwards compatibility and now support api21:

https://developer.android.com/jetpack/androidx/releases/core#core-splashscreen-1.0.0-alpha02

### Possible implementation

It may simply be that it "just" works now, vs when you first attempted to play with the api in it's alpha01 incarnation

Have you tried lowering minSdkVersion and already know it won't work?

If you have, and you know it won't work, please just say so :-), but if you simply haven't tried, I can try when I attempt to integrate v4 in a few days

**Comment by zoontek** [comment]
It's only a recommendation from the README, but it should run as promised on Android 21.

I dropped the support since the "minimal support" offered by the AndroidX core lib is just transition to the `AppTheme` (but no splash screen appears, only the background color if I remember it correctly)

**Comment by zoontek** [comment]
I'd rather push users to update to at least Android 6.x, not everyone has Facebook marketshare needs 🙂

**Comment by mikehardy** [comment]
I live in Ecuador, we have some ooooold phones around here. Pushing doesn't work, we just have to wait for them to die.
Then we have to wait for them to stop being revived again with hacked together screens and batteries and really die :laughing:

**Comment by zoontek** [comment]
Give it a try, but I just tried a Gradle sync with `minSdkVersion: 21` and see no issue. I will not implement / maintain a full custom fallback for these devices, a background color will be enough.

If you animate the logo in a smooth transition (like in the example), consider fading it in on react native bundle loaded, it could be a nice and clean solution for these users:

```ts
const isLegacy = Platform.OS === "android" && Platform.Version < 23;
const opacity = new Animated.Value(isLegacy ? 0 : 1);
const translateY = new Animated.Value(0);

const anims: Animated.CompositeAnimation[] = [
  Animated.spring(translateY, {
    useNativeDriver: true,
    toValue: Dimensions.get("window").height,
  }),
];

if (isLegacy) {
  anims.unshift(
    Animated.spring(opacity, { useNativeDriver: true, toValue: 1 }),
  );
}

Animated.sequence(anims).start();
```

**Comment by mikehardy** [comment]
I agree no special consideration should be done, while I want to support API21 I consider that "it runs" is good enough and happy even if it is pretty degraded as an experience. Cool trick on the fade on though, others may need it more than me and that chunk of code should help them

**Comment by zoontek** [comment]
I confirm, I just ran the example on an API 21 emulator with success. Only the background color is shown.

**Comment by mikehardy** [comment]
that's a "win" I think - I believe my new PR is valid then, with a push for 23 but mentioning 21 is possible though degraded
Of course wording is always open for debate :-), but at least technically it's not wrong then

**Comment by zoontek** [comment]
I also pushed a new version of `react-native-bars` that support Android 5.x for you: https://github.com/zoontek/react-native-bars/releases/tag/1.0.4

Same, I don't really wanna mention it in the `README.md` 😬
