### ISSUE TITLE
error: cannot find symbol  RNBootSplash.init(R.drawable.bootsplash, MainActivity.this); //    location: class drawable

### ISSUE THREAD

**Issue by arturasbortkevicius** [zoontek/react-native-bootsplash#281]
### Bug summary

While trying to build android app i get this error:

error: cannot find symbol
    RNBootSplash.init(R.drawable.bootsplash, MainActivity.this)                              ^
  symbol:   variable bootsplash
  location: class drawable

### Library version

4.0.0-beta.2

### Environment info

```shell
OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 880.87 MB / 7.92 GB
  Binaries:
    Node: 14.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 15.0.2 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1.just type react-native run-android

### Reproducible sample code

```js
package com.lukoil_serbia;

import android.os.Bundle;
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.zoontek.rnbootsplash.RNBootSplash;


public class MainActivity extends ReactActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    RNBootSplash.init(R.drawable.bootsplash, MainActivity.this); // <- initialize the splash screen

  }
  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "lukoil_serbia";
  }
}
```

**Comment by zoontek** [comment]
Take a look at the migration guide: https://github.com/zoontek/react-native-bootsplash/blob/master/MIGRATION.md

**Comment by tobiasalthoff** [comment]
I've the same problem with a clean installation of react-native-bootsplash. The migration guide doesn't help.

`/android/app/src/main/java/com/knipex/MainActivity.java:30: error: cannot find symbol
        RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
                                    ^
  symbol:   variable bootsplash
  location: class com.knipex.R.drawable
Note: /android/app/src/debug/java/com/knipex/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.`

**Comment by tobiasalthoff** [comment]
I've the same problem with a clean installation of react-native-bootsplash. The migration guide doesn't help.

> /android/app/src/main/java/com/***/MainActivity.java:30: error: cannot find symbol
        RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
                                    ^
  symbol:   variable bootsplash
  location: class com.***.R.drawable
Note: /android/app/src/debug/java/com/***/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.

**Comment by tobiasalthoff** [comment]
Ah, I have found the problem.

@zoontek You should update Setup Android Step 5 in the readme:

> RNBootSplash.init(MainActivity.this);

instead of

> RNBootSplash.init(R.drawable.bootsplash, MainActivity.this); // <- initialize the splash screen

**Comment by zoontek** [comment]
@tobiasalthoff Thanks, I forgot this line! I changed it.
