### ISSUE TITLE
I think minSdkVersion should be 21...

### ISSUE THREAD

**Issue by siddharth-kt** [zoontek/react-native-bootsplash#282]
### Why it is needed?

Thanks for such great lib.

I think minSdkVersion should be 21 because there are a lot of people still relying on old mobiles, so kindly do it or recommend us any solution to make it work for minSdkVersion 21 ?

**Comment by zoontek** [comment]
Hello, like the documentation said: `AndroidX splashscreen has basic support for 21 (only the background color), so 23 is best`
That's not on me, that's on Google. Set `minSdkVersion`, handle the fallback as you wish (several clues in this duplicate issue: https://github.com/zoontek/react-native-bootsplash/issues/275)

**Comment by siddharth-kt** [comment]
Thanks for such a fast reply, I have few other question :

- I am still using react-native 0.64.2 because react-native 0.65.x or 0.66.x have problems with other packages like react-native-video (exoplayer) so updating android/build.gradle as recommended in (https://github.com/zoontek/react-native-bootsplash) docs will be safe for me ?
- I also want to use https://github.com/zoontek/react-native-bars but its minimum requirement is react-native 0.65.0+ what should I do?
- This question is regrading https://github.com/zoontek/react-native-bars, when we start react-native app with system/device theme as dark then app opens with white device-navigation-bar color (when bootsplashing) how to set it to black/white according to system/device theme. (it you can share some link for help) 

Thanks anyways 🙂

**Comment by zoontek** [comment]
It should be fine, I just don't offer support for these versions (or at least free support, I guess if companies want to support these versions and have issues with the libs they can sponsor issue resolution 🙂 - it's still way cheaper than other solutions)
I'm personally use the latest version of React Native and our app only supports iOS 12+ and Android 6+

**Comment by siddharth-kt** [comment]
> It should be fine, I just don't offer support for these versions (or at least free support, I guess if companies want to support these versions and have issues with the libs they can sponsor issue resolution 🙂 - it's still way cheaper than other solutions) I'm personally use the latest version of React Native and our app only supports iOS 12+ and Android 6+

I got your point. Thanks for answering 🙂.

**Comment by zoontek** [comment]
@siddharth-kt Regarding react-native-bars, check the example project:

- MainActivity: https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/java/com/rnbootsplashexample/MainActivity.java#L24
- values/styles.xml: https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/res/values/styles.xml
- values-v27/styles.xml: https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/res/values-v27/styles.xml

**Comment by siddharth-kt** [comment]
> @siddharth-kt Regarding react-native-bars, check the example project:
> 
> * MainActivity: https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/java/com/rnbootsplashexample/MainActivity.java#L24
> * values/styles.xml: https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/res/values/styles.xml
> * values-v27/styles.xml: https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/res/values-v27/styles.xml
> 
> On Android < 6, set:
> 
> ```
> <resources>
> 
>     <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
>         
>         <item name="android:windowDrawsSystemBarBackgrounds">true</item>
>         <item name="android:fitsSystemWindows">false</item>
> 
>         <item name="android:windowTranslucentStatus">true</item>
>         <item name="android:windowTranslucentNavigation">true</item>
>     </style>
> 
>     
>     <style name="BootTheme" parent="Theme.SplashScreen">
>         <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
>         <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
>         <item name="postSplashScreenTheme">@style/AppTheme</item>
> 
>         <item name="android:windowTranslucentStatus">true</item>
>         <item name="android:windowTranslucentNavigation">true</item>
>     </style>
> 
> </resources>
> ```

Thankyou so much 🤗

**Comment by voids** [comment]
I found that the "android:windowBackground" of "Theme.SplashScreen"  can be specified, so I write an drawable file:

> bootsplash_legacy_logo.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/colorPrimary" />
    <item android:gravity="center">
        <bitmap android:gravity="center" android:src="@mipmap/bootsplash_logo" />
    </item>
</layer-list>
```
> values/styles.xml

```xml
    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/colorPrimary</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="android:windowBackground">@drawable/bootsplash_legacy_logo</item> <!-- specify legacy logo -->
        <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>
```

> values-v23/styles.xml

```xml
<resources>
    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/colorPrimary</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>
</resources>
```

It works well in emulator.

**Comment by zoontek** [comment]
@voids I would **not** recommend doing that.
