### ISSUE TITLE
How to set full screen in version 4.0.0

### ISSUE THREAD

**Issue by Miluaaa** [zoontek/react-native-bootsplash#283]
### Why it is needed?

android full screen

    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-bootsplash": "^4.0.0",

**Comment by Woverlin** [comment]
Same question, I try to edit bootsplash.xml file  (included delete this file), but nothing change, the splash screen is still exist, How to edit the splash screen ?

**Comment by Miluaaa** [comment]
> bootsplash.xml

The documentation for 4.0.0 indicates that the bootsplash.xml file is not required.
If bootsplash.xml is set, then it will not be hidden. I have been trying for a day and still haven't found a solution

**Comment by zoontek** [comment]
Did you read the migration guide: https://github.com/zoontek/react-native-bootsplash/blob/master/MIGRATION.md ?

What do you mean by full screen splash screen? Transparent bars?

**Comment by zoontek** [comment]
If by "full screen", you mean an image that take full width / height, that's not possible: https://developer.android.com/guide/topics/ui/splash-screen

This library always encouraged user to set a simple logo and a background color as splash screen. Google seems to agree with that.

**Comment by Miluaaa** [comment]
> 如果“全屏”是指采用全宽/全高的图像，那是不可能的：[https](https://developer.android.com/guide/topics/ui/splash-screen) : [//developer.android.com/guide/topics/ui/splash-screen](https://developer.android.com/guide/topics/ui/splash-screen)
> 
> 这个库总是鼓励用户设置一个简单的标志和背景颜色作为启动画面。谷歌似乎同意这一点。

Thanks for the reply
I've read the migration guide
I have implemented fullscreen in IOS by modifying the BootSplash.storyboard file

Will android support fullscreen in the future?
I think many people need it ......

**Comment by zoontek** [comment]
@Miluaaa Ask Google. I personally think people don't need it.

**Comment by pohy** [comment]
We also need this feature. Is there a way to display a fullscreen image on the splash screen in the latest version of this library? Thanks! 🙏

**Comment by zoontek** [comment]
@pohy Not on Android. Read https://developer.android.com/guide/topics/ui/splash-screen

**Comment by Woverlin** [comment]
Hi. Is any way to set background color like this ? @zoontek 
![image](https://user-images.githubusercontent.com/15994572/143522736-e2682890-bd20-47a5-9d0f-640b655e0d1d.png)

**Comment by zoontek** [comment]
@Woverlin No

**Comment by billnbell** [comment]
I have a way to do this in IOS by changing storyboard file to extend.

Android was possible in last version but in 4.0 is seems to be nearly impossible to do this.

**Comment by zoontek** [comment]
Yes, the standard way though Xcode. Nothing special here. It's impossible on Android dur to the limitations of the new Splash Screen API

**Comment by zacdemi** [comment]
not impossible! https://github.com/crazycodeboy/react-native-splash-screen/issues/546#issuecomment-1108846899

**Comment by zoontek** [comment]
@zacdemi It's a crappy hack, I don't want to maintain that kind of stuff.

**Comment by tientv1995** [comment]
make background into image
<item name="windowSplashScreenBackground">@drawable/splash</item>

**Comment by tientruongvan1995** [comment]
1. set icon size to 0
2. set image to background variants
`
<style name="BootTheme" parent="Theme.SplashScreen">
  <item name="android:windowBackground">@drawable/splash</item>
  <item name="windowSplashScreenBackground">@drawable/splash</item>
  <item name="splashScreenIconSize">0dp</item>
  <item name="postSplashScreenTheme">@style/AppTheme</item>
</style>
`

**Comment by FusionReaction** [comment]
I was able to set a single image to full screen instead of the small logo by following @tientruongvan1995 suggestion:

```    
<!-- BootTheme should inherit from Theme.SplashScreen -->
    <style name="BootTheme" parent="Theme.SplashScreen">
      <item name="android:windowBackground">@mipmap/bootsplash_logo</item>
      <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
      <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
      <item name="splashScreenIconSize">0dp</item>
      <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>
```

**Comment by ducpt-bili** [comment]
hi @FusionReaction and @tientruongvan1995 , on Samsung Z Fold it still show the logo and splash image behind. Do you guy met this issue? I use @tientruongvan1995  solution.

**Comment by tientruongvan1995** [comment]
> hi @FusionReaction and @tientruongvan1995 , on Samsung Z Fold it still show the logo and splash image behind. Do you guy met this issue? I use @tientruongvan1995 solution.

any screenshot?

**Comment by ducpt-bili** [comment]
![2023-04-07 17 49 55](https://user-images.githubusercontent.com/101504153/230713093-9a0cbb98-121a-4a0a-a004-ddae18b8ad9c.jpg)

**Comment by ducpt-bili** [comment]
hi @tientruongvan1995  any suggestion? please.

**Comment by Yurii-Lutsyk** [comment]
@zoontek @ducpt-bili Everything works fine on Android.
```
    <style name="BootTheme" parent="Theme.BootSplash">
      <item name="android:windowBackground">@drawable/bootsplash_logo</item>
      <item name="android:windowSplashScreenBackground">@color/bootsplash_background</item>
      <item name="postBootSplashTheme">@style/AppTheme</item>
    </style>
```

**Comment by zoontek** [comment]
@Yurii-Lutsyk Not a good idea, as this is not supported by the Android system. See https://developer.android.com/develop/ui/views/launch/splash-screen#how:

> The system shows the splash screen using themes and any animations that you define.

Try it on Android >= 12, but pretty sure this will not works (or will break on some devices).

**Comment by Yurii-Lutsyk** [comment]
@zoontek i tested it on the Android 13

**Comment by zoontek** [comment]
@Yurii-Lutsyk https://developer.android.com/develop/ui/views/launch/splash-screen#implement

This is a dangerous path 🤷🏻‍♂️

**Comment by lvothnrv** [comment]
> hi @tientruongvan1995 any suggestion? please.

Hi I have something that could help you if you want, I redid a module which like react-native-splash-screen you can just put an image. https://www.npmjs.com/package/@lvothnrv/react-native-launchscreen

**Comment by zoontek** [comment]
@lvothnrv This does not work properly on Android 12+ (double splash screen issue)

See https://github.com/crazycodeboy/react-native-splash-screen/issues/613

Except with hacks like `windowIsTranslucentˋ which can add significant delay on app open after user icon press. It's a choice.

**Comment by lvothnrv** [comment]
> @lvothnrv This does not work properly on Android 12+ (double splash screen issue)
> 
> See [crazycodeboy/react-native-splash-screen#613](https://github.com/crazycodeboy/react-native-splash-screen/issues/613)
> 
> Except with hacks like `windowIsTranslucent` which can add significant delay on app open after user icon press. It's a choice.

No my friend I wasn't talking about the splashscreen that they added at the beginning but indeed we can cheat with windowIsTranslucent. But I was talking about the splashscreen that we put, a lot of people like me just want to be able to put an image for the splashscreen, to design custom backgrounds it's much better. With react-native-bootsplash we can't do that, we put icon and then we can put a background but the rendering is not the same, and also the background is distorted.

**Comment by zoontek** [comment]
So, you have a double splash screen.

**Comment by praneshvr00** [comment]
@tientruongvan1995
 Just by adding splashScreenIconSize to 0 makes the image to appear full screen !
