### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by birdofpreyru** [zoontek/react-native-bootsplash#285]
### Bug summary

I got several apps upgraded to RN-Bootsplash v4, and overall it works fine, but I just captured this error via Sentry:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.remove(ArrayList.java:503)
    at com.zoontek.rnbootsplash.RNBootSplashModule.shiftNextTask(RNBootSplashModule.java:3)
    at com.zoontek.rnbootsplash.RNBootSplashModule.access$200(RNBootSplashModule.java:1)
    at com.zoontek.rnbootsplash.RNBootSplashModule$d$a.run(RNBootSplashModule.java:4)
    at java.util.TimerThread.mainLoop(Timer.java:562)
    at java.util.TimerThread.run(Timer.java:512)
```
Looking at my code, my best guess is that in some corner-case I may call RN-Bootsplash `.hide()` method more than once, and probably that causes the issue. I'll patch my code to ensure `.hide()` is never called more than once, but I wonder, if that is the problem, you probably can patch the library as well to ensure multiple `.hide()` calls are safe? Or, do you think something different caused the error?

### Library version

4.0.0

### Environment info

```shell
N/A
```

### Steps to reproduce

N/A

### Reproducible sample code

```js
N/A
```

**Comment by zoontek** [comment]
Indeed, it's linked to the fact that you called it multiple times.
I would love to see some code, since a check is done before shifting a task (`!mTaskQueue.isEmpty()` -> `mTaskQueue.remove(0)`), but it seems to call `mTaskQueue.remove(0)` with an empty `ArrayList` (`Index: 0, Size: 0`)

**Comment by birdofpreyru** [comment]
Essentially, I do the following in my app's root component. I am sure doing a bunch of other unrelated stuff in this hook, which I want to do when the app goes from background to foreground and vice-versa, so it looked like a convenient place for me to also  schedule `RNBootSplash.hide()` call there. `heap.coreReady` in my case a singleton promise, which resolves once my app is ready.
```js
useEffect(() => {
  const onStateChanged = async state => {
    if (state === 'active') {
      RNBootSplash.getVisibilityStatus().then(async status => {
        if (status === 'visible') {
          heap.coreReady.then(() => RNBootSplash.hide({fade: true}));
        }
      });
    }
  };

  const appStateSub = AppState.addEventListener('change', onStateChanged);
  onStateChanged(AppState.currentState);

  return () => {
    appStateSub.remove();
  };
}, [/* Some dependencies here. */]);
```

**Comment by zoontek** [comment]
I'm actually testing replacing `ArrayList` with `Stack`, which is a thread safe LIFO implementation: https://www.baeldung.com/java-lifo-thread-safe. It seems to work quite well.

**Comment by zoontek** [comment]
I published a new version using `Stack`: https://github.com/zoontek/react-native-bootsplash/releases/tag/4.0.1
Please update and report if the issue still appears.
