### ISSUE TITLE
react native 0.61.4 ? 

### ISSUE THREAD

**Issue by Miluaaa** [zoontek/react-native-bootsplash#29]
### 💻 My environment

- react-native-bootsplash version:
- react-native version:
- Platform: ios / android / both
- OS version: ?
- Device: brand + model
- Simulator: yes / no
- Android Studio version: ?
- Android buildToolsVersion: ?
- Xcode version: ?

### 🕵️‍♂️ Reproducing the issue

Explain what you did, what you expected to happen, and what actually happens.
Provide some code or screenshots if needed.

### 🤞Solution

Do you know what needs to be done to address this issue?
Ideally, provide a pull request with a fix.

**Comment by zoontek** [comment]
The template is totally blank, I close this.
