### ISSUE TITLE
Unable to initialize splash screen in Android

### ISSUE THREAD

**Issue by mehtishamulhaq** [zoontek/react-native-bootsplash#291]
### Bug summary

In the Android section of Docs it is metioned to initialize the splash screen in the loadApp (5th step)
<img width="891" alt="Screen Shot 2021-12-02 at 6 01 34 PM" src="https://user-images.githubusercontent.com/43884999/144427542-198ba1fa-79ae-4934-953d-6b42c84dfae8.png">
but in react native version 0.66.0 the file structure of mainActivity is changed and there is no loadApp method there.
<img width="1019" alt="Screen Shot 2021-12-02 at 6 03 36 PM" src="https://user-images.githubusercontent.com/43884999/144427805-274fc1cf-a86f-464a-9d72-828ae7103456.png">
kindly update the docs as how to initialize it for android 
I've tried to initialize it in the method protected String getMainComponentName() for the sake of try but the app crashes after showing splash screen 

### Library version

4.0.2

### Environment info

```shell
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 80.17 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.9.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.21.1 - /usr/local/bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
package com.mobile;
import android.os.Bundle;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate; 
import com.zoontek.rnbootsplash.RNBootSplash; 

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
   RNBootSplash.init(MainActivity.this);
    return "Swished";
  }

}
```

**Comment by zoontek** [comment]
Add the imports, override the method.

**Comment by afilp** [comment]
@zoontek I have the same problem, not sure what needs to be done, whatever I do Android Studio shows an error. 

Example:

![image](https://user-images.githubusercontent.com/7850073/148595414-5becb91e-d279-4f07-8e39-688e04cb255a.png)

Highlighted with error:
`'loadApp(String)' cannot override 'loadApp(String)' in 'com.facebook.react.ReactActivity'; overridden method is final`

**Comment by zoontek** [comment]
@afilp Read the README correctly 😄

**Comment by afilp** [comment]
I just read it again, I did not find any reference to the new react-native code (eg: `protected String getMainComponentName() {`.

As @mehtishamulhaq mentioned `readme` is not clear on this case.

I did a different replacement, maybe this is what you mean?

```
package xx.xxxx.xxx;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.zoontek.rnbootsplash.RNBootSplash;

public class MainActivity extends ReactActivity {

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {

      @Override
      protected void loadApp(String appKey) {
        RNBootSplash.init(MainActivity.this); // <- initialize the splash screen
        super.loadApp(appKey);
      }
    };
  }
}
```

Still the app crashes after showing the splash screen.

What do I miss in the README if you don't mind telling me?  (and @mehtishamulhaq  ?)

Thanks a lot.

**Comment by afilp** [comment]
Wait, I am adding this and also keeping the other code.

**Comment by afilp** [comment]
Wait, I am adding this and also keeping the other code, and now it works. 

It was not very very clear to me, thank you for the support.

**Comment by uojiaku** [comment]
https://github.com/zoontek/react-native-bootsplash/blob/master/MIGRATION.md
this helped me understand where to position it!
