### ISSUE TITLE
library not found for -lRNBootSplash

### ISSUE THREAD

**Issue by chj-damon** [zoontek/react-native-bootsplash#292]
### Bug summary

![image](https://user-images.githubusercontent.com/4902684/144745158-15b893d8-e9a3-4abe-b94d-d4361935b40d.png)

### Library version

4.0.2

### Environment info

```shell
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 92.39 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. npx react-native init xxxProject

2. yarn add react-native-bootsplash@latest

3. cd ios && pod install

4. open xcode and then build...

### Reproducible sample code

```js
ios build error
```

**Comment by zoontek** [comment]
Clean your project using https://github.com/pmadruga/react-native-clean-project

**Comment by chj-damon** [comment]
I solved this by change ios build target to 11.0

**Comment by chj-damon** [comment]
maybe this is worth to write in the readme I suppose?

**Comment by zoontek** [comment]
That's already the case: https://github.com/zoontek/react-native-bootsplash#support

v4 requires RN 0.65, which requires iOS >= 11 (https://github.com/facebook/react-native/blob/0.65-stable/template/ios/Podfile#L4)

**Comment by chj-damon** [comment]
Thank you.

**Comment by samleurs247** [comment]
I have the same issue. It only happens with a release build, not with a debug build. I have cleaned the project and the ios build target is set to 11.0. But it still happens.

**Comment by MelanieSwood** [comment]
Hello @samleurs247 ,

I had the same problem as you, library not found only during archiving.

I solved it by changing the OS in Target > General > Deployment Info manually.
<img width="690" alt="Capture d’écran 2021-12-29 à 12 56 56" src="https://user-images.githubusercontent.com/77326493/147659950-235eb164-6629-4942-9e80-0e82ecf87b02.png">

Hope it helps you too !
