### ISSUE TITLE
Use new animation API to add animations on logo

### ISSUE THREAD

**Issue by ShivamJoker** [zoontek/react-native-bootsplash#293]
### Why it is needed?

I saw the new splash screen introduced in Android 12 and notices YouTube new animated splash I was wondering if you can make something like that as well or not.
Maybe just a rotation and scale or fading logo or maybe sliding in

Here is the demo
I know it's complex but simple animations would do the job

https://user-images.githubusercontent.com/23727670/144792603-00724b85-eaaa-4139-8526-d8931b586bae.mp4

**Comment by zoontek** [comment]
It could be quite easy to add a parameter to allow access to the whole `OnExitAnimationListener` logic but it will mess with the `fade` option.

Something like this:

```java
RNBootSplash.init(MainActivity.this, new SplashScreen.OnExitAnimationListener() {
  @Override
  public void onSplashScreenExit(@NonNull SplashScreenViewProvider splashScreenViewProvider) {
    View splashScreenView = splashScreenViewProvider.getView();

    splashScreenView
      .animate()
      // Go crazy with native animations here
      .setDuration(220)
      .alpha(0.0f)
      .setInterpolator(new AccelerateInterpolator())
      .setListener(new AnimatorListenerAdapter() {
        @Override
        public void onAnimationEnd(Animator animation) {
          super.onAnimationEnd(animation);
          splashScreenViewProvider.remove();
        }
      }).start();
  }
});
```

Another solution is just using a logic similar to the example project (animate the logo on the JS side, which is way easier  and cross platform).

**Comment by ShivamJoker** [comment]
On JS side we will first get the normal splash then the JS will load so I don't think it would be ideal

In the example you are animating the whole view not just the logo (correct me if I am wrong) and the fade parameter acts on whole instead of just logo.

So it should not conflict with existing fade animation.

**Comment by zoontek** [comment]
Indeed, but it's just an example. You can split your logo into layer and animate them independently.

That's actually how it's done in your example (Youtube)

**Comment by maXXCZ1** [comment]
Hello, i just tried your library and i am very pleased with the result.
I am junior programmer in RN (never worked with java obviously), so excuse my lack of knowledge. Ask section pointed me to SOF, but there is literally zero info, so i decided to try my luck here.

I am facing problem which has lot in common with this request. My loading time before JS hits is quite significant, therefore i would prefer to animate my image on native side of things (instantly after app starts).

I figured out how to do simple animation in java, but i struggle to understand if i am allowed to change ` bootsplash.xml` as i like (i need Layout and imageView to be able to animate it) AND also if i should edit with `loadAnimation` `MainActivity.java` or `RNBootSplashActivity.jav`a (i guess the former).

So far i tried to change layer-list for anything else and i failed even with that.
for tried this simple layout:

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                                                   android:layout_width="match_parent"
                                                   android:layout_height="match_parent">

    <ImageView
            android:id="@+id/imageView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@mipmap/bootsplash_logo" />
</RelativeLayout>
```

Do i understand correctly, that we can use only layer-list?

**Comment by aurotones** [comment]
> ```java
> RNBootSplash
> ```

I tried to customize based on this code and having trouble, it appears some of the methods are protected and can't be accessed from MainActivity class.
Was it meant to be customized inside MainActivity?

**Comment by zoontek** [comment]
@aurotones It's a proposal, not implemented.

**Comment by aurotones** [comment]
@zoontek I see, i would love to see this get implemented but it's alright for now.

**Comment by page403** [comment]
Theres no need adding features, its already there called windowSplashScreen**Animated**Icon

`<item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>` <--u can just replace with your animated AVD (xml) compatible format.

Make your animation by refering to this [Android Developer Web](https://developer.android.com/develop/ui/views/launch/splash-screen#splash_screen_animations_and_the_launch_sequence) cause u'll gonna need resolution requirement. Otherwise your animated logo cropped.

Once u have your xml, place it for ex in drawable. 
so `<item name="windowSplashScreenAnimatedIcon">@drawable/your_animated_logo</item>`


- "react-native-bootsplash": "^4.3.3",


https://user-images.githubusercontent.com/82417973/202340909-0c52446a-a1e1-4c2e-8eae-a0258014ab17.mov

**Comment by zoontek** [comment]
@page403 The appearing animation can be handled using a drawable, but the disappearing one currently cannot (at least, not on the Java side)

**Comment by zoontek** [comment]
I'm closing this, I planned to facilitate exit animations on the JS thread, but will not implement something specific to Android only.

**Comment by Code-Victor** [comment]
@zoontek Please is there any way I can achieve this with expo?
