### ISSUE TITLE
v4.0.2 - Hide method is not working on android

### ISSUE THREAD

**Issue by ValGeorgiev** [zoontek/react-native-bootsplash#297]
### Bug summary

Following the readme, the android app is "freezing" with the splash screen and the hide method is not working

Screenshot:

<img width="1267" alt="Screenshot 2022-01-06 at 23 16 54" src="https://user-images.githubusercontent.com/12056467/148453606-cbb7b80b-15b6-4999-9a60-db8393f1a4f4.png">

I tried with useEffect and NavigationContainer - onReady method, but still the same, the splash screen is not hided.

MainActivity.java 
```
package com.barclays;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate; // <- add this necessary import
import com.zoontek.rnbootsplash.RNBootSplash;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "Barclays";
  }
  
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {

      @Override
      protected void loadApp(String appKey) {
        RNBootSplash.init(MainActivity.this); // <- initialize the splash screen
        super.loadApp(appKey);
      }
    };
  }

}
```

### Library version

4.0.2

### Environment info

```shell
info Fetching system and libraries information...
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 1.28 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2022.01.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Init brand new RN application on Android
2. Follow the readme to include the splash screen
3. Check the android emulator.

### Reproducible sample code

```js
https://github.com/ValGeorgiev/barclays
```

**Comment by ValGeorgiev** [comment]
> Did you tried the example app? Because that's not reproducible.

Good point, I compared MainActivity.java and MainApplication.java with the example and found the issue. I tried the react-native-splash-screen library and change the MainApplication.java, but forgot to revert the change when I migrated to rn-bootsplash and this broke the logic... Silly mistake. Thanks for your help @zoontek . The library and specially the cli are so easy to use. Great job.

I am closing this..

**Comment by JadeByfield89** [comment]
> > Did you tried the example app? Because that's not reproducible.
> 
> Good point, I compared MainActivity.java and MainApplication.java with the example and found the issue. I tried the react-native-splash-screen library and change the MainApplication.java, but forgot to revert the change when I migrated to rn-bootsplash and this broke the logic... Silly mistake. Thanks for your help @zoontek . The library and specially the cli are so easy to use. Great job.
> 
> I am closing this..

Could you clarify what the differences between the 2 files were? I also tried react-native-splash-screen library first, and running into the same issue.
