### ISSUE TITLE
Add support for tvOS

### ISSUE THREAD

**Issue by jonny22094** [zoontek/react-native-bootsplash#298]
### Why it is needed?

Because it would be great if it's will be possible to use the library for every platform

Currently, on all devices bootsplash v4 works well only on TvOS there is a problem to run the app with incompatibility error

`[!] The platform of the target project-tvOS (tvOS 12.0) is not compatible with RNBootSplash (4.0.2), which does not support tvOS.`

**Comment by zoontek** [comment]
I added tvOS target to podspec https://github.com/zoontek/react-native-bootsplash/releases/tag/4.1.1
