### ISSUE TITLE
Security exception: Permission Denial

### ISSUE THREAD

**Issue by sggonzalezg** [zoontek/react-native-bootsplash#3]
### ERROR
Starting: Intent { cmp=[appName]/.MainActivity }
Security exception: Permission Denial: starting Intent { flg=0x10000000 cmp=[appName]/.MainActivity } from null (pid=27721, uid=2000) not exported from uid 10085

java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=[appName]/.MainActivity } from null (pid=27721, uid=2000) not exported from uid 10085
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1632)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:438)
	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:278)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:817)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4532)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:417)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:141)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15014)
	at android.os.Binder.shellCommand(Binder.java:594)
	at android.os.Binder.onTransact(Binder.java:492)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4243)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2919)
	at android.os.Binder.execTransact(Binder.java:697)

### 💻 My environment

- react-native-bootsplash version: "^0.1.1"
- react-native version:  "0.60.4",
- Platform: android
- Device: Nexus 6
- Simulator: yes 
- Android Studio version: 3.4.2
- Android buildToolsVersion: 28.0.3

### 🕵️‍♂️ Reproducing the issue

Install react-native-bootsplash and run react-native run-android

**Comment by sggonzalezg** [comment]
If I put  android:exported="true" in <activity android:name=".MainActivity" ...>
Get this error
<img width="305" alt="Captura de pantalla 2019-07-22 a la(s) 14 04 31" src="https://user-images.githubusercontent.com/5217655/61650261-a6c5f900-ac89-11e9-85ca-a03affe2003d.png">

**Comment by zoontek** [comment]
Are you installing the module twice? WIth RN 0.60 and autolinking, you don't need to return it in the `getPackages` method.

**Comment by sggonzalezg** [comment]
Thanks, sorry for the issue.

**Comment by sggonzalezg** [comment]
Hi, sorry but the issue is still happing.

The error ocurred when I run react-native run-android in Terminal, but when I start diretcly form Andorid Studio starts OK

Regards

**Comment by zoontek** [comment]
Could you try with the updated react-native cli instead? It's bundled with react-native now.
https://github.com/react-native-community/cli

**Comment by camilo-5972** [comment]
In my case I reduced the size of the splashScreen image

**Comment by rizal-azalli** [comment]
I have a same problem but solved the problem with:
```
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
        </intent-filter>
      </activity>

      <activity
        android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
        android:exported="true"
        android:theme="@style/BootTheme">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
```
In .MainActivity please insert back

>         <intent-filter>
>           <action android:name="android.intent.action.MAIN" />
>         </intent-filter>

**Comment by giacomocerquone** [comment]
I solved adding android:exported="true"
Here for more explanation: https://medium.com/handlebar-labs/how-to-add-a-splash-screen-to-a-react-native-app-ios-and-android-30a3cec835ae

**Comment by leoxiaoping** [comment]
I have same error

**Comment by zoontek** [comment]
I added `android:exported="true"` to the example and the `README`. Thanks @giacomocerquone !

**Comment by mashad6** [comment]
@zoontek Hey, setting [an](android:exported="true") is causing vulnerability when running pen-test.
It says that exported should be false. setting it false causing this same issue then
<img width="1014" alt="Screenshot 2023-04-14 at 2 36 05 AM" src="https://user-images.githubusercontent.com/55269021/231888325-bb31905e-5524-4aac-96e7-f701097888a9.png">

**Comment by zoontek** [comment]
@mashad6 Since Android 12, activities from LAUNCHER category **must** have exported: true
Documentation: https://developer.android.com/about/versions/12/behavior-changes-12#exported

**Comment by mashad6** [comment]
@zoontek Thanks, it helped
