### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNBootSplash.hide')

### ISSUE THREAD

**Issue by vitalbone** [zoontek/react-native-bootsplash#30]
### 💻 My environment

- react-native-bootsplash version: `^1.0.3`
- react-native version: `0.61.4`
- Platform: ios
- OS version: macOS Catalina `v10.15.1`
- Device: iPhone 11
- Simulator: yes
- Android Studio version: n/a
- Android buildToolsVersion: n/a
- Xcode version: `11.2.1`

### 🕵️‍♂️ Reproducing the issue

1. `yarn add react-native-bootsplash`
2. Follow exact steps in https://github.com/zoontek/react-native-bootsplash#setup
3. Add `RNBootSplash` to `App.tsx`

```tsx
import * as React from 'react';
import RNBootSplash from "react-native-bootsplash";
import AsyncStorage from '@react-native-community/async-storage';
import { AppNavigator } from './Navigation';
import { ApolloProvider, ApolloClient, createHttpLink, InMemoryCache } from '@apollo/client';
import { setContext } from 'apollo-link-context';

const httpLink = createHttpLink({
  uri: '...special_url...',
});

const authLink = setContext(async (_, { headers }) => {
  const token = await AsyncStorage.getItem('@userToken');
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : '',
    }
  }
});

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache()
});

export default function App() {
  const init = () => {
    RNBootSplash.hide();
  }
  React.useEffect(() => {
    init();
  }, []);

  return (
    <ApolloProvider client={client}>
      <AppNavigator />
    </ApolloProvider>
  );
}
```
4. See this error `TypeError: null is not an object (evaluating 'RNBootSplash.hide')`
5. Try linking manually following https://github.com/zoontek/react-native-bootsplash#-manual-linking
6. Same error shows

### 🤞Solution

Unsure how to navigate this. Any help would be appreciated, thanks.

**Comment by zoontek** [comment]
@vitalbone Hi. Did you do a `pod install`, opened the `xcworkspace`, clean the project in Xcode, and then build?

**Comment by vitalbone** [comment]
Hi @zoontek thanks for your response. I hadn't run that specific sequence of events at the time but have subsequently, and am now unable to build the app, due to this error in the `AppDelegate.m`:

`Use of undeclared identifier 'RNBootSplash'`

Pointing at this line:

```objectivec
[RNBootSplash show:@"LaunchScreen" inView:rootView];
```

Any idea what else I could try?

**Comment by zoontek** [comment]
If it's correctly linked, it should be visible in your `Pods/Development Pods`. Clean up the Xcode cache and build.

**Comment by vitalbone** [comment]
Ah yep, I was missing the header file, have added it and it is now working. Thanks for all your help.

**Comment by AlexanderVoronin-ux** [comment]
> @vitalbone Hi. Did you do a `pod install`, opened the `xcworkspace`, clean the project in Xcode, and then build?

This helped me
