### ISSUE TITLE
Please make the package work with androidx.core:core-splashscreen:1.0.0-beta01

### ISSUE THREAD

**Issue by jimbofoo** [zoontek/react-native-bootsplash#301]
### Bug summary

Using the just released androidx.core:core-splashscreen:1.0.0-beta01 the plugin crashes with:

java.lang.NoSuchMethodError: No virtual method setKeepVisibleCondition(Landroidx/core/splashscreen/SplashScreen$KeepOnScreenCondition;)V in class Landroidx/core/splashscreen/SplashScreen

AndroidRuntime:        at com.zoontek.rnbootsplash.RNBootSplashModule.init(RNBootSplashModule.java:69)

### Library version

4.0.2

### Environment info

```shell
any
```

### Steps to reproduce

1. replace implementation 

"androidx.core:core-splashscreen:${safeExtGet("androidXSplashScreenVersion", "1.0.0-alpha02")}"

to 

"androidx.core:core-splashscreen:${safeExtGet("androidXSplashScreenVersion", "1.0.0-beta01")}"

### Reproducible sample code

```js
none
```

**Comment by zoontek** [comment]
Hi, finally a beta release! I will update the package this weekend.

**Comment by zoontek** [comment]
Just shipped it: https://github.com/zoontek/react-native-bootsplash/releases/tag/4.1.0
