### ISSUE TITLE
Weird bootsplash resizing issue when starting app in landscape mode.

### ISSUE THREAD

**Issue by gwilkinsong** [zoontek/react-native-bootsplash#302]
### Bug summary

When I put the phone in landscape and have a different background color the bootsplash resizes all over place and looks entirely weird and doesn't fill the whole screen. Even with an orientation locker.

This bug only happens on iPhone once started in landscape mode when the app starts and once transitioned to portrait mode, please see the recording below.

https://user-images.githubusercontent.com/88524178/149316046-a82014df-96ff-496a-97a0-fbff474b3b18.MP4

### Library version

4.0.2

### Environment info

```shell
any
```

### Steps to reproduce

1. Disable Portrait Orientation lock in the Control Center
2. Rotate device in landscape mode first, and start the app.
3. Once the splash screen has been shown, rotate the device back to portrait.
4. Bootsplash appears resizing all over the place with a black background with bars from top to bottom or some other different colour.

### Reproducible sample code

Using the example repo:

Install 'react-native-orientation' via `yarn add 'react-native-orientation'`

Set the project in Xcode to the following device orientation:

<img width="406" alt="device_orientation_repro" src="https://user-images.githubusercontent.com/88524178/149315953-6269f9a3-e5f9-4a93-ab69-79857ded2b61.png">

Used example repo and set the root view background color to any color, (example in video uses black instead of white)

```objc
rootView.backgroundColor = [UIColor blackColor];
```

In the example repo `App.tsx`, add `import Orientation from 'react-native-orientation';` to the top.

In App.tsx, inside the `init` add `await Orientation.lockToPortrait();` like this:

```js
const init = async () => {
    // You can uncomment this line to add a delay on app startup
    // await fakeApiCallWithoutBadNetwork(3000);

    try {
      await Orientation.lockToPortrait();

      await BootSplash.hide();

      Animated.stagger(250, [
        Animated.spring(translateY.current, {
          useNativeDriver: true,
          toValue: -50,
        }),
        Animated.spring(translateY.current, {
          useNativeDriver: true,
          toValue: Dimensions.get("window").height,
        }),
      ]).start();

      Animated.timing(opacity.current, {
        useNativeDriver: true,
        toValue: 0,
        duration: 150,
        delay: 350,
      }).start(() => {
        setBootSplashIsVisible(false);
      });
    } catch (error) {
      setBootSplashIsVisible(false);
    }
  };
```

Run the app and the bug will appear.

**Comment by zoontek** [comment]
Splash screen is inside a different UIView, you have to wait until it's hidden before locking orientation I think.

**Comment by gwilkinsong** [comment]
@zoontek I tried this and it made no difference, I still get this bug.

**Comment by zoontek** [comment]
Tried with both a real device and the simulator, no issues:

https://user-images.githubusercontent.com/1902323/152644862-f9c1ba13-5ae4-4bbe-9cf9-10f83b74ea8d.MP4

https://user-images.githubusercontent.com/1902323/152644856-a1592c06-ffb4-485a-bddd-2d522b44725a.mov

I would suggest to remove `react-native-orientation` / try another dependency (it seems unmaintained)

**Comment by rcidt** [comment]
@zoontek can we reopen this issue? The same bug exists with `react-native-orientation-locker` ([repo](https://github.com/wonday/react-native-orientation-locker)).

**Comment by kosbog** [comment]
I had a black area around too. My mistake was that I did not specify Bootsplash.storyboard as "Launch Screen File" in the Xcode. Check that.
