### ISSUE TITLE
Android weird cicle

### ISSUE THREAD

**Issue by jamesjara** [zoontek/react-native-bootsplash#304]
### Bug summary

NO DETAILS

It's showing a circle empty 

### Library version

4.0.2

### Environment info

```shell
info Fetching system and libraries information...
System:
    OS:  
    CPU: 
    Memory: 62.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/dev/ampm/generic/node_modules/.bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
```

### Steps to reproduce

1.  Follow the instruction in the readme
2.  Open the app

### Reproducible sample code

```js
there is no custom code, the same in the readme.
```
<img width="389" alt="Screen Shot 2022-01-15 at 1 13 23 PM" src="https://user-images.githubusercontent.com/780219/149634914-955a642e-b084-4e3a-92bd-d615bc69c68b.png">

Pixel 4a API 30

**Comment by zoontek** [comment]
Please:
1) Update
2) Give details (screenshot - video - phone model - android version)

**Comment by jamesjara** [comment]
Pixel 4a API 30, description update, thank you I have trying many many approaches before opening the ticket without success

**Comment by zoontek** [comment]
Publish your `styles.xml`. It **really** seems to be a config issue.

**Comment by jamesjara** [comment]
Sure,  thanks

styles.xml
```<resources>

    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:fitsSystemWindows">false</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:windowTranslucentNavigation">true</item>
    </style>

    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="android:forceDarkAllowed">false</item>
        <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
        <item name="windowSplashScreenAnimatedIcon">@drawable/splash</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>
    <resources>```
    
    mainactivity
    ``` 
package com.generic;

import android.os.Bundle;
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.zoontek.rnbootsplash.RNBootSplash;

public class MainActivity extends ReactActivity {
    /**
    * Returns the name of the main component registered from JavaScript. This is used to schedule
    * rendering of the component.
    */
    @Override
    protected String getMainComponentName() {
    return "generic";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected void loadApp(String appKey) {
                RNBootSplash.init(MainActivity.this);
                super.loadApp(appKey);
            }
        };
    }
}
```
manifest
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.generic"
    xmlns:tools="http://schemas.android.com/tools">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.USE_FINGERPRINT" />
    <uses-permission android:name="android.permission.CAMERA" />
    <application
        android:name=".MainApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:allowBackup="false"
        android:networkSecurityConfig="@xml/network_security_config"
        android:theme="@style/BootTheme"
        android:exported="true"
        tools:node="merge"
        > 
        <activity
          android:name=".MainActivity"
          android:label="@string/app_name"
          android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
          android:launchMode="singleTask"
          android:windowSoftInputMode="adjustResize"
          android:exported="true"
          tools:node="merge"
        >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" /> 
        </intent-filter>
        </activity>
        <uses-library android:name="org.apache.http.legacy" android:required="false"/>
    </application>
</manifest>

```

**Comment by zoontek** [comment]
`@drawable/splash`. What's that? Is this assets generated with the CLI?

**Comment by jamesjara** [comment]
I just replaced that line with the original, I was trying using a drawable, latest snapshot , and yes generated with the cli

```

    Android
✏️   android/app/src/main/res/values/colors.xml
✨  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png (288x288)
✨  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png (432x432)
✨  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png (576x576)
✨  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png (864x864)
✨  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png (1152x1152)

    iOS
✨  ios/Generic/BootSplash.storyboard
✨  ios/Generic/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png (300x300)
✨  ios/Generic/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png (100x100)
✨  ios/Generic/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png (200x200)
```

![image](https://user-images.githubusercontent.com/780219/149635202-7faebeac-6ed5-4fa0-9901-707a4e387535.png)

**Comment by zoontek** [comment]
Don't use a drawable.

**Comment by jamesjara** [comment]
Yes, is not using the code below, wrong copy/paste, the screenshot with the issue is using the correct code
```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:fitsSystemWindows">false</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:windowTranslucentNavigation">true</item>
    </style>
    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="android:forceDarkAllowed">false</item>
        <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>
</resources>
```
And the png is being generated with the script

**Comment by zoontek** [comment]
Tries on a fresh install or with the example project.

**Comment by jamesjara** [comment]
The code below is exactly the same in the example code, when closing an issue, please at least solve the issue, I got this repo from the repo of cody but it seems with the same bugs as the other one. How we can solve the issue?

**Comment by jamesjara** [comment]
Repo is not working I saw other issues related on huawei 
![image](https://user-images.githubusercontent.com/780219/149635425-f4298a43-5c3b-4e41-9014-c00dbf40a71e.png)

**Comment by zoontek** [comment]
Please publish a full repository with complete code.

**Comment by jamesjara** [comment]
I solved the issue (partially) splash is not hiding, but that maybe not related to this repo, I will take a look and paste if related, the issue was being caused by having a folder called `mimap-anydpi-v26` 
> anydpi-v26: This is an additional filter over just anydpi. This says resources will always be picked up from anydpi-v26 regardless of devices density only if SDK/API level is 26 or higher(Oreo).
Seems the repo is not working with these folder, actually the script is not generating the asset in there @zoontek

**Comment by zoontek** [comment]
That why I said to download and try the example project on this repository. If it works, it's an issue on your side.

**Comment by zoontek** [comment]
Next time, remember:
- Be polite and explicit (seriously, the message in your first "description"…don't do that). Provide details. Try to help the open source maintainers.
- Try to isolate your issue, be sure it does came from the library before bothering people.

**Comment by jamesjara** [comment]
Sure, but the example is to basic example, users will have multiple different scenarios, using a folder `anydpi-v26` is not an issue, actually, there is a bug in the library because is not handling all the `Screen pixel density (dpi)`
list of dpis: 
ldpi
mdpi
hdpi
xhdpi
xxhdpi
xxxhdpi
nodpi
tvdpi
anydpi
nnndpi 
Hope this finding helps you for adding the support of all dps, and thanks for the feedback I will try to be more explicit next time, and thanks for the free support time

**Comment by baselbj** [comment]
I am facing the same issue on huawei but when I tried the same code on emulator it worked perfectly. It seems that this library depends on some google services that are not available on Huawei.

You might need to find a fix for this issue or to just mention in the document that you might face issues on Huawei.

**Comment by muhsin-k** [comment]
@zoontek I am also getting the same issue. In my case, the the circle is sowing after splash screen image.

https://github.com/zoontek/react-native-bootsplash/assets/12408980/2900dc92-0688-49ec-9aaa-795aa8c9e2de


Library version is **5.0.1**

> The new SplashScreen API only allow a very specific layout. A background color + a logo inside a circle mask. https://developer.android.com/guide/topics/ui/splash-screen

Is there any way to remove this circle completely?

[Link to source code](https://github.com/chatwoot/chatwoot-mobile-app-upgrade-0.72.x/pull/2)

**Comment by zoontek** [comment]
@muhsin-k That's a different issue, this one is related to your manufacturer Android fork. Which phone / android version / custom UI is that? (MIUI?)

**Comment by muhsin-k** [comment]
> @muhsin-k That's a different issue, this one is related to your manufacturer Android fork. Which phone / android version / custom UI is that? (MIUI?)

Model: Pixel 4A.
Android version: 13

**Comment by zoontek** [comment]
@muhsin-k Weird, I have exactly the same phone and this never occur during all the development phase. I think we miss something here, but why? Try removing the AndroidX splashscreen dependency like I mentioned in the PR comment, do a gradle sync / rebuild.

I will investigate today by forking your repository. Having access to the source code sure help 🙏

**Comment by muhsin-k** [comment]
@zoontek It worked after removing the dependency. Thank you so much for this awesome package.

**Comment by zoontek** [comment]
@muhsin-k Really good to know! It will help if someone is in the same case as you.

**Comment by jfbourne** [comment]
Had same issue and after removing the AndroidX dependency in android/app/build.gradle it worked.
