### ISSUE TITLE
Generate bootsplash logo from SVG file

### ISSUE THREAD

**Issue by taylorkline** [zoontek/react-native-bootsplash#313]
### Why it is needed?

Rather than downloading from Figma in SVG, converting to a large PNG, it would be great if `generate-bootsplash` could take in an SVG in the first place.

### Possible implementation

A simple `yarn react-native generate-bootsplash assets/bootsplash_logo.svg` would create the bootsplash logo.

### Code sample

```js
`yarn react-native generate-bootsplash assets/bootsplash_logo.svg`
```

**Comment by zoontek** [comment]
I already tried to implement that, but it's too complex since most of the image manipulation node library don't handle SVG / handle them poorly.

**Comment by taylorkline** [comment]
No worries. Just for a status update, it looks like that may be a WIP on `Jimp`: oliver-moran/jimp#1049

**Comment by zoontek** [comment]
@taylorkline Thanks for the info! If it lands in `jimp` I will probably implement it 😊

**Comment by taylorkline** [comment]
FYI, in case it helps anyone else, I have the following `script` in my `package.json`:

`"generate-bootsplash": "rsvg-convert -w 800 assets/bootsplash_logo.svg > assets/bootsplash_logo.png && react-native generate-bootsplash assets/bootsplash_logo.png
 --logo-width=100 && rm assets/bootsplash_logo.png"`

It works well 😄 

@zoontek Are you interested in a PR adding this workaround to the README for the time being?

**Comment by zoontek** [comment]
@taylorkline Unfortunately I don't think `rsvg-convert` is available on macOS.

**Comment by taylorkline** [comment]
> @taylorkline Unfortunately I don't think `rsvg-convert` is available on macOS.

@zoontek It is! `brew install librsvg`

**Comment by zoontek** [comment]
@taylorkline Nice. Mentioning it in the README could be nice, thanks

**Comment by princefishthrower** [comment]
I actually had a question about this, as I'm interested in using an svg (and subsequent png) for my splash screen. @zoontek - could you provide hints on the relative dimensions the SVG should have to start with? Would 9:16 be fine? I'm assuming `react-native-bootsplash` must have to crop / stretch / zoom for certain device screen sizes. Would love to hear more on the technicalities on what happens behind the scenes.
