### ISSUE TITLE
Enable 2+ images to be included in splashscreen

### ISSUE THREAD

**Issue by omniviewsports** [zoontek/react-native-bootsplash#315]
### Why it is needed?

Some apps have a unique brand name/logo and also have a parent company brand logo. Accordingly, you would want to include both logos. 

### Possible implementation

You can a sample repo that uses bootsplash with react-native-lottie. Is there a way to allow a second image via lottie?

**Comment by zoontek** [comment]
You can add a `<item name="windowSplashScreenBrandingImage">@mipmap/company_logo</item>`;

Check the following tutorial: https://www.rockandnull.com/splash-screen-android-example/

**Comment by phuongnguyenzoi** [comment]
@zoontek This "windowSplashScreenBrandingImage" only available from android 12+, is there any work around for this?
