### ISSUE TITLE
Changing logo after generation

### ISSUE THREAD

**Issue by KJ-GM** [zoontek/react-native-bootsplash#317]
### Why it is needed?

Hello, I am not sure how do I **`reset`** the splash screen logo after generation ? I have not seen anything about it in the docs. Does regenerating one more time works?

**Comment by zoontek** [comment]
Just re-run the generator to override the previous files.

**Comment by efstathiosntonas** [comment]
@zoontek encountered a weird issue today on `4.1.3` on iOS `15.2` iPhone 13, I was playing around to find the perfect size of my logo and I made multiple generations with different widths and when building again then the previous dimension logo is loading for 1 sec and then shows the new dimension logo.

In other words what I did:
1. Run generator with width 200
2. xCode build on real device
3. width was not looking good so repeated steps 1 & 2 above with dimension 150 
4. When the app loads it shows for 1 sec dimension 200 and then shows dimension 100

What I tried:
1. Deleted `DerivedData` 
2. Clean build folder
3. uninstalled the app
4. Won't  fix
5. Buid on emulator, same issue

Any ideas what might cause this? If you want me to open a new issue let me know

**Comment by zoontek** [comment]
@efstathiosntonas It's Spotlight cache, on device. No big deal. Once you find the perfect size, follow this: https://stackoverflow.com/a/35783070/5529224

It will never happen to your users, it only happens in dev.

**Comment by efstathiosntonas** [comment]
@zoontek excellent, thanks!

**Comment by AlixH** [comment]
It's not true that it only happens in dev, just happened to me in beta version. I had a remaining artifact of the previous launch screen. Is there a way to ensure it will never happen ?

**Comment by zoontek** [comment]
@AlixH [This should do the trick](https://github.com/zoontek/react-native-bootsplash/releases/tag/5.3.0)
