### ISSUE TITLE
Splashscreen doesn't appear on Oneplus android 12

### ISSUE THREAD

**Issue by a-molinaro** [zoontek/react-native-bootsplash#319]
### Bug summary

Splashscreen doesn't appear on Oneplus device with Android 12. I have test it on other device device with other Android version and works fine.

![photo_2022-02-11_16-55-35](https://user-images.githubusercontent.com/24268950/153624422-a7979529-bbf4-4125-bccd-9bb0b21c3d01.jpg)

### Library version

4.1.3

### Environment info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 4.55 GB / 15.77 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: Not Found
  Languages:
    Java: 17.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Just test it on Oneplus device. I have tested on my Oneplus 9.

### Reproducible sample code

```js
There's no sample code just test it with Oneplus device. I tested it on my Oneplus 9.
```

**Comment by a-molinaro** [comment]
@zoontek I just run npx react-native run-android

**Comment by zoontek** [comment]
> @zoontek I just run npx react-native run-android

Same, it's started by an intent. But does it works when you restart the app manually after that?

**Comment by zoontek** [comment]
@a-molinaro Please give a reproduction repository then.

**Comment by zoontek** [comment]
@a-molinaro It works perfectly on a Pixel 4a (Android 12). I doubt OnePlus Android fork is that fucked 🤔

**Comment by artdevgame** [comment]
> @a-molinaro Did you started it from Android studio? There a known issue on Android 12 splash screens that doesn't appear when the app is started like this. But it works when started from the app drawer (in real conditions)

What is the known issue? Where can I find some more info on that? I see the same problem on Samsung S10 (running Android 12) but like you said, when started from the app drawer I do see the missing mipmap (though very small)

Don't want to distract from the thread, but sounds related to me 🤔

**Comment by zoontek** [comment]
> > @a-molinaro Did you started it from Android studio? There a known issue on Android 12 splash screens that doesn't appear when the app is started like this. But it works when started from the app drawer (in real conditions)
> 
> What is the known issue? Where can I find some more info on that? I see the same problem on Samsung S10 (running Android 12) but like you said, when started from the app drawer I do see the missing mipmap (though very small)
> 
> Don't want to distract from the thread, but sounds related to me 🤔

I'm talking about this issue: https://stackoverflow.com/a/69831106

Their issue tracker seems unavailable for now. I hope they will fix that in a future release.

**Comment by zoontek** [comment]
Regarding the comments:

> I use Nova Launcher as desktop and you will never get the icon/images on the splash screen when launching the app from a shortcut or the drawer when using Nova Launcher.

@a-molinaro is that something you have? A custom launcher?

**Comment by OmgDef** [comment]
I'm having the same issue with Android simulator API 32 (Pixel 2). On the same device with API 30 and 29, everything works fine. Tested on a new react-native project (0.67.2)

**Comment by claudiozam** [comment]
I'm having the same issue with Android 12 on a real Samsung Galaxy S10+ and  Android 12 - Pixel 2 (Emulator).  Tested on a new react-native project (0.67.3)

**Comment by zoontek** [comment]
@claudiozam @OmgDef Did you checked that it's not this case: https://github.com/zoontek/react-native-bootsplash/issues/325#issuecomment-1050398394

**Comment by claudiozam** [comment]
@zoontek now is working thank!. 

One important question? RN 0.67.3 (last stable version) targetSdkVersion to 30 (not 31).

Maybe we must wait to RN 0.68 with targetSdkVersion 31

**Comment by zoontek** [comment]
@claudiozam targetSdkVersion 31 is required to use Android SplashScreen API

**Comment by beng970804** [comment]
Is this library using the SplashScreen API already? If haven't, will it be implement in near future?

**Comment by zoontek** [comment]
@beng970804 Yes, it uses the SplashScreen API.

**Comment by zoontek** [comment]
Nobody actually reported the same issue? So I think it was not a library issue?

**Comment by jhoanborges** [comment]
Actually i'm having the same problem with a Samumg Galxy S10+ Android 12, but i haven't tested on another device. I'll do that.

**Comment by minhoyooDEV** [comment]
i have same issue note 20+ and 22 ultra

**Comment by zoontek** [comment]
@minhoyooDEV @jhoanborges https://stackoverflow.com/questions/69812590/android-12-splash-screen-icon-not-displaying/69831106#comment123436148_69812590

**Comment by minhoyooDEV** [comment]
> @minhoyooDEV @jhoanborges https://stackoverflow.com/questions/69812590/android-12-splash-screen-icon-not-displaying/69831106#comment123436148_69812590

Thanks you for your kindness :)

**Comment by zoontek** [comment]
I added a note in the README: https://github.com/zoontek/react-native-bootsplash#android-1

**Comment by jhoanborges** [comment]
> I added a note in the README: https://github.com/zoontek/react-native-bootsplash#android-1

Thank you. I'll try it later.

**Comment by Aurelienlajoinie** [comment]
If it can help someone, after some research i found a workaround to get it work at the first launch.
Adding `.init()` method at the begining of the `onCreate()` work for me :)

MainActivity.java:
```
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(null);

    //....
    RNBootSplash.init(MainActivity.this);
    //....
}
```

**Comment by mordechaim** [comment]
I still experience this issue when launching from the usual launcher screen on Samsung s10e with Android 12.

It will only happen after a force stop, subsequent runs work properly.

**Comment by zoontek** [comment]
@mordechaim That's normal and even the first thing written under "Android" in the README. It will not appear when it's started programmatically (ex: Android studio). The feature is made as it, not related to this library 🤷🏻‍♂️  Google is aware of it and say it's a wontfix.

![8B39F2B5-4059-4E7A-A20E-CC02C9D8FC09](https://user-images.githubusercontent.com/1902323/184779831-88c16ae2-7be2-4627-8dfb-bf1dccf89ea8.jpeg)

**Comment by mordechaim** [comment]
@zoontek yeah I saw that note, but I have this issue when starting from the regular launcher on the phone itself after a full app kill.

In any event I see this isn't related to this library (great library btw).
