### ISSUE TITLE
Android: Support for Android Xml Activity as Splash Screen

### ISSUE THREAD

**Issue by andreh111** [zoontek/react-native-bootsplash#320]
### Why it is needed?

In the current version there is only support for drawables files in Android which we cannot control them as custom xml layout files

**Comment by zoontek** [comment]
It cannot works with SplashScreen API (Android 12+)

**Comment by RiusmaX** [comment]
Hi, so, how can we customize correctly the bootscreen for Android ?

**Comment by augusto-booment** [comment]
This exactly what I was wondering

**Comment by Arron-Gill** [comment]
^ bump to the previous comment
