### ISSUE TITLE
"Action bar"-wide gap in landscape after upgrading to v4

### ISSUE THREAD

**Issue by Zloka** [zoontek/react-native-bootsplash#322]
### Bug summary

I followed the migration guide. Pardon if I misunderstood something, but prior to upgrading a screen (which is locked to landscape) looked like this:

![WhatsApp Image 2022-02-16 at 14 45 58 (1)](https://user-images.githubusercontent.com/17513212/154268275-87d6b0aa-5dce-45c9-8c30-c627beb14275.jpeg)

Following the upgrade, there is a gap on the left side:

![WhatsApp Image 2022-02-16 at 14 45 58](https://user-images.githubusercontent.com/17513212/154268243-8bc7b295-11c3-4092-b892-1fd752d52414.jpeg)

Here are the contents of my `styles.xml` file:
```
<resources>

  <!-- Base application theme. -->
  <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
    <!-- Customize your theme here. -->
    <item name="android:textColor">#000000</item>
  </style>

  <!-- BootTheme should inherit from Theme.SplashScreen -->
  <style name="BootTheme" parent="Theme.SplashScreen">
    <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
    <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
    <item name="postSplashScreenTheme">@style/AppTheme</item>
  </style>

</resources>
```

Is there something obvious I missed in the migration? For example, I have set `.NoActionBar` on `AppTheme`, but `BootTheme` no longer inherits from it. Though I suppose ` <item name="postSplashScreenTheme">@style/AppTheme</item>` indicates `AppTheme` should be used following the splash screen.

Tested this on my Samsung Galaxy S10 running Android 10. This particular screen is not wrapped in any SafeAreaViews, and doing so does not seem to matter either.

### Library version

^4.1.2

### Environment info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 731.32 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.6 - /Library/Java/JavaVirtualMachines/jdk-11.0.6.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

I haven't created a reproducible example yet.

### Reproducible sample code

```js
I haven't created a reproducible example yet.
```

**Comment by Zloka** [comment]
After some more testing, this seems to happen on all screens in landscape, but not on portrait. It's basically as if the app reserves space for a status bar that, naturally, isn't located on the side after rotating 🤔

**Comment by zoontek** [comment]
`Theme.SplashScreen` came from AndroidX directly:

- https://github.com/androidx/androidx/blob/androidx-main/core/core-splashscreen/src/main/res/values/styles.xml#L45

And is overridden:
- https://github.com/androidx/androidx/blob/androidx-main/core/core-splashscreen/src/main/res/values-v27/styles.xml
- https://github.com/androidx/androidx/blob/androidx-main/core/core-splashscreen/src/main/res/values-v29/styles.xml
- https://github.com/androidx/androidx/blob/androidx-main/core/core-splashscreen/src/main/res/values-v31/styles.xml

Do you see something that could mess up with your style?

**Comment by zoontek** [comment]
The AndroidX SplashScreen package take some liberties regarding the system UI: https://github.com/androidx/androidx/blob/androidx-main/core/core-splashscreen/src/main/java/androidx/core/splashscreen/SplashScreen.kt#L473 (that's precisely why I shipped `react-native-bars`, it's way easier to handle system UI with [`react-native-safe-area-context`](https://github.com/th3rdwave/react-native-safe-area-context) after that! No more opaque system UI, no special rules between iOS and Android.

**Comment by enverkoselertr** [comment]
@Zloka hello my friend i have the same problem how did you solve it i would be grateful if you can help me

**Comment by Zloka** [comment]
Didn't have time to get back to this until now. Admittedly, I have yet to figure out a "proper solution", but I figured I'd document what I did here. I found that adding the following line to the `AppTheme` is good enough in my case...

`<item name="android:windowBackground">@android:color/black</item>`

...it results in this in my application:
![WhatsApp Image 2022-03-06 at 12 23 31 PM (1)](https://user-images.githubusercontent.com/17513212/156919133-5ee7eee0-1ff5-44b2-8dc0-92ae38a8a184.jpeg)

For comparison, this is what e.g. Google Maps looks like in landscape:
![WhatsApp Image 2022-03-06 at 12 23 31 PM](https://user-images.githubusercontent.com/17513212/156919159-69fbe9af-a812-4c5f-b28a-02251fa754c1.jpeg)

I suppose I quite rarely use apps in landscape, but it seems like the black inset is quite common. In my app, I could fill the entire screen easily without running into styling issues, but this is also acceptable and I'm afraid I don't have that much time to spend on this project.

The only difference is that one can see that the Google Maps example is rounded, whereas my app is not. In my case, it actually looks better when it isn't rounded as the user will be swiping in screens from the right, so I guess that is a happy little accident 🙂

**Comment by zoontek** [comment]
@Zloka Is that OK for you if we close this issue?

**Comment by Zloka** [comment]
> @Zloka Is that OK for you if we close this issue?

Yeah, go ahead!

**Comment by enverkoselertr** [comment]
@Zloka By the way, I solved my problem by deleting this package (react-native-bootsplash). I made my own splash screen. Thanks anyway

**Comment by nhanders** [comment]
Just in case anyone comes across this problem, the problem I identified was that `windowLayoutInDisplayCutoutMode` is being set to `shortEdges` in the styles file [values-v27/styles.xml](https://github.com/androidx/androidx/blob/androidx-main/core/core-splashscreen/src/main/res/values-v27/styles.xml) . As far as I can tell, the desired behaviour of the issue author is `default`. (see [display cutout docs](https://developer.android.com/guide/topics/display-cutout))

[values-v27/styles.xml](https://github.com/androidx/androidx/blob/androidx-main/core/core-splashscreen/src/main/res/values-v27/styles.xml):
```
<style name="Base.v27.Theme.SplashScreen" parent="Base.v21.Theme.SplashScreen">
    <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
</style>
```

I updated my `AppTheme` to handle this:
```
<style name="AppTheme" parent="BaseAppTheme">
    <item name="android:windowLayoutInDisplayCutoutMode">default</item>
</style>
```

**Comment by sparklaunch** [comment]
> Just in case anyone comes across this problem, the problem I identified was that `windowLayoutInDisplayCutoutMode` is being set to `shortEdges` in the styles file [values-v27/styles.xml](https://github.com/androidx/androidx/blob/androidx-main/core/core-splashscreen/src/main/res/values-v27/styles.xml) . As far as I can tell, the desired behaviour of the issue author is `default`. (see [display cutout docs](https://developer.android.com/guide/topics/display-cutout))
> 
> [values-v27/styles.xml](https://github.com/androidx/androidx/blob/androidx-main/core/core-splashscreen/src/main/res/values-v27/styles.xml):
> 
> ```
> <style name="Base.v27.Theme.SplashScreen" parent="Base.v21.Theme.SplashScreen">
>     <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
> </style>
> ```
> 
> I updated my `AppTheme` to handle this:
> 
> ```
> <style name="AppTheme" parent="BaseAppTheme">
>     <item name="android:windowLayoutInDisplayCutoutMode">default</item>
> </style>
> ```

**Comment by sparklaunch** [comment]
It doesn't solve the problem. I tried both "never" and "default" values for "android:windowLayoutInDisplayCutoutMode". But all it did was turn the action bar from a white rectangle to a black rounded rectangle. I really want to know how to absolutely remove the action bar or something like that.
