### ISSUE TITLE
windowSplashScreenAnimatedIcon not showing logo

### ISSUE THREAD

**Issue by djdannycastillo** [zoontek/react-native-bootsplash#325]
### Bug summary

Hi! I've followed the instructions to config the library but the logo image is not showing but the background color, it does.

The plugin works correctly, but it's not showing the logo.

The resources has been generate correctly, I can see the file "bootsplash_logo.png" in all folder start with mipmap-...

I don't know what's the problem

### Library version

4.1.3

### Environment info

```shell
react: 17.0.2
react-native: 0.67.3
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>

    <!-- BootTheme should inherit from Theme.SplashScreen -->
    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>

</resources>
```

**Comment by zoontek** [comment]
@djdannycastillo Give me more infos.
Phone? Android version?

Did you restart the app after building? (see https://github.com/zoontek/react-native-bootsplash/issues/319#issuecomment-1038958870)

**Comment by djdannycastillo** [comment]
@zoontek Oh I see! That was the problem, I'm trying to launch the app from the terminal but I needed to launch in normal conditions (from the app drawer).

Thank you for your help!
