### ISSUE TITLE
react-native-bootsplash has been initialized too early: rootviewcontroller must be set in react native

### ISSUE THREAD

**Issue by ngohuy0972** [zoontek/react-native-bootsplash#328]
### Bug summary

We have problems with bootsplash when testing push notifications (Notifee) from IOS 15 (Kill App State).
Summarize bug: 
Device: iPhone 11 (15.0). iPad mini 6 (15.2)

![IMG_0973](https://user-images.githubusercontent.com/49360277/156494557-b535827f-88ab-473a-9e00-acd124a04626.PNG)

Does anyone have a solution for this bug? Please have me!! Thanks so much!!

### Library version

3.2.4

### Environment info

```shell
Device Test: iPhone 11 (15.0). iPad mini 6 (15.2)
MacMini 2018
Processer: 3 GHz 6-Core Intel Core i5
Memory: 16GB 2667 MHz DDR4
Node: v16.13.2
yarn: 1.22.17
npm: 8.1.2
watchman: 2021.10.18.00
```

### Steps to reproduce

1. Open the app
=> Show Home screen
2. Quit the app
3. Push a notification
=> Show head up notification
4. Don't Touch on Notification
5. Open the app again : 
Result: Don't show anything on the app even though data is loaded (Home Screen is blank)

### Reproducible sample code

```js
RNBootSplash.hide()
```

**Comment by zoontek** [comment]
Just update.
