### ISSUE TITLE
Gradient background color

### ISSUE THREAD

**Issue by NixFull** [zoontek/react-native-bootsplash#330]
### Why it is needed?

When you add drawable gradient background color, it hide the splash screen logo

**Comment by zoontek** [comment]
It can be achieve with Android SplashScreen API

**Comment by Lapaenergy** [comment]
@zoontek  Do you have an example with achieved gradient with use Android SplashScreen API ?

**Comment by jaredkotoff** [comment]
@Lapaenergy @zoontek this seems to work just fine https://medium.com/geekculture/implementing-the-perfect-splash-screen-in-android-295de045a8dc

**Comment by medelmourabite** [comment]
@jaredkotoff is this possible on ios?

**Comment by jaredkotoff** [comment]
> @jaredkotoff is this possible on ios?

The issues here are more specific to Android because of changes to the API. But yes, iOS uses storyboards and works fine. For my use-casue I just used a lot of constraints that are relative to the SuperView

**Comment by quicksilverr** [comment]
Hey @jaredkotoff Can you please share your approach?

**Comment by jaredkotoff** [comment]
> Hey @jaredkotoff Can you please share your approach?

Can you be more specific?
For iOS just Google it. It's pretty intuitive in xcode.
For Android, I patched in support into this project for the layout type I wanted to use
