### ISSUE TITLE
Add GIF image file support 

### ISSUE THREAD

**Issue by pratikdonda** [zoontek/react-native-bootsplash#334]
### Why it is needed?

**GIF image file supports**
Please add GIF image support as well so developer can easily show GIF image file instead of static image if required.

thanks.

**Comment by MaxJadav** [comment]
@zoontek  @pratikdonda 
Seems like GIF not work. Any update on this?

**Comment by zoontek** [comment]
@MaxJadav Support will never be added. GIF quality / size is kind of bad.
If you want animation, use Lottie or similar.
