### ISSUE TITLE
Android bootsplash icon is showing small

### ISSUE THREAD

**Issue by OshedheMunasinghe** [zoontek/react-native-bootsplash#335]
### Bug summary

Doesn't matter which size you have icon.png 
after generated the bootsplash is showing very small icon 😂

Also it didn't generated bootsplash.xml - I guess that it doesn't need it? 

I just wondering how to make the bootsplash icon to full screen? 

### Library version

4.1.3

### Environment info

```shell
System:
    OS: Windows 10 
    CPU: (8) ia32 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 939.87 MB / 7.89 GB
  Binaries:
    Node: 16.14.1 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.4 - C:\Program Files (x86)\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    Visual Studio: 17.0.32112.339 (Visual Studio Community 2022)
  Languages:
    Java: 16.0.2 - /c/Program Files/Java/jdk-16.0.2/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. android but I haven't tried iOS yet

### Reproducible sample code

```js
?
```

**Comment by zoontek** [comment]
You can set --logo-width param in the generator CLI.
Above 192 it might be cropped on Android. It's a system limitation.
