### ISSUE TITLE
timeout on launch

### ISSUE THREAD

**Issue by BartJanvanAssen** [zoontek/react-native-bootsplash#34]
Hey i'm having an issue that the app will not launch and was wondering if this was the issue...

2019-12-06 08:39:30.999 2051-2072/? W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{7203840 u0 com.[MYAPP]/com.zoontek.rnbootsplash.RNBootSplashActivity t16}

any idea?

### 💻 My environment

- react-native-bootsplash version: newest
- react-native version: newest
- Platform: android 
- OS version: newest
- Simulator: yes / no
- Android Studio version: newest
- Android buildToolsVersion: newest

### 🕵️‍♂️ Reproducing the issue
startup

**Comment by zoontek** [comment]
@BartJanvanAssen Your app hangs at startup. Could you upload your `AndroidManifest.xml`?

**Comment by BernardoBF4** [comment]
@BartJanvanAssen, you closed this issue because you managed to solve it? If yes, I am having the same problem and I'd like to understand your solution.

**Comment by BartJanvanAssen** [comment]
Im sorry have no clue, long time ago 😅

**Comment by BernardoBF4** [comment]
Oh, okay, then. Thanks for your attention :)

**Comment by mkbhdana** [comment]
@BartJanvanAssen  I am also facing this issue on release mode with new architecture on old it was fine.
