### ISSUE TITLE
hide not working in release mode

### ISSUE THREAD

**Issue by dancixx** [zoontek/react-native-bootsplash#340]
### Bug summary

Hi, it works everything fine, but on iOS in release, mode cant hides the splash image.
I use the latest release of this library. It is weird but the underlay screen works if I touch the screen.

### Library version

4.1.4

### Environment info

```shell
react-native@67.1
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
My AppDelegate.m


// default react-native
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];  
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  // initialize BootSplash
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];

  // Expo react-native-unimodules
  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
```

Navcontainer
```
 <NavigationContainer
      theme={MyTheme}
      ref={navigationRef}
      onReady={() => {
        routeNameRef.current = navigationRef.current!.getCurrentRoute()!.name;

        return RNBootSplash.hide({fade: true});
      }}
```
```

**Comment by dancixx** [comment]
Sorry my mistake

**Comment by lorenjohnson** [comment]
Hi @dancixx! What was the solution? Been having this problem as well. Triple-checked my setup, also hiding in React Navigation `onReady` and screen doesn't hide most of the time on my Production builds.

**Comment by LukasMod** [comment]
Hi @dancixx,
Could you share your solution? What was the mistake?
I got the same behavior on release ios builds only. But there is no error/crash, nothing suspicious in logs.

**Comment by javiermojito** [comment]
Hi @dancixx, Can you please share your solution? It seems that everyone here it's facing the same problem.

**Comment by javiermojito** [comment]
@LukasMod Thanks!

**Comment by ayoubechc** [comment]
any solution ??
