### ISSUE TITLE
Documentation for onCreate Android

### ISSUE THREAD

**Issue by DaveAldon** [zoontek/react-native-bootsplash#341]
### Why it is needed?

Hello and thank for you your work on this project! Please let me know if this is covered somewhere, but if my Android project uses `onCreate` instead of the documentation's `loadApp`, is there _supposed_ to be a 1:1 change? I did this:

```typescript
@Override
  protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      RNBootSplash.init(MainActivity.this);
  }
```

But my android build would crash immediately. So I did a `abd logcat` and saw this message:
`You need to use a Theme.AppCompat theme...`

Looking at the docs here: https://developer.android.com/reference/kotlin/androidx/core/splashscreen/SplashScreen
I saw that the compat themes are supposed to be initialized _before_ setContentView is being called inside the onCreate override in the MainActivity.

### Possible implementation

All I did was swap the calls, so I init RNBootSplash before `super.onCreate` and the crashes stopped. Is this okay? Or is there something else going on that I should change? I couldn't find any previous issues that were specifically like this.

### Code sample

```typescript
@Override
  protected void onCreate(Bundle savedInstanceState) {
      RNBootSplash.init(MainActivity.this);
      super.onCreate(savedInstanceState);
  }
```

**Comment by santhosh-umapathi-appymango** [comment]
> ```ts
>       RNBootSplash.init(MainActivity.this);
> ```

Thank you for this case, this solved my issue as well

**Comment by andvalsol** [comment]
Please update the documentation since adding  `RNBootSplash.init(MainActivity.this)`  inside the `onCreate()` for the MainActivity was the solution for the You need to use a Theme.AppCompat theme... issue

**Comment by zoontek** [comment]
The documentation is up to date and don't mention onCreate since v4: https://github.com/zoontek/react-native-bootsplash#android-1

**Comment by nelsonprsousa** [comment]
Hi @zoontek 

Just want to let you know, I am using react-native 0.67.4 and the docs point me to this specific document: https://github.com/zoontek/react-native-bootsplash/blob/4.1.3/README.md

However, I still have the onCreate() and getMainComponent() methods on MainActivity.java, so it is rather confusing or I missed something.

**Comment by nelsonprsousa** [comment]
> > ```ts
> >       RNBootSplash.init(MainActivity.this);
> > ```
> 
> Thank you for this case, this solved my issue as well

I'll like to add that `RNBootSplash.init()` should go first (compared to `super.onCreate(null)`), like this:

```java
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    RNBootSplash.init(MainActivity.this);
    super.onCreate(null);
    RNBars.init(MainActivity.this, "dark-content");
  }
```

Otherwise the app will crash.
