### ISSUE TITLE
Support 0.68 Fabric

### ISSUE THREAD

**Issue by dougg0k** [zoontek/react-native-bootsplash#342]
### Why it is needed?

It's the only library that I use that is not yet compatible.

Do you guys have any intention of adding it?

If so would it be soon? If you need an example to run, this example <https://github.com/react-native-community/react-native-template-typescript> are fully working with the latest stable version. You might need to activate through the config though.

I dont know enough about the new architecture nor Android, and I dont know Objective-C/Swift to help with a PR.

**Comment by dougg0k** [comment]
I see the splash screen, but then it crashes. I only tested on Android so far.

```
Unknown

Unknown

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 11914 (create_react_co), pid 11248 (app_name)
```

**Comment by zoontek** [comment]
@dougg0k Hi! I opened a ticket about the current situation: https://github.com/zoontek/react-native-bootsplash/issues/343
