### ISSUE TITLE
[call for sponsors] - React Native new architecture support

### ISSUE THREAD

**Issue by zoontek** [zoontek/react-native-bootsplash#343]
Hi everyone 👋

@zoontek here, creator and maintainer of `react-native-{bootsplash / localize / permissions / bars / dev-menu}`.
I'm opening this issue to prevent multiple ones from being created about the new React Native architecture compatibility ([introduced in version `0.68`](https://reactnative.dev/blog/2022/03/30/version-068)).

I'm excited about these changes and the future of React Native, but it's quite hard for me to free up time to work on it.
To explain myself a little bit: I did a lot of open source these last years, mainly for free - and I enjoyed it, don't even doubt about that 😄. It's not only about writing code, but also about helping people, so they can craft great products ✨.

But time flies. On a personal note, I'm currently trying to buy my own flat and started a freelance activity in addition to my regular job to achieve this goal.
Open source is time-consuming (handling issues, reproducing, reviewing PRs, etc) and doesn't pay bills. Even worse: it currently costs me money (I bought several used phones for testing, a personal MacBook recently). I could use this time to work for paid freelancing instead.

On the other side, every day I see companies using these libraries in quite popular apps. That's why I'm calling them for sponsorship. It doesn't have to be a recurrent, monthly sponsorship, but if you want to push for the new arch landing on this repository, understand that it will be easier for me to find some time if I'm being paid for the task 🙂 (actually, it could be fast!)

👉 For that, I created one-time sponsorship tiers ([available here](https://github.com/sponsors/zoontek?frequency=one-time)). You don't have to respect the amounts (custom is possible - maybe you are an individual and can only give a little or maybe you want to give even more than the last tier).
If you are not used to giving money for open source software, you can think of it as a one-time payment license (even if it's clearly not - it will stay free and MIT).

P.S. I'm aware I could also wait for a PR written for free by a community member to land, but that's **not** what I want.
Even if it happens, I will still have to learn about the new arch, review it, and will maintain it / answer your questions after it's merged. So it will probably be easier if I work on it initially.

P.S. (2) That doesn't mean that it will never land if I don't get sponsorships, just that it will be less of a priority for me.

**Comment by francesco-clementi-92** [comment]
I would appreciate a price for the feature instead of a sponsorship. 
If you setup for example 3000$ for this integration and each one of us that use the package will donate would be awesome and faster :)

**Comment by zoontek** [comment]
@francesco-clementi-92 That's a good idea.

Unfortunately, Github sponsors does not support setting multiple goals, only one per user (not per project), and I need to set once for `react-native-bootsplash`, `react-native-localize` and `react-native-permissions`.

I know it's doable on [Open Collective](https://opencollective.com/) ([docs](https://docs.opencollective.com/help/collectives/collective-settings/tiers-goals)), that could be a solution if people here are OK with that.

**Comment by zoontek** [comment]
To be absolutely transparent, since this call for sponsors (on `react-native-bootsplash / localize / permissions` repositories), I received 278$ (from one-time sponsors) and I'm now receiving 63$ per month as recurring sponsors.

**Comment by zoontek** [comment]
Quick update: I created an Open collective page to set a goal: https://opencollective.com/react-native-bootsplash/contribute/new-architecture-support-44900

As @francesco-clementi-92 suggested, 3000$ seems to be a correct goal regarding the freelance rates in my town 🙂 I hope companies will play the game, will open similar goals for react-native-localize / react-native-permissions

**Comment by zoontek** [comment]
@affansk Unfortunately:

> EDIT: I'm closing it. If nothing happen in 20 days (even with communication about it), I think it will probably never reach its goal 😕

**Comment by affansk** [comment]
@zoontek  i think you should give people more time. i guess most of the people dont know about it.
