### ISSUE TITLE
[Android] splash screen - set fullscreen image instead background color and icon centered on screen

### ISSUE THREAD

**Issue by oleksandr-ccm** [zoontek/react-native-bootsplash#347]
### Why it is needed?

I think this approach was implemented some time ago, but now I cannot reach this with react-native-bootsplash.

I've left the answer here https://stackoverflow.com/questions/71969718/react-native-bootsplash-fullscreen-image

If you have any helps, could you provide this ?

### Possible implementation

Add way to set background image instead just background color and icon set optionally

### Code sample

```js
<item name="android:windowBackground">@drawable/background_splash</item>
```

**Comment by oleksandr-ccm** [comment]
Hi, may you share the link with solution if this question really duplication ?

**Comment by zoontek** [comment]
This question already has been answered a few times here.

It's an official platform API since Android 12, and now an Android limitation: https://developer.android.com/guide/topics/ui/splash-screen

**Comment by oleksandr-ccm** [comment]
Thanks for you instant response =) 
As I understand it's impossible to find workaround to reach the goal, correct?

**Comment by zoontek** [comment]
@oleksandr-ccm Not anymore indeed

**Comment by oleksandr-ccm** [comment]
Thanks a lot for your work!

**Comment by oleksandr-ccm** [comment]
@zoontek   I have one more question. I want to set company icon with shape - rectangle. But result - is circled shape and cutted logo. I use pure settings from doc. Is it possible to stretch the icon  or increase the size ?

**Comment by zoontek** [comment]
No, check the Android doc. It's a circle mask (max 192dp)
