### ISSUE TITLE
disabling Android 12 rounded splash image style

### ISSUE THREAD

**Issue by kockok** [zoontek/react-native-bootsplash#349]
### Why it is needed?

Not everyone wanted a rounded logo on the splash-screen
![201895453--35751407--1150887](https://user-images.githubusercontent.com/232541/164983433-9a335659-0ce2-4355-8668-90d27b8fed14.jpeg)
.

### Possible implementation

Set an option to disable such a rounded shaping.

**Comment by zoontek** [comment]
@SMKH-PRO Reduce its size so it can fit inside the mask area (the logo width param)

**Comment by naheed-s** [comment]
any solution for this ?

**Comment by marksyzm** [comment]
Just android being crap again, then.
