### ISSUE TITLE
[Discussion / Feature Request?] Is it possible to customize Splash screen?

### ISSUE THREAD

**Issue by zxccvvv** [zoontek/react-native-bootsplash#352]
### Why it is needed?

I want to add Text at the bottom of SplashScreen something like

> Made with a lot of ❤️ by Founder

### Possible implementation

I don't know how RN Bootsplash working
sorry for my lack of knowledge 😢 

### Code sample

```js
I don't mind to customize native platform to achieve this feature,

but it would be good if we can do that at JS side, something like `TextBottom('Here we go')`
```

**Comment by zoontek** [comment]
It can't be done since the JS has to be loaded, parsed and executed at start.

**Comment by zxccvvv** [comment]
@zoontek can you help me how to achieve it on native side? Especially android?

**Comment by zoontek** [comment]
You can use `<item name="android:windowSplashScreenBrandingImage">@drawable/...</item>`, but it will only work on Android 12+
