### ISSUE TITLE
Why RNBootSplash.show disappeared ?

### ISSUE THREAD

**Issue by arnaudambro** [zoontek/react-native-bootsplash#354]
### Why it is needed?

Hello !
Great lib sofar, but I was making some good uses of `RNBootSplash.show` in previous versions...
Why did you deleted it ? I'm sad !

**Comment by zoontek** [comment]
Because Android SplashScreen API doesn't offer it by default

**Comment by arnaudambro** [comment]
alright

I just created my own "custom" ! working good enough

```jsx
import React from 'react';
import { Modal } from 'react-native';
import { atom, useRecoilValue } from 'recoil';
import styled from 'styled-components';

export const showBootSplashState = atom({
  key: 'showBootSplashState',
  default: false,
});

const CustomBootsplash = () => {
  const showBootSplash = useRecoilValue(showBootSplashState);

  return (
    <Modal visible={showBootSplash} animationType="fade">
      <FullScreen>
        <StyledImage source={require('../assets/images/Icon.png')} />
      </FullScreen>
    </Modal>
  );
};

const FullScreen = styled.View`
  height: 100%;
  width: 100%;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  justify-content: center;
  align-items: center;
  background-color: #4030a5;
`;

const StyledImage = styled.Image`
  width: 250px;
  height: 250px;
`;

export default CustomBootsplash;
```

**Comment by DARPANMANEK** [comment]
> alright
> 
> I just created my own "custom" ! working good enough
> 
> ```js
> import React from 'react';
> import { Modal } from 'react-native';
> import { atom, useRecoilValue } from 'recoil';
> import styled from 'styled-components';
> 
> export const showBootSplashState = atom({
>   key: 'showBootSplashState',
>   default: false,
> });
> 
> const CustomBootsplash = () => {
>   const showBootSplash = useRecoilValue(showBootSplashState);
> 
>   return (
>     <Modal visible={showBootSplash} animationType="fade">
>       <FullScreen>
>         <StyledImage source={require('../assets/images/Icon.png')} />
>       </FullScreen>
>     </Modal>
>   );
> };
> 
> const FullScreen = styled.View`
>   height: 100%;
>   width: 100%;
>   top: 0;
>   bottom: 0;
>   left: 0;
>   right: 0;
>   justify-content: center;
>   align-items: center;
>   background-color: #4030a5;
> `;
> 
> const StyledImage = styled.Image`
>   width: 250px;
>   height: 250px;
> `;
> 
> export default CustomBootsplash;
> ```

hi arnaudambro, can you help me to implement it?
