### ISSUE TITLE
App Does not Go pass The Slash Screen on APK Debug 

### ISSUE THREAD

**Issue by sheggietyn** [zoontek/react-native-bootsplash#356]
### Bug summary

my app works perfectly on development, but on production it does not go pass the splash screen of bootsplash 

### Library version

react-native-bootsplash android

### Environment info

```shell
>=0.56
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
please what is the solution
```

**Comment by zoontek** [comment]
Please provide more details.

**Comment by camilo-Grability** [comment]
I am having the same problem, when generating the apk, the app puts a black image and does not go beyond the black image, but in the android and ios emulators it works correctly, I am going to upload the . aab to the stores to see if the problem is solved in production

**Comment by kss943** [comment]
I have the same problem when generating the debug apk and trying to open it on a real device. An app just stacks on the splash screen. Release apk works fine.
