### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by MohamadKh75** [zoontek/react-native-bootsplash#36]
### 💻 My environment

- react-native-bootsplash version: 1.0.3
- react-native version: 0.61.5
- Platform: android
- OS version: Win 8.1
- Device: Samsung galaxy 7 edge
- Simulator: no
- Android Studio version: -
- Android buildToolsVersion: 28.0.3
- Xcode version: -

### 🕵️‍♂️ Reproducing the issue

I want to set up deep linking with react-navigation as described [here](https://reactnavigation.org/docs/en/deep-linking.html). I finally made it but the problem is when i open the app using the deep link, I get my props as `undefined` but if i reload the app, i see it!
It's somehow weird!

## AndroidManifest.xml
```xml
<application
  android:name=".MainApplication"
  android:label="@string/app_name"
  android:icon="@mipmap/ic_launcher"
  android:roundIcon="@mipmap/ic_launcher_round"
  android:allowBackup="false"
  android:theme="@style/AppTheme">

  <activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:screenOrientation="portrait"
    android:windowSoftInputMode="adjustPan"
    android:exported="true"
    android:launchMode="singleTask">

    <!-- Deep Linking -->
    <intent-filter>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.DEFAULT" />
      <category android:name="android.intent.category.BROWSABLE" />
      <data android:scheme="aramesh" />
    </intent-filter>
  </activity>

  <!-- Splash Screen -->
  <activity
    android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
    android:theme="@style/BootTheme">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
  </activity>

  <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
</application>
```

## Router.js
```js
_Landing: {
  screen: Landing,
  path: 'agent/:personID'
},
```

## Code
```js
componentDidMount() {
  alert(this.props.navigation.getParam('personID'));
}
```

### 🤞Solution

I guess it's somehow related to #24 which has been solved via #11. But i can't understand why i get this as `undefined` for the first time :neutral_face:

**Comment by zoontek** [comment]
When your app the first time, it open with `RNBootSplashActivity` then `MainActivity`. The `RNBootSplashActivity` will pass all extras intents to your `MainActivity`, and starts it.
When you reload your app, the active Activity is already `MainActivity`, which can receive `aramesh` links according to your manifest.

Try adding the intent-filter to the splash screen activity too.

```xml
<activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:screenOrientation="portrait"
    android:windowSoftInputMode="adjustPan"
    android:exported="true"
    android:launchMode="singleTask">

    <!-- Deep Linking -->
    <intent-filter>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.DEFAULT" />
      <category android:name="android.intent.category.BROWSABLE" />
      <data android:scheme="aramesh" />
    </intent-filter>
  </activity>

  <!-- Splash Screen -->
  <activity
    android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
    android:theme="@style/BootTheme">
    <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>

    <!-- Deep Linking -->
    <intent-filter>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.DEFAULT" />
      <category android:name="android.intent.category.BROWSABLE" />
      <data android:scheme="aramesh" />
    </intent-filter>
  </activity>
```

**Comment by MohamadKh75** [comment]
Tnx for your reply.

Unfortunately, the problem exist :neutral_face: 
I edited manifest and rebuild. Now when i click on the button with link of `aramesh://agent/2` android gives me two options (Both are my app with same package name) and both of them don't load the `Landing` page. (As you can see, i added the `path: 'agent/:personID'` to my router!

I followed [this doc](https://reactnavigation.org/docs/en/deep-linking.html) so, am i missing something? Or is this a bug?

**Comment by zoontek** [comment]
@MohamadKh75 I just published a release with the fix (`1.1.0`).

To handle deep linking, you have to:
- Add `android:launchMode="singleTask"` on your `MainActivity`
- Add `android:launchMode="singleTask"` on your `RNBootSplashActivity `
- Add the deep linking `<intent-filter>` inside the `RNBootSplashActivity`

For you, it will be:

```xml
<application
  android:name=".MainApplication"
  android:label="@string/app_name"
  android:icon="@mipmap/ic_launcher"
  android:roundIcon="@mipmap/ic_launcher_round"
  android:allowBackup="false"
  android:theme="@style/AppTheme">

  <activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:screenOrientation="portrait"
    android:windowSoftInputMode="adjustPan"
    android:exported="true"
    android:launchMode="singleTask" />

  <!-- Splash Screen -->
  <activity
    android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
    android:theme="@style/BootTheme"
    android:launchMode="singleTask">

    <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>

    <!-- Deep Linking -->
    <intent-filter>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.BROWSABLE" />
      <category android:name="android.intent.category.DEFAULT" />
      <data android:scheme="aramesh" />
    </intent-filter>

  </activity>

  <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
</application>
```

Can you try and confirm that everything is OK? Thanks!

**Comment by MohamadKh75** [comment]
Yep! Everything is OK :tada: 

Tnx :heart: 

I'll create a PR to add this to readme :grin:

**Comment by paolospag** [comment]
I had the same problem in the recent days and [this annotation](https://github.com/zoontek/react-native-bootsplash/issues/36#issuecomment-565745200) seems to have solved it, but what about usage with notifications' modules?
E.g., integrating RN Firebase Notifications (v5.6.0) and following the [documentation](https://rnfirebase.io/docs/v5.x.x/notifications/android) for Android, it requires `singleTop` instead of `singleTask` launch mode.

So what needs to be done in these cases?

**Comment by zoontek** [comment]
If I refer to https://inthecheesefactory.com/blog/understand-android-activity-launchmode/en, singleTop could be used as well (on both Activity). But I would recommend keeping `singleTask` on the BootSplash one

**Comment by paolospag** [comment]
So, the code should be:

```xml
<application
  android:name=".MainApplication"
  android:label="@string/app_name"
  android:icon="@mipmap/ic_launcher"
  android:roundIcon="@mipmap/ic_launcher_round"
  android:allowBackup="false"
  android:theme="@style/AppTheme">

  <activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:screenOrientation="portrait"
    android:windowSoftInputMode="adjustPan"
    android:exported="true"
    android:launchMode="singleTop" /> <!-- change this for Notifications support -->

  <!-- Splash Screen -->
  <activity
    android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
    android:theme="@style/BootTheme"
    android:launchMode="singleTask"> <!-- maintain on SingleTask for Bootsplash -->

    <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
    <intent-filter>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.BROWSABLE" />
      <category android:name="android.intent.category.DEFAULT" />
      <data android:scheme="aramesh" />
    </intent-filter>

  </activity>

  <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
</application>
```

Is it correct?

**Comment by zoontek** [comment]
@paolospag Yes! Android has some debug tools to test deeplinks, give it a try

**Comment by enverkoselertr** [comment]
> @MohamadKh75 I just published a release with the fix (`1.1.0`).
> 
> To handle deep linking, you have to:
> 
> * Add `android:launchMode="singleTask"` on your `MainActivity`
> * Add `android:launchMode="singleTask"` on your `RNBootSplashActivity `
> * Add the deep linking `<intent-filter>` inside the `RNBootSplashActivity`
> 
> For you, it will be:
> 
> ```
> <application
>   android:name=".MainApplication"
>   android:label="@string/app_name"
>   android:icon="@mipmap/ic_launcher"
>   android:roundIcon="@mipmap/ic_launcher_round"
>   android:allowBackup="false"
>   android:theme="@style/AppTheme">
> 
>   <activity
>     android:name=".MainActivity"
>     android:label="@string/app_name"
>     android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
>     android:screenOrientation="portrait"
>     android:windowSoftInputMode="adjustPan"
>     android:exported="true"
>     android:launchMode="singleTask" />
> 
>   
>   <activity
>     android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
>     android:theme="@style/BootTheme"
>     android:launchMode="singleTask">
> 
>     <intent-filter>
>       <action android:name="android.intent.action.MAIN" />
>       <category android:name="android.intent.category.LAUNCHER" />
>     </intent-filter>
> 
>     
>     <intent-filter>
>       <action android:name="android.intent.action.VIEW" />
>       <category android:name="android.intent.category.BROWSABLE" />
>       <category android:name="android.intent.category.DEFAULT" />
>       <data android:scheme="aramesh" />
>     </intent-filter>
> 
>   </activity>
> 
>   <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
> </application>
> ```
> 
> Can you try and confirm that everything is OK? Thanks!

Hello, I am getting an error like this, where am I going wrong

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.smartiq">
    <queries>
      <package android:name="com.google.android.googlequicksearchbox"/>
    </queries>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        
      </activity>
       
      <activity
        android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
        android:theme="@style/BootTheme"
        android:launchMode="singleTask">

        <intent-filter android:autoVerify="true"> 
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="smartiq" />
            <data android:scheme="https" android:host="login.smartiq.io" />
        </intent-filter>

      </activity>
    </application>
</manifest>


* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.


// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        maven { url 'https://www.jitpack.io' }
    }
}

**Comment by enverkoselertr** [comment]
@zoontek help me pls

**Comment by zoontek** [comment]
@enverkoselertr Just follow the error message…This is not a library issue.

```xml
<activity
  android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
  android:theme="@style/BootTheme"
  android:launchMode="singleTask"
  android:exported="true"><!-- add this line -->
```

Please consider a one time sponsorship (click on the sponsor button), because you by mentioning me explicitly you bothered me in my personal life. Open source is not a free products with folks working for you, willing to help at any time.

And if you don't want to support a free library and the people behind it, next time ask for help elsewhere.

**Comment by enverkoselertr** [comment]
@zoontek 

Thank you very much for your answer. I've never thought of it this way. I am so sorry for my thoughtlessness. I will do what is necessary, have a nice day

**Comment by jakubkoziejj** [comment]
@zoontek What should AndroidManifest.xml look like now after the structure change?
