### ISSUE TITLE
StatusBar backgroundColor and barStyle not applied properly on Android 12

### ISSUE THREAD

**Issue by LazyAfternoons** [zoontek/react-native-bootsplash#366]
### Bug summary

When using this library in combination to the React Native StatusBar component, backgroundColor and barStyle properties are only applied correctly upon first startup in Android 12. Killing the app and reopening it results in them not being applied correctly.
Icons will be shown in 'light-content' even if 'dark-content' is set. Please note that this only occurs when both backgroundColor and barStyle are set. Removing backgroundColor seems to fix the issue.

### Library version

4.2.1

### Environment info

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 25.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /var/folders/t_/ynmjm_hd3q992t7hhs5cyky80000gn/T/yarn--1656324793667-0.9955478753482732/node
    Yarn: 1.22.18 - /var/folders/t_/ynmjm_hd3q992t7hhs5cyky80000gn/T/yarn--1656324793667-0.9955478753482732/yarn
    npm: 8.5.0 - /usr/local/opt/node@16/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.0 => 0.69.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Clone the provided repository;
2. run `yarn install `and `yarn react-native run-android` on an **Android 12** emulator or physical device;
3. Open the app and the properties will be applied correctly;
4. Close the app from the task manager and reopen it. Properties will not be applied correctly, icons will be shown in 'light-content'.

The bug only occurs on Android 12 on both emulator and physical device, currently testing on a Pixel 4A. Android 11 seems to work just fine, iOS too. 

### Reproducible sample code

```js
https://github.com/LazyAfternoons/rn-bugreport
```

**Comment by zoontek** [comment]
@LazyAfternoons Please follow https://github.com/zoontek/react-native-bars#with-react-native-bootsplash

**Comment by zoontek** [comment]
@LazyAfternoons I added a check on Android 12 to avoid calling `core-splashscreen` `remove`: https://github.com/zoontek/react-native-bootsplash/commit/37ae1e6d4fbf185e56af39f60efcaf5f5f525ca7

Upgrade to `4.2.2` and give it a try 🙂

**Comment by LazyAfternoons** [comment]
> @LazyAfternoons I added a check on Android 12 to avoid calling `core-splashscreen` `remove`: [37ae1e6](https://github.com/zoontek/react-native-bootsplash/commit/37ae1e6d4fbf185e56af39f60efcaf5f5f525ca7)
> 
> Upgrade to `4.2.2` and give it a try 🙂
> 
> More infos: [#331 (comment)](https://github.com/zoontek/react-native-bootsplash/issues/331#issuecomment-1164421552)

Fixed, lovely. Thanks a lot for the fast response and the support.

**Comment by LazyAfternoons** [comment]
Sorry to bother you @zoontek but the fix you pushed seems to work only on React 0.69. When I generated the reproducible sample code I downloaded the usual React Native temple which now uses React 0.68, released a few days ago. Before your fix even this release was affected by the issue and it looks like preventing the call to applyThemesSystemBarAppearance does the trick on React 0.69.

When I tried to update this package in my projects currently running on React 0.68 I noticed that the issue is still there. 
I decided then to generate a new reproducible sample code based on React 0.68 (you can find it in the repository linked in the origin post, I re-created the repository based on React 0.68) and the issue is definitely still there. I then decided to generate a new sample based on 0.69 and the issue is definitely fixed on that version. 

Any idea on what's going on? Thank you again for your hard work.

**Comment by zoontek** [comment]
React Native < 0.69 does not use AndroidX APIs and it has a lot of quirks (https://reactnative.dev/blog/2022/06/21/version-069#highlights-of-069)

For old RN versions, react-native-bars will work perfectly.

**Comment by chj-damon** [comment]
thanks for this!
