### ISSUE TITLE
Unable to install the NPM

### ISSUE THREAD

**Issue by govarthananve** [zoontek/react-native-bootsplash#384]
### Bug summary

npm i react-native-bootsplash
npm ERR! code 128
npm ERR! path /.../node_modules/react-native-bootsplash
npm ERR! command failed
npm ERR! command sh -c -- git config --local core.hooksPath .hooks
npm ERR! fatal: --local can only be used inside a git repository

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/name/.npm/_logs/2022-08-14-debug-0.log

### Library version

4.3.1

### Environment info

```shell
npm i react-native-bootsplash
```

### Steps to reproduce

npm i react-native-bootsplash

### Reproducible sample code

```js
npm i react-native-bootsplash
```

**Comment by govarthananve** [comment]
"react": "18.0.0",
"react-native": "0.69.3",

**Comment by zoontek** [comment]
Fixed: https://github.com/zoontek/react-native-bootsplash/releases/tag/4.3.2

**Comment by govarthananve** [comment]
Thanks👍🏾
Now working fine
