### ISSUE TITLE
Rollback to 2.2.8

### ISSUE THREAD

**Issue by BuiltbyGit** [zoontek/react-native-bootsplash#385]
### Bug summary

Hi there. Running npm audit reports this vulnerability: 

`# npm audit report

jpeg-js  <0.4.4
Severity: high
Infinite loop in jpeg-js - https://github.com/advisories/GHSA-xvf7-4v9q-58w6
fix available via `npm audit fix --force`
Will install react-native-bootsplash@2.2.8, which is a breaking change
node_modules/jpeg-js
  @jimp/jpeg  <=0.12.0 || >=0.16.1
  Depends on vulnerable versions of jpeg-js
  node_modules/@jimp/jpeg
    @jimp/types  <=0.11.1-canary.891.908.0 || >=0.16.1
    Depends on vulnerable versions of @jimp/jpeg
    node_modules/@jimp/types
      jimp  0.3.6-alpha.5 - 0.11.1-canary.891.908.0 || >=0.16.1
      Depends on vulnerable versions of @jimp/types
      node_modules/jimp
        react-native-bootsplash  1.2.1 - 2.2.4 || >=3.0.0-alpha.0
        Depends on vulnerable versions of jimp
        node_modules/react-native-bootsplash

5 high severity vulnerabilities`

### Library version

4.3.2

### Environment info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 1.03 GB / 7.88 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 30, 31, 32
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.2 => 0.69.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Install react native
2. Install react-native-bootsplash

### Reproducible sample code

```js
No need for reproduction as npm installation shows vulnerability
```

**Comment by zoontek** [comment]
Version is pinned in the package.json, `npm audit` returns incorrect data (as usual): https://github.com/zoontek/react-native-bootsplash/blob/master/package.json#L66
