### ISSUE TITLE
[Android] Wrong center in default usage

### ISSUE THREAD

**Issue by exzos28** [zoontek/react-native-bootsplash#389]
### Bug summary

Discrepancies in logo centering in native splash and in JS component on android
I expect that the center in JS and in the native splash will be the same.

https://user-images.githubusercontent.com/39951413/191507775-9e73633b-032e-43a8-aef7-a8cd0e98d1ea.mov

### Library version

4.3.2

### Environment info

```shell
npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
```

### Steps to reproduce

Code:

### Reproducible sample code

```js
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
        
    </style>

    <!-- BootTheme should inherit from Theme.SplashScreen -->
    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>

</resources>


function Launcher({children}: ViewProps) {
  useEffect(() => {
    RNBootSplash.hide();
  }, []);
  return (
    <View style={{flex: 1}}>
      {children}
      <View style={StyleSheet.absoluteFill}>
        <SplashScreen />
      </View>
    </View>
  );
}
```

**Comment by zoontek** [comment]
You need to make the status and navigation bar transparents for that: https://github.com/zoontek/react-native-bars
The example on this repository does that.

**Comment by exzos28** [comment]
> You need to make the status and navigation bar transparents for that: https://github.com/zoontek/react-native-bars
> The example on this repository does that.

But if I don't want to make them transparent? What can I do?

**Comment by zoontek** [comment]
@exzos28 Set them opaque in the BootTheme then.

**Comment by exzos28** [comment]
> @exzos28 Set them opaque in the BootTheme then.

I tried to do this, but I didn't succeed.
Could you suggest how to do it?

**Comment by zoontek** [comment]
@exzos28 Please ask for help on [StackOverflow](https://stackoverflow.com/), this is not an issue with the library.

**Comment by exzos28** [comment]
@zoontek But I think mis-centering is happening in this library. And I can't override it.

**Comment by exzos28** [comment]
Once I used the 3rd version of this library and did not come across this.

**Comment by zoontek** [comment]
@exzos28 It's not. It's just the behavior of Android new SplashScreen API (on Android 12+) / AndroidX core compat library:
- https://developer.android.com/develop/ui/views/launch/splash-screen
- https://developer.android.com/reference/kotlin/androidx/core/splashscreen/SplashScreen
- https://github.com/androidx/androidx/blob/androidx-main/core/core-splashscreen/src/main/java/androidx/core/splashscreen/SplashScreen.kt#L474

**Comment by exzos28** [comment]
@zoontek Then it turns out that on a 12+ android, I won’t be able to add a color for status and navigation bars?

**Comment by zoontek** [comment]
@exzos28 Not on splash screen, no.

> Enter animation: This consists of the system view to the splash screen. This is controlled by the system and is not customizable.

**Comment by exzos28** [comment]
@zoontek I'm not against react-native-bars, but there you can't set up these panels at least translucent.

**Comment by exzos28** [comment]
@zoontek And I would love to have that opportunity. ☺️
