### ISSUE TITLE
Crash on android 10

### ISSUE THREAD

**Issue by mnill** [zoontek/react-native-bootsplash#39]
### 💻 My environment

- react-native-bootsplash version: 1.0.3
- react-native version: 0.61.5
- Platform: android
- OS version: 10
- Device: emulator 
- Simulator: yes
- Android buildToolsVersion:  28

### 🕵️‍♂️ Reproducing the issue

Crashed on startup

java.lang.RuntimeException: Unable to start activity ComponentInfo{co.inskate/com.zoontek.rnbootsplash.RNBootSplashActivity}: android.content.res.Resources$NotFoundException: Drawable co.inskate:drawable/bootsplash with resource ID #0x7f07005e

Due to 

Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #6: <item> tag requires a 'drawable' attribute or child tag defining a drawable

### 🤞Solution
In you readme we created
```<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
  <!-- the background color. it can be a system color or a custom one defined in colors.xml -->
  <item android:drawable="@android:color/white" />

  <item>
    <!-- the app logo, centered horizontally and vertically -->
    <bitmap
      android:src="@mipmap/ic_launcher"
      android:gravity="center" />
  </item>
</layer-list>
```

but must be something like
```
  <item  android:drawable="@android:color/white">
    <!-- the app logo, centered horizontally and vertically -->
    <bitmap
      android:src="@mipmap/ic_launcher"
      android:gravity="center" />
  </item>
```

Thank you for your work.

**Comment by zoontek** [comment]
@mnill I just give a shot to the example on an Android 10 emulator and everything went well, I guess it's something else.

Could you publish the content of your `drawable/bootsplash.xml` file? Thanks!

**Comment by mnill** [comment]
My bootsplash exactly as is in readme.

I failed to fast create minimal reproducible example, looks like it is because of combination of plugins in my project, also i have multidex enabled.

i'll try research it in future.

thank you.

**Comment by mnill** [comment]
Failed to reproduce from a scratch, sorry for your time.

**Comment by mnill** [comment]
It was because I've used [react-native-make](https://github.com/bamlab/react-native-make) to set-icon.

It created mipmap with ic_launcher.png icon and mipmap-v26 with ic_launcher.XML for android 9+.

So on android 9+ bitmap fail to find @mipmap/ic_launcher and crashed

My first solution was wrong.

**Comment by FadiAboMsalam** [comment]
@mnill  i am facing same issue how did you manage to fix that 🤔  ?

**Comment by ferdynator** [comment]
Had the same issue because the `bitmap` in `bootsplash.xml` was referencing the `ic_launcher` resource, which is an XML file and not valid for `<bitmap src>`. This solved the issue:

    <layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
        <item android:drawable="@android:color/white" />
        
        <item android:drawable="@mipmap/ic_launcher" android:gravity="center" />
    </layer-list> 

See [this Stackoverflow answer](https://stackoverflow.com/a/24451261/1847340) for an explanation.
