### ISSUE TITLE
bootsplash overrides DevMenu

### ISSUE THREAD

**Issue by onlyling** [zoontek/react-native-bootsplash#400]
### Bug summary

if development server not work, it will show red screen(some error messages). but now bootsplash is still showing, and it also covers DevMenu, I can't switch development server URL by setting.

1. if development server not work, it auto hide.
2. adjust bootsplash's z-axis level, do not cover the DevMenu.(recommend)

当开发服务器没有启动的时候，将显示红屏（一些错误提示）。但是现在 bootsplash 还在显示，同时也覆盖了 DevMenu，我不能 通过设置修改开发服务器 URL。

1. 如果开发服务器找不到，自动隐藏（关闭）
2. 调整 bootsplash 的 z 轴层级，不要盖住 DevMenu。（推荐）

### Library version

4.3.2

### Environment info

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 84.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/8s/8gnn9h1n3zdgw3vgbcl1v8g40000gn/T/yarn--1667887815168-0.2762749719664377/node
    Yarn: 1.22.19 - /var/folders/8s/8gnn9h1n3zdgw3vgbcl1v8g40000gn/T/yarn--1667887815168-0.2762749719664377/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. npx react-native init MyApp --template @fruits-chain/react-native-lidong-template
2. yarn android
3. close metro server
4. open app, wait a minute, no red screen, can't open DevMenu

### Reproducible sample code

```js
npx react-native init MyApp --template @fruits-chain/react-native-lidong-template
```

**Comment by zoontek** [comment]
Duplicate of https://github.com/zoontek/react-native-bootsplash/issues/296

As the splashscreen is a native Activity, it's above your MainActivity. Fortunately, errors appear in metro now, so you're aware if it fails to load.

Also, this happen only on Android since RN iOS fire a callback when this happen, and we can remove the splash screen at this time.
