### ISSUE TITLE
Show splash again

### ISSUE THREAD

**Issue by Hostname47** [zoontek/react-native-bootsplash#401]
### Why it is needed?

In my app, I have a languages screen where the user can change the app language. When the language changed I reload the app and I want the splash to be appeared again when the app reload, but what I get is just a white splash appeared.
Is there any method like `RNBootSplash.hide({fade: true})` to show the splash when app is reloading !?
Thanks.

**Comment by zoontek** [comment]
Hi, this is not possible since Android 12 (and with AndroidX core splash screen module).
You can use a modal instead: https://reactnative.dev/docs/modal

**Comment by zoontek** [comment]
Duplicate of https://github.com/zoontek/react-native-bootsplash/issues/391 and https://github.com/zoontek/react-native-bootsplash/issues/354
