### ISSUE TITLE
[Android 13] Logo image is not shown on Android 13 when reloading the app.

### ISSUE THREAD

**Issue by kupilikula** [zoontek/react-native-bootsplash#403]
### Bug summary

I followed the readme for bootsplash on Android and am running the app on a Google Pixel 4a with Android 13. I see the logo image on the first install when the app is launched from the terminal. But on subsequent openings of the app, I do not see the logo, but only the correct background color. This is the OPPOSITE behavior of the known issue on Android 12. I tried changing the logo image resolution since maybe the loading of the image is very slow but it didn't help. On iOS the splash screen is working perfectly, maybe because the logo image is loaded from the bundled assets? Or maybe my logo image files are not correct resolutions? I reproduced the issue on a brand new react native template app and on multiple physical android phones.

### Library version

4.3.3

### Environment info

```shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 79.27 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. react-native init test
2. npm i react-native-bootsplash
3. npx react-native generate-bootsplash AppSplash.png --background-color=ff6961 --logo-width=192 --assets-path=assets
4. Edit styles.xml to be the following:
```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>

    <!-- BootTheme should inherit from Theme.SplashScreen -->
    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>

</resources>
```
5. Edit MainActivity.java to add the following (along with imports):

```
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    RNBootSplash.init(this); // <- initialize the splash screen
    super.onCreate(savedInstanceState); // or super.onCreate(null) with react-native-screens
  }
```
6. Edit AndroidManifest.xml to change the theme:

```
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/BootTheme">
```

8. Add useEffect in App.js to hide the splash screen:

```
  useEffect( () => {
    RNBootSplash.hide({fade: true});
  }, [])

```

9. Run the app on an Android device (I tried two different physical Pixel phones running Android 13.). The logo icon is visible on the first load of the app (from terminal) but missing on subsequent opening of the app (after closing the app).

### Reproducible sample code

```js
See the above Steps to reproduce. I have reproduced the same issue on a brand new react native template app.
```

**Comment by kupilikula** [comment]
I want to add that even on the first load of the app from the terminal, the logo is sometimes(~20% of the time) not visible. What resolution should the initial logo image file be when using the command `npx react-native generate-bootsplash AppSplash.png --background-color=ff6961 --logo-width=192 --assets-path=assets` ?

**Comment by zoontek** [comment]
@kupilikula On Android, the logo appears when opening the app using the launcher (not Android Studio, the terminal or else). You have to start the app, kill it and relaunch it manually.

This is quite painful, but it's a known issue on Android > 12: https://github.com/zoontek/react-native-bootsplash#android-1

**Comment by kupilikula** [comment]
Thanks for replying! It's good to know that the issue is with Android > 12 not Android == 12. My issue is that the logo is not appearing when opening the app using the launcher from the list of apps in Settings/Search bar. My android app icon is not showing up on the homescreen for some reason, so I cannot launch it from the app icon on the homescreen. However, I can search for the app in the search bar on the home screen and the app shows up in the search results. It's also listed in the list of apps in Settings where I can launch it from. In either case, the logo doesn't show up.

**Comment by zoontek** [comment]
@kupilikula I edited the README. What is your phone? A Pixel?

**Comment by kupilikula** [comment]
I tried Pixel 4a, Pixel 6, as well as emulator. Initially, I was able to see the logo on initial launch from terminal but now even that is not working.

**Comment by zoontek** [comment]
@kupilikula Don't count on the terminal, it's an Android issue. If it works when starting the app from launcher, it's all good.

**Comment by kupilikula** [comment]
By launcher, do you mean the grid of all apps that appears when you drag upwards? It's not working when I launch it from there either.

**Comment by zoontek** [comment]
I tested it (Pixel 4a, Android 13), no issue.
Maybe are you using a custom launcher app?

https://user-images.githubusercontent.com/1902323/202714375-55ab99ce-9f0f-45bc-b809-21eff9604719.mp4

**Comment by raymondjacobson** [comment]
I also see this, not in production or when opening the app from the launcher, but it makes dev hard!

**Comment by kupilikula** [comment]
FYI, my android app got released and the logo doesn’t appear in production either. iOS is working just fine.

**Comment by kidculli** [comment]
To add on, I recently updated my phone to android 12. My production app no longer renders the splash screen logo. It was working fine before.

**Comment by zoontek** [comment]
@kidculli Yes, it's the API itself (on Android 12): https://github.com/zoontek/react-native-bootsplash/issues/408#issuecomment-1425488937
