### ISSUE TITLE
Full screen image instead of Logo

### ISSUE THREAD

**Issue by redjohnfrv** [zoontek/react-native-bootsplash#407]
### Why it is needed?

This module has simple setup and settings. But I didn't find any ways to change Logo to Full screen image by using this module.
Is there any way to do it? It would be great! 

### Possible implementation

I'm not professional in RN, but I saw some settings like 
`android:theme="@android:style/Theme.Light.NoTitleBar.Fullscreen"`
or some tags into main/res like 
`<item name="android:windowSplashScreenBrandingImage">@drawable/ic_splashscreen_branding_centered</item>`
`<item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>`

maybe there is exist something similar?

**Comment by zoontek** [comment]
Hey 👋

https://github.com/zoontek/react-native-bootsplash/issues?q=is%3Aissue+Full+screen
https://github.com/zoontek/react-native-bootsplash/issues/283

**Comment by redjohnfrv** [comment]
Thank you. I didn't find this issues list, sorry. 
But, I think, u can add this link or just note so it's impossible )
Anyway thank you for your great work!
