### ISSUE TITLE
Can not upgrade to 1.1.1/1.1.3

### ISSUE THREAD

**Issue by voydz** [zoontek/react-native-bootsplash#41]
When trying to upgrade via yarn it spits out the following error:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-bootsplash/-/react-native-bootsplash-1.1.3.tgz: Request failed \"404 Not Found\"".
```

### 💻 My environment

- react-native-bootsplash version: 1.1.0
- react-native version: 0.61.5
- Platform: both
- OS version: 10.15.1
- Device: irrelevant
- Simulator: irrelevant
- Android Studio version: 3.5.2
- Android buildToolsVersion: 26.x
- Xcode version: 11.3
- yarn version: 1.19.1

### 🕵️‍♂️ Reproducing the issue

Explain what you did, what you expected to happen, and what actually happens.
Provide some code or screenshots if needed.

* Running `yarn upgrade` does not complete successfully.

### 🤞Solution

Do you know what needs to be done to address this issue?
Ideally, provide a pull request with a fix.

* Stuck with 1.1.0 at this time.

**Comment by zoontek** [comment]
@voydz I don't know why, but npm shits the bed right now (that's why I published 1.1.1, 1.1.2, 1.1.3). I prefer context their support instead of continuing publishing

**Comment by voydz** [comment]
@zoontek Thanks for the info :)

**Comment by zoontek** [comment]
I had to publish version `1.2.0` because npm could not erase empty versions. It's available!
