### ISSUE TITLE
Bootsplash splash screen is half size on galaxy s10

### ISSUE THREAD

**Issue by raymondjacobson** [zoontek/react-native-bootsplash#410]
### Bug summary

Trying to understand how hdpi and this library work together.
My splash screen was generated with width of 150px and I have an Animated.Image component that is also width of 150px. On iOS & pixel phones, the BootSplash screen and the Animated.Image are identical size, however on a Galaxy S10, the image is twice the size of the bootsplash (e.g. the width of the bootsplash image is equivalent to React Native 75px).

### Library version

4.3.3

### Environment info

```shell
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 101.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.5/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.5 => 0.66.5
    react-native-macos: Not Found
```

### Steps to reproduce

Run on Galaxy S10

![Screenshot_20221201-152421_Audius Bounce](https://user-images.githubusercontent.com/2731362/205182617-9421d30d-ef7f-4d01-9a8f-a40f3150b8f0.jpg)
![Screenshot_20221201-152453_Audius Bounce](https://user-images.githubusercontent.com/2731362/205182622-e2a70c0d-f6dd-452b-a9da-d1384d4b7293.jpg)

### Reproducible sample code

```js
1.

npx react-native generate-bootsplash src/assets/images/bootsplash_logo.png --background-color=7E1BCC --logo-width=150 --assets-path=src/assets/images
```
2.
```
logo: {
    width: 150
}

<Animated.Image
    source={bootSplashLogo}
    fadeDuration={0}
    resizeMode="contain"
    onLoadEnd={() => setBootSplashLogoIsLoaded(true)}
    style={[
      styles.logo,
      { transform: [{ translateY: translateY.current }] },
    ]}
  />
```
```

**Comment by zoontek** [comment]
@raymondjacobson First, re-read the README to be sure you didn't miss a thing. (ex: uses `<item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>`, not `<item name="android:windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>` if you want support of Android < 12 (needed to use AndroidX core package)

Secondly, by default, the android image include some padding (it's computed for you if you use the CLI tool). But if you want to output files to use with Image, use the --assets-path param. It will output a logo without padding, and the transition will be perfect.

Check the example app on the repository, you will get it.

**Comment by zoontek** [comment]
@raymondjacobson I saw that [this PR](https://github.com/AudiusProject/audius-client/pull/2339) has been merged. Does this mean you fixed your issue?

**Comment by SchlagerKhan** [comment]
@raymondjacobson Did you manage to solve this? I'm having the same issue.

**Comment by dowon938** [comment]
I'm having the same issue. in 4.7.1

**Comment by RamProg** [comment]
We are having the same issue with 4.7.3. Looks good on an emulated Pixel 5, then too small on a physical Samsung Galaxy S20+

**Comment by raymondjacobson** [comment]
> @raymondjacobson Did you manage to solve this? I'm having the same issue.

Nope- just removed the animation
