### ISSUE TITLE
After adding BootSplash and RN Bars, items under the Android keyboard move up. Removing these 2 packages fixes the issue.

### ISSUE THREAD

**Issue by MyPalVikram** [zoontek/react-native-bootsplash#415]
### Bug summary

EDIT: I've now confirmed this is happening because of the RNBars package and not Bootsplash. I can close this and repost it there.

A bizarre bug occurs when installing the bootsplash package and RN bars. On my login screen, I have components that are spaced apart. On Android, this will move up the bottom component when the keyboard is presented. iOS is fine. I've tracked the issue to one of these two packages by starting a fresh React Native project and setting up just one screen with these packages.

I've followed the sets on both platforms to set this up. But at this time I've had to remove it to prevent Android from malfunctioning.

Here is a video on the behavior.

https://imgur.com/a/P0xmuKN

### Library version

4.4.0

### Environment info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.45 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/vikrampal/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
Video provided. A screen in a stack with two items spaced apart.
```

**Comment by zoontek** [comment]
@MyPalVikram I think I know what it is. Can you try without react-native-bars (only bootsplash?)

**Comment by MyPalVikram** [comment]
> @MyPalVikram I think I know what it is. Can you try without react-native-bars (only bootsplash?)

Yeah it was the bars. Removed the bars and the bug went away. Boot splash alone working great.

**Comment by zoontek** [comment]
This is related to https://github.com/zoontek/react-native-bars/pull/16
It's actually a tricky issue on Android (it appears when using `WindowCompat.setDecorFitsSystemWindows(window, false);`, which is required for fully transparent system bars)

**Comment by zoontek** [comment]
@MyPalVikram Can you open this issue on react native bars repository instead? Thanks!

**Comment by MyPalVikram** [comment]
> @MyPalVikram Can you open this issue on react native bars repository instead? Thanks!

Yes, of course. Will do!
