### ISSUE TITLE
Can get locked out of device on Android

### ISSUE THREAD

**Issue by Rc85** [zoontek/react-native-bootsplash#418]
### Bug summary

If the device's screen turns off while app is in foreground and the boot splash screen is showing, the device will not unlock until the boot splash screen is hidden.

### Library version

4.3.2

### Environment info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 12.71 GB / 31.93 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210102.202219.0 - C:\Users\roger\watchman\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8815526
    Visual Studio: 15.9.28307.1401 (Visual Studio Community 2017)
  Languages:
    Java: 17.0.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.2 => 0.70.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Keep device screen off
2. Install your app
3. Turn device screen on after installation and unlock your device
4. Your device will hang before screen turns off again

If app is already installed, sometimes turning off the screen for a long time and then turning it back on and unlocking the device wll reproduce the problem. This is because the app reopens and the boot splash is showing.

I've only tested this on Android 8, 10, and 12.

### Reproducible sample code

```js
This needs to be tested on real device.
```

**Comment by zoontek** [comment]
@Rc85 Could you provide more infos (especially about the conditions). Does this happen on an Android < 12 phone or on an >= 12 phone?

**Comment by zoontek** [comment]
It should be fixed with https://github.com/zoontek/react-native-bootsplash/pull/475

**Comment by zoontek** [comment]
Version 5.0.0 is available: https://github.com/zoontek/react-native-bootsplash/releases/tag/5.0.0
