### ISSUE TITLE
Implement privacy screen

### ISSUE THREAD

**Issue by marcocaldera** [zoontek/react-native-bootsplash#422]
### Why it is needed?

I'm looking to implement a privacy cover screen.

iOS:
When the app is in background it should shows the splash screen and the splash screen should disappear if the app is brought back to the front.

Android:
Should use the FLAG_SECURE to blur the activity when the app is in background. The flag should be removed when the app is brought back to the front.

I already reached an almost final solution patching this package for iOS and I'm still looking to find the optimal way for Android. I'm curious if there is an interest to add this feature to the package.

I'm happy to discuss and contribute to it.

**Comment by zoontek** [comment]
Hi! I don't think it's the purpose of a splash screen library.
Maybe you can play around with `<Modal />` instead?

**Comment by marcocaldera** [comment]
I don't feel the Modal approach can really match a good native experience. I'll maybe create a new package. Thank you
