### ISSUE TITLE
How do i add a blob / extra elements apart from the Icon with version 4.5.0 

### ISSUE THREAD

**Issue by NiharR27** [zoontek/react-native-bootsplash#429]
### Bug summary

Hi There, i recently completed the migration using https://github.com/zoontek/react-native-bootsplash/blob/master/MIGRATION.md guide.

I saw that we had to remove the `bootsplash.xml` file / regenerate the assets, etc , and make the `styles.xml` to be something like

```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->

    <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>

  <!-- BootTheme should inherit from Theme.SplashScreen -->
  <style name="BootTheme" parent="Theme.SplashScreen">
   <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
   <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
   <item name="postSplashScreenTheme">@style/AppTheme</item>
  </style>

</resources>
```

my concern is that inside `bootsplash.xml` file, I had extra stuff like (removing the ones that we took to styles.xml when migrating) which I want to add to the background:

```
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
    <item>
        <bitmap android:src="@drawable/blob1" android:gravity="top|right" />
    </item>

    <item>
        <bitmap android:src="@drawable/blob2" android:gravity="bottom|left" /> 
    </item>
</layer-list>
```
which would put the blobs on left and right corner. Is there any way that I can put these blobs in with the newer version?

I tried replacing things inside `<item name="windowSplashScreenBackground">@color/bootsplash_background</item>` with `<item name="windowSplashScreenBackground">@drawable/bootsplash</item>`, but that would create a crash on [some android](https://stackoverflow.com/questions/72730209/android-content-res-resourcesnotfoundexception-drawable-compat-splash-screen-n)

### Library version

4.5.0

### Environment info

```shell
"react-native": "0.70.6",
"react-native-bootsplash": "^4.5.0",
```

### Steps to reproduce

1. Switch to v4 from v3 with multiple items in bootsplash.xml
2. When deleting the bootsplash.xml, we will have to remove the extra information that we wrote inside it

### Reproducible sample code

```js
Just use png as an example for blob images in order to replicate this
```

**Comment by zoontek** [comment]
You can't (on Android), since splash screen are now standardized on this platform: https://developer.android.com/develop/ui/views/launch/splash-screen#elements
