### ISSUE TITLE
Why can't my launch icon slide down

### ISSUE THREAD

**Issue by afeichuanqi** [zoontek/react-native-bootsplash#43]
### 💻 My environment

- react-native-bootsplash version:
- react-native version:
- Platform: ios / android / both
- OS version: ?
- Device: brand + model
- Simulator: yes / no
- Android Studio version: ?
- Android buildToolsVersion: ?
- Xcode version: ?

### 🕵️‍♂️ Reproducing the issue

Explain what you did, what you expected to happen, and what actually happens.
Provide some code or screenshots if needed.

### 🤞Solution

Do you know what needs to be done to address this issue?
Ideally, provide a pull request with a fix.
Is this startup map to be edited by yourself or fixed? Only use the app icon as the startup map

**Comment by zoontek** [comment]
Sorry, but you have to fill the template.
