### ISSUE TITLE
Needs an ability to set the any IOS splash screen size.

### ISSUE THREAD

**Issue by UraFIZ** [zoontek/react-native-bootsplash#430]
### Why it is needed?

First of all, thank you for such a good lib!
I use this lib on one of the stages of the automation of building an app.
I know about the Android dimensions limitation and am good with it. 
Having a flag (--platform=IOS) would be pretty handy. Based on this flag, setting any width for IOS may be possible.

Is it possible to have this flag?

If it is not possible soon, please recommend a viable solution for my case.

### Possible implementation

npx react-native "generate-bootsplash" assets/splash.png --background-color=FFFFFF --platform=IOS  --logo-width=600 --flavor=main

**Comment by zoontek** [comment]
@UraFIZ Hello! What about updating the check [here](https://github.com/zoontek/react-native-bootsplash/blob/c25aa4ac8a2bd288e7e9f2f0bd3c244e9c23929b/src/generate.ts#L165) to remove the `process.exit` calls and update the error message a bit?

```ts
if (logoWidth > 288) {
  log.warn("⚠️   Logo width exceed 288dp. It will be cropped on Android.");
} else if (logoHeight > 288) {
  log.warn("⚠️   Logo height exceed 288dp. It will be cropped on Android.");
} else if (logoWidth > 192) {
  log.warn("⚠️   Logo width exceed 192dp. It might be cropped on Android.");
} else if (logoHeight > 192) {
  log.warn("⚠️   Logo height exceed 192dp. It might be cropped on Android.");
}
```

Would that be OK?

**Comment by UraFIZ** [comment]
@zoontek, thank you! It would be absolutely OK.  When can we expect to get this update, please?

**Comment by zoontek** [comment]
@UraFIZ It's available https://github.com/zoontek/react-native-bootsplash/releases/tag/4.5.1

**Comment by UraFIZ** [comment]
@zoontek, thank you for this release. I have already tried it. 
I run this line `yarn react-native "generate-bootsplash" ./splash-ios.png --background-color=2E3586   --logo-width=600 --flavor=main`
The error occurred in the terminal `[Error: Image to composite must have same dimensions or smaller].` 

Do you know what the reason for this error is?

**Comment by zoontek** [comment]
@UraFIZ Yeah, my bad. I will make a new release that skip android generation in such cases.

**Comment by zoontek** [comment]
Done: https://github.com/zoontek/react-native-bootsplash/releases/tag/4.5.2
