### ISSUE TITLE
Android 12 splash does not hide.

### ISSUE THREAD

**Issue by MUZAFFAR-PURELOGICS** [zoontek/react-native-bootsplash#432]
### Bug summary

Android 12 splash does not hide.
App stack on splash screen.

### Library version

4.5.2

### Environment info

```shell
0.71
```

### Steps to reproduce

Kill app and open splash stuck

### Reproducible sample code

```js
Kill app and open splash stuck
```

**Comment by MUZAFFAR-PURELOGICS** [comment]
Why you close my issue. It is still occurs in android 12.

**Comment by zoontek** [comment]
@MUZAFFAR-PURELOGICS I couldn't reproduce it using your reproducible sample code

**Comment by sallar** [comment]
I'm having the same issue. I downgraded to [4.4.1](https://github.com/zoontek/react-native-bootsplash/releases/tag/4.4.1) and the issue went away. I think the problem is caused by https://github.com/zoontek/react-native-bootsplash/commit/2abca66895e3323de103b9be89a15610ae89046c

**Comment by zoontek** [comment]
@sallar I just gave a new try. Android 12, with `fade: true` and `fade: false`. No issue.
Maybe it's just because your forgot tu run `adb reverse tcp:8081 tcp:8081`? (the JS bundle cannot be loaded, explaining why `Bootsplash.hide()` is never called)

More infos here: https://reactnative.dev/docs/running-on-device

**Comment by emil-malmgaard-rasmussen** [comment]
Im running the `adb reverse tcp:8081 tcp:8081` on an android 11, but bootsplash isn't hiding, only when I run it locally on my test phone (Oneplus Nord N100)

**Comment by HuuNguyen312** [comment]
I'm having the same issue. Bootsplash icon cannot display on Android 12 (Samsung s10 plus)
