### ISSUE TITLE
Can I make bootSplash using lottie json file?

### ISSUE THREAD

**Issue by jhui134** [zoontek/react-native-bootsplash#433]
### Why it is needed?

I want to make it like Netflix Splash Screen.

Please let me know if you can.

**Comment by zoontek** [comment]
Yes: https://github.com/zoontek/react-native-bootsplash-lottie-example

**Comment by humarkx** [comment]
@zoontek do you think it is possible to have an up-to-date example with the latest RN version? :pray:

**Comment by zoontek** [comment]
@humarkx Yeah, I can do that!

**Comment by zoontek** [comment]
@humarkx Done! I used the Netflix logo, which I find to be cooler:

https://user-images.githubusercontent.com/1902323/225163621-4ec7c9fe-eb40-41fe-9f18-dbb32aa6b088.MP4

**Comment by jhui134** [comment]
@zoontek @humarkx 

react-native : 0.71.4
react-native-reanimated : 2.14.1

My example utilizes react-native-reanimated's Animated, not react-native Animated. There aren't many lines of code, but please note that the key point is that reanimated was utilized.


`import Animated, {
  interpolateColor,
  runOnJS,
  useAnimatedProps,
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';

const App = () => {
 const [animationIsVisible, setAnimationIsVisible] = React.useState(true);
  const ref = React.useRef<LottieView>(null);
  const progress = useSharedValue(0);
  const animatedProps = useAnimatedProps(() => {
    return {
      progress: progress.value,
    };
  });

useEffect(() => {  
    setTimeout(() => {
      RNBootSplash.hide();
    }, 500);
  }, []);

  useEffect(() => {
    progress.value = withTiming(1, { duration: 5500 }, (finished) => {
      if (finished) {
        runOnJS(setAnimationIsVisible)(false);
      }
    });
  }, [progress]);

return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <StatusBar barStyle="dark-content" backgroundColor="#fff" />
         <RootScreen />
        {animationIsVisible && (
          <Animated.View
            style={[
              {
                alignItems: 'center',
                justifyContent: 'center',
                position: 'absolute',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
              },
              rStyle,
            ]}
          >
            <AnimatedLottieView
              ref={ref}
              source={require('@/Assets/Lottie/splash.json')}
              loop={false}
              animatedProps={animatedProps}
              resizeMode={'center'}
              imageAssetsFolder={'images'}
            />
          </Animated.View>
        )}
      </PersistGate>
    </Provider>
  );
}

`

**Comment by SulaimanAlbulaihy** [comment]
I believe the splashscreen is an image at start
when the app loads the run the lottie ?
Isn't this bad UX ?
