### ISSUE TITLE
an option to change naming for files generated using CLI

### ISSUE THREAD

**Issue by milindgoel15** [zoontek/react-native-bootsplash#434]
### Why it is needed?

So basically, the current CLI generates a predefined naming scheme as defined in the example folder. But would it be possible to integrate it as an optional feature that allows changing the scheme? Instead of relying on any other package, having it built-in in this library would be awesome. 

### Possible implementation

I'm not really sure. Not a coding expert.

**Comment by zoontek** [comment]
You can use a simple script to rename the file once they are generated.

https://linux.die.net/man/1/mv

**Comment by milindgoel15** [comment]
That's what the feature request is all about. Why rely on external scripts or libraries when it can be integrated into this package itself?

**Comment by zoontek** [comment]
@milindgoel15 No need for a library, just a command line will do the trick.
There is little to no interest in such a feature.
