### ISSUE TITLE
java.lang.UnsupportedOperationException: This method is not supported for ReactViewGroup instances

### ISSUE THREAD

**Issue by Juan2662** [zoontek/react-native-bootsplash#439]
### Bug summary

Hi, I'm trying build a splash screen for mi react native app
In this moment my splash screen does not disappear even though I'm using RNBootSplash.hide()
Works fine in iOS

My app stays here infinitely
![image](https://user-images.githubusercontent.com/58581443/229535565-9db3c60a-d150-4d45-b99c-4a71f5b56a2a.png)

My code: 
android/app/src/main/res/values/styles.xml
![image](https://user-images.githubusercontent.com/58581443/229538700-d4f55f57-7148-4080-96ce-05f5481de61c.png)

android/app/src/main/res/drawable/bootsplash.xml
![image](https://user-images.githubusercontent.com/58581443/229538863-3b904708-e4f2-4e7e-b55a-6ae6d7043b6a.png)

android/app/src/main/java/com/awesomeproject/MainActivity.java
![image](https://user-images.githubusercontent.com/58581443/229540886-65666db2-dd46-4e9e-861b-fa588aa791cb.png)

android/app/src/main/AndroidManifest.xml
![image](https://user-images.githubusercontent.com/58581443/229540582-85c0d90a-3f73-4331-8f5a-7e49fd7b59a5.png)

android/app/build.gradle
![image](https://user-images.githubusercontent.com/58581443/229539841-5ee8446e-db26-4403-b246-13be75f6bdce.png)

App.tsx
![image](https://user-images.githubusercontent.com/58581443/229540098-ab5ed0b3-6abf-4175-b5bb-5a07129e320e.png)

### Library version

4.5.3

### Environment info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 84.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.0/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Create a new react native app
1. npx react-native@0.71.4 init AwesomeProject --version 0.71.4
2. Follow the installation steps for react-native-bootsplash
3. Make sure that you have a drawable image and use it as "android:background" in your styles.xml 

### Reproducible sample code

```js
.
```

**Comment by zoontek** [comment]
Not an issue with `react-native-bootsplash`, you cannot use `android:background` in React Native. More infos: https://github.com/facebook/react-native/issues/9072

**Comment by Juan2662** [comment]
How can I do it without use `android:background`

**Comment by zoontek** [comment]
@Juan2662 By reading the README. `android:background` is never mentioned.

**Comment by Juan2662** [comment]
We can use a xml in the background ?

**Comment by zoontek** [comment]
@Juan2662 No https://developer.android.com/develop/ui/views/launch/splash-screen
