### ISSUE TITLE
Auto Linking not working on version 4.5.3

### ISSUE THREAD

**Issue by LucasDants** [zoontek/react-native-bootsplash#442]
### Bug summary

I update from v4 and the auto linking stop to work. At iOS when I ran pod install the RNBootSplash pod is removed.

I could run it after doing a manually linking

### Library version

4.5.3

### Environment info

```shell
System:
    OS: macOS 13.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 74.69 MB / 16.00 GB
    Shell: 5.9
  Binaries:
    Node: 18.14.2 
    Yarn: 1.22.19 
    npm: 9.5.0
    Watchman: 2023.01.23.00
  Managers:
    CocoaPods: 1.12.0
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b
  Languages:
    Java: 11.0.15
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

IOS
1. Install the pods
2. Build iOS
Android
1. Build the android

### Reproducible sample code

```js
Just follow the README and try to build
```

**Comment by zoontek** [comment]
I couldn't reproduce it.

**Comment by 738** [comment]
Me too.

When I run `pod install`, then `RNBootsplash` was removed.

My env is here.

```
"react-native-bootsplash": "4.7.1",
"react-native": "0.71.6",
```

**Comment by DenisQC** [comment]
As funny as it can be, I had auto-linking running on my local dev env, but on CI the auto-link failed -- and I could see on the logs that it was present in `package.json` and `node_modules`. I'm not sure if this is a React script problem or this module, but I guess auto-link could be misleading.

**Comment by swansontec** [comment]
I did some digging, and the `react-native.config.js` file is crashing with the following error:

```
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
```

My interpretation is that the CLI depends on a C++ image library that needs to be compiled, and if something goes wrong with that (native code is tricky), the whole package will become invisible to React Native.

I am fixing this temporarily with the following patch file:

```diff
diff --git a/node_modules/react-native-bootsplash/react-native.config.js b/node_modules/react-native-bootsplash/react-native.config.js
index 2f63b22..e465992 100644
--- a/node_modules/react-native-bootsplash/react-native.config.js
+++ b/node_modules/react-native-bootsplash/react-native.config.js
@@ -1,5 +1,4 @@
 const path = require("path");
-const { generate } = require("./dist/commonjs/generate");

 module.exports = {
   commands: [
@@ -45,6 +44,7 @@ module.exports = {
         { project: { android, ios } },
         { backgroundColor, logoWidth, assetsPath, flavor, platforms },
       ) => {
+        const { generate } = require("./dist/commonjs/generate");
         const workingPath =
           process.env.INIT_CWD || process.env.PWD || process.cwd();
```

As you can see, this simply moves the `require` statement so it won't be called until the user invokes `generate-bootsplash`. This gives a few advantages:

- Solves the auto-linking problems, if there is a problem with `sharp`.
- Might make the react-native CLI slightly faster to load.
- If something does go wrong with `sharp`, the user a sees a nice error message when they try to run `generate-bootsplash`, instead of having the command simply not exist.

I can submit this as a pull request if the change would be acceptable.

**Comment by zoontek** [comment]
@swansontec Totally, please submit it as a PR!

**Comment by swansontec** [comment]
> EDIT: I published it as I had to do a release, and chose to include it.

Amazing! Thanks.

**Comment by Yuniac** [comment]
This just happened to me too, running `pod install` removes everything about `RNBootSplash (4.6.0)`. The podfile afterward shows everything about this package is deleted and now I can't build for IOS. How can we solve this?

**Comment by Yuniac** [comment]
> This just happened to me too, running `pod install` removes everything about `RNBootSplash (4.6.0)`. The podfile afterward shows everything about this package is deleted and now I can't build for IOS. How can we solve this?

Okay, I removed it `yarn remove react-native-bootsplash` then did a `yarn add react-native-bootsplash` (which installed version 4.7.4), `cd ios && pod install` then it worked and I was able to build!

**Comment by swansontec** [comment]
@Yuniac The latest version published a few days ago should have the fix.
