### ISSUE TITLE
Support for MacOS and Windows

### ISSUE THREAD

**Issue by HunainHumail** [zoontek/react-native-bootsplash#450]
### Why it is needed?

There is no support for MacOS and Windows in this library, as React native also supports Windows and Macos Officially, this library should support that as well.

**Comment by zoontek** [comment]
@HunainHumail Do you know one desktop application that use splash screens? I don't think this is a common pattern.

**Comment by zoontek** [comment]
Closing this as I cannot find a desktop app that use splash screen.
