### ISSUE TITLE
Add support generate BootSplash.storyboard with custom name

### ISSUE THREAD

**Issue by MasonLe2497** [zoontek/react-native-bootsplash#451]
### Why it is needed?

<img width="236" alt="image" src="https://github.com/zoontek/react-native-bootsplash/assets/43195241/d9ef672c-2db1-471c-a7ef-a8291843b7b2">
I have multiple scheme for multiple application with single source base
Can u add 'storyboard-name' parameter for cli?
Thanks

### Possible implementation

Add 'storyboard-name' parameter for cli

### Code sample

```js
CLI param:
--storyboard-name="BootSplashApp1"
```

**Comment by zoontek** [comment]
You can just use the CLI `&& mv BootSplash.storyboard BootSplash1.storyboard`

**Comment by MasonLe2497** [comment]
yep thanks
