### ISSUE TITLE
Move sharp to optional dependencies

### ISSUE THREAD

**Issue by yuameshi** [zoontek/react-native-bootsplash#454]
### Why it is needed?

for some reasons i need to develop react native directly on my android phone by using termux, but i cannot install this package because sharp was not implemented on this platform.

on android, i just need to use this package but not generating splash images so sharp is not needed

### Possible implementation

move `sharp` to `optionalDependencies` and add failure import detect in cli interface

**Comment by zoontek** [comment]
This would ruin the DX for everyone.

Your situation is a very unique case, uses resolutions (yarn) or overrides (npm) to replace sharp with https://www.npmjs.com/package/no-op instead
