### ISSUE TITLE
No matter how I change xcode, the react chart is always displayed at the beginning and then launchScreen.xib is displayed. Please tell me why?

### ISSUE THREAD

**Issue by afeichuanqi** [zoontek/react-native-bootsplash#46]
No matter how I change xcode, the react chart is always displayed at the beginning and then launchScreen.xib is displayed. Please tell me why?

**Comment by panda0603** [comment]
@afeichuanqi @zoontek I have the same Issue at the moment. I directly edited LaunchScreen.xib in Xcode, deleted the default react native splash screen and put my splash Icons there. I still see the default react native's splash screen, then my custom splash screen after. How did you solve this problem?

**Comment by zoontek** [comment]
Clean the build cache?

**Comment by panda0603** [comment]
@zoontek just deleted the app in simulator and ran build again. Worked. Thanks!
