### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by zhuminjunivan** [zoontek/react-native-bootsplash#461]
### Bug summary

use `npm install react-native-bootsplash` or `npm install react-native-bootsplash@4.7.2` to install,but failed.
use `npm install react-native-bootsplash@4.3.2` is OK.

### Library version

4.7.2

### Environment info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 1.94 GB / 15.75 GB
  Binaries:
    Node: 16.16.0 - D:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.11.0 - D:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 18.0.2.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: ^0.69.7 => 0.69.7
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1、use `npm install react-native-bootsplash` or `npm install react-native-bootsplash@4.7.2` to install,but failed.
![image](https://github.com/zoontek/react-native-bootsplash/assets/16554031/015e9de7-ab40-46cc-85d8-fb1846bfd965)
2、use `npm install react-native-bootsplash@4.3.2` is OK.
![image](https://github.com/zoontek/react-native-bootsplash/assets/16554031/b3c5ca6a-e1e1-443d-a97d-857fc0b0d198)

### Reproducible sample code

```js
no
```

**Comment by zhuminjunivan** [comment]
i build a new RN project with the version 0.71.11 and install react-native-bootsplash,but not ok.can install other frameworks like `react-native-mmkv`,`react-native-vision-camera` etc

**Comment by zoontek** [comment]
Just read the error message?

> sharp: Please see [https://sharp.pixelplumbing.com/install](https://sharp.pixelplumbing.com/install) for required dependencies
