### ISSUE TITLE
[Android 13+] barStyle prop of react-native-bars is not applied properly

### ISSUE THREAD

**Issue by phuongphamx96** [zoontek/react-native-bootsplash#464]
### Bug summary

[Android 13+] barStyle prop of react-native-bars is not applied properly
Hi @zoontek, I got this problem in my project and I tried with the example in your lib. I think the status bar content style follows what I set in `styles.xml` after the splash screen was hidden. If it's `true`, when I kill the app and open it again, the status bar content style still dark-content regardless the value I set in barStyle prop is light-content.
`
        <item name="android:windowLightStatusBar" tools:targetApi="m">true</item>
        <item name="android:windowLightNavigationBar" tools:targetApi="o_mr1">true</item>`
The issue happens on Android 13+ only. I tested on lower versions and it's working as my expectation.
Thanks.
[issue.webm](https://github.com/zoontek/react-native-bootsplash/assets/37136659/fb6136ce-ff20-4129-a04c-5756d0d6103c)

### Library version

4.7.2

### Environment info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.84 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/1434_1687227067221/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/1434_1687227067221/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/1434_1687227067221/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.7 => 0.71.7
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Open https://github.com/zoontek/react-native-bootsplash/blob/master/example/App.tsx
2. Change barStyle prop to light-content, change backgroundColor to a darker color (ex. '#000000')
3. It's okay now
4. Kill the app
5. Open the app again
6. The status bar is still dark-content

### Reproducible sample code

```js
...
const styles = StyleSheet.create({
  container: {
    ...
    backgroundColor: "#000000",
  },
  ...
  ...
  return (
    <View style={styles.container}>
      <SystemBars barStyle="light-content" />
      ...
    </View>
  );
};
```

**Comment by zoontek** [comment]
@phuongphamx96 This is not a `react-native-bootsplash` issue, but a `react-native-bars` one, please open this issue on the correct repository.
