### ISSUE TITLE
[iOS]White flash after upgrade to 0.72 with low power mode

### ISSUE THREAD

**Issue by batuhansahan** [zoontek/react-native-bootsplash#465]
### Bug summary

With low power mode enabled on ios(not new arch) there is a white flash right after bootsplash finished

it did not happened on 0.71.x

here is my appdelegate for now. i will provide a repro. i do not know how to debug that if bootsplash library causing it or is it react native issue. Looking for help thanks.

```
@implementation AppDelegate 
  
 - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions 
 { 
   [OverrideColorScheme enableAlertSupport]; 
   [FIRApp configure]; 
   self.moduleName = @"MyApp"; 
   self.initialProps = @{}; 
  
  
   return [super application:application didFinishLaunchingWithOptions:launchOptions]; 
 }

...


- (UIView *)createRootViewWithBridge:(RCTBridge *)bridge 
                           moduleName:(NSString *)moduleName 
                            initProps:(NSDictionary *)initProps { 
   UIView *rootView = [super createRootViewWithBridge:bridge 
                                           moduleName:moduleName 
                                            initProps:initProps]; 
  
   [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; 
  
   return rootView; 
 } 
  
 @end
```

### Library version

4.7.1

### Environment info

```shell
will add
```

### Steps to reproduce

1.Enable low power mode
2.Open app

### Reproducible sample code

```js
will add
```

**Comment by zoontek** [comment]
@batuhansahan I updated this repository example to 0.72 and cannot reproduce that (I tried in debug and release mode). Maybe an incorrect update? Don't hesitate to use the [react native upgrade helper](https://react-native-community.github.io/upgrade-helper).

https://github.com/zoontek/react-native-bootsplash/assets/1902323/20945c63-ab47-4bb6-b382-7484f015430f

If you want to try on your side, I kept the [`dark-background` branch](https://github.com/zoontek/react-native-bootsplash/tree/dark-background/example) on the repository, you can ran the example.
