### ISSUE TITLE
Upgrade androidx.core:core-splashscreen:1.0.0 to 1.0.1

### ISSUE THREAD

**Issue by billnbell** [zoontek/react-native-bootsplash#469]
### Bug summary

Please upgrade to 1.0.1 androidx.core:core-splashscreen

### Library version

latest

### Environment info

```shell
upgrade
```

### Steps to reproduce

Upgrade

### Reproducible sample code

```js
Upgrade
```

**Comment by zoontek** [comment]
Given the changelog (an error about Android wear), I don't think it's worth it to bother all lib users for that. We can wait for 1.1.0.
