### ISSUE TITLE
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.labelvie.fid.staging/com.labelvie.fid.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by walidhousni30** [zoontek/react-native-bootsplash#472]
### Bug summary

Please Help i have this problem when i wanna run my android app , either it stucks in the bootsplash screen or quit the app during the loading of the splash screen 

below you ll find the logcat log
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.labelvie.fid.staging/com.labelvie.fid.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

here's my androidManifest.xml file 
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" package="com.labelvie.fid">
  <uses-permission android:name="android.permission.INTERNET" />
  <queries>
    <intent>
      <action android:name="android.intent.action.VIEW" />
      <data android:scheme="https" android:host="api.whatsapp.com"/>
    </intent>
    <intent>
      <action android:name="android.intent.action.VIEW" />
      <data android:scheme="https" android:host="com.facebook.orca"/>
    </intent>
  </queries>
  <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/BootTheme">
  <activity android:name=".MainActivity" android:label="@string/app_name" android:screenOrientation="portrait" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>

    </activity>
    <meta-data android:name="com.google.android.geo.API_KEY" android:value="GOOGLE_MAPS_ANDROID_API_KEY" />

    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
    <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
    
    <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_stat_ic_notification" />
    
    <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/notification" tools:replace="android:resource" />
  </application>
</manifest>
`

here's my styles.xml file

`<resources xmlns:android="http://schemas.android.com/apk/res/android">

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>

      
    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>
</resources>
`

my styles.xml v31 

`<resources xmlns:android="http://schemas.android.com/apk/res/android">

    
    <style name="AppTheme" parent="@style/Theme.AppCompat">
        
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>

    
    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="android:windowSplashScreenBrandingImage">@mipmap/bootsplash_logo_bottom</item>
        <item name="android:windowBackground">@drawable/splash_background_lbv</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>

    </style>

</resources>
`

### Library version

4.7.2

### Environment info

```shell
System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 91.39 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 4.0.0-rc.45
    path: ~/Desktop/projects/labelvie/fid-mobile-copy/node_modules/.bin/yarn
  npm:
    version: 9.6.7
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/walidhousni/.rvm/gems/ruby-3.2.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "31"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.2
      - 34.0.0
    System Images:
      - android-33 | Google TV Intel x86 Atom
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/walidhousni/.rvm/rubies/ruby-3.2.2/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 11.3.2
    wanted: 11.3.2
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
npx react-native run-android --tasks clean,installStagingDebug
```

**Comment by zoontek** [comment]
@walidhousni30 https://github.com/zoontek/react-native-bootsplash/issues?q=You+need+to+use+a+Theme.AppCompat+theme

Please takes 2 min of your time instead of making maintainers lose their own.

**Comment by walidhousni30** [comment]
@zoontek i did try every possible solution and it dosent work , once  i add the module manually it tells me that there's turboengine issue and that RNBOOTSplash is not there , and i need help because i ve been trying to solve the issue for like 2 weeks now

**Comment by zoontek** [comment]
@walidhousni30 Sure, as it's not an issue with the library but with your setup, you can reach me by email for premium (paid) support.
