### ISSUE TITLE
[v5] O appears when hidden

### ISSUE THREAD

**Issue by pmogollons** [zoontek/react-native-bootsplash#477]
### Bug summary

Bootsplash gets hidden and then a O appears in the screen without any background.

https://github.com/zoontek/react-native-bootsplash/assets/32210050/d507e8ba-0f9e-4346-9295-f62be505fdff

### Library version

5.0

### Environment info

```shell
System:
  OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
  CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Memory: 1.96 GB / 31.23 GB
  Shell:
    version: 5.2.15
    path: /bin/bash
Binaries:
  Node:
    version: 16.13.0
    path: ~/.nvm/versions/node/v16.13.0/bin/node
  Yarn:
    version: 1.22.5
    path: /usr/bin/yarn
  npm:
    version: 8.1.0
    path: ~/.nvm/versions/node/v16.13.0/bin/npm
  Watchman:
    version: 4.9.0
    path: /home/linuxbrew/.linuxbrew/bin/watchman
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: Not found
```

### Steps to reproduce

Just install the package and follow install instructions

### Reproducible sample code

```js
NA
```

**Comment by zoontek** [comment]
@pmogollons Please provide some files for a reproduction (styles.xml, MainActivity.java) + infos about your phone.

**Comment by zoontek** [comment]
I'm closing this as there's no way to reproduce it (I tried with some exotic phones on Browserstack, without any success). I guess it was a human error during the migration.

**Comment by zoontek** [comment]
Another user reported this issue, it appears to occurs when you forget to remove the `implementation("androidx.core:core-splashscreen:1.0.0")` dependency.
