### ISSUE TITLE
Could not resolve androidx.core:core-splashscreen:1.0.0

### ISSUE THREAD

**Issue by Melekhin** [zoontek/react-native-bootsplash#478]
### Bug summary

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve androidx.core:core-splashscreen:1.0.0.
     Required by:
         project :app
      > Could not resolve androidx.core:core-splashscreen:1.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/core/core-splashscreen/1.0.0/core-splashscreen-1.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/core/core-splashscreen/1.0.0/core-splashscreen-1.0.0.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.5.1/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### Library version

4.7.0(4.7.5)

### Environment info

```shell
System:
    OS: macOS 13.2.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 32.60 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.24.0 - /usr/local/bin/npm
    Watchman: 2023.07.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 25, 26, 27, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      Android NDK: 23.0.7344513-beta4
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.12 => 0.71.12 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

When installing the module on ios device everything starts correctly, but when starting on android device (Asus, Android 9) use `react-native run-android` an error appears. At the same time I can download the pom file through the browser without problems.

I use IDE,
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022

1)gradle.properties
...
org.gradle.java.home=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/

2)build.gradle
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}

3)app/build.gradle
...
dependencies {
    implementation("com.facebook.react:react-android")
    implementation('androidx.swiperefreshlayout:swiperefreshlayout:1.0.0')
    implementation('androidx.core:core-splashscreen:1.0.0')
...

4) griddle-wrapper.properties
...
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip

Translated with www.DeepL.com/Translator (free version)

5) package.json
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/material-top-tabs": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.8",
    "babel-plugin-module-resolver": "^5.0.0",
    "i18n-js": "^4.3.0",
    "lodash": "^4.17.21",
    "mobx": "^6.10.0",
    "mobx-react": "^9.0.0",
    "mobx-state-tree": "^5.1.8",
    "moment": "^2.29.4",
    "patch-package": "^8.0.0",
    "react": "18.2.0",
    "react-native": "0.71.12",
    "react-native-bootsplash": "^4.7.0",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-pager-view": "^6.2.0",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.23.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-vector-icons": "^10.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.10",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  ...

### Reproducible sample code

```js
After installing this module in 4.7.0 or 4.7.5, the following error appears when running the project on an android device. I also downloaded the project example(react-native-bootsplash/example) from github and when I run it on my computer and android device the same error appears again. 
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve androidx.core:core-splashscreen:1.0.0.

```

**Comment by zoontek** [comment]
Don't forget to run a gradle sync once you added the dependency in your build.gradle file.

**Comment by Melekhin** [comment]
> Don't forget to run a gradle sync once you added the dependency in your build.gradle file.

Thanks! 
The problem turned out to be completely different, I have a clumsy mood depending on the version of Android Studio, jdk on my Mac computer, Because such problems do not occur on Windows...
