### ISSUE TITLE
iOS application is shown first than bootsplash icon is shown

### ISSUE THREAD

**Issue by vitalyiegorov** [zoontek/react-native-bootsplash#48]
### 💻 My environment

- react-native-bootsplash version:1.2.1
- react-native version: 0.61.5
- Platform: ios
- OS version: MacOS Catalina 0.15.3 Beta (19D49f)
- Device: Iphone 8 (emulator)
- Simulator: yes
- Xcode version: 11.3 (11C29)

### 🕵️‍♂️ Reproducing the issue
This issue only relates to IOS, android works perfectly.

Expected: 
- Bootsplash logo on custom background until `hide()` is called

Actual:
- Application icon with gradient background on a custom background color is shown for a small period of time than bootsplash_logo icon is shown on custom background color as expected. 

What I did:
- I have integrated this awesome library following the readme
- generated bootsplash_logo files using the generator
- configured LaunchScreen according to the example and changed the custom background color

We have an application icon with a gradient and a transparent bootsplash logo icon on a transparent background.

![example 2](https://user-images.githubusercontent.com/586558/71416543-88fe2500-2669-11ea-9fdf-86ec5b192906.png)
![exemple 1](https://user-images.githubusercontent.com/586558/71416552-90bdc980-2669-11ea-9e9f-445cb8096c78.png)

**Comment by zoontek** [comment]
@vitalyiegorov This seems to be a tricky one. Could you provide a x1.00 speed playback video capture?

**Comment by Arvi128** [comment]
@vitalyiegorov I faced the same issue on both simulator and device. 
Solved it by uninstalling the app and rebuilding the application using Xcode.

**Comment by zoontek** [comment]
@vitalyiegorov Could you confirm that @Arvi128 solution works for you? 🙂
