### ISSUE TITLE
Black circle appears on Android

### ISSUE THREAD

**Issue by szalarski-vazco** [zoontek/react-native-bootsplash#482]
### Bug summary

On Android something strange happens, at first the icon scales strangely, and then a black circle appears on the screen. On the iOS platform, everything works as it should.

https://github.com/zoontek/react-native-bootsplash/assets/110384195/0f283898-b6db-4526-a067-282deb634c3d

### Library version

5.0.2

### Environment info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 128.55 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.1.1 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.10.10.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/szymon/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 8.0.0 => 8.0.0
    react: 18.2.0 => 18.2.0
    react-native: 0.69.7 => 0.69.7
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.4 is now available (your project is running on v0.69.7).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.4.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.69.7.
info To upgrade, run "react-native upgrade".
```

### Steps to reproduce

1. Install library and setup according to docs.

### Reproducible sample code

```js
Styles .xml

<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
        <item name="android:forceDarkAllowed">false</item>
    </style>

    <style name="BootTheme" parent="Theme.BootSplash">
        <item name="bootSplashBackground">@color/bootsplash_background</item>
        <item name="bootSplashLogo">@drawable/bootsplash_logo</item>
        <!-- <item name="bootSplashBrand">@drawable/bootsplash_brand</item> -->
        <item name="postBootSplashTheme">@style/AppTheme</item>
    </style>
</resources>
```

**Comment by zoontek** [comment]
@szalarski-vazco Did you correctly uninstall `implementation("androidx.core:core-splashscreen:1.0.0")` + performed a gradle sync?
See this duplicate issue: https://github.com/zoontek/react-native-bootsplash/issues/477#issuecomment-1691140683

**Comment by szalarski-vazco** [comment]
@zoontek Thank you for your reply, removing ```androidx.core:core-splashscreen``` fixed issue with black circle on the screen. Unfortunately a bug with strange image dimensions still exists.
After 0.5 second scaled image is replaced with image in right format, please see this video:

https://github.com/zoontek/react-native-bootsplash/assets/110384195/c7b707b2-e1f9-4fb0-a524-e574d56328f9

**Comment by zoontek** [comment]
> For the icon size issue, you probably gave a way too large logo width. What was its value?

+ Please post here your `/android/app/src/main/res/drawable-mdpi/bootsplash_logo.png`

**Comment by szalarski-vazco** [comment]
@zoontek here it is: 
![bootsplash_logo](https://github.com/zoontek/react-native-bootsplash/assets/110384195/70281aff-f45a-4b5e-8dc5-7f97cdf539d2)

Dimensions - 90x135
Resolution - 72x72

**Comment by zoontek** [comment]
@szalarski-vazco It appears you didn't use [this package CLI generator](https://github.com/zoontek/react-native-bootsplash#assets-generation). Logos must include a padding ([see the example asset for comparaison](https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/res/drawable-mdpi/bootsplash_logo.png?raw=true))

[See here why](https://developer.android.com/develop/ui/views/launch/splash-screen#dimensions).

**Comment by szalarski-vazco** [comment]
@zoontek yeah, I had problems with using CLI generator because I have multiple flavours, single one per each environment.

**Comment by zoontek** [comment]
@szalarski-vazco There's a --flavor and a platforms arg, use --flavor=xxx --platforms=android

**Comment by szalarski-vazco** [comment]
@zoontek Thanks for help, but something is not working. I'm using this command ```yarn react-native generate-bootsplash ./apps/booksalon-mobile/assets/images/launch_image.svg --flavor=production --platforms=android```>

This is the output:
```
yarn react-native generate-bootsplash ./apps/booksalon-mobile/assets/images/launch_image.svg --flavor=production --platforms=android
warn Package @sentry/react-native contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  🔑  Get a license key for brand image / dark mode support  ┃
┃      https://zoontek.gumroad.com/l/bootsplash-generator     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

💖  Thanks for using react-native-bootsplash
```

**Comment by zoontek** [comment]
@szalarski-vazco Run the command in your `./apps/booksalon-mobile` directory.

**Comment by ErnestTeluk** [comment]
Unfortunately, it will be difficult to upload such a screenshot here for security reasons. Still, as far as the structure is concerned, we are using nx, and the path for Android looks like `booksalon/apps/booksalon-mobile/android`. There is a corresponding `booksalon/apps/booksalon-mobile/ios`. I try to run the command in the parent folder where android is 
and I will get back to you with the results.

**Comment by zoontek** [comment]
I will add a warning to handle this case, inviting the user to run the command in the correct directory.
