### ISSUE TITLE
Need this library for react-native < 0.71

### ISSUE THREAD

**Issue by abhijeet0009** [zoontek/react-native-bootsplash#489]
### Why it is needed?

Because i am using "react-native": "0.72.3" its working fine in android but need same for ios too

**Comment by zoontek** [comment]
It supports iOS.

**Comment by abhijeet0009** [comment]
i am getting error Incompatible pointer types sending 'UIView *' to parameter of type 'RCTRootView * _Nonnull'

**Comment by zoontek** [comment]
@abhijeet0009 Follow the README, you probably just didn't update your AppDelegate

**Comment by abhijeet0009** [comment]
#import "AppDelegate.h"
#import <Firebase.h>
#import <React/RCTBundleURLProvider.h>
#import "RNBootSplash.h"
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  self.moduleName = @"mystylistvendor";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// ⬇️ Add this before file @end
- (UIView *)createRootViewWithBridge:(RCTBridge *)bridge
                          moduleName:(NSString *)moduleName
                           initProps:(NSDictionary *)initProps {
  UIView *rootView = [super createRootViewWithBridge:bridge
                                          moduleName:moduleName
                                           initProps:initProps];

  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];
  return rootView;
}

@end

**Comment by zoontek** [comment]
@abhijeet0009 Are you using the latest version of react-native-bootsplash? master README reflects this version, not old ones. You seem trying to use the current version install method with an old version.
