### ISSUE TITLE
Scale issue on RN 0.71.13 on IOS

### ISSUE THREAD

**Issue by McFly78** [zoontek/react-native-bootsplash#490]
### Bug summary

I've just upgraded from RN 0.70.13 to RN 0.71.13 and I'm having a problem scaling the size of the splash screen.
On iPhone, when I launch the application, the size of the splash screen is correct but after 1 second, the size of the splash screen is not correct.
I did not test on Android.

I have tested different versions of react-native-bootsplash and I have different scaling problems with RN 0.71.13 :
- 4.7.1 to 4.7.5: the scale is too small
- 4.5.3 to 4.6.0: the scale is too large

The test was carried out on a physical iPhone and on a simulator.

I have this problem with the appdelegate.mm configuration recommended in the documentation (see configuration below).
I managed to find a workaround by modifying the appdelegate.mm file (see configuration below).

Do you have any idea what could be causing such a problem?
Thank you very much for your help.

### Library version

4.7.5

### Environment info

```shell
info Fetching system and libraries information...
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 275.23 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 9.5.0 - /opt/homebrew/bin/npm
    Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.13 => 0.71.13 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Open the app on simulator
2. The splash screen scale size is first good
3. After 1 second the splash screen scale size is too small

### Reproducible sample code

```js
Appdelegate.mm WITH SCALE ISSUE:

#import "AppDelegate.h"
#import "RNBootSplash.h"
#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"SunApp";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}


- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  return true;
}

// react-native-bootsplash
- (UIView *)createRootViewWithBridge:(RCTBridge *)bridge
                          moduleName:(NSString *)moduleName
                           initProps:(NSDictionary *)initProps {
  UIView *rootView = [super createRootViewWithBridge:bridge
                                          moduleName:moduleName
                                           initProps:initProps];

  [RNBootSplash initWithStoryboard:@"LaunchScreen" rootView:rootView]; // initialize the splash screen
  
  return rootView;
}
@end

Appdelegate.mm WITHOUT SCALE ISSUE:
#import "AppDelegate.h"
#import "RNBootSplash.h"
#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"SunApp";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  // react-native-bootsplash
  [super application:application didFinishLaunchingWithOptions:launchOptions];
  UIView *rootView = self.window.rootViewController.view; // ⬅️ ❗️ only required for react-native >= 0.71
  [RNBootSplash initWithStoryboard:@"LaunchScreen" rootView:rootView]; // ⬅️ initialize the splash screen
  return YES;
 }
  
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  return true;
}
@end
```

**Comment by zoontek** [comment]
Do you have a video? Are you sure this isn't during to the iOS cache issue?

https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update (this has been posted multiple times here)

**Comment by McFly78** [comment]
I have made some others tests.
When using the BootSplash example storyboard on my app everything is fine.
When using my own storyboard with BootSplash example logos I have the issue.
So it seems that my storyboard is having issue with the new configuration recommended with RN 0.71.X. 
Maybe it is related to the fact that I resize the image to the full width of the screen ????

Please find 2 videos:
- using the bootSplash example Storyboard
- using my own StoryBoard

https://github.com/zoontek/react-native-bootsplash/assets/47537385/e40b6198-f978-47fe-8884-90ab2de1f5c6
https://github.com/zoontek/react-native-bootsplash/assets/47537385/918c63ed-08d7-438f-af91-4ef8bba01bf5

Please also find my storyboard file:
[LaunchScreenTest.storyboard.zip](https://github.com/zoontek/react-native-bootsplash/files/12642575/LaunchScreenTest.storyboard.zip)

**Comment by zoontek** [comment]
@McFly78 Did you use the CLI assets generator to create this storyboard? (I doubt it)

**Comment by McFly78** [comment]
Thanks 
Sorry I did not know it was mandatory to use the Cli to create the storyboard.
I will look at it.

**Comment by zoontek** [comment]
@McFly78 It's not mandatory, but if you don't know how to properly understand iOS layouting system you can't open issue to ask for free help about it.

**Comment by McFly78** [comment]
Sorry but there's been a misunderstanding.
I never asked for free help about "IOS layouting system". If I knew the issue was coming from the storyboard file I would have never opened an issue.
I opened an issue because this splash screen has been working for many years until this latest upgrade (and only when using the new recommended react-native-bootsplash configuration for RN 0.71.X as I explained).
I spent hours looking at all issues, testing different versions of the library as well as appdelegate.mm configurations trying to resolve this issue.
Thanks to you I understand now something is wrong with the storyboard file even if it was working fine before this upgrade (maybe it was just luck).
So I will now look at iOS layouting system.
I'm sorry I bothered you. I won't disturb you any longer.
And many thanks for your great library.

**Comment by zoontek** [comment]
@McFly78 In order to provide a good reproduction, remember to always use a minimal installation of a library (in a brand new environment - with latest versions), see if it occurs when following the documentation only, in order to prevent opening issues with one of these false positives:

- You made custom changes, but there's actually no issue with the library
- The issue is caused by another dependency
- The issue has already been fixed, but you didn't update the library yet

**Comment by McFly78** [comment]
For those having the same issue I solved it by just recreating my splash screen storyboard from scratch in Xcode.
So it was something wrong in my old storyboard that is not working anymore with the latest update.
Thanks again @zontek for your help.
