### ISSUE TITLE
iOS ignores the splashscreen command to hide in release mode

### ISSUE THREAD

**Issue by Decezaris** [zoontek/react-native-bootsplash#492]
### Bug summary

I'm using react-native: `0.72.4` and bootsplash `5.0.3` in Android everything works great and also in iOS debug mode, but in release the behavior is like shown in the video bellow. The command `hide()`  have been ignored, and the application only loads after splashscreen hide.
 

### Library version

5.0.3

### Environment info

```shell
System:
  OS: macOS 12.6.8
  CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  Memory: 46.50 MB / 8.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.19.4
    path: ~/Documents/tmp-monitore/node_modules/.bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/decezarisaugusto/.rvm/gems/ruby-2.6.10/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /Users/decezarisaugusto/.rvm/rubies/ruby-2.6.10/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "react-native": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. I am using the simulator in release mode via `npx react-native run-ios --mode Release --simulator 'iPhone 14'`
2. Using expo bare workflow with version `49.0.7`

https://github.com/zoontek/react-native-bootsplash/assets/23064759/1f809659-f7ec-4a4d-bfb5-ffb508f80110

### Reproducible sample code

```js
async function easUpdate() {
    try {
      const { isAvailable } = await Updates.checkForUpdateAsync();

      if (isAvailable) {
        await Updates.fetchUpdateAsync();
        await Updates.reloadAsync();
      }
    } catch (err) {
      console.log(err);
    }

    setExpoUpdate(true);
  }

  const waitInitialization =
    !(fontsLoaded && expoUpdate) ||
    isSigned === null ||
    isNotFirstLogin === null ||
    trader === null ||
    customLogoUri === null;


  useEffect(() => {
    if (!waitInitialization && isNavigatorReady) {
      BootSplash.hide({ fade: true });
    }
  }, [waitInitialization, isNavigatorReady]);

  if (signed === null) return <Loading />;

  return (
    <NavigationContainer
      theme={{ colors: { background: 'transparent' } }}
      ref={navigationRef}
      linking={linking}
      onReady={() => {
        analyticsScreen(navigationRef.current.getCurrentRoute().name);
        setIsNavigatorReady(true);
      }}
      onStateChange={async () => {
        const previousRouteName = routeNameRef.current;
        const currentRouteName = navigationRef.current.getCurrentRoute().name;

        if (previousRouteName !== currentRouteName) {
          await analyticsScreen(currentRouteName);
        }
        // Save the current route name for later comparison
        routeNameRef.current = currentRouteName;
      }}
    >
      <Stack.Navigator screenOptions={{ headerShown: false }}>
        {signed ? (
          <Stack.Screen name="SignedStack" component={goToSigned} />
        ) : (
          <>
            <Stack.Screen name="Login" component={LoginScreen} />
            <Stack.Screen
              name="Register"
              component={RegisterScreen}
              options={{ presentation: 'modal' }}
            />
          </>
        )}
      </Stack.Navigator>
    </NavigationContainer>
  );
```

**Comment by zoontek** [comment]
@Decezaris Just in case, also check [this issue](https://github.com/zoontek/react-native-bootsplash/issues/486).

PS: I can't properly debug your issue with this reproduction as it includes a lot of unknown code (what are `isSigned`, `isNotFirstLogin`, `trader` etc?).
Please provide a real reproduction (a minimal app that I can try easily by cloning it, installing deps and run the `npx react-native run-ios --mode Release --simulator 'iPhone 14'` command you gave me).

**Comment by Decezaris** [comment]
@zoontek thanks for the quick response. It's because the code uses authentication service and db readings. I will try to remove all that and post here, but even if I comment the `BootSplash.hide({ fade: true });` the splashscreen hides

**Comment by zoontek** [comment]
@Decezaris If it hides automatically, that means the initialisation is not done properly. Publish your `AppDelegate.mm`.

**Comment by Decezaris** [comment]
I will try that! Thanks, any news I'll give you a update here!

**Comment by Decezaris** [comment]
Same result here! I will try to clean the code for minimal reproduction.

**Comment by igorkirnbb** [comment]
@zoontek Hi, we have the same bug on Android. It seems like library showing SplashScreen and hiding it as soon as JS loaded. After that it shows only empty screen until `hide` call from JS thread.

I checked source code and it looks like library have 250 duration by default now. Is it possible that lib calls hide automatically and screen disappears after 250ms (for some reason)? Because even on first app load after starting build from terminal - I can see splash logo for small amount of time and then its empty screen with loading on top.

**Comment by zoontek** [comment]
@igorkirnbb No, hide is not called directly, or after 250ms. Are you also using Expo?

**Comment by igorkirnbb** [comment]
@zoontek Hey, we have expo installed in the app with some expo packages. But project was created natively with RN CLI.
```
"expo": "^49.0.11",
"react-native": "^0.72.4",
```

**Comment by igorkirnbb** [comment]
Im also not entirely sure if its the same issue. Because in our case it seems like `hide` actually works (on Android) but logo disappears without waiting for the function call. And then `hide` remove empty screen.

**Comment by zoontek** [comment]
Same, provide a reproduction repository that isolate the issue or it's hard not to consider that as an install issue / something coming from the rest of your stack 😕

**Comment by igorkirnbb** [comment]
@zoontek Hey, I found out that on Android 9 library doesnt show splash logo at all, white screen only.
I will try to create repro rep as soon as I have free time.

**Comment by zoontek** [comment]
@igorkirnbb Doesn't appear to.

Debug build:

https://github.com/zoontek/react-native-bootsplash/assets/1902323/957e2afb-2993-410d-94fd-0912155b4f6b

Release build:

https://github.com/zoontek/react-native-bootsplash/assets/1902323/ef4dc9c5-a21b-4dc3-80f1-2c2ec6f8e22d

Folks, if you don't come with a solid reproduction, I will have to close this, as for the moment, it appears not to be an issue with the library 😕

**Comment by Decezaris** [comment]
Sorry for the late response, I'll post the reproduction repo today.

**Comment by Decezaris** [comment]
Hi, sorry about the late response, I've created a empty project and it's working fine on ios in release mode. It's not related with this library!

**Comment by bonnmh** [comment]
@Decezaris  how did you fix it?

**Comment by Decezaris** [comment]
Hi @bonnmh, I just created a empty project and tested on iOS and worked fine.

**Comment by raymondjacobson** [comment]
None of these worked. I was previously manually calling Bootsplash.hide. Seems like I need to use `useHideAnimation` w/ the ready param now to get it working.
