### ISSUE TITLE
Dark background in Dark mode even after background color is set to white(Xiaomi Note 12)

### ISSUE THREAD

**Issue by ValentineCodes** [zoontek/react-native-bootsplash#497]
### Bug summary

Splash screen displays a dark background briefly(about 2 secs) in dark mode before display the specified color in --background-color flag.

### Library version

5.0.4

### Environment info

```shell
react-native: 0.71.11
OS: Mac Monterey
Device: Xiaomi Note 12
```

### Steps to reproduce

1. Setup react-native-bootsplash
2. yarn android

### Reproducible sample code

```js
just run it!
```

**Comment by zoontek** [comment]
> Reproducible sample code
> just run it!

@ValentineCodes No. You have to run on a Xiaomi phone, using MIUI, as it appears Xiaomi continue to screw up with splash screens.

- https://xiaomi.eu/community/threads/splash-screen-is-a-little-dark-on-miui-14.68670/
- https://www.reddit.com/r/miui/comments/11j40ys/looks_like_xiaomi_screwed_up_dark_mode_again_in/
- https://www.reddit.com/r/miui/comments/14pjuxr/bug_in_splash_screen_miui_14_android_12_redmi/

Is there still a "Force dark mode" option in MIUI? That setting do stupid things, tries to invert colors even if they are not defined.

**Comment by ValentineCodes** [comment]
Alright. 
Guess the war is with XIAOMI then
THIS IS WAR!!!🔥😡

**Comment by zoontek** [comment]
@ValentineCodes Implementing the splash screen in dark mode might solve the issue, but it's a real shame that MIUI respect nothing 😕

**Comment by danidaryaweesh** [comment]
@ValentineCodes I tried the latest version and still having the issue mentioned in this ticket. Really frustrated with Xiaomi...

**Comment by zoontek** [comment]
@danidaryaweesh If you buy a license and generate a proper version for the dark mode, it should solves issues with MIUI.

**Comment by RobertPetricevic** [comment]
Hi @zoontek, I've purchased the license and generated files for both light and dark mode, but I still face this issue where the dark background is displayed for 1,2 seconds before the actual dark splash screen. Is this still known issue for Xiaomi phones even with dark mode files?

**Comment by zoontek** [comment]
@RobertPetricevic Which version of the library are you using? Latest?

**Comment by RobertPetricevic** [comment]
@zoontek thanks for the quick reply, yes it is the latest version, 6.1.3

**Comment by zoontek** [comment]
@RobertPetricevic I'm asking because of [this issue](https://github.com/zoontek/react-native-bootsplash/issues/565) (but fixed since 5.5.0). Does this occur with a Xiaomi on MIUI? Did you tried on an emulator?

**Comment by RobertPetricevic** [comment]
@zoontek  Yes, I should have mentioned that this happens only on a Xiaomi mobile on MUIU, on other phones or emulators everything works well. 
I asked this cause I thought the exact issue on MIUI would be solved if splash versions for dark mode were generated as well.

**Comment by zoontek** [comment]
Unfortunately I don't have a Xiaomi with MIUI to / reproduce debug this (but rough guess: they don't follow the Android standard APIs), but does others people have the issue here?

**Comment by RobertPetricevic** [comment]
@zoontek here is the video

https://github.com/user-attachments/assets/4129ca9d-1d18-45c8-afc7-e0c153352fd5

**Comment by zoontek** [comment]
My rough guess: MIUI think that your bright orange is not dark enough and apply a filter / change the color (even if we didn't ask for it 🥲)

Try to use a darker color for the dark mode and see if it stays the same.

**Comment by RobertPetricevic** [comment]
@zoontek aaaand you are correct :)

thanks for your help and quick replies, and of course thanks for this library
