### ISSUE TITLE
The splash is not filling the screen on iOS

### ISSUE THREAD

**Issue by SoyDiego** [zoontek/react-native-bootsplash#499]
### Bug summary

Hi, I have a problem in my app and maybe someone can help me.
Only on iOS (14 Pro max my example) (Real device. In the emulator works perfectly). You can see black spaces around the logo.
On Android works perfectly.

## Screenshot
![image](https://github.com/zoontek/react-native-bootsplash/assets/19764334/5285492a-dc6d-40fe-b9e6-6f381f588ae3)

### Library version

4.7.5

### Environment info

```shell
Real device, iOS 17.0, iPhone 14 Pro max.
```

### Steps to reproduce

1. … I'm doing the configuration that you recommend in the README

### Reproducible sample code

```js
-
```

**Comment by zoontek** [comment]
@SoyDiego First, please update to latest version. Second: did you manually touched to the storyboard file of just ran the CLI command?

**Comment by zoontek** [comment]
Closed, as there's no reply from @SoyDiego.

**Comment by SoyDiego** [comment]
> Closed, as there's no reply from @SoyDiego.

Sorry @zoontek because I didn't reply to you. I never do this things.
Finally a colleage solves the problem and I forgot to write here. 
I think was not a problem of the library, I don't remember if the size of the image or something like that was the problem.

Thanks again for try to help and good job with this library ^^
