### ISSUE TITLE
LinearGradient support

### ISSUE THREAD

**Issue by paolospag** [zoontek/react-native-bootsplash#5]
Does this package support the ability to set a background with LinearGradient in both Android and iOS? If so, how?

**Comment by MoOx** [comment]
You will probably have to handle the linear gradient via iOS .xib [UIView gradient](https://stackoverflow.com/questions/23074539/programmatically-create-a-uiview-with-color-gradient) / Android [drawable gradient](https://stackoverflow.com/questions/35814174/splash-screen-and-gradient).
Nothing specific related to this package as this package allow you to rely on native solution to show a splash screen.

**Comment by paolospag** [comment]
@MoOx thanks for your suggestion.
Unfortunately, [Xcode doesn't allow runtime code in .xib](https://stackoverflow.com/questions/46057103/how-to-set-linear-gradient-to-background-of-launchscreen-xib-in-ios#answer-46057277) and I'm unable to create UIView with gradient. 
Any workaround to do that without using a background image?

For Android: can I put `LinearLayout` into the `bootsplash.xml` file?

**Comment by MoOx** [comment]
I am not familiar enough with iOS and Android best practices to help you more than using StackOverflow, sorry 😅

**Comment by zoontek** [comment]
For Android, it should not be difficult. For iOS you have two options: A full sized image or a 1px width image stretch horizontally.
