### ISSUE TITLE
How to stretch pictures to full screen according to screen size

### ISSUE THREAD

**Issue by Zhang-DaLei** [zoontek/react-native-bootsplash#50]
### 💻 My environment

- react-native-bootsplash version:1.2.1
- react-native version:0.61.5
- Platform: ios / android / both android
- OS version: 8.0
- Device: brand + model
- Simulator: yes
- Android Studio version: 3.5.3
- Android buildToolsVersion: ?
- Xcode version: ?

### 🕵️‍♂️ Reproducing the issue

I want to spread a large picture over the whole screen, but the picture is beyond the scope of the screen, without width and height scaling.

**Comment by zoontek** [comment]
@Zhang-DaLei Check the documentation for XML bitmap: https://developer.android.com/guide/topics/resources/drawable-resource#XmlBitmap

It has `android:gravity` prop which can be set to `fill` apparently

**Comment by danieltereschenko** [comment]
> @Zhang-DaLei Check the documentation for XML bitmap: https://developer.android.com/guide/topics/resources/drawable-resource#XmlBitmap
> 
> It has `android:gravity` prop which can be set to `fill` apparently

Hello, I added android:gravity="fill_horizontal" and it works fine for the second part of the splash screen, the first one seems to ignore this. Is it possible to make it so both parts are filled horizontally? Thanks

https://user-images.githubusercontent.com/37038091/125471458-3e6c032f-cd9a-4006-a9c3-394d75b184e6.mov
