### ISSUE TITLE
Splash screen disappeared unexpectedly

### ISSUE THREAD

**Issue by yuameshi** [zoontek/react-native-bootsplash#500]
### Bug summary

I've met this bug since i updated this lib from v4.7.5 to the latest version of this library & i m trying to use `VectorDrawable` in android. when the app was launched, the splash screen will 'splash' literally. (the splash screen will disappear even `hide()` havn't called)

i ve tried to log `isVisible()`, it reveals that when the splash screen disappears, program still considers it is visible.
![new ducument](https://github.com/zoontek/react-native-bootsplash/assets/64469437/fdcd3e51-06e9-485f-97bf-fbad86e2f7d3)

https://github.com/zoontek/react-native-bootsplash/assets/64469437/8fe1fa83-9485-4266-88b0-7b143c8b6026

I ran a logcat and found a relative error: 
`E [Splash Screen  com.packagename#0](this:0xb400007dd7b3c900,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Splash Screen com.packagename#0'

### Library version

5.0.4

### Environment info

```shell
> npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
  Memory: 979.47 MB / 15.64 GB
Binaries:
  Node:
    version: 18.17.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.6.7
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "31"
      - "33"
    Build Tools:
      - 30.0.3
      - 33.0.0
    Android NDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.7.34018.315 (Visual Studio Community 2022)
Languages:
  Java: 11.0.20
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

-

### MainActivity.java
![image](https://github.com/zoontek/react-native-bootsplash/assets/64469437/bfe9236e-2a2a-44ac-8226-3220b9b9456f)

### AndroidManifest.xml
![image](https://github.com/zoontek/react-native-bootsplash/assets/64469437/6714c510-3462-4a68-aaf2-592d3a582234)

### `res` folder structure
![image](https://github.com/zoontek/react-native-bootsplash/assets/64469437/781b7b21-f80a-4624-9c81-3b1dfe0e38d2)
### `res/values(-night)/colors.xml`

<resources>
    <color name="splash_background_color">#191B1D</color>
</resources>

### `res/values/styles.xml`
```xml
<resources xmlns:tools="http://schemas.android.com/tools">
	<!-- Base application theme. -->
	<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
		<!-- Customize your theme here. -->
		<item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
	</style>
	<style name="BootTheme" parent="Theme.BootSplash.EdgeToEdge">
		<item name="bootSplashBackground">@color/splash_background_color</item>
		<item name="bootSplashLogo">@drawable/splash_logo_black</item>
		<!-- Brand image -->
		<item name="bootSplashBrand">@drawable/splash_brand_image_black</item>
		<item name="postBootSplashTheme">@style/AppTheme</item>
		<item name="android:statusBarColor" tools:targetApi="m">@color/splash_background_color</item>
		<item name="android:windowLightStatusBar" tools:targetApi="m">true</item>
	</style>
</resources>
```
### `res/values-night/styles.xml`
```xml
<resources xmlns:tools="http://schemas.android.com/tools">
	<style name="BootTheme" parent="Theme.BootSplash.EdgeToEdge">
		<item name="bootSplashBackground">@color/splash_background_color</item>
		<item name="bootSplashLogo">@drawable/splash_logo_white</item>
		<!-- Brand image -->
		<item name="bootSplashBrand">@drawable/splash_brand_image_white</item>
		<item name="postBootSplashTheme">@style/AppTheme</item>
		<item name="android:statusBarColor" tools:targetApi="m">@color/splash_background_color</item>
		<item name="android:windowLightStatusBar" tools:targetApi="m">true</item>
	</style>
</resources>
```

**Comment by yuameshi** [comment]
6

**Comment by zoontek** [comment]
Duplicate of https://github.com/zoontek/react-native-bootsplash/issues/495

Vector drawables are not supported to ensure compatibility on Android 5.x.

Use the CLI to generate dark assets in multiple sizes instead.
