### ISSUE TITLE
I can't create a full screen image as bootsplash like the one on v4

### ISSUE THREAD

**Issue by gelodgreat** [zoontek/react-native-bootsplash#503]
### Bug summary

Seems the documentation doesn't provide info on how we can make a full screen image as our bootsplash

### Library version

5.0.4

### Environment info

```shell
Seems the documentation doesn't provide info on how we can make a full screen image as our bootsplash
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
Seems the documentation doesn't provide info on how we can make a full screen image as our bootsplash
```

**Comment by zoontek** [comment]
This wasn't possible on v4, as it already used Android SplashScreen API, that offers a limited amount of customization.

https://developer.android.com/develop/ui/views/launch/splash-screen
