### ISSUE TITLE
Add an option for custom output path for Android and iOS assets

### ISSUE THREAD

**Issue by AlixH** [zoontek/react-native-bootsplash#504]
### Why it is needed?

Option for custom output path for Android and iOS assets
This would be very useful to generate assets dynamically during build phase without impacting git working tree

**Comment by zoontek** [comment]
@AlixH What do you mean exactly 😅? Maybe just add the files in your gitignore?

**Comment by AlixH** [comment]
> @AlixH What do you mean exactly 😅? Maybe just add the files in your gitignore?

Yes I could but I don't really know all the files possible,  would be easier to exclude a dedicated folder because I have other assets I don't want to exclude

**Comment by zoontek** [comment]
To know all the files, clean you git stage, run the command, you will have them 🙂

**Comment by AlixH** [comment]
I can exclude the files, but I cannot exclude the colors since they are inserted inside existing files
