### ISSUE TITLE
Feature request: the scripts should accept args, so it can be run in a CLI

### ISSUE THREAD

**Issue by ssilverr** [zoontek/react-native-bootsplash#51]
Hi!

I'm really liking this package, and I have a suggestion:

It would be nice, if the  `generate-bootsplash-assets` script acccepted args after it, like:

`npx generate-bootsplash-assets . brands/default icon.png 300`

Or have an exported member, so it can be called in a script like:

```
import {generate_bootsplash_assets} from 'react-native-bootsplash'


generate_bootsplash_assets({
       projectPath: ".",
       assetsPath: "assets",
       etc...
      })

```

This way, it could be run in a none interactive environment like a CLI.

**Comment by zoontek** [comment]
You are right: CLI support could be nice (with fallback to interactive mode if some args are missing).
https://github.com/sindresorhus/meow could be a great solution for implementing it.

**Comment by ssilverr** [comment]
I guess that I wrote that while tired, and I think we're on the same page, but just for completeness' sake, I meant: run in a CI/CD environment, not CLI (that is what it already does 😄)

**Comment by zoontek** [comment]
@ssilverr Yeah I understood, no worry 😄

**Comment by ssilverr** [comment]
@zoontek Hi again! Sorry to bother you, but any news on v3.0.0 progress?

**Comment by zoontek** [comment]
@ssilverr I waited a bit after some RN 0.63 decisions. As I know, the default splash screen will be named `LaunchScreen.storyboard` out of the box, which is cool since it will remove some Xcode config steps.

I need to rename generated files and write a migration guide before shipping a beta.

**Comment by ssilverr** [comment]
@zoontek ahh gotcha, guess it'll be out some time after v0.63 then, thanks

**Comment by zoontek** [comment]
@ssilverr The new version (3.0.0) relying on the react-native CLI, is available in alpha. Please give it a try: https://github.com/zoontek/react-native-bootsplash/tree/3.0.0 🙂

**Comment by ssilverr** [comment]
@zoontek Sweet! Tried it out in a fresh rn project. It's super fast! Works very well as package.json script. Thank you for your work.

<details>
  <summary> </summary>
  
I finally won't have to patch-package my shitty solution each release 😄  Now to find the time to upgrade the ongoing project to rn 63 😢 
</details>
