### ISSUE TITLE
Custom size of logo and brand images

### ISSUE THREAD

**Issue by myleshk** [zoontek/react-native-bootsplash#514]
### Why it is needed?

To allow customisation of logo and brand dimensions. It's now hardcoded here https://github.com/zoontek/react-native-bootsplash/blob/master/android/src/main/res/drawable-v23/compat_splash_screen.xml, making it impossible to use logo and brand images with different aspect ratio than this hardcoded one.

Similar for the position of brand (bottom of 60dp), but not as important as the dimensions.

### Possible implementation

Simply removing that hardcoded part works for me. Not sure if any other impacts though.

**Comment by zoontek** [comment]
It aligns with Android 12+ SplashScreen API. 

Removing the hardcoded part will just break the design for these versions of the OS.

![IMG_1561](https://github.com/zoontek/react-native-bootsplash/assets/1902323/b5c95f71-4238-4205-83b6-6c10a847b7c1)

**Comment by zoontek** [comment]
Applying a local patch will just break your design on Android 12+.

At start, the splash screen is shown by the system using a few properties, then it switches to the app compat implementation. If you play with that, it will show briefly the logo / brand image with a max size and a defined position, then shift to the size / position defined in your patch.

https://developer.android.com/develop/ui/views/launch/splash-screen

**Comment by myleshk** [comment]
You are right, appreciate for it. Will change our design then.
