### ISSUE TITLE
[Android] Got ANR error after loading the splash screen finished

### ISSUE THREAD

**Issue by datngotan-aavn** [zoontek/react-native-bootsplash#515]
### Bug summary

Hi, thank you for your great library; I've used this library to show splash screens on Android devices. It worked perfectly on Version 4. However, when I migrated from V4 to V5 to resolve [this crash issue](https://github.com/zoontek/react-native-bootsplash/issues/381), the app showed the ANR error after loading the splash screen finished.
![anr-example-framed](https://github.com/zoontek/react-native-bootsplash/assets/107596496/df3b29d3-42ac-4478-afc3-8ea61a77f2d8)

### Library version

5.1.3

### Environment info

```shell
System:
    OS: macOS 14.0
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 273.30 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      API Levels: 28, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-31 | Google Play Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Migrate [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash) from v.4 to v.5

### Reproducible sample code

```js
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
<!--        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>-->
        <item name="android:navigationBarColor">@color/footer_bar_color</item>
    </style>
    <!-- BootTheme should inherit from Theme.BootSplash or Theme.BootSplash.EdgeToEdge -->
    <style name="BootTheme" parent="Theme.BootSplash.EdgeToEdge">
        <item name="android:navigationBarColor">@color/footer_bar_color</item>
        <item name="bootSplashBackground">@color/bootsplash_background</item>
        <item name="bootSplashLogo">@drawable/bootsplash_logo</item>
        <item name="bootSplashBrand">@drawable/bootsplash_brand</item>
<!--        <item name="android:windowDisablePreview">true</item>-->
        <!--        <item name="android:windowIsTranslucent">true</item>-->

    </style>
</resources>
```

**Comment by zoontek** [comment]
@datngotan-aavn Isn't `ANR` just the name of your app? I need a crash log.

**Comment by datngotan-aavn** [comment]
> @datngotan-aavn Isn't `ANR` just the name of your app? I need a crash log.
> 
> * https://developer.android.com/studio/debug/logcat (Android studio)
> * https://developer.android.com/tools/logcat (CLI)

Hi, thank you for replying to me. It's not crashed. It just show the ANR dialog like in the screenshot.

**Comment by zoontek** [comment]
@datngotan-aavn Probably an error on your side. Publish the log.

**Comment by datngotan-aavn** [comment]
> @datngotan-aavn Probably an error on your side. Publish the log.

thank you, I'll check on my side

**Comment by zoontek** [comment]
@datngotan-aavn If you follow the links I gave to read the logs, you will get the error.
