### ISSUE TITLE
Splash screen jump

### ISSUE THREAD

**Issue by alnthomas** [zoontek/react-native-bootsplash#52]
The splash screens are misaligned and cause jump similar to the react-native-splash-screen.

Tested on Pixel 3 XL emulator and real device 19:8 aspect ratio.

Installed the latest version and followed the instructions on https://www.npmjs.com/package/react-native-bootsplash almost the same

The differences are
**Styles.xml**
```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:textColor">#000000</item>
        <item name="android:statusBarColor">@color/statusbar</item>
        <item name="android:windowLightStatusBar">true</item>

        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>

    <style name="SplashTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:background">@drawable/background_splash</item>
        <item name="android:statusBarColor">@color/splash</item>
        <item name="android:windowLightStatusBar">true</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
</resources>
```

**background_splash**
```
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
  <item android:drawable="@color/splash" />

  <item
        android:width="222dp"
        android:height="222dp"
        android:drawable="@mipmap/icon"
        android:gravity="center" />
</layer-list>
```

Why is this happening?

**Comment by zoontek** [comment]
@alnthomas Please respect the issue template.

**Comment by alnthomas** [comment]
### 💻 My environment

- react-native-bootsplash version: 1.2.0
- react-native version: 0.60
- Platform: android
- OS version: 10
- Device: Mi 9 Pro
- Simulator: no
- Android Studio version: 3.5
- Android buildToolsVersion: 26.1.1

Inherited the app theme, it did work on the simulator (Pixel 2 XL). However, still jumps on the real device. 

Added a landing/home screen similar to the splash screen as follows

```
        <View style={styles.container}>
                <Image style={{ width: 222, height: 222, flex: 1 }} 
                    source={require('res/images/icon.png')} 
                    resizeMode='contain' 
                    fadeDuration={0} />
                <StatusBar
                    barStyle='dark-content'
                />
        </View>
```

The new screen and RN Bootsplash screen (the second splash screen opened from Main Activity) are perfectly aligned. But not the first one (The real android splash screen)

**AndroidManifest.xml**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.assetvuemobile">

    <uses-permission android:name="android.permission.INTERNET" />

  <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
        android:theme="@style/SplashTheme">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|smallestScreenSize|screenLayout"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

**Comment by zoontek** [comment]
I see you are setting `android:windowLayoutInDisplayCutoutMode`. Do you handle the notch? Did you add code in your `MainActivity` (like in this tutorial: https://dev.to/brunolemos/adding-notch-support-to-your-react-native-android-app-3ci3) ?

**Comment by alnthomas** [comment]
No.
I removed `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>`.
Not using in fullscreen any more.

**Comment by zoontek** [comment]
@alnthomas Then you confirm that a status bar is visible 100% of the time and that your app does not draw under?

**Comment by alnthomas** [comment]
Yes. I confirm that a status bar is visible 100% of the time.

**Comment by zoontek** [comment]
Do you have another physical device to test it?
Also can you create a repository with the minimal amount of code to reproduce the issue?

**Comment by afeichuanqi** [comment]
> Do you have another physical device to test it?
> Also can you create a repository with the minimal amount of code to reproduce the issue?

Xiaomi Mi 6 is also beating. I fully follow your demonstration to operate the android configuration file.

**Comment by zoontek** [comment]
@afeichuanqi  Could you provide a minimal example repository to help me reproduce the error?

**Comment by afeichuanqi** [comment]
> Do you have another physical device to test it?
> Also can you create a repository with the minimal amount of code to reproduce the issue?

I took a closer look just now. I think it's a problem with the status bar.
It is when the status bar appears that the height of center's father may have changed so that the logo icon sinks the distance of the status bar.
So how can I solve this

**Comment by zoontek** [comment]
@afeichuanqi If you never provides me some code, we will never solve this!

**Comment by whimsicaldreamer** [comment]
@zoontek Tried it on xiaomi mi a3. The screen do jump a bit.

**MainActivity.java**  

```
@Override
  protected void onCreate(Bundle savedInstanceState) {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
          WindowManager.LayoutParams layoutParams = new WindowManager.LayoutParams();
          layoutParams.layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;
          getWindow().setAttributes(layoutParams);
          getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
          getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);
      }
      super.onCreate(savedInstanceState);
      RNBootSplash.show(R.drawable.bootsplash, MainActivity.this);
  }
```

**styles.xml**  

<resources>

```
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>

    <style name="BootTheme" parent="AppTheme">
        <item name="android:background">@drawable/bootsplash</item>
    </style>

</resources>
```

**NOTE:** I do have another issue and that is on setting the following:

```
getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);
```
all screens have a translucent status bar and navigation, which is obvious, but then how can I only set translucent behaviour only on the splash screen and not on other screens.

**Comment by zoontek** [comment]
@whimsicaldreamer The issue here is that you set your status bar style directly in code (in your `MainActivity`) but your app does not start with it (it uses `RNBootSplashActivity`).

So instead of Java code, try to set your styles with a dedicated file (`styles-v28.xml` for Android Pie):

```xml
<!-- Base application theme. -->
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <!-- Customize your theme here. -->
    <item name="android:textColor">#000000</item>
    <item name="android:windowDrawsSystemBarBackgrounds">true</item>
    <item name="android:windowTranslucentStatus">true</item>
    <item name="android:windowTranslucentNavigation">true</item>
    <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
</style>

<style name="BootTheme" parent="AppTheme">
    <item name="android:background">@drawable/bootsplash</item>
</style>
```

Not sure about the android config keys, but you get the idea 🙂

**Comment by Rapsssito** [comment]
@zoontek, I also set the status bar and bottom navigation bar styles in the `MainActivity.java` in order to get a **fully transparent look on devices with notches and other decorations**.

```java
    @Override // Added
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this);
        super.onCreate(savedInstanceState);
        // Invisible navigation bar
        final Window win = getWindow();
        win.getDecorView().setSystemUiVisibility(
                View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                        | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                        | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
        );
        win.setNavigationBarColor(Color.TRANSPARENT);
        win.setStatusBarColor(Color.TRANSPARENT);
    }
```

Is there any possibility to get `RNBootSplashActivity.java` compatible with styling directly `onCreate`?

**Comment by whimsicaldreamer** [comment]
I get the idea but what is the difference? Am sorry for this silly question but I am totally naive with android native code. Should I be creating a different values directory under res directory with the name `values-v28`?
Am not sure actually. 😖

**Comment by Rapsssito** [comment]
@zoontek, thanks for the advice! Didn't think about that!

> 
> 
> @Rapsssito Same as @whimsicaldreamer, match the applied style in your xml (best option IMHO) or extend the https://github.com/zoontek/react-native-bootsplash/blob/master/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java class to add custom code in the `onCreate`
> 
> ```java
> package com.project;
> 
> public class CustomSplashActivity extends RNBootSplashActivity {
>   @Override
>   protected void onCreate(@Nullable Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
>     // Your custom code
>   }
> }
> ```
> 
> I don't see a possible restriction about this.

**Comment by zoontek** [comment]
@whimsicaldreamer Yes, `res/values-v28/styles.xml` indeed 😅(not `styles-v28.xml`, my bad!).

The difference is that `react-native-bootsplash` starts with `RNBootSplashActivity` instead of `MainActivity` (because RN currently does not support `android:background` to set a splash screen and `android:windowBackground` is unreliable with notches).

`RNBootSplashActivity` does not have a translucent status bar, `MainActivity` yes (because you set it directly in the class code) -> the jump happens!

Setting your params in the XML is a **better solution** because it does not involve Java code and because `BootTheme` inherits from the `AppTheme`, enforcing exactly the same config at the only exception of `<item name="android:background">@drawable/bootsplash</item>`.

I hope it's clear enough 😄

**Comment by whimsicaldreamer** [comment]
@zoontek ok I tried your suggestion and it turns out that if I set
 `<item name="android:windowTranslucentStatus">true</item>`, the splash screen has the top area of splash screen covered with the splash screen backround colour. But then on my app's first screen the status is translucent which I do not want. How can that be fixed?

**values-v28/styles.xml**  

```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>

    <style name="BootTheme" parent="AppTheme">
        <item name="android:background">@drawable/bootsplash</item>
    </style>

</resources>
```

**values/styles.xml**  

```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
        <item name="android:windowFullscreen">true</item>
    </style>

    <style name="BootTheme" parent="AppTheme">
        <item name="android:background">@drawable/bootsplash</item>
    </style>

</resources>

**MainActivity**  

```
  @Override
  protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      RNBootSplash.show(R.drawable.bootsplash, MainActivity.this);
  }
```
```

**Comment by whimsicaldreamer** [comment]
@zoontek Why do we need to have `AppTheme` as a parent of `BootTheme`? Why cant we use `SomeOtherTheme` as a parent of `BootTheme`?

**Comment by zoontek** [comment]
> Why do we need to have AppTheme as a parent of BootTheme?

To apply the same config and prevent these kinds of behaviors.

**Comment by whimsicaldreamer** [comment]
If thats the case then how should I be doing so that my app screens have a opaque statusbar except for the splash screen?

**Comment by zoontek** [comment]
@whimsicaldreamer If you want an opaque status bar, you can apply splash screen status bar color and change it with https://facebook.github.io/react-native/docs/statusbar#setbackgroundcolor once the app is started.

```xml
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:textColor">#000000</item>
        <item name="android:statusBarColor">@color/appStatusBarColor</item>
    </style>

    <style name="BootTheme" parent="AppTheme">
        <item name="android:background">@drawable/bootsplash</item>
    </style>
</resources>
```

```js
const App = () => {
  useEffect(() => {
    BootSplash.hide();
    StatusBar.setBackgroundColor("#FFF");
  }, []);

  // …
```
```

**Comment by whimsicaldreamer** [comment]
In that case the splash screen too will have a status bar isnt it?
My requirement is that the splash screen should not have any statusbar. While the app screens should have a opaque statusbar.

**Comment by krakz999** [comment]
> In that case the splash screen too will have a status bar isnt it?
> My requirement is that the splash screen should not have any statusbar. While the app screens should have a opaque statusbar.

No it won't. Statusbar will come back in the same time you call ```BootSplash.hide();```

If you set a duration when you invoke hide like this ```BootSplash.hide(250);```, create a timeout with the same duration and call ```StatusBar.setBackgroundColor("#FFF");``` in it.

**Comment by whimsicaldreamer** [comment]
@zoontek @krakz999 Am not sure but somehow in Mi A3 I don't get the splashscreen full screen.

**Comment by zoontek** [comment]
@whimsicaldreamer Just apply the background color as status bar color.

**Comment by whimsicaldreamer** [comment]
@zoontek and remove other android config keys like full screen?

**Comment by zoontek** [comment]
@whimsicaldreamer Yes

**Comment by whimsicaldreamer** [comment]
@zoontek it brings a statusbar to the splashscreen. :(

**Comment by zoontek** [comment]
You want no status bar on the splash screen and an opaque status bar in your app. At some point, a jump will happen, it's inevitable.

You can also starts your app without a status bar and use the StatusBar module to display it when you want, but it will be ugly too. My advice: stay consistent. Keep a status bar on both, or no status bar on both.

**Comment by whimsicaldreamer** [comment]
I understand. Can you advice me on how some apps get the splash screen without a statusbar while rest of the app with a status bar?

**Comment by zoontek** [comment]
Keep the status bar translucent, put a View on top of your app with the StatusBar height and a white background?

**Comment by zoontek** [comment]
I'm closing this since it's not related to this library directly, but rather a misconfiguration between the `SplashActivity` and the `MainActivity`. If identical settings are applied, it works 😅

**Comment by whimsicaldreamer** [comment]
It would be great if isolated configuration could be done, if possible. 😇

**Comment by GIAVINH2010** [comment]
> @whimsicaldreamer The issue here is that you set your status bar style directly in code (in your `MainActivity`) but your app does not start with it (it uses `RNBootSplashActivity`).
> 
> So instead of Java code, try to set your styles with a dedicated file (`styles-v28.xml` for Android Pie):
> 
> ```
> 
> <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>     
>     <item name="android:textColor">#000000</item>
>     <item name="android:windowDrawsSystemBarBackgrounds">true</item>
>     <item name="android:windowTranslucentStatus">true</item>
>     <item name="android:windowTranslucentNavigation">true</item>
>     <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
> </style>
> 
> <style name="BootTheme" parent="AppTheme">
>     <item name="android:background">@drawable/bootsplash</item>
> </style>
> ```
> 
> Not sure about the android config keys, but you get the idea

It works for me. Thanks

**Comment by maystrenkoYurii** [comment]
Hi i fixed this issue.
1) Set in app theme and splash theme
`<item name="android:windowTranslucentStatus">true</item>`
2) Fix adjustResize
`public class FrameAssistant {
  public static void assistActivity (Activity activity) {
    new FrameAssistant(activity);
  }

  private View childContent;
  private FrameLayout.LayoutParams frameLayoutParams;
  private int frameHeightPrevious;

  private FrameAssistant(Activity activity) {
    FrameLayout content = (FrameLayout) activity.findViewById(android.R.id.content);

    childContent = content.getChildAt(0);

    childContent.getViewTreeObserver().addOnGlobalLayoutListener(this::possiblyResizeChildOfContent);

    frameLayoutParams = (FrameLayout.LayoutParams) childContent.getLayoutParams();
  }

  private void possiblyResizeChildOfContent() {
    int frameHeight = getFrameHeight();

    if (frameHeight != frameHeightPrevious) {
      frameLayoutParams.height = frameHeight;

      childContent.requestLayout();

      frameHeightPrevious = frameHeight;
    }
  }

  private int getFrameHeight() {
    Rect rect = new Rect();

    childContent.getWindowVisibleDisplayFrame(rect);

    return rect.bottom;
  }
}`

**Comment by yum650350** [comment]
in my case it is fixed by this

MainActivity.java
```JAVA
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Window window = getWindow();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
            int option = View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN | 
                         View.SYSTEM_UI_FLAG_LAYOUT_STABLE;
            window.getDecorView().setSystemUiVisibility(option);
            window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);

            getWindow().setStatusBarColor(Color.TRANSPARENT); // set color to transparent
        }
        super.onCreate(savedInstanceState);
        RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);

        // ...
    }
```

styles.xml

```xml
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:windowTranslucentStatus">true</item>
    </style>
    <style name="BootTheme" parent="AppTheme">
        <item name="android:background">@drawable/bootsplash</item>
    </style>
</resources>
```

But here is another issue, although status bar color has been set to transparent, the status bar still has a semi transparent color at the beginning of the application.

![ezgif-7-35c386322f02](https://user-images.githubusercontent.com/48589760/90288367-50d37d00-deac-11ea-9932-5074d3385c98.gif)

Do anyone have an idea to get rid of it?

**Comment by Magudeshwaran** [comment]
> It would be great if isolated configuration could be done, if possible. 😇 

Hi ,did it worked for you ?

**Comment by shoopi12** [comment]
> @whimsicaldreamer The issue here is that you set your status bar style directly in code (in your `MainActivity`) but your app does not start with it (it uses `RNBootSplashActivity`).
> 
> So instead of Java code, try to set your styles with a dedicated file (`styles-v28.xml` for Android Pie):
> 
> ```
> 
> <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>     
>     <item name="android:textColor">#000000</item>
>     <item name="android:windowDrawsSystemBarBackgrounds">true</item>
>     <item name="android:windowTranslucentStatus">true</item>
>     <item name="android:windowTranslucentNavigation">true</item>
>     <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
> </style>
> 
> <style name="BootTheme" parent="AppTheme">
>     <item name="android:background">@drawable/bootsplash</item>
> </style>
> ```
> 
> Not sure about the android config keys, but you get the idea 🙂

This fixed the jumpy behavior. But I want my navigation bar to remain black / opaque. I tried giving it a black color but that didn't help. Is there anyway around this?

**Comment by shoopi12** [comment]
So, from my experience, what was causing the jumpy behavior is actually the Android NavigationBar (not the StatusBar, even though it may appear like it). You can confirm this by only using this line:
`<item name="android:windowTranslucentNavigation">true</item>` - and now the splash screen is centered correctly.

What finally worked for me that seems acceptable was making the NavigationBar translucent, and also black. Then combining that with Safe Area View so that elements wouldn't render beneath it.

The way to achieve this is by settings flags in onCreate method, such as:
```
    Window w = getWindow();
    w.setNavigationBarColor(getResources().getColor(R.color.black));
    w.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
```

([full example](https://unicorn-utterances.com/posts/draw-under-navbar-using-react-native/#The-Right-Way)).

This is a lot of work for fixing something that is both basic and common - full screen splash image (in my use-case, I had to transition a full screen image into a full screen video, so they had to match exactly).

Hopefully this helps somebody. I spent way too much time on this.

**Comment by Yashpk789987** [comment]
After using <item name="android:windowTranslucentStatus">true</item>
status bar was hidden but the problem is react-native-keyboard-aware-scroll-view stopped working on android

i found the problem was using  <item name="android:windowTranslucentStatus">true</item> causes this issue
so for anyone's need

i created native  module  so that after hiding the splash we can set android:windowTranslucentStatus = false

![Screenshot 2020-12-13 at 5 24 02 AM](https://user-images.githubusercontent.com/43312758/101999476-46769380-3c92-11eb-8b72-7940af6c7ac4.png)

And then after hiding splash

`       await RNBootSplash.hide({fade: true});
        if (Platform.OS === 'android') {
          NativeModules.StatusBarModule.toggle(false);
        }
`

**Comment by zoontek** [comment]
@Yashpk789987 https://reactnative.dev/docs/statusbar#translucent

**Comment by Yashpk789987** [comment]
@zoontek i know but that's was not resolving the issue of keyboard-aware-scroll-view
but native-module did .

**Comment by tranvanduong2483** [comment]
> After using `<item name="android:windowTranslucentStatus">true</item>`
> status bar was hidden but the problem is react-native-keyboard-aware-scroll-view stopped working on android
> 
> i found the problem was using true causes this issue
> so for anyone's need
> 
> i created native module so that after hiding the splash we can set android:windowTranslucentStatus = false
> 
> ![Screenshot 2020-12-13 at 5 24 02 AM](https://user-images.githubusercontent.com/43312758/101999476-46769380-3c92-11eb-8b72-7940af6c7ac4.png)
> 
> And then after hiding splash
> 
> ` await RNBootSplash.hide({fade: true}); if (Platform.OS === 'android') { NativeModules.StatusBarModule.toggle(false); }`

It works! 👏

**Comment by maxpill** [comment]
@Yashpk789987 Could you share the whole SplashBarModule.java and SplashBarPackage.java files?

**Comment by Yrsafam** [comment]
`if (Platform.OS === 'android') {
    StatusBar.setTranslucent(true);
    RNBootSplash.hide();
    StatusBar.setTranslucent(false);
  } else {
    RNBootSplash.hide();
  }`

**Comment by emonidi** [comment]
in [LoginForm.js Line:114](https://github.com/Expensify/App/blob/5e5eb9d5acc5941310e8889398390b45325c85b0/src/pages/signin/LoginForm.js#L114) set `translateX={-10}`

This will fix it.
