### ISSUE TITLE
Problem Building with Tecat Native 0.73 for Android

### ISSUE THREAD

**Issue by s1tony** [zoontek/react-native-bootsplash#524]
### Bug summary

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     error: resource style/Theme.SplashScreen (aka com.collections:style/Theme.SplashScreen) not found.
     com.collections.app-mergeDebugResources-34:/values/values.xml:5470: error: style attribute 'attr/windowSplashScreenBackground (aka com.collections:attr/windowSplashScreenBackground)' not found.
     com.collections.app-mergeDebugResources-34:/values/values.xml:5471: error: style attribute 'attr/windowSplashScreenAnimatedIcon (aka com.collections:attr/windowSplashScreenAnimatedIcon)' not found.
     com.collections.app-mergeDebugResources-34:/values/values.xml:5472: error: style attribute 'attr/postSplashScreenTheme (aka com.collections:attr/postSplashScreenTheme)' not found.
     error: failed linking references.
re

### Library version

5.2.1

### Environment info

```shell
0.73.1
```

### Steps to reproduce

1. Create a new React Native project with version 0.73.1
2. Add react-native-bootsplash to the project per the instructions
3. 3. Build for Android

### Reproducible sample code

```js
<SafeAreaProvider>
      <ThemeProvider theme={CustomTheme}>
        <AppProvider id={appId}>
          <UserProvider
            // @ts-ignore
            fallback={LoginScreen}
          >
            <NavigationContainer
              theme={IS_COLOR_SCHEME_DARK ? NavigationThemeDark : NavigationThemeLight}
              onReady={() => RNBootSplash.hide()}
            >
              <Stack.Navigator
                screenOptions={{
                  headerTitleStyle: {
                    fontSize: 24
                  },
                }}
              >
                <Stack.Screen
                  name="CollectionsStack"
                  component={collectionsStackScreen}
                  options={{ headerShown: false }}
                />
              </Stack.Navigator>
            </NavigationContainer>
          </UserProvider>
        </AppProvider>
      </ThemeProvider>
    </SafeAreaProvider>
```

**Comment by s1tony** [comment]
This is a brand new project I just started.

**Comment by zoontek** [comment]
Hey! `Theme.SplashScreen` is not from the library. Don't know what you are trying to achieve, but follow the README for the setup.

**Comment by s1tony** [comment]
Not sure what I was doing - I created images with Android Studio and believe I copied the incorrect config data over to my project - my apologies.
