### ISSUE TITLE
Can't generate bootsplash screen with new version Sharp

### ISSUE THREAD

**Issue by dungpasoftware** [zoontek/react-native-bootsplash#526]
### Bug summary

I upgrade this library version from 4.5.3 to 5.2.1 and when I try to generate the boot splash screen. It shows this error
Something went wrong installing the "sharp" module

dlopen(/Users/xx/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node, 0x0001): symbol not found in flat namespace '_mallctl'

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install.
Error: 
Something went wrong installing the "sharp" module

dlopen(/Users/xx/xx/xx/xx/xxx/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node, 0x0001): symbol not found in flat namespace '_mallctl'
Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/xxx/GoldenCat/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/xxx/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn react-native generate-bootsplash splash/splash.png --background=FFFFFF --platforms=android,ios --logo-width=150  --assets-output=assets --flavor=main

### Library version

5.2.1

### Environment info

```shell
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 268.89 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.5.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.11.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11090377
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /Users/dphamanh/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
yarn react-native generate-bootsplash splash/splash.png --background=FFFFFF --platforms=android,ios --logo-width=150  --assets-output=assets --flavor=main
```

**Comment by zoontek** [comment]
Did you tried those?

> Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
>
> Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"

**Comment by dungpasoftware** [comment]
Yes, I did but it still returns this error
After running this command, it will install the latest Sharp version
`"sharp": "^0.33.1",`

**Comment by dungpasoftware** [comment]
I tried to do it in another Mac M1, and it's working, so I think the problem is from my computer environment.

**Comment by zoontek** [comment]
Consider opening an issue on the sharp repository too.

How is node installed on your computer / which version? Which package manager are you using / which version?
