### ISSUE TITLE
Can I use windowSplashScreenBehaviour?

### ISSUE THREAD

**Issue by dkahdwk** [zoontek/react-native-bootsplash#527]
### Why it is needed?

I want app icon will be displayed and the bootsplash image will be exposed when running the Android app.
So Android 12 and later models, the app icon can be displayed on splash through the windowSplashScreenBehaviour attribute, is it also possible in this library?

(reference: https://developer.android.com/reference/android/R.attr#windowSplashScreenBehavior)

**Comment by zoontek** [comment]
I guess yes, but there's no interest in supporting it as it would result in a different behavior than iOS / Web.

**Comment by dkahdwk** [comment]
@zoontek 
Thank you for your kind reply!
As a developer, I appreciate this library.

I'm sorry, but can I ask you one more question?
I want to specify a splash like that image in an Android environment.
However, due to the Android splash policy, it looks like it is cut into a circle and comes out properly.
Can't you solve this problem?
![스크린샷 2024-01-02 오후 5 41 03](https://github.com/zoontek/react-native-bootsplash/assets/56759331/63c983c0-ce45-45a2-bbea-3a6b6e2b8c5b)

**Comment by zoontek** [comment]
Unfortunately, no.

You have to make it in the rounded mask, there's no way for this library to do override this as the splash screen starts **before** your app (handled by the system)

**Comment by dkahdwk** [comment]
@zoontek 
Thank you for your quick response.
Have a great day!
