### ISSUE TITLE
Manual `hide` functionality when using `useHideAnimation`

### ISSUE THREAD

**Issue by kyle-belle** [zoontek/react-native-bootsplash#528]
### Why it is needed?

Currently I don't have a way to hide the animated bootsplash only after load. it automatically hides on its own. When using the regular bootsplash i can call `hide` when i want which has been helpful for my use case. I'd really like to be able to call hide manually for the animated version. also react-navigation's initialization causes the animation to lag/hang and i am not able to delay it until `onReady`

### Code sample

```js
const {container, logo, hide /*, brand */} = BootSplash.useHideAnimation({
...
})

useEffect(() => {
  isReady && hide();
}, [isReady]);
```

**Comment by kyle-belle** [comment]
I kinda get around it by having the `visible` state default to null then then only showing the animated bootSplash (setting visible to true) when the onReady is called

```ts
const [bootSplashVisible, setBootSplashVisible] = useState<boolean | null>(
    null
  );

useEffect(() => {
    SetNavBarColor(bootSplashVisible !== false? 'transparent' : isDarkMode ? '#242424' : '#FFFFFF', !isDarkMode, true);
  }, [isDarkMode, bootSplashVisible]);

...

<StatusBar translucent={bootSplashVisible !== false} backgroundColor={bootSplashVisible !== false ? 'transparent' : isDarkMode ? '#242424' : '#FFFFFF' }
 barStyle={isDarkMode ? 'light-content' : 'dark-content'} />

<NavigationContainer
    onReady={() => {
      setBootSplashVisible(true); 
      // void BootSplash.hide({fade: true});
    }}
}}>
   <MainNavigator />
</NavigationContainer>

{bootSplashVisible && (
   <AnimatedBootSplash
      onAnimationEnd={() => {
         setBootSplashVisible(false);
      }}
   />
 )}

**Comment by zoontek** [comment]
This is a good idea, but having a `hide` function to call is actually a breaking change as we will need to fire it.

What do you think about this instead?

```tsx
// ready is a prop and handled by the parent. default to true (auto hide)
const { container, logo } = BootSplash.useHideAnimation({
  ready: isReady,
});
```

**Comment by kyle-belle** [comment]
> This is a good idea, but having a `hide` function to call is actually a breaking change as we will need to fire it.
> 
> What do you think about this instead?
> 
> ```tsx
> // ready is a prop and handled by the parent. default to true (auto hide)
> const { container, logo } = BootSplash.useHideAnimation({
>   ready: isReady,
> });
> ```

Hi. Yeah i also think this would be fine.

**Comment by zoontek** [comment]
After a bit if reflexion, it appears that this is just adding additional confusion, and it would be clearer with a TS union:

```tsx
const [bootSplashState, setBootSplashState] = useState<
  "visible" | "hiding" | "hidden"
>(null);

const barColor =
  bootSplashState === "hidden"
    ? isDarkMode
      ? "#242424"
      : "#FFFFFF"
    : "transparent";

useEffect(() => {
  SetNavBarColor(barColor, !isDarkMode, true);
}, [barColor, isDarkMode]);

// ...

return (
  <>
    <StatusBar
      translucent={bootSplashState !== "hidden"}
      barStyle={isDarkMode ? "light-content" : "dark-content"}
      backgroundColor={barColor}
    />

    <NavigationContainer
      onReady={() => {
        setBootSplashState("hiding");
      }}
    >
      <MainNavigator />
    </NavigationContainer>

    {bootSplashState === "hiding" && (
      <AnimatedBootSplash
        onAnimationEnd={() => {
          setBootSplashState("hidden");
        }}
      />
    )}
  </>
);
```

**Comment by maksim-romanov** [comment]
You can hide splash screen manually call start animation function
