### ISSUE TITLE
Discord for chatting about the library and problems

### ISSUE THREAD

**Issue by VilleMiekkoja** [zoontek/react-native-bootsplash#529]
### Why it is needed?

Chat brings more publicity to the library and also brings the user of the library together. It can give us peer help and the maintainer is not the only one who has to answer to the questions. It also lowers the threshold for asking help, as currently there's quite a big threshold for discussion as you need to provide lot of details and a fully reproducable code example. It would also contribute to the FAQ section, as it would be easier to find out what questions are asked most often, and what are the most common pitfalls and problems.

### Possible implementation

Just create discord server, does not require much

**Comment by zoontek** [comment]
Hi 👋

I'm not a fan of Discord, since it's another tool / channel to find information, and it's not easily searchable. What would you think of using GitHub discussions instead? With multiple options, like https://github.com/urql-graphql/urql/discussions/new/choose

**Comment by VilleMiekkoja** [comment]
> Hi 👋
> 
> I'm not a fan of Discord, since it's another tool / channel to find information, and it's not easily searchable. What would you think of using GitHub discussions instead? With multiple options, like https://github.com/urql-graphql/urql/discussions/new/choose

Github discussions could work as well, it would be an improvement for sure 👍
