### ISSUE TITLE
Do you support GIF format or dynamic effect?

### ISSUE THREAD

**Issue by suwu150** [zoontek/react-native-bootsplash#53]
Do you support GIF format or dynamic effect?

**Comment by zoontek** [comment]
@suwu150 When the JS bundle is loaded and parsed, you can use animate your can copy and splash screen content with `Animated`. See the example: https://github.com/zoontek/react-native-bootsplash/blob/master/example/App.js

After, that, use your imagination: a Netflix-like logo intro, Twitter-like logo intro, make it glowing during your app bootstrapping (network requests), use Lottie to make a kick-ass animation with After Effect… the choice is yours :)

**Comment by pratikdonda** [comment]
@zoontek

**Comment by pratikdonda** [comment]
> @suwu150 When the JS bundle is loaded and parsed, you can copy your splash screen content style and animate it with `Animated` (it's only an option). See the example: https://github.com/zoontek/react-native-bootsplash/blob/master/example/App.js
> 
> But use your imagination: a Netflix-like logo intro, Twitter-like logo intro, make it glowing during your app bootstrapping (network requests), use Lottie to make a kick-ass animation with After Effect… the choice is yours 🙂

Link is not found here, Can you please update accordingly?

**Comment by zoontek** [comment]
https://github.com/zoontek/react-native-bootsplash/blob/master/example/App.tsx

**Comment by pratikdonda** [comment]
> https://github.com/zoontek/react-native-bootsplash/blob/master/example/App.tsx

I would like to display GIF image in splash screen can you suggest me for same?
