### ISSUE TITLE
image splash not config for full screen 

### ISSUE THREAD

**Issue by phamhieu1412** [zoontek/react-native-bootsplash#533]
### Why it is needed?

my app has image splash full screen, include icon and background image, but react-native-splash has config for only icon. This is issue??
react-native 0.73.2
react-native-bootsplash: 5.2.2

this is my splash before
![launch_screen](https://github.com/zoontek/react-native-bootsplash/assets/48906710/6a0e6773-ed9c-467a-befd-d22a23613dfb)

Tks for help!!

**Comment by zoontek** [comment]
https://github.com/zoontek/react-native-bootsplash/issues?q=is%3Aissue+Full+Screen
