### ISSUE TITLE
New Issue - Dark background does not work anymore

### ISSUE THREAD

**Issue by AlixH** [zoontek/react-native-bootsplash#534]
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

bootsplash dark background colors is not working anymore
In dark theme, the background stays white

### Library version

5.3.0

### Environment info

```shell
System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 72.50 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Set dark background color in the command line generator
2. Launch the app in dark mode
3. Notice it stays white or at least does not use color specified

### Reproducible sample code

```js
TBD
```

**Comment by zoontek** [comment]
@AlixH On which platform? Did you correctly drag and drop the generated `Colors.xcassets` (on iOS)?

**Comment by AlixH** [comment]
It's on iOS sorry. Is this some new step for the new version ? I am not doing anything manually, I generate the splash screen on my CI before deploying

**Comment by zoontek** [comment]
This step is here since the dark mode is supported (v5)

**Comment by AlixH** [comment]
> This step is here since the dark mode is supported (v5.0.0)

Weird because it was working with 5.0.4. I upgraded to 5.3.0 because I had the caching issue.

**Comment by zoontek** [comment]
@AlixH Probably that you did it at the time, and overridden your `project.pbxproj` without keeping it when updating.

**Comment by AlixH** [comment]
You are right, I just dragged and drop the Colors.xcasset into Xcode and it got added to the .pbxproj. Was missing 🤔 
Thanks a lot again for this library and your quick answers (We have a license :D)
