### ISSUE TITLE
Unusual ghosting effect when going in and out of the app

### ISSUE THREAD

**Issue by 8BallBomBom** [zoontek/react-native-bootsplash#535]
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Not exactly sure of the cause as i haven't looked deeply yet.
But i can say the issue does not exist when this library is not being used.
When going in and out of the app you'll see a weird ghosting effect on the left of the screen.
Haven't tested with any other devices other than what i currently have on hand which is a Galaxy S9.

### Library version

5.3.0

### Environment info

```shell
System:
  OS: Linux 6.6 Fedora Linux 39 (KDE Plasma)
  CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Memory: 19.34 GB / 31.27 GB
  Shell:
    version: 5.2.26
    path: /bin/bash
Binaries:
  Node:
    version: 18.18.0
    path: ~/.nvm/versions/node/v18.18.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.18.0/bin/yarn
  npm:
    version: 10.3.0
    path: ~/.nvm/versions/node/v18.18.0/bin/npm
  Watchman:
    version: 0.0.0
    path: /usr/bin/watchman
SDKs:
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 33.0.1
      - 34.0.0
    System Images:
      - android-26 | Google Play Intel x86 Atom
      - android-27 | Google Play Intel x86 Atom
      - android-28 | Google Play Intel x86_64 Atom
      - android-29 | Google Play Intel x86_64 Atom
      - android-30 | Google Play Intel x86_64 Atom
      - android-31 | Google Play Intel x86_64 Atom
      - android-33 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Steps to reproduce

1. Create a new RN app, basic template, currently RN 0.73.2
2. Go through the basic integration steps of this library.
3. Run the app and experience the issue when going in and out of the app.
4. Most likely a Samsung issue as i haven't seen the same on an emulated device.

Easier to see a preview rather than just describe.
Doesn't happen with other apps and doesn't happen with a clean app without this library.

### Without this library

https://github.com/zoontek/react-native-bootsplash/assets/3690196/9df2a939-8bcd-4d5a-b530-2c9ae1c70f34

### With this library

https://github.com/zoontek/react-native-bootsplash/assets/3690196/3c880a54-729f-4672-9e42-e99aabb38e0e

**Comment by zoontek** [comment]
@8BallBomBom Is it running Android 12 or 13? Because Samsung has a very bad implementation of the Android SplashScreen API on Android 12 (OneUI 4), this library already include hacks specific to this OS / version (see https://github.com/zoontek/react-native-bootsplash/releases/tag/5.1.0)

**Comment by 8BallBomBom** [comment]
Ahhh yes I was looking at that but no, it is running Android 10 with an old version of OneUI v2.5 far as I can tell 🤔

**Comment by Qudaeo** [comment]
I have same issue on android emulator & samsung a13

**Comment by 8BallBomBom** [comment]
Took a while to track this one down but it appears to occur due to the following being used with the BootSplash theme.
```xml
<item name="android:windowIsTranslucent">true</item>
```
Forgot why i was using that, think it might have been to hide the splash theme when the keyboard appears 😅

**Comment by zoontek** [comment]
@8BallBomBom A lot of people are recommending this "solution" to avoid the "double splash screen issue" and use a full screen image, as they are not happy with the [SplashScreen API](https://developer.android.com/develop/ui/views/launch/splash-screen) limitations.

Except it's stupid: it's a hack to avoid showing the system splash screen and delay the app opening response, which defeat the whole point of the SplashScreen API in the first place. I'm trying [to fight against](https://github.com/zoontek/react-native-bootsplash/issues/496#issuecomment-1913263993) and hide mention of it, but… 😅

**Comment by 8BallBomBom** [comment]
No worries, understandable and thanks for the example, makes perfect sense 👍🏻 
Are there any plans to have something in place which allows changing the Splash Screen after the app has been launched?
Essentially as it stands if you show the keyboard or you change from portrait to landscape then you can see the Splash Screen under the app for a brief moment, same as if you have a screen without a background.

**Comment by zoontek** [comment]
@8BallBomBom This occurs because you probably set the theme on `application`. It's more bulletproof to keep `@style/AppTheme` on `application` and apply `@style/BootTheme` on `activity` ([I updated the README some time ago](https://github.com/zoontek/react-native-bootsplash?tab=readme-ov-file#android-1)).

Do that + update to the latest version, no issue should occur anymore.
