### ISSUE TITLE
When the screen is full, the picture stretches and deforms, but there is no adaption

### ISSUE THREAD

**Issue by meiqi1992** [zoontek/react-native-bootsplash#54]
### 💻 My environment

- react-native-bootsplash version:
- react-native version:
- Platform: ios / android / both
- OS version: ?
- Device: brand + model
- Simulator: yes / no
- Android Studio version: ?
- Android buildToolsVersion: ?
- Xcode version: ?

### 🕵️‍♂️ Reproducing the issue

When the screen is full, the picture stretches and deforms, but there is no adaption，is it can scale?

### 🤞Solution

Do you know what needs to be done to address this issue?
Ideally, provide a pull request with a fix.

**Comment by zoontek** [comment]
@meiqi1992 Please fill the template (OS, version, etc). Provides your `bootsplash.xml`. Maybe add a screenshot.
