### ISSUE TITLE
iOS - The application has terminated unexpectedly

### ISSUE THREAD

**Issue by DaniilSerga** [zoontek/react-native-bootsplash#544]
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

## Problem 
I've faced an interesting behavior of the splash screen. At first it seemed to work absolutely normal on android, but as soon as I moved to testing the splash screen on an iOS simulator I got an exception, saying that 

> **the application has terminated unexpectedly**

I followed all the instructions provided at the docs and added all the necessary lines of code (also the import) in my AppDelegate.mm file.

## Solution
The **reason** of that behavior appeared to be an **unchecked "target membership" checkbox at created BootSplash.storyboard in xcode**. Once I set this checkbox to target my current project - it worked fine with no complains.

### Library version

5.4.0

### Environment info

```shell
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M1
  Memory: 152.09 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.01.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-33 | Intel x86_64 Atom
      - android-33 | Google APIs ATD Intel x86_64 Atom
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. install the library with yarn
2. create splash screen with yarn react-native generate-bootsplash
3. go to ios folder and run `pod install`
4. start the project with yarn start, select iOS
5. the application crashes

**Comment by zoontek** [comment]
I added this in the latest release, using `@expo/config-plugins`, but as there's no documentation for their `XcodeUtils`, I forgot to set `isBuildFile: true`, which appear to do that. Fixed in [5.4.1](https://github.com/zoontek/react-native-bootsplash/releases/tag/5.4.1).
