### ISSUE TITLE
Apple Store will force using storyboard instead of xib by April 2020

### ISSUE THREAD

**Issue by sebinq** [zoontek/react-native-bootsplash#55]
Hello there!

As quoted in [Apple Store news](https://developer.apple.com/news/?id=01132020b):

> As announced at WWDC19, starting April 2020, apps submitted to the App Store must use an Xcode storyboard to provide the app’s launch screen and must have an interface that supports any display size.

This lib is currently not supporting Storyboard am I right?

**Comment by zoontek** [comment]
@sebinq Hello! Not yet indeed. We need to find a new way to achieve the same result with a storyboard file and deprecate the xib support.

**Comment by igor-bv** [comment]
Hi there! @zoontek I'm not totally sure if my problem related to current issue, but I think it is so...
I've intialized latest rn app(0.61.5) from scratch, and trying to setup splash-screen for ios as described in docs, but in case if I remove this lines from `Info.plist`: 
```
<key>UILaunchStoryboardName</key>
<string>LaunchScreen</string>
```
I'll receive the issue described here https://medium.com/codespace69/os-app-does-not-take-full-screen-on-iphones-602814e8dd54

And if I'll apply the fix provided in the link above - this .storyboard/.xib(I tried to create both) splash screen shows and hides automatically, so in result I don't have any control on when to hide the splash screen(I need to delay hiding a bit).

Could you help in understanding this situation/problem please?

**Comment by zoontek** [comment]
@sebinq It's available in the new version: https://github.com/zoontek/react-native-bootsplash/releases/tag/2.0.0 🤘
