### ISSUE TITLE
Updating README for iOS

### ISSUE THREAD

**Issue by vaibhavpadalia** [zoontek/react-native-bootsplash#550]
### Why it is needed?

Empty black screen appears before splash

### Possible implementation

Add the step for updating `Launch Screen File` as `BootSplash.storyboard`

![image](https://github.com/zoontek/react-native-bootsplash/assets/23230806/f686b1ae-ab30-41dc-9683-572b316430ea)

**Comment by zoontek** [comment]
This is not needed with the latest version, and the README is versioned with tags.
