### ISSUE TITLE
Splash Screen Reappears During Screen Transitions on Android

### ISSUE THREAD

**Issue by Protino** [zoontek/react-native-bootsplash#552]
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Splash screen re-appears in between screen transitions on Android when the app is opened from a background state (where the activity was destroyed by the system or the user locale was changed). We can simulate this behavior by turning on `Don't keep activities` in developer options or by changing the font or display size of the device and re-open the app.

Recording - 
![Screen Recording 2024-03-04 at 4 38 10 PM](https://github.com/zoontek/react-native-bootsplash/assets/8778375/6fbca68f-0073-45a0-9647-eabb05a4532f)

### Library version

5.4.1

### Environment info

```shell
System:
  OS: macOS 14.2.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 93.39 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.0
    path: ~/.nvm/versions/node/v20.5.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v20.5.0/bin/yarn
  npm:
    version: 9.8.0
    path: ~/.nvm/versions/node/v20.5.0/bin/npm
  Watchman:
    version: 2023.11.27.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/<redacted>/.gem/ruby/3.2.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "28"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-23 | Google APIs ARM 64 v8a
      - android-24 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/<redacted>/.rubies/ruby-3.2.2/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. Clone the reproducible repo given below
2. Setup and run on Android emulator
3. Enable 'Don't keep activities' in developer options
4. Open App
5. Press Home
6. Open the App again and switch screens

### Reproducible sample code

```js
https://github.com/Protino/splash-flash-repro
```

**Comment by Protino** [comment]
I can see that there are a few static variables in `RNBootSplashModuleImpl` these remain as is upon activity re-creation and re-initialization is not done because of the check on `if (mThemeResId != -1) {`

**Comment by zoontek** [comment]
Legitimate question, but: what does it solves in real life? Excepted if you enable `Don't keep activities`, which is in a hidden menu of your phone, you will never met this kind of behaviour.

The fix should implement [`onHostDestroy`](https://reactnative.dev/docs/native-modules-android#listening-to-lifecycle-events) instead.

**Comment by Protino** [comment]
No no, that option is just debugging. Real life scenario is as follow, app is in background, system kills it to recoup resources and when user re-opens the app  this behaviour will occur. 
https://developer.android.com/guide/components/activities/activity-lifecycle#asem

Can't implement onHostDestroy for RNBootSplash since it is not a react native module. Just have to make it [lifecycle aware](https://developer.android.com/topic/libraries/architecture/lifecycle) will share a new PR.

**Comment by zoontek** [comment]
@Protino When this occur, the app will "start" again. Meaning that the `Activity` will be recreating, react native modules instances recreated, etc.

**Comment by Protino** [comment]
When app restarts, the activity is recreated but other instances are not and in this case it is the RNBootSplashModuleImpl instance which holds data in static variables and these hold old values. So when init is called it is returned without initializing.

We've this occurring on one of our production app. You can reproduce this by cloning the repro i mentioned. Run it, press home button, go to settings and change font size and reopen the app from background. (Another real life scenario would be keep the app in background state and open other resource heavy apps like games etc.. and re-open the app, this would be tedious to repro).

Yes i agree that re-initializing would be terrible if dialog is already shown, but as far as i have gone through the source code this won't occur, init is only called on Activity creation as recommended and we de-initialize only on activity destroy.

**Comment by zoontek** [comment]
@Protino Did you tried with `onHostDestroy`?

**Comment by Protino** [comment]
Yes, PR updated long back - https://github.com/zoontek/react-native-bootsplash/pull/553

**Comment by zoontek** [comment]
Thanks @Protino, it will be in the next release.

**Comment by zoontek** [comment]
@Protino This is available in the next RC: https://github.com/zoontek/react-native-bootsplash/pull/563

**Comment by zoontek** [comment]
Available in [5.5.0](https://github.com/zoontek/react-native-bootsplash/releases/tag/5.5.0)

**Comment by samarthskadam-lokal** [comment]
@zoontek I’m facing an issue during screen transitions where the splash screen briefly appears. Do you know how to fix this? This started happening after enabling the new architecture

**Comment by valesh-gosats** [comment]
@samarthskadam-lokal Facing the same issue. Have you found a solution?
