### ISSUE TITLE
iOS error during debug scheme starting

### ISSUE THREAD

**Issue by LucasHimelfarb** [zoontek/react-native-bootsplash#557]
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

<img width="432" alt="Screenshot 2024-03-14 at 4 58 57 PM" src="https://github.com/zoontek/react-native-bootsplash/assets/46998551/4a508c4f-b0a3-464c-a8f4-a1a8900d94d9">

### Library version

5.4.1

### Environment info

```shell
System:
  OS: macOS 14.4
  CPU: (8) arm64 Apple M1
  Memory: 193.25 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v20.11.0/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /Users/lucashimelfarb/.jenv/shims/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.5
    wanted: 0.73.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
This happened when try to run react native app on iOS simulator
```

**Comment by zoontek** [comment]
@LucasHimelfarb Reproduction please, or I will close this.

**Comment by LucasHimelfarb** [comment]
During code debugging, I found that the bootSplash screen does not link to the project correctly when the following pods are present:

GTMSessionFetcher
GoogleDataTransport
GoogleMLKit
GoogleToolboxForMac
GoogleUtilities
GoogleUtilitiesComponents
MLImage
MLKitCommon
MLKitTextRecognition
MLKitTextRecognitionCommon
MLKitTextRecognitionJapanese
MLKitTextRecognitionKorean
MLKitVision
PromisesObjC
RNSelphidPluginModule
nanopb
zipzap

After removing the above pods, the project started functioning again... In my case, it's crucial to have the above installed, so I'm going to give up on using bootSplash. Thanks for your quick response anyway
