### ISSUE TITLE
How can i show code push progress bar in splash screen?

### ISSUE THREAD

**Issue by w3company-leo** [zoontek/react-native-bootsplash#558]
### Why it is needed?

I want to show code push progress bar in splash screen with out BootSplash.hide(). 
Because after update finished, white screen is appear in android so user experience not good

How can i show progress bar before call BootSplash.hide() ??  
I can't find this information

**Comment by zoontek** [comment]
Wait for a screen with your progress bar to be mounted and hide the splash screen.
