### ISSUE TITLE
Output/Document need to manually create missing images

### ISSUE THREAD

**Issue by nmehlei** [zoontek/react-native-bootsplash#560]
### Why it is needed?

First of all, great work on creating such a useful library. Kudos!

For a new implementation, I just added react-native-bootsplash and created the images with the included command-line tool. This leads to the following error:

`error: resource drawable/bootsplash_brand (aka net.mycompany.app.testing:drawable/bootsplash_brand) not found.`

As I understand it, the brand images are excluded from the generation of the free non-licenses variant. Therefore I assume that the error is just because the tool does not generate all mandatory images.

I completely understand the motivation and need for moving advanced functionality behind a paywall. Yet I would argue that it would be a better user experience to let the user know and/or document it what exactly still needs to be done manually with the free variant.

### Possible implementation

1) Either create all images necessitated by a basic set-up (with advanced features as opt-in), maybe with an overlay (e.g. "Unlicenses" text over the generated image) to show what kind of image is needed, yet therefore still forcing the user to generate it oneself.

OR

2) Add basic documentation on how Bootsplash expects the images to be manually created (size, format, content placement, etc.)

**Comment by zoontek** [comment]
@nmehlei Hello! It people wants to know how to size the brand images, they can look to the Android documentation. If they don't want to, they could pay. This is not a huge amount, especially for companies 🙂
