### ISSUE TITLE
Adding android:windowBackground causes it to appear after original splash hides

### ISSUE THREAD

**Issue by endrits079** [zoontek/react-native-bootsplash#570]
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

I wanted to add a background image to my splash screen, on IOS added it without any issue, although on android
inside drawable I added splash_background.xml with this content

```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <item>
        <bitmap
            android:gravity="fill"
            android:src="@drawable/splash" />
    </item>
</layer-list>
```

and updated my styles.xml  to include the splash_background

<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>

     <style name="BootTheme" parent="Theme.BootSplash">
        <item name="bootSplashBackground">@color/bootsplash_background</item>
        <item name="bootSplashLogo">@drawable/bootsplash_logo</item>
        <item name="android:windowBackground">@drawable/splash_background</item> //added this
        <item name="postBootSplashTheme">@style/AppTheme</item>
    </style>

</resources>

but instead of showing both at the same it shows the original splash first and after hiding it shows my windowBackground

### Library version

5.4.1

### Environment info

```shell
System:
  OS: macOS 14.2
  CPU: (12) arm64 Apple M2 Max
  Memory: 155.81 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: /usr/local/bin/node
  Yarn:
    version: 4.0.2
    path: ~/.nvm/versions/node/v20.10.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/endrit.shabani/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. Create an xml for your splash image in drawable with this content
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <item>
        <bitmap
            android:gravity="fill"
            android:src="@drawable/splash" />
    </item>
</layer-list>
```
(make sure to replace splash with your image name)
2. Reference it in styles.xml

<item name="android:windowBackground">@drawable/splash_background</item>

### Reproducible sample code

```js
Clone this repo which is created on top of the example 
https://github.com/endrits079/rn-bootsplash-android

Run it on android

It has been tested in device running Android 13 
And emulators running both Android 13 and 14
```

**Comment by zoontek** [comment]
Then don't add it. It's not supported anyway.

**Comment by endrits079** [comment]
@zoontek it is not a duplicate tho, is there another way then to add a background image?

**Comment by zoontek** [comment]
@endrits079 It is. Read the duplicates for your answer: https://github.com/zoontek/react-native-bootsplash/issues?q=is%3Aissue+background+image
