### ISSUE TITLE
Small icon size on Samsung devices with Android 12

### ISSUE THREAD

**Issue by Navipro70** [zoontek/react-native-bootsplash#577]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [ ] I checked for possible duplicate issues, with possible answers.

### Bug summary

On some samsung devices with android 12 splash screen icon is ~5 times smaller compared to other Android/IOS devices.

Splash Icon on Samsung device from list of devices enumerated in Environment info:
![BrokenSamsungSplash](https://github.com/zoontek/react-native-bootsplash/assets/60893275/266be229-61d4-4a6c-afb6-d5dd362d400d)

Splash Icon on Nexus 4:
![Screenshot_1714475206](https://github.com/zoontek/react-native-bootsplash/assets/60893275/84a78781-4749-4f17-8884-f1630e941ee5)

### Library version

5.4.0

### Environment info

```shell
Reproducible devices:
Samsung Galaxy S22 Ultra Android 12.0
Samsung Galaxy S22 Android v12.0
Samsung Galaxy S21 Android v12.0
Samsung Galaxy S20 Android v12.0
```

### Steps to reproduce

1. Generate splash screen with bootsplash command: `yarn react-native generate-bootsplash pathToLogo --background=E52E6B --logo-width=142`
2. Run any device from Environment info devices list

### Reproducible sample code

```js
`yarn react-native generate-bootsplash pathToLogo --background=E52E6B --logo-width=142`
```

**Comment by zoontek** [comment]
@Navipro70 Hey! You tick the "I checked for possible duplicate issues, with possible answers" but didn't.

https://github.com/zoontek/react-native-bootsplash/issues/466

There's nothing we can do as the issue occurs on system thread (It's an issue with OneUI v4, Samsung fixed it only on OneUI v5)

**Comment by Navipro70** [comment]
@zoontek Hello!

I've already checked issue above, but the title is wrong. In my case logo is not half sized, it's ~5 times smaller than on another devices.

And also I didn't understand, what solution was applied to the https://github.com/zoontek/react-native-bootsplash/issues/466? Can you please provide actual information about that problem and why we can't fix it, because other apps have normal icon size on Samsung with Android 12
