### ISSUE TITLE
[Expo - iOS] react-native 0.74.3 breaks the splash screen

### ISSUE THREAD

**Issue by antFrancon** [zoontek/react-native-bootsplash#590]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

After upgrading React Native to version `0.74.3`, the splash screen feature is broken on iOS.

Specifically:
- The native splash screen hides too early.
- The JS splash screen (the one that hides with `useHideAnimation`) no longer hides.

This issue may be related to this commit in the last RN release: [Support customizeRootView from RCTRootViewFactory](https://github.com/facebook/react-native/commit/d9e42785f386326b98b189599a9efc3e6dc902b9).

### Library version

5.5.3

### Environment info

```shell
// Old architecture
"react": "18.2.0",
"react-native": "0.74.2",
"react-native-bootsplash": "^5.5.3",

// Dev
"@react-native/babel-preset": "0.74.84",
"@react-native/eslint-config": "0.74.84",
"@react-native/metro-config": "0.74.84",
"@react-native/typescript-config": "0.74.84",
```

### Steps to reproduce

1. Run the example with RN 0.74.2 --> ✅
2. Upgrade to RN 0.74.3 --> ❌

I tested both in dev and release mode.

### Reproducible sample code

Run the example including the `useHideAnimation` part.

**Comment by zoontek** [comment]
@antFrancon Are you using Expo?

**Comment by antFrancon** [comment]
> @antFrancon Are you using Expo?

Oh yes, of course, I forgot that. I am using Expo Bare Workflow.
So I did the native IOS setup

```swift
- (void)customizeRootView:(RCTRootView *)rootView {
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // ⬅️ initialize the splash screen
}
```

```shell
"expo": "51.0.15",
```

**Comment by zoontek** [comment]
Yeah, Expo fixed compat issues with react-native-bootsplash, I have to ship v6 this weekend

**Comment by zoontek** [comment]
@antFrancon After investigation, it appears that if the new expo release fix the issue with `customizeRootView`, it also introduces a small regression with the internal splash screen module.

You have to call [`preventAutoHideAsync`](https://docs.expo.dev/versions/latest/sdk/splash-screen/#splashscreenpreventautohideasync) to prevent Expo from hiding bootsplash, even if `expo-splash-screen` is not installed / linked.

**Comment by Kudo** [comment]
not sure whether https://github.com/expo/expo/pull/30245 helps for the issue?

**Comment by zoontek** [comment]
@Kudo Yes, this is what missing! I though it was already supported, my bad.

**Comment by Kudo** [comment]
it's my bad that to miss i have copied code inside expo. the fix is merged and should be published next week.

> Also, if called (or if expo-splash-screen is not installed), expo should not hide the added loadingView (UIView*).

could you elaborate this case more? or a repro would be much appreciated. i tried the following stack and it doesn't appear problems. maybe i miss anything.
-  `yarn create expo-app -t blank@@sdk-51 sdk51`
-  without expo-dev-client / expo-updates / expo-splash-screen
- `yarn add react-native-bootsplash@^6.0.0-beta.9`
- apply patch from https://github.com/expo/expo/pull/30245
- change `RNBootSplash.initWithStoryboard` call from createRootViewWithBridge to customizeRootView
- tried both debug and release build

**Comment by zoontek** [comment]
> could you elaborate this case more? or a repro would be much appreciated. i tried the following stack and it doesn't appear problems. maybe i miss anything.

I just didn't think too much before talking, the issue was that it's not called, not that expo remove the UIView 😅

This will fix it! Thanks a lot @Kudo

**Comment by zoontek** [comment]
Expo `51.0.20` supports `customizeRootView`, the latest beta includes the fix: https://github.com/zoontek/react-native-bootsplash/pull/578

Everything is finally ready for v6 stable 😮‍💨
