### ISSUE TITLE
App Development build fails on EAS

### ISSUE THREAD

**Issue by Code-Victor** [zoontek/react-native-bootsplash#595]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

When I try to build my app, I get this error
```bash
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     com.examcrush.client.app-mergeDebugResources-63:/values/values.xml:5152: error: resource drawable/bootsplash_logo (aka com.examcrush.client:drawable/bootsplash_logo) not found.
     com.examcrush.client.app-mergeDebugResources-63:/values/values.xml:5152: error: resource drawable/bootsplash_logo (aka com.examcrush.client:drawable/bootsplash_logo) not found.
     error: failed linking references.
```
Even though, I'm specifying the correct path in my app.json

### Library version

^6.0.0

### Environment info

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Memory: 3.50 GB / 19.85 GB
Binaries:
  Node:
    version: 18.19.0
    path: ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
  Yarn:
    version: 3.6.4
    path: ~\scoop\apps\yarn\current\bin\yarn.CMD
  npm:
    version: 10.2.3
    path: ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowAllTrustedApps: Disabled
    Versions:
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.7.34202.233 (Visual Studio Community 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. install package
2. add to `package.json`
 ```json 
"expo": {
    "autolinking": {
      "exclude": [
        "expo-splash-screen"
      ]
    }
  }
```
3.  Generate splash screen 
```bash
npx react-native generate-bootsplash ./src/assets/images/logo.svg --background=#110412 --platforms=android,ios --assets-output=./src/assets/splash
```
4.  Update app.json
```json
  [
        "react-native-bootsplash",
        {
          "assetsDir": "./src/assets/splash"
        }
 ],
```

### Reproducible sample code

```js
I didn't add any extra code yet(I need the dev build to do that).
```

**Comment by zoontek** [comment]
`assetsDir` is likely not targetting the correct directory. Could you publish a screenshot of your file tree (`src/assets/splash` deployed)?

**Comment by Code-Victor** [comment]
Thanks for the Quick reply,
Here is the screenshot
![image](https://github.com/user-attachments/assets/3f6f7436-56ec-4b11-b47e-1a79783c730b)
![image](https://github.com/user-attachments/assets/4823b35f-b091-4dee-a905-242cf1e73413)

**Comment by Code-Victor** [comment]
I just tried the `src/assets/splash` but it still doesn't work.

**Comment by zoontek** [comment]
I tried running `eas build` locally, and I had no issue. Did you ran the command in the CI? In this case, are you correctly commited your `src/assets/splash` directory?

<img width="1173" alt="Screenshot 2024-07-24 at 14 04 04" src="https://github.com/user-attachments/assets/7a1d5552-f6cc-4aad-bb7a-885400f07ab3">

**Comment by zoontek** [comment]
I tried it and it went well:

<img width="972" alt="Screenshot 2024-07-24 at 14 10 49" src="https://github.com/user-attachments/assets/f8e7e90a-7524-410c-b821-063b2831b4af">

<img width="1188" alt="Screenshot 2024-07-24 at 14 11 07" src="https://github.com/user-attachments/assets/8cac173a-7fff-416f-8fba-3e6819a74eef">

Try running `npx expo prebuild --clean --platform android` locally and check if the `bootsplash_logo` files are correctly copied in `android/app/src/main/res`.

**Comment by Code-Victor** [comment]
> I tried running `eas build` locally, and I had no issue. Did you ran the command in the CI? In this case, are you correctly commited your `src/assets/splash` directory?
> 
> <img alt="Screenshot 2024-07-24 at 14 04 04" width="1173" src="https://private-user-images.githubusercontent.com/1902323/351705934-7a1d5552-f6cc-4aad-bb7a-885400f07ab3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjMwNDQsIm5iZiI6MTcyMTgyMjc0NCwicGF0aCI6Ii8xOTAyMzIzLzM1MTcwNTkzNC03YTFkNTU1Mi1mNmNjLTRhYWQtYmI3YS04ODU0MDBmMDdhYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMTIwNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdmODI0ZGQzM2IwMWQzYjM2MDg5ZGYyNjViNmFkN2ExNTFlYTIzZTRmZDA5YzI1NjM4NThlMmE5OWFmMzE3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PfAeFoie5o_QarhoerAz7yJzR1iWz_836MGcF0AQvis">

I used the CLI and got an error.
![image](https://github.com/user-attachments/assets/a3ba46d0-5982-4232-b95a-c5aa23d69ab1)

**Comment by zoontek** [comment]
> Please, any idea what I'm doing wrong here?

Check if the `bootsplash_logo` files are correctly copied in `android/app/src/main/res/drawable-*` after your prebuild.

**Comment by Code-Victor** [comment]
I think they are correctly copied 
![image](https://github.com/user-attachments/assets/c31ca7ef-24f0-4bbd-9f91-a6ee253f687e)

**Comment by zoontek** [comment]
Not sure of what happen then, as ˋeas build` run a prebuild at first.

**Comment by Code-Victor** [comment]
OMG!!!
I feel like such a fool. Expo's prebuild documentation misled me.
In the **[Using EAS Build section](https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build)**, we were advised to add the `android` and `ios` folder in the `.gitignore` and `.easignore`.
This was the code they provided:
```
android/
ios/
```
It turns out this recursively checks through the projects and ignores any folder with the `android/` and `ios/`(soEAS never got my generated splash screen content) instead of just targeting the root `ios` and `android` folders. 
Here's my fix:
```diff
- android/
- ios/
+ /android
+ /ios
```
I was really lucky to find this out(Thank God vscode greys out `.gitignored ` files I wouldn't have noticed otherwise).

Thanks so much for your speedy response!
Awesome library overall👍🏾

**Comment by zoontek** [comment]
Good to know! Thanks for the PR on the Expo repo 🙏
