### ISSUE TITLE
Ability to specify whether the project is bare or expo 

### ISSUE THREAD

**Issue by vstatsura** [zoontek/react-native-bootsplash#597]
### Why it is needed?

I'm having a little problem. My project uses expo modules but is bare created via npx @react-native-community/cli. When generating resources for splash screen, a check is used to see if this project is an expo or not. When generating resources for splash screen, a check is used to see if this project is an expo or not. In my case (and I think many others) there are ios and android directories, and I expect the generated files to be placed in these directories, which is not the case now and I have to add them manually

### Possible implementation

Add an option to cli that will ignore the next line  `const { isExpo } = getExpoConfig(workingPath);` and set isExpo to false

`npx react-native generate-bootsplash --expo true`

**Comment by zoontek** [comment]
Available in [6.1.0](https://github.com/zoontek/react-native-bootsplash/releases/tag/6.1.0)
