### ISSUE TITLE
Does this work on RN 0.59?

### ISSUE THREAD

**Issue by kenvunz** [zoontek/react-native-bootsplash#6]
Hi,

Is there a hard dependency on RN 0.60? Or you have just been testing this on 0.60?

Cheers,
Ken

**Comment by MoOx** [comment]
No real hard dependency. But Android part rely on AndroidX so if you want to use it with RN 0.59-, you will need to use https://github.com/mikehardy/jetifier

**Comment by zoontek** [comment]
No as it relies on AndroidX.
You should use https://github.com/mikehardy/jetifier/blob/master/README.md#to-reverse-jetify--convert-node_modules-dependencies-to-support-libraries

**Comment by MoOx** [comment]
I confirm it works with 0.59, I just integrated this into my app :clap:!

**Comment by zoontek** [comment]
@kenvunz instructions has been addto the readme: https://github.com/zoontek/react-native-bootsplash/issues/7

**Comment by kenvunz** [comment]
Thanks for the quick response! 👍
