### ISSUE TITLE
After upgrading to v6, images aren't updating in native folders

### ISSUE THREAD

**Issue by SergiOnGit** [zoontek/react-native-bootsplash#600]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

After I upgraded to v6, yarn react-native generate-bootsplash creates files only in assets folder, not in native android and ios folders like:

android/app/src/main/res/drawable-mdpi/bootsplash_logo.png
android/app/src/main/res/drawable-hdpi/bootsplash_logo.png
android/app/src/main/res/drawable-xhdpi/bootsplash_logo.png
android/app/src/main/res/drawable-xxhdpi/bootsplash_logo.png
android/app/src/main/res/drawable-xxxhdpi/bootsplash_logo.png
android/app/src/main/AndroidManifest.xml
android/app/src/main/res/values/colors.xml
android/app/src/main/res/values/styles.xml

ios/YourApp/BootSplash.storyboard
ios/YourApp/Colors.xcassets/BootSplashBackground-<hash>.colorset/Contents.json
ios/YourApp/Images.xcassets/BootSplashLogo-<hash>.imageset/Contents.json
ios/YourApp/Images.xcassets/BootSplashLogo-<hash>.imageset/logo-<hash>.png
ios/YourApp/Images.xcassets/BootSplashLogo-<hash>.imageset/logo-<hash>@2x.png
ios/YourApp/Images.xcassets/BootSplashLogo-<hash>.imageset/logo-<hash>@3x.png
ios/YourApp/Info.plist
ios/YourApp.xcodeproj/project.pbxproj

### Library version

6.1.0

### Environment info

```shell
System:
  OS: macOS 14.5
  CPU: (11) arm64 Apple M3 Pro
  Memory: 359.92 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn:
    version: 4.2.2
    path: ~/.nvm/versions/node/v20.11.0/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/warlock/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/warlock/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.4
    wanted: 0.74.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

yarn react-native generate-bootsplash ./resources/splash.png --platforms=android,ios --background=2273C8 --logo-width=150 --flavor=main --license-key=key --dark-background=1D62B6 --brand=./resources/jet-fitness-bottom-logo.png --brand-width=120

### Reproducible sample code

```js
yarn react-native generate-bootsplash ./resources/splash.png --platforms=android,ios --background=2273C8 --logo-width=150 --flavor=main --license-key=key --dark-background=1D62B6 --brand=./resources/jet-fitness-bottom-logo.png --brand-width=120
```

**Comment by zoontek** [comment]
@SergiOnGit Are you using expo / have expo dependency?

**Comment by SergiOnGit** [comment]
Using Expo in bare workflow

**Comment by zoontek** [comment]
Add `--project-type=bare`, otherwise if `expo` dependency exists it will follow expo assets generation flow (everything in `assets`, then copied on prebuild).

**Comment by SergiOnGit** [comment]
@zoontek Great! One more thing, now I noticed that generate command formats androidManifest.xml but also removes comments, would be great if you let us have comments there.

**Comment by zoontek** [comment]
I'm using expo plugin system for that, will see if we can swap to a XML parser that supports comments.
