### ISSUE TITLE
Android resource linking failed error: resource style/Theme.BootSplash

### ISSUE THREAD

**Issue by c-info** [zoontek/react-native-bootsplash#611]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     error: resource style/Theme.BootSplash (aka demo.dev:style/Theme.BootSplash) not found.
     demo.dev.app-mergeDebugResources-25:/values/values.xml:1513: error: style attribute 'attr/bootSplashBackground (aka demo.dev:attr/bootSplashBackground)' not found.
     demo.dev.app-mergeDebugResources-25:/values/values.xml:1514: error: style attribute 'attr/bootSplashLogo (aka demo.dev:attr/bootSplashLogo)' not found.
     demo.dev.app-mergeDebugResources-25:/values/values.xml:1515: error: style attribute 'attr/postBootSplashTheme (aka demo.dev:attr/postBootSplashTheme)' not found.
     error: failed linking references.

### Library version

6.1.1

### Environment info

```shell
System:
  OS: macOS 14.1.1
  CPU: (8) arm64 Apple M2
  Memory: 86.91 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.yarn/bin/yarn
  npm:
    version: 9.6.6
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "23"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-33 | Google Play ARM 64 v8a
      - android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.1
    wanted: 0.75.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

follow basic instructions

### Reproducible sample code

```js
-
```

**Comment by zoontek** [comment]
Cannot be reproduced with the given instructions.

**Comment by MelanieJourne** [comment]
@c-info Hi, I seems to have the same problem after upgrading to RN 0.73, have you find any solutions ?

**Comment by aliisajokinen** [comment]
I have the same problem. RN 0.74.5 & bootsplash 6.1.3 (migration done).

**Comment by LuongTruong** [comment]
hey mate I had the same issue. It is kinda weird but when I add the below code to `app/build.gradle`. The issue is gone
```
/* Auto linking */
autolinkLibrariesWithApp()
```

Please also remember to remove the below code if you build unsuccessfully with error "double PackageList"
```
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

**Comment by Inayat567** [comment]
add this to setting.gradle file:

    include ':react-native-bootsplash'
    project(':react-native-bootsplash').projectDir = new File(rootProject.projectDir, '../node_modules/react-native- 
    bootsplash/android')
    
add this to android/app/build.gradle file:
    
        implementation project(':react-native-bootsplash')

**Comment by torreant** [comment]
hello guys, 
I still have this issue, none of the above solutions worked for me.

RN: 0.75.5
library version: 6.3.3

Any hint?

**Comment by mzanini** [comment]
> hey mate I had the same issue. It is kinda weird but when I add the below code to `app/build.gradle`. The issue is gone
> 
> ```
> /* Auto linking */
> autolinkLibrariesWithApp()
> ```
> 
> Please also remember to remove the below code if you build unsuccessfully with error "double PackageList"
> 
> ```
> apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
> ```

You are totally right that autolinking step is needed. It's also included in the android example here: https://github.com/zoontek/react-native-bootsplash/blob/37be6884964e6d8eae120494b0c0d2c64ee49644/example/android/app/build.gradle#L54
