### ISSUE TITLE
App with `expo-router` automatically hides splash

### ISSUE THREAD

**Issue by ferretwithaberet** [zoontek/react-native-bootsplash#613]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

When using `expo-router`, this package's splash gets automatically hidden once the app loads.

### Library version

6.1.1

### Environment info

```shell
System:
  OS: Linux 6.10 EndeavourOS
  CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
  Memory: 6.48 GB / 15.06 GB
  Shell:
    version: 5.2.32
    path: /bin/bash
Binaries:
  Node:
    version: 20.10.0
    path: ~/.asdf/installs/nodejs/lts/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.asdf/installs/nodejs/lts/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman:
    version: 20240414.112832.0
    path: /usr/bin/watchman
SDKs:
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-34 | Google APIs Intel x86_64 Atom
      - android-34 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: AI-241.18034.62.2411.12071903
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.2.4
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. Create new expo app using the `create-expo-app` package;
2. Remove `expo-splashscreen` related code;
3. Add and configure `react-native-bootsplash`;
4. Start app, splash will automatically hide after app loads, without waiting for `BootSplash.hide()`.

### Reproducible sample code

https://github.com/ferretwithaberet/react-native-bootsplash-expo-router-bug

**Comment by zoontek** [comment]
@ferretwithaberet Excuse me, but… this again? 😅

> [x]  I checked for possible duplicate issues, with possible answers.

I wish.

- https://github.com/zoontek/react-native-bootsplash/issues/612
- https://github.com/zoontek/react-native-bootsplash/issues/606

`npm uninstall expo-dev-client` (at least, until they [fix it](https://github.com/expo/expo/issues/30526))

**Comment by ferretwithaberet** [comment]
> > [x]  I checked for possible duplicate issues, with possible answers.
> 
> I wish 😅

Yeah, I thought it's `expo-router` related (as I know in the past it was reexporting `SplashScreen`) and searched for that, did not see the others. Sorry for the duplicate.
