### ISSUE TITLE
A method to show the splash screen again

### ISSUE THREAD

**Issue by panda0603** [zoontek/react-native-bootsplash#62]
### 💻 My environment

- react-native-bootsplash version: 1.2.1
- react-native version: 0.61.5
- Platform:  both
- OS version: ? mac 10.14
- Device: Macbook pro 13
- Simulator: yes 

Thanks for the library. 

Currently, there seems to be no method to show the splash screen again. For example, react-native-splash screen has the .show() method. 

Is there any plans to implement such method?

**Comment by zoontek** [comment]
@panda0603 Yes, I'm currently working on it. IOS is done, I need to code the Android part

**Comment by zoontek** [comment]
@panda0603 It's available in the new version: https://github.com/zoontek/react-native-bootsplash/releases/tag/2.0.0 🤘
