### ISSUE TITLE
The RN bootsplash logo appears downsized on Samsung S10 devices

### ISSUE THREAD

**Issue by kasunprabath98** [zoontek/react-native-bootsplash#621]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

RN bootsplash logo is appearing downsized on samsung s10 devices. 
check the attached image shot here 

<img width="376" alt="Screenshot 2024-08-27 at 11 15 55" src="https://github.com/user-attachments/assets/ae9362f6-8fa0-48cd-a78f-3706834d4260">

### Library version

5.5.3

### Environment info

```shell
OS: macOS 14.4.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 86.20 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.2
    path: ~/.nvm/versions/node/v20.12.2/bin/node
  Yarn:
    version: 3.6.4
    path: ~/node_modules/.bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v20.12.2/bin/npm
  Watchman:
    version: 2024.08.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.15
    wanted: 0.72.15
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
```

### Steps to reproduce

1. install the RN boot splash library. 
2. generated the bootsplash logos using command line 
3. generate and install the app in S10 device

### Reproducible sample code

```js
RNBootSplash
```

**Comment by xaiamov** [comment]
It shouldn't be marked as *duplicate* without linking to the original.
:-\

**Comment by zoontek** [comment]
There: https://github.com/zoontek/react-native-bootsplash/issues

**Comment by zoontek** [comment]
@xaiamov https://github.com/zoontek/react-native-bootsplash/issues/466

Note that GitHub has a search feature for the closed issues.

**Comment by xaiamov** [comment]
> @xaiamov #466
Thank you

> Note that GitHub has a search feature for the closed issues.
That's how I found this very issue :)
