### ISSUE TITLE
Incorrect folder generation

### ISSUE THREAD

**Issue by wogno** [zoontek/react-native-bootsplash#629]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

This command not add file in correct directory in android res folder and ios one.

yarn react-native generate-bootsplash logo.png \
  --platforms=android,ios,web \
  --background=F5FCFF \
  --logo-width=100 \
  --assets-output=assets/bootsplash \
  --flavor=main \
  --html=public/index.html
<img width="678" alt="Capture d’écran 2024-09-20 à 12 56 38" src="https://github.com/user-attachments/assets/230261c7-d6a1-450a-92f5-2cda86add12e">

  
  
  

### Library version

6.1.3

### Environment info

```shell
System:
  OS: macOS 14.5
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 22.59 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.5.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.1
    path: ~/Documents/***/***/node_modules/.bin/yarn
  npm:
    version: 10.8.3
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.07.29.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /Users/****/.jenv/shims/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.3
    wanted: 0.75.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Steps to reproduce

1.Just install library and run generation

### Reproducible sample code

```js
yarn react-native generate-bootsplash logo.png \
  --platforms=android,ios,web \
  --background=F5FCFF \
  --logo-width=100 \
  --assets-output=assets/bootsplash \
  --flavor=main \
  --html=public/index.html
<img width="678" alt="Capture d’écran 2024-09-20 à 12 56 38" src="https://github.com/user-attachments/assets/230261c7-d6a1-450a-92f5-2cda86add12e">
```

**Comment by zoontek** [comment]
@wogno  You have expo as dependency? Set --platform-type=bare?

**Comment by wogno** [comment]
Yes, I added expo for expo updates, but It's still the same after add platform type, I get error error: unknown option '--platform-type=bare'

**Comment by zoontek** [comment]
Ah yes my bad, it's `--project-type=bare`

**Comment by wogno** [comment]
Thanks, it worked fine.
