### ISSUE TITLE
Unresolved reference: BootTheme

### ISSUE THREAD

**Issue by dydyF05** [zoontek/react-native-bootsplash#633]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Hey there,

Can't build android with react-native-bootsplash@6.1.3. The `R.style.BootTheme` in MainActivity.kt seems to throw error although the packages were imported in the file following your [simple readme](https://github.com/zoontek/react-native-bootsplash?tab=readme-ov-file#android)

The logos and splashscreens were generated using
```
cd apps/mobile

npx react-native generate-bootsplash src/assets/example_logo.png \
--platforms=android,ios  \
--project-type=bare \
--assets-output=src/assets/bootsplash/bootsplash \
--flavor=src/assets/bootsplash
``` 

### Library version

6.1.3

### Environment info

```shell
System:
  OS: macOS 14.5
  CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Memory: 337.89 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/Projects/toasty/example/apps/mobile/node_modules/.bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.17.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2024.09.16.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
    System Images:
      - android-26 | Google APIs Intel x86 Atom
      - android-30 | Google APIs Intel x86 Atom
      - android-34 | Google APIs Intel x86_64 Atom
      - android-UpsideDownCake-ext5 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/nikpomme/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: "*"
  react-native:
    installed: 0.74.1
    wanted: "*"
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. Pull https://github.com/dydyF05/nx-rn-example
2. npm install
3. npm run android

### Reproducible sample code

```js
I setup a little repository here https://github.com/dydyF05/nx-rn-example

It has all the dependencies of the original repo I am not allowed to share
```

**Comment by zoontek** [comment]
@dydyF05 There's no `BootTheme` here, indeed: https://github.com/dydyF05/nx-rn-example/blob/main/apps/mobile/android/app/src/main/res/values/styles.xml#L4

And it's probably because you pass an incorrect [`flavor`](https://developer.android.com/build/build-variants#product-flavors): `--flavor=src/assets/bootsplash`. Remove this and run the CLI command again, your `styles.xml` will be correctly updated.

**Comment by dydyF05** [comment]
Thousand thanks @zoontek I clearly f*cked up there thanks for your time 🙏
