### ISSUE TITLE
Error react-native-bootsplash:generateCodegenArtifactsFromSchema when update new architecture

### ISSUE THREAD

**Issue by threeng0227** [zoontek/react-native-bootsplash#634]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

![Screenshot 2024-10-04 at 16 58 02](https://github.com/user-attachments/assets/4e654f60-8f1a-4d1b-b82c-0651551933c5)
when i run ./gradlew generateCodegenArtifactsFromSchema --stacktrace --info for android, i see the error image above. i can't fix it, hope to get someone's help. 

### Library version

^6.1.3

### Environment info

```shell
System:
  OS: macOS 15.0
  CPU: (8) arm64 Apple M2
  Memory: 102.42 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.2
    path: ~/.nvm/versions/node/v20.12.2/bin/node
  Yarn:
    version: 1.22.22
    path: ~/Desktop/unity-fitness-app/node_modules/.bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v20.12.2/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. Turn on newArchEnabled = true in android/gradle.properties
2. Run ./gradlew generateCodegenArtifactsFromSchema --stacktrace --info
![Screenshot 2024-10-04 at 16 58 02](https://github.com/user-attachments/assets/1e9ed116-8f5d-42ab-abb5-c330c2cbc577)

### Reproducible sample code

```js
# Use this property to enable support to the new architecture.
# This will allow you to use TurboModules and the Fabric render in
# your application. You should enable this flag either if you want
# to write custom TurboModules/Fabric components OR use libraries that
# are providing them.
newArchEnabled=true

# Use this property to enable or disable the Hermes JS engine.
# If set to false, you will be using JSC instead.
hermesEnabled=true
```

**Comment by threeng0227** [comment]
> @threeng0227 No issue on my side.
> 
> > react-native: Not Found
> 
> Which version are you using? Latest stable?
> 
> EDIT: Be sure [your environment is correctly setted up](https://reactnative.dev/docs/set-up-your-environment)

I'm sorry for the lack of information
System:
  OS: macOS 15.0
  CPU: (8) arm64 Apple M2
  Memory: 558.27 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.2
    path: ~/.nvm/versions/node/v20.12.2/bin/node
  Yarn:
    version: 1.22.22
    path: ~/uniscore-mobile/node_modules/.bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v20.12.2/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

**Comment by zoontek** [comment]
New architecture is only supported with the latest stable version until it is stable / the default.

Use a previous version of bootsplash that supports new arch for 0.73, or update to 0.75 (as they made breaking changes in codegen)
