### ISSUE TITLE
Cannot find protocol definition for 'NativeRNBootSplashSpec'

### ISSUE THREAD

**Issue by yashdiq** [zoontek/react-native-bootsplash#647]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

I found this error when running on RN 0.76.1 as attached in the screenshot.
<img width="1161" alt="Screenshot 2024-11-03 at 20 19 41" src="https://github.com/user-attachments/assets/01e417da-349e-4d94-84f6-62af7ad1480a">

### Library version

6.2.6

### Environment info

```shell
System:
  OS: macOS 15.0.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 36.05 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.9.0
    path: ~/.nvm/versions/node/v20.9.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v20.9.0/bin/yarn
  npm:
    version: 10.1.0
    path: ~/.nvm/versions/node/v20.9.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    API Levels:
      - "23"
      - "28"
      - "29"
      - "30"
      - "31"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
      - 34.0.0
      - 35.0.0
    System Images:
      - android-30 | Google Play Intel x86 Atom
      - android-33 | Google APIs Intel x86_64 Atom
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.7
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Steps to reproduce

1. clear all cache and deintegrate pods
2. run bundle install && bundle exec pod install

### Reproducible sample code

```js
run from the example codes
```

**Comment by zoontek** [comment]
Be sure that RN codegen properly ran.

Run https://www.npmjs.com/package/react-native-clean-project if required.

**Comment by nagykrisztianendre** [comment]
Hello @yashdiq 

Did you manage to solve the problem?

I'm facing the same issue but can't see anything wrong during RN codegen. When I comment out Bootsplash, everything builds correctly.

**Comment by yashdiq** [comment]
Hi @nagykrisztianendre I wanna try your workaround above but I can't see this option: Build Settings -> Apple Clang - Language -> Compile Sources As to 'Objective-C++'. Can you give me the screenshot of your XCode?

**Comment by nagykrisztianendre** [comment]
Yes. @yashdiq Here it is:

![image](https://github.com/user-attachments/assets/cbbce3af-b490-42e0-9c68-856ef188ff26)

**Comment by yashdiq** [comment]
Thanks bro @nagykrisztianendre found it.

**Comment by yashdiq** [comment]
<img width="1203" alt="Screenshot 2024-11-06 at 17 40 57" src="https://github.com/user-attachments/assets/93922f3a-46d3-4e5f-82af-aa8c6dfa1cb0">
Still the same 😂

**Comment by nagykrisztianendre** [comment]
Have you tried running pod install before rebuilding the project?
