### ISSUE TITLE
BootSplash logo is appearing with a delay

### ISSUE THREAD

**Issue by mydesweb** [zoontek/react-native-bootsplash#648]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

I started to see this issue on iPhone 11 (production build) - in Simulator everything works as expected..

https://github.com/user-attachments/assets/715ab0d9-fab3-4ee3-9ac9-7c879c9cff74

If you check my screen recording video, you will see that initially BootSplash is presented without the logo, then the logo is displayed for a very short time.

Another thing I notice is even I select BootSplash.storyboard under Xcode -> Launch Screen File it is automatically getting removed and remain empty, anyway in Info.plist -> Launch screen interface file base name is set to **BootSplash** (without .storyboard extension) as it should be.

### Library version

6.2.6 

### Environment info

```shell
System:
  OS: macOS 14.6.1
  CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  Memory: 2.36 GB / 48.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.yarn/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman:
    version: 2024.10.07.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/alex/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.21829.142.2421.12409432
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/alex/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
https://github.com/user-attachments/assets/715ab0d9-fab3-4ee3-9ac9-7c879c9cff74
```

**Comment by zoontek** [comment]
@mydesweb Looks like an issue in your project. Is your `BootSplash.storyboard` correctly added in your bundle resource, in dev and in release?

<img width="1040" alt="Screenshot 2024-11-04 at 15 53 42" src="https://github.com/user-attachments/assets/529d695b-24cb-446f-8fda-db581b0cfa13">

**Comment by mydesweb** [comment]
@zoontek just checked and all files are in place. I executed again `react-native generate-bootsplash` command, in Xcode -> Launch Screen File is empty and if I manually select  BootSplash.storyboard is automatically removed and remain empty.

**Comment by mydesweb** [comment]
anyway, it started to work normally after I created a new build
just for your records Xcode -> Launch Screen File is still empty, I don't know if it is OK or not

**Comment by zoontek** [comment]
@mydesweb Yes, that's wanted: https://github.com/zoontek/react-native-bootsplash/pull/573
