### ISSUE TITLE
iOS build failure react-native v0.76

### ISSUE THREAD

**Issue by bhandanyan-nomad** [zoontek/react-native-bootsplash#651]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

New iOS build error when trying to upgrade to react-native v0.76.1 from v0.75.4

```
In file included from ios/Application/AppDelegate.mm:9:
ios/Pods/Headers/Public/RNBootSplash/RNBootSplash.h:3:9: fatal error: could not build module 'ReactCodegen'
    3 | #import <RNBootSplashSpec/RNBootSplashSpec.h>
      |  ~~~~~~~^
345 warnings and 3 errors generated.

ios/Pods/Headers/Public/glog/glog/logging.h:512:1: Import of module 'glog.glog.log_severity' appears within namespace 'google'

ios/Pods/Headers/Public/React-debug/react/debug/react_native_assert.h:54:10: Could not build module 'glog'

ios/Pods/Headers/Public/RNBootSplash/RNBootSplash.h:3:9: Could not build module 'ReactCodegen'
```

### Library version

6.2.6

### Environment info

```shell
info Fetching system and libraries information...
System:
  OS: macOS 14.7
  CPU: (12) arm64 Apple M2 Pro
  Memory: 246.36 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/benjamin/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.4
    path: /Users/benjamin/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: 15.1.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Steps to reproduce

1. Try to build an app

### Reproducible sample code

```js
-
```

**Comment by zoontek** [comment]
I [updated the example app](https://github.com/zoontek/react-native-bootsplash/commit/0512c0d9b9c79b9283b82399b9676fa49d1fd6d1) to check. I indeed has a build issue with React Codegen, but did a project clean to remove old build artifacts from 0.75.4, rebuild, everything went well. So, cache issues.

<img width="295" alt="Screenshot 2024-11-08 at 23 39 44" src="https://github.com/user-attachments/assets/9d0cb036-ed16-4104-b629-3ea81841937d">

**Comment by bhandanyan-nomad** [comment]
I made sure to clean the build folder several times and the issue persisted for me. I will continue troubleshooting

**Comment by zoontek** [comment]
No, just a regular update using [the upgrade helper](https://react-native-community.github.io/upgrade-helper/). Let me know if you have a solid reproduction (ideally, a repo)

**Comment by bhandanyan-nomad** [comment]
@zoontek could you please check if the build still works if you:
* remove `gem 'xcodeproj', '< 1.26.0'`
* upgrade cocoapods to `1.16.2`

I am still getting the build failure even after completely wiping all my caches 🤔

**Comment by zoontek** [comment]
`gem 'xcodeproj', '< 1.26.0'` is a bundle dependency on react-native 0.76+

**Comment by bhandanyan-nomad** [comment]
The issue with 1.26.0 is fixed in 1.27.0, react-native just hasn't pushed a new version since

**Comment by zoontek** [comment]
@bhandanyan-nomad 

<img width="485" alt="Screenshot 2024-11-12 at 01 02 48" src="https://github.com/user-attachments/assets/e8dde8ba-8c3b-46b0-a2e9-6a547e9a06d1">

<img width="974" alt="Screenshot 2024-11-12 at 01 05 53" src="https://github.com/user-attachments/assets/bca42ebb-c8df-4ab1-af79-b163ec3a7c53">

**Comment by c100k** [comment]
@bhandanyan-nomad Have you solved your issue ? I've created a discussion here https://github.com/zoontek/react-native-bootsplash/discussions/657 as I'm having the same and everything mentioned in this issue didn't help.

**Comment by bhandanyan-nomad** [comment]
I have not solved it. I have not upgraded to react-native 0.76 yet, but when I come back to it in a week or two I may upgrade with the new architecture disabled to workaround this issue.

**Comment by zoontek** [comment]
@bhandanyan-nomad Found it (it's probably the same issue): https://github.com/zoontek/react-native-bootsplash/discussions/657#discussioncomment-11417484

**Comment by bhandanyan-nomad** [comment]
It's not the same issue for me, unfortunately

**Comment by zoontek** [comment]
@bhandanyan-nomad So this is related to something else in your project. I recommand starting from a clean base regarding your `*.xcodeproj` file.

Generate a new prioject using the same name and latest RN version. Copy / paste this files. Re-apply **safe** settings using git diff.

**Comment by bhandanyan-nomad** [comment]
The following change (along with some import tweaks in AppDelegate.h) fixed my build issues

```diff
-  8EC73EE827FDCEB400945966 /* AppDelegate.mm in Sources */ = {isa = PBXBuildFile; fileRef = 8EC73EE727FDCEB400945966 /* AppDelegate.mm */; settings = {COMPILER_FLAGS = "-fmodules -fcxx-modules"; }; };
+  8EC73EE827FDCEB400945966 /* AppDelegate.mm in Sources */ = {isa = PBXBuildFile; fileRef = 8EC73EE727FDCEB400945966 /* AppDelegate.mm */; };
```

**Comment by arneson** [comment]
@bhandanyan-nomad When you say 'some import tweaks', could you provide any more details? I seem to be having your exact issue but I've checked every solution in this thread very thoroughly.

**Comment by ttdatt** [comment]
I wanted to check if you found a solution to your problem @arneson ? I'm encountering the same issue and have been trying to resolve it by creating a fresh project and transferring components over one by one

**Comment by arneson** [comment]
If I don't misremember @arneson I fixed my issues by skipping RN 0.76 completely and just updating to RN 0.77, where the issues apparently didn't exist.

**Comment by anujsachan1990** [comment]
I am having the same issue and it is not the same as: https://github.com/zoontek/react-native-bootsplash/discussions/657#discussioncomment-11417484 

React native: 0.76.7
 "react-native-bootsplash": "^5.5.1",

<img width="626" alt="Image" src="https://github.com/user-attachments/assets/2ae67ccf-7e81-4996-a4d6-e9bf699b19a6" />

<img width="878" alt="Image" src="https://github.com/user-attachments/assets/a9fd2463-28de-48ed-9173-61b810b4a785" />

When I am removing splash screen imports from AppDelegate.mm it builds fine

// #import "RNBootSplash.h"

 // [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];

**Comment by jpetrieam** [comment]
So has anyone found an actual working solution to this problem?  We fixed the styling issues under iOS which were due to the new architecture/fabric, but still continuing to get this build error when including RNBootSplash.h in our project and trying every single alleged solution we can find on the Internet.  Upgrading to RN 0.77.3 (as stated in my last comment) did not solve this either.
