### ISSUE TITLE
Background image support

### ISSUE THREAD

**Issue by LuizFelipe16** [zoontek/react-native-bootsplash#652]
### Why it is needed?

Hi, and thanks for the great work on react-native-bootsplash! I would like to request a new feature that allows setting a background image for the splash screen directly through the library, rather than just a background color.

Problem Statement
Currently, react-native-bootsplash supports setting a background color and displaying an app icon, which works well for many cases. However, some apps require more visual customization, such as displaying a background image (e.g., a branded image or custom gradient) during the splash screen.

**Comment by arsensgitacc** [comment]
@LuizFelipe16 have you found a solution for this?

**Comment by zoontek** [comment]
@arsensgitacc This is **not** possible given Android SplashScreen API
