### ISSUE TITLE
generate options error

### ISSUE THREAD

**Issue by dkahdwk** [zoontek/react-native-bootsplash#654]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

```
// generate
yarn react-native-bootsplash generate src/assets/splash.svg \                   
  --project-type=bare \
  --platforms=android,ios \
  --background=008DEF \
  --logo-width=180 \
  --assets-output=assets/bootsplash \
  --flavor=development
```

Below are the execution results.

![스크린샷 2024-11-20 오후 3 49 46](https://github.com/user-attachments/assets/3850ff34-407d-4d98-9564-8b6c485d90e0)

I made an asset with this command to apply new bootsplash while upgrading from v5 to v6, but the option was not applied.
The BootSplash.storyboard generated by this command is as follows.

- BootSplash.storyboard
```
<?xml version="1.0" encoding="UTF-8"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="21701" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" launchScreen="YES" useTraitCollections="YES" useSafeAreas="YES" colorMatched="YES" initialViewController="01J-lp-oVM">
    <device id="retina4_7" orientation="portrait" appearance="light"/>
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="21678"/>
        <capability name="Named colors" minToolsVersion="9.0"/>
        <capability name="Safe area layout guides" minToolsVersion="9.0"/>
        <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
    </dependencies>
    <scenes>
        <!--View Controller-->
        <scene sceneID="EHf-IW-A2E">
            <objects>
                <viewController modalTransitionStyle="crossDissolve" id="01J-lp-oVM" sceneMemberID="viewController">
                    <view key="view" autoresizesSubviews="NO" contentMode="scaleToFill" id="Ze5-6b-2t3">
                        <rect key="frame" x="0.0" y="0.0" width="375" height="667"/>
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <subviews>
                            <imageView autoresizesSubviews="NO" clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" image="BootSplashLogo-cf6192" translatesAutoresizingMaskIntoConstraints="NO" id="3lX-Ut-9ad">
                                <rect key="frame" x="137.5" y="313.5" width="100" height="40"/>
                                <accessibility key="accessibilityConfiguration">
                                    <accessibilityTraits key="traits" image="YES" notEnabled="YES"/>
                                </accessibility>
                            </imageView>
                        </subviews>
                        <viewLayoutGuide key="safeArea" id="Bcu-3y-fUS"/>
                        <color key="backgroundColor" name="BootSplashBackground-cf6192"/>
                        <constraints>
                            <constraint firstItem="3lX-Ut-9ad" firstAttribute="centerX" secondItem="Ze5-6b-2t3" secondAttribute="centerX" id="Fh9-Fy-1nT"/>
                            <constraint firstItem="3lX-Ut-9ad" firstAttribute="centerY" secondItem="Ze5-6b-2t3" secondAttribute="centerY" id="nvB-Ic-PnI"/>
                        </constraints>
                    </view>
                </viewController>
                <placeholder placeholderIdentifier="IBFirstResponder" id="iYj-Kq-Ea1" userLabel="First Responder" sceneMemberID="firstResponder"/>
            </objects>
            <point key="canvasLocation" x="0.0" y="0.0"/>
        </scene>
    </scenes>
    <resources>
        <image name="BootSplashLogo-cf6192" width="100" height="40"/>
        <namedColor name="BootSplashBackground-cf6192">
            <color red="1.00000000000000" green="1.00000000000000" blue="1.00000000000000" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
        </namedColor>
    </resources>
</document>

```

Files made with this command do not have the option applied to the logo size and background color as I specified.
What could be the reason?

### Library version

6.3.1

### Environment info

```shell
(expo bare workflow)
- react-native: 0.74.6
- expo: ^51.0.0
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
yarn react-native-bootsplash generate src/assets/splash.svg \                   
  --project-type=bare \
  --platforms=android,ios \
  --background=008DEF \
  --logo-width=180 \
  --assets-output=assets/bootsplash \
  --flavor=development
```

**Comment by zoontek** [comment]
```
yarn react-native-bootsplash generate src/assets/splash.svg \                   
  --project-type=bare \
  --platforms=android,ios \
  --background=008DEF \
  --logo-width=180 \
  --assets-output=assets/bootsplash \
  --flavor=development
```

`\` is used in commands to escape the next character. Here, it's a the end of lines to escape the newline one (`\n`).
But if you add a bunch of spaces at the end of the first line, it escapes the first space char and assume the command ends at the end of the line (like could do any command line). Here you can see that it ignored everything, not just the width, but also platforms, etc:

<img width="694" alt="Screenshot 2024-11-20 at 09 27 23" src="https://github.com/user-attachments/assets/4b259758-7b8a-4dce-a43c-59c0a25c0ea5">

<img width="1141" alt="Screenshot 2024-11-20 at 09 26 09" src="https://github.com/user-attachments/assets/287b393f-93ce-4259-8b81-87d86243e84c">

If you don't add extra spaces, or put everything on the same line, it works.

<img width="536" alt="Screenshot 2024-11-20 at 09 27 34" src="https://github.com/user-attachments/assets/5fb16bff-3d86-4265-9b17-77a51a721d7e">

<img width="1303" alt="Screenshot 2024-11-20 at 09 27 54" src="https://github.com/user-attachments/assets/5d34852e-a24d-46ab-9e5c-07109ea7176f">

**Comment by dkahdwk** [comment]
@zoontek 
Thank you for your quick response every time. Can I ask you one more question?
It's a separate question from this issue, but when you use expo-updates, there is an issue that the black screen flashes quickly before the splash comes out.
Looking at the related issue, it seems to have been resolved in expo 51.0.20 on https://github.com/zoontek/react-native-bootsplash/pull/578#issue-2273853937 , but I still get that issue. Is there any probable cause?
(using version expo 51.0.39)

**Comment by zoontek** [comment]
@dkahdwk No, this has been fixed in Expo 52 (with the `expo-splash-screen` revamp too)

**Comment by dkahdwk** [comment]
@zoontek 
I updated it to expo 52 and tested it, but the blinking problem still persists. It's not a bootsplash problem, but I want you to know it, so I'm sharing the issue.

https://github.com/expo/expo/issues/33257
