### ISSUE TITLE
expo52  requires @expo/config-plugins@~9.0.0

### ISSUE THREAD

**Issue by tarkanlar** [zoontek/react-native-bootsplash#655]
### Why it is needed?

When upgrading expo 52 expo doctor complains about the expo-config plugin version used in this library.

### Possible implementation

Upgrading config plugin to 9.0.0

**Comment by zoontek** [comment]
Done in [6.3.2](https://github.com/zoontek/react-native-bootsplash/releases/tag/6.3.2)
