### ISSUE TITLE
Expo build error

### ISSUE THREAD

**Issue by brayohmurithidev** [zoontek/react-native-bootsplash#659]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Hello am on expo and am getting error: "assets/bootsplash/android" doesn't exist. Did you ran the asset generation command? though I have generated the bootsplash folder. Any work solution for this?
<img width="565" alt="Screenshot 2024-12-05 at 15 11 39" src="https://github.com/user-attachments/assets/33461297-31ab-4779-84b8-8cd7e72b3c84">

### Library version

^6.3.2

### Environment info

```shell
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
      npm: 10.8.3 - ~/.nvm/versions/node/v20.17.0/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.15 
      expo-router: ~4.0.11 => 4.0.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.4.2
    Expo Workflow: bare
```

### Steps to reproduce

1. Generated the assets directory and checked to ensure it is available

### Reproducible sample code

```js
npx react-native-bootsplash generate assets/images/splash-logo.png \
  --platforms=android,ios,web \
  --background=E3F1B0 \
  --logo-width=100 \
  --assets-output=assets/bootsplash \
  --flavor=main \
  --html=public/index.html
```

**Comment by zoontek** [comment]
@brayohmurithidev Does this occurs locally or on EAS?

**Comment by Safee-ullah1** [comment]
> @brayohmurithidev Does this occurs locally or on EAS?
> 
> Probably a duplicate of [#595 (comment)](https://github.com/zoontek/react-native-bootsplash/issues/595#issuecomment-2254211269)

Yeah I was having the exact same issue and [#595 (comment)](https://github.com/zoontek/react-native-bootsplash/issues/595#issuecomment-2254211269) solved it.

**Comment by brayohmurithidev** [comment]
> @brayohmurithidev Does this occurs locally or on EAS?
> 
> Probably a duplicate of [#595 (comment)](https://github.com/zoontek/react-native-bootsplash/issues/595#issuecomment-2254211269)

Thank you this helped. I will close this now
