### ISSUE TITLE
How may I change the color(theme) of the Status Bar in Splash Screen (Android)?

### ISSUE THREAD

**Issue by panda0603** [zoontek/react-native-bootsplash#66]
First of all, thanks for your library. 

I would like to change the status bar color in the splash screen so that it matches the background color of the splash screen in Android. 

Where do I specify this?

**Comment by zoontek** [comment]
@panda0603 Using theme: http://www.gadgetsaint.com/tips/change-statusbar-color-android/

**Comment by ItsFlash10** [comment]
The above link isn't operational anymore, can someone please share the solution

**Comment by zoontek** [comment]
@ItsFlash10 https://web.archive.org/web/20200701000000*/http://www.gadgetsaint.com/tips/change-statusbar-color-android/
