### ISSUE TITLE
RN triggers a lot of warnings after hiding SplashScreen - iOS

### ISSUE THREAD

**Issue by dudusotero** [zoontek/react-native-bootsplash#70]
### 💻 My environment

- react-native-bootsplash version: 2.0.5
- react-native version: 0.61.5
- Platform: ios
- OS version: 13.3
- Device: Apple iPhone 11
- Simulator: yes
- Xcode version: 11.3.1 (11C504)

### 🕵️‍♂️ Reproducing the issue

I just did the installation tutorial, both for Android and iOS, but the problem occurs only with iOS.
My simulator triggers a lot of warning messages after hiding the SplashScreen, saying: "RCTBridge required dispatch_sync to load RCTDevLoadingView. This may lead to deadlocks."

![image](https://user-images.githubusercontent.com/7073199/76453245-4408a580-63b1-11ea-984b-9fd4d4c958e0.png)

Doing a quick search at GitHub, I found some workaround code [here](https://github.com/facebook/react-native/issues/16376#issuecomment-350523177).

What do I need to do to fix it? Doing that workaround will cause some performance issues to my app? There's more people with that same error?

**Comment by zoontek** [comment]
@dudusotero Hi 👋 Could you try the latest version? https://github.com/zoontek/react-native-bootsplash/releases/tag/2.1.0. The iOS logic has been updated, we now rely on `loadingView` and the bootsplash is only presented when the JS has finished loading.

**Comment by dudusotero** [comment]
@zoontek Of course! I will create a brand new project for testing purposes, any problems I will report here.

**Comment by dudusotero** [comment]
Everything working fine!! Just update to the latest version, run ```pod install``` and install the app again.
Thank you @zoontek

**Comment by zoontek** [comment]
@dudusotero Glad to hear that 🙏

**Comment by shoopi12** [comment]
I am using bootsplash 2.2.6 and get the same deadlock warning in IOS.

**Comment by amandeepmittal** [comment]
Hi @zoontek I am also facing the issue on iOS. Here is my environment:

### My Environment

react-native-bootsplash version: 3.2.4
react-native version: 0.65.1
Platform: ios
OS version: 14.5
Device: Apple iPhone 12
Simulator: yes
Xcode version: 12.5.1 (12E507)

<img width="400" alt="CleanShot 2021-08-30 at 22 21 22@2x" src="https://user-images.githubusercontent.com/10234615/131375472-d10050fd-7fff-484e-986f-ac549f1a10ca.png">


It is using the default template that is generated by React Native. I am not sure what is causing this. Any help/suggestion/guidance is appreciated 🙏

**Comment by jbromberg** [comment]
I am also getting this same issue. Only happens sometimes on app start.
