### ISSUE TITLE
Matching View color with icon color

### ISSUE THREAD

**Issue by handoff** [zoontek/react-native-bootsplash#71]
### 💻 My environment

- react-native-bootsplash version: 2.0.5
- react-native version: 0.61.5
- Platform: ios
- OS version: 10.3.3
- Device: iPhone 5c
- Simulator: no
- Xcode version: 11.3.1

### 🕵️‍♂️ Reproducing the issue

I am not able to match the colors of the background View och the BootSplashLogo. I have checked the color of the Logo with the Mac color picker, and also in Gimp. When I set the color of the View in XCode (or using the provided script) the colors don't match when the splash screen is displayed. In the original .xib that was included in the react project I had no problem settings these colors. In the .storyboard I can't get them to match. Any ideas?

**Comment by zoontek** [comment]
@handoff Hi. Try updating the color profile of the background color to `Display P3`.

<img width="1566" alt="Screenshot 2020-03-13 at 14 16 50" src="https://user-images.githubusercontent.com/1902323/76624396-80fda500-6535-11ea-8e57-795d02cfadf1.png">

**Comment by handoff** [comment]
Yes, that was it! Thanks a million!

**Comment by zoontek** [comment]
No problem! 🙂
