### ISSUE TITLE
[Share] bootsplash in dark mode

### ISSUE THREAD

**Issue by punisher97** [zoontek/react-native-bootsplash#73]
This is not a issue, only share to help anybody, if you want create bootsplash based on device theme.

Sorry my english.

# Android:

1. create two files bootsplash.xml as in README.md but change background color
- bootsplash_dark.xml
- bootsplash_light.xml

example: bootsplash_dark.xml
```xml
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
  <!--  here change color, dark: @android:color/background_dark or @android:color/background_light -->
  <item android:drawable="@android:color/background_dark" />

  <item>
    <!-- the app logo, centered horizontally and vertically -->
    <bitmap
        android:src="@mipmap/bootsplash_logo"
        android:gravity="center" />
  </item>
</layer-list>
```

2. create this files in android/app/src/main/res/values/styles.xml
``` xml
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
    </style>
    <!-- Add the following lines -->
    <!-- BootTheme should inherit from AppTheme -->
    <style name="BootTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- set bootsplash.xml as activity background -->
        <item name="android:background">@drawable/bootsplash_light</item>
    </style>
</resources>
```

3. Create this file in android/app/src/main/res/values-night/styles.xml

```xml
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
    </style>
    <!-- Add the following lines -->
    <!-- BootTheme should inherit from AppTheme -->
    <style name="BootTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- set bootsplash.xml as activity background -->
        <item name="android:background">@drawable/bootsplash_dark</item>
    </style>
</resources>

```
and MainActivity.java:

```java
....


import android.content.res.Configuration; // check if these already import
 
public class MainActivity extends ReactActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        int drawableId = (getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK) == Configuration.UI_MODE_NIGHT_YES
                ? R.drawable.bootsplash_dark
                : R.drawable.bootsplash_light; //Default light theme
        RNBootSplash.init(drawableId, MainActivity.this);
    }

```

# iOS:

Setting System default color in BootSplash.storyboard > View

 
![image](https://user-images.githubusercontent.com/8255332/76683896-86123100-65d5-11ea-8128-d9bd97ed0951.png)

Thank you to [this](https://blog.brainsandbeards.com/how-to-add-a-dark-mode-splash-screen-to-a-react-native-app-f0fb8724d9d7) tutorial

**Comment by zoontek** [comment]
Thanks! I'm closing since it's not an issue, it will still be searchable. Maybe create a blog article too?

**Comment by punisher97** [comment]
> Thanks! I'm closing since it's not an issue, it will still be searchable. Maybe create a blog article too?

Maybe, when i write blog with full example i will share here.

**Comment by alexandersandberg** [comment]
@punisher97 This is great, thanks!

@zoontek Maybe we should add a link to this in the README? 🙂

**Comment by zoontek** [comment]
@alexandersandberg The link seems to be dead right now. I will wait to check later if the server is just down and add it to the `README` if it's still available.

For me, what feels **super slick** is when you transition from your app icon to the splash screen and start animating it (like the Netflix & Twitter apps, that's the whole point of this lib). That's why I don't think splash screens should supports dark mode, but rather uses your brand colors.

But it's a totally personal opinion and as this library relies on native implementations, it's absolutely possible to do it if you want 🙂

**Comment by alexandersandberg** [comment]
@zoontek Yes, you're definitely right about that! But some also use light- and dark mode-specific branding. 🙂 

Also, Apple's Human Interface Guidelines, for instance, recommends you to _"Design a launch screen that’s nearly identical to the first screen of your app."_ ([reference](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/launch-screen/)). If your app supports dark mode you would have to optimize this launch screen for dark mode as well.

But like you say, of course, it's an opinionated topic. 🙂

**Comment by mixmaker** [comment]
> This is not a issue, only share to help anybody, if you want create bootsplash based on device theme.
> 
> # Android:
> 1. create two files bootsplash.xml as in README.md but change background color
> 
> * bootsplash_dark.xml
> * bootsplash_light.xml
> 
> example: bootsplash_dark.xml
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> 
> <layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
>   
>   <item android:drawable="@android:color/background_dark" />
> 
>   <item>
>     
>     <bitmap
>         android:src="@mipmap/bootsplash_logo"
>         android:gravity="center" />
>   </item>
> </layer-list>
> ```
> 
> 2. create this files in android/app/src/main/res/values/styles.xml
> 
> ```
> <resources>
> 
>     
>     <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>         
>         <item name="android:textColor">#000000</item>
>     </style>
>     
>     
>     <style name="BootTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
>         
>         <item name="android:background">@drawable/bootsplash_light</item>
>     </style>
> </resources>
> ```
> 
> 3. Create this file in android/app/src/main/res/values-night/styles.xml
> 
> ```
> <resources>
> 
>     
>     <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>         
>         <item name="android:textColor">#000000</item>
>     </style>
>     
>     
>     <style name="BootTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
>         
>         <item name="android:background">@drawable/bootsplash_dark</item>
>     </style>
> </resources>
> ```
> 
> and MainActivity.java:
> 
> ```java
> ....
> 
> 
> import android.content.res.Configuration; // check if these already import
>  
> public class MainActivity extends ReactActivity {
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         int drawableId = (getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK) == Configuration.UI_MODE_NIGHT_YES
>                 ? R.drawable.bootsplash_dark
>                 : R.drawable.bootsplash_light; //Default light theme
>         RNBootSplash.init(drawableId, MainActivity.this);
>     }
> ```
> 
> # iOS:
> Setting System default color in BootSplash.storyboard > View
> 
> ![image](https://user-images.githubusercontent.com/8255332/76683896-86123100-65d5-11ea-8128-d9bd97ed0951.png)
> 
> Thank you to [this](https://blog.brainsandbeards.com/how-to-add-a-dark-mode-splash-screen-to-a-react-native-app-f0fb8724d9d7) tutorial

I had a confusion. Where should I create `bootsplash_light.xml` and `bootsplash_dark.xml`, I mean the exact directory?

**Comment by alexandersandberg** [comment]
> I had a confusion. Where should I create `bootsplash_light.xml` and `bootsplash_dark.xml`, I mean the exact directory?

See [this blog post](https://brainsandbeards.com/blog/how-to-add-a-dark-mode-splash-screen-to-a-react-native-app) that was linked at the beginning for more information.
