### ISSUE TITLE
The startup diagram cannot fill up the screen

### ISSUE THREAD

**Issue by Gert-YXS** [zoontek/react-native-bootsplash#75]
### 💻 My environment

- react-native-bootsplash version: 2.1.0
- react-native version: 0.61.5
- Platform:  android
- Device: Android Simulator
- Simulator: yes
- Android buildToolsVersion: 28.0.3

### 🕵️‍♂️ Reproducing the issue

I hope that the startup map on the IOS or Android device can fill the screen. I have carefully read the documentation and run the examples provided by this library, but still cannot fill the screen. I do n’t have enough basic knowledge of IOS and Android development. Thank you for building This lib, your answers are greatly appreciated!

![ON`$T)S0L2M7{3%V `OQX8S](https://user-images.githubusercontent.com/23646949/77068427-8ff6c280-6a21-11ea-8eb9-53d97fd27f38.png)

**Comment by zoontek** [comment]
@Gert-YXS Hi! As Android devices have a ton of possible ratios, this format of splash screen (plain image) is not ideal. But you can see the [Android documentation](https://developer.android.com/guide/topics/resources/drawable-resource#XmlBitmap). Try `android:gravity="fill_vertical"`

**Comment by Gert-YXS** [comment]
非常感谢您的回答，设置了`android:gravity="fill"` 解决了我的问题

**Comment by Gert-YXS** [comment]
Thank you very much for your answer, setting `"android: gravity =" fill"` solved my problem
