### ISSUE TITLE
Hello there! How does Android hide the status bar at startup?

### ISSUE THREAD

**Issue by Hicbik** [zoontek/react-native-bootsplash#76]
### 💻 My environment

- react-native-bootsplash version:2.0.5
- react-native version: 0.61
- Platform: android

### 🕵️‍♂️ Reproducing the issue
 I need to set the color of the status bar at startup, or display the pictures full screen to make them look uniform! I don't have the basics of native Android knowledge ... thanks for the answers!

**Comment by zoontek** [comment]
@Hicbik Hi! Set `android:statusBarColor` in your `styles.xml`. See https://stackoverflow.com/questions/37197235/change-status-bar-color-in-android
