### ISSUE TITLE
Splash Icon size change bug in iOS

### ISSUE THREAD

**Issue by panda0603** [zoontek/react-native-bootsplash#77]
Hello there, 
I have created a .storyboard file and image asset for splash screen in xcode (did not use the cli). Splash screen shows fine, but the splash screen icon size changes(very quickly) when splash screen is shown. 

![gif](https://user-images.githubusercontent.com/34116285/77246335-a5f6c400-6c69-11ea-820d-406ecaed7c05.gif)

It is quite fast, but you can notice the size change. Small -> grows larger -> back to small 

I only have one storyboard file, and thought problem may be related to image asset, so I've tried replacing 1x 2x 3x with all same file but ended up with same result. 

![image](https://user-images.githubusercontent.com/34116285/77246403-2d443780-6c6a-11ea-892f-23dc596ed166.png)

Any ideas to this problem? Thanks

### 💻 My environment

- react-native-bootsplash version: 2.1.0
- react-native version: 0.61.5
- Platform: ios 
- OS version: ?
- Device: iphone 11 simulator
- Simulator: yes

**Comment by zoontek** [comment]
Maybe a mismatch between the declared size and the assets size? Did you change it or it always has been the défaut size?

**Comment by panda0603** [comment]
I have just tried the cli and works fine. Though the logo in the center is too small, I wish to make it larger (I'v set the icon width to 100 in cli). Do i have to go through the cli again to set the width to bigger size? I'll close the issue for now

**Comment by zoontek** [comment]
Yes, just give a number higher than 100, the CLI will handle the rest 🙂

**Comment by rahulje9** [comment]
I'm having the same issue, 
I used size 225, android is fine, but in ios at first the small icon is displayed then the larger one will be displayed. created everything with the cli

**Comment by aprilmintacpineda** [comment]
I'm having the same issue, I used the following command:

```json
"generate-bootsplash": "react-native generate-bootsplash assets/bootsplash_logo_original.png --background-color=ffffff --logo-width=120 --assets-path=assets"
```

then `yarn generate-bootsplash`

For me, it's the reverse. First, a bigger photo will appear then a smaller photo. On Android, everything seems well.

My `bootsplash_logo_original.png` is 512x512

**Comment by rahulje9** [comment]
@aprilmintacpineda 
Check the bootsplash.storyboard file and and click on the image and change 
`Content Mode` under `View` to `center` that fixed my issue.

**Comment by aprilmintacpineda** [comment]
@rahulje9 thanks for the advice, still the same problem after updating it...

![image](https://user-images.githubusercontent.com/21032419/102366350-85d71400-3ff3-11eb-9c84-9d410e242e33.png)

**Comment by zoontek** [comment]
@aprilmintacpineda Try https://github.com/zoontek/react-native-bootsplash/issues/105#issuecomment-621678048

**Comment by aprilmintacpineda** [comment]
ooooh, makes sense, because I mistakenly did `--logo-width=512` before, if that's the case then this might happen in production when I change the splash screen icon, users might still see the previous one then it will change to the new one, if so, then do you think this will work?

```swift
import UIKit

public extension UIApplication {

    func clearLaunchScreenCache() {
        do {
            try FileManager.default.removeItem(atPath: NSHomeDirectory()+"/Library/SplashBoard")
        } catch {
            print("Failed to delete launch screen cache: \(error)")
        }
    }

}
```

taken from: https://rambo.codes/posts/2019-12-09-clearing-your-apps-launch-screen-cache-on-ios

**Comment by zoontek** [comment]
@aprilmintacpineda That doesn't happen in production since your app is packaged in release mode + you have to bump the build number to create an update.

**Comment by aprilmintacpineda** [comment]
Ahhh I see, thank you very much for the help! :bow:

**Comment by alifsis** [comment]
try this command: 

npx react-native generate-bootsplash ./src/assets/bootsplash_logo_original.png --logo-width=230
