### ISSUE TITLE
use my custom layout ,but  it don't work and  still show bootsplash.xml

### ISSUE THREAD

**Issue by shadow-boy** [zoontek/react-native-bootsplash#78]
RNBootSplash.init(R.layout.launch_screen, MainActivity.this);

**Comment by ikotsov** [comment]
Will this work?

Is there an answer to this question, why has the issue been closed?

I tried it too without success. Is this supported by the package?

Thank you!

**Comment by zoontek** [comment]
@ikotsov Because this is not an issue, just a line of code.

**Comment by ikotsov** [comment]
Ohh, thank you for the immediate response!

Is there a way to render a `layout.xml` as a splash screen and not a resource? In case someone wants to include both a background resource and a logo, that would be really helpful!

Suppose you have two resources in drawable and want to use them both in the splash screen.

Thank you for this package by the way! Great work 👌

**Comment by zoontek** [comment]
@ikotsov No, it's not possible (on Android - it could be on iOS). Android 12 will have a splash screen API which is very similar to what this library can offer: A color, a logo, an exit animation. Check it: https://developer.android.com/about/versions/12/features/splash-screen

Don't overthink splash screens, keep it as short as possible and don't put too much informations on it 🙂
