### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNBootSplash.hide') / Class RNBootSplash was not exported

### ISSUE THREAD

**Issue by OlegWock** [zoontek/react-native-bootsplash#80]
### 💻 My environment

- react-native-bootsplash version: 2.1.0
- react-native version:0.58.6
- Platform: ios
- OS version: Mac os x 
- Device: iphone 8
- Simulator: yes
- Xcode version: 11.0

### 🕵️‍♂️ Reproducing the issue

Tried to setup bootsplash for ios. I faced some errors, but it might be related to old rn version. I was managed to fix them and run module, did everything according to README and bootsplash is showing. However, I'm unable to hide it and I see these logs in XCode (filtered):

```
2020-03-24 16:56:31.255 [info][tid:main][RCTBridge.m:134] Class RNBootSplash was not exported. Did you forget to use RCT_EXPORT_MODULE()?
2020-03-24 16:56:31.254942+0200 MyModule[5659:12880777] Class RNBootSplash was not exported. Did you forget to use RCT_EXPORT_MODULE()?

TypeError: null is not an object (evaluating 'RNBootSplash.hide')
TypeError: null is not an object (evaluating 'RNBootSplash.hide')
```
Also tried steps proposed there #30, but without success 

### 🤞Solution

I tried to take a look myself, but without any success :( 
I see that RCT_EXPORT_MODULE() macro is present, but RN seems to ignore it somehow

**Comment by zoontek** [comment]
This module does not support React Native < 0.60. See https://github.com/zoontek/react-native-bootsplash#support

**Comment by OlegWock** [comment]
Oh, sorry, I didn't noticed this :(

> For 0.59-, you should use `jetify -r`

But jetify is for Android, isn't it? Android version of app works like clockwork

**Comment by zoontek** [comment]
Jetify is for Android only yes. It's more about "this package has not been tested on RN under 0.60 / will not be fixed / maintained for these versions" 😕

**Comment by OlegWock** [comment]
Ah, got it. Thanks for your help :)
