### ISSUE TITLE
Can't integrate with RNN on iOS

### ISSUE THREAD

**Issue by hannojg** [zoontek/react-native-bootsplash#81]
### 💻 My environment

- react-native-bootsplash version:  2.1.0
- react-native version: 0.61.5
- Platform: ios
- OS version: 13.4.99 
- Device: iPhone 11
- Simulator: yes
- Android Studio version: not relevant
- Android buildToolsVersion: not relevant
- Xcode version: 11.4

### 🕵️‍♂️ Reproducing the issue

I am trying to implement this library and I am using in my react-native project wix's react-native-navigation. 
The setup on android worked, but I can't get it working for iOS. 
Your documentation proposes the following:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // …
  rootViewController.view = rootView;
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // <- initialization using the storyboard file name

  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  return YES;
}
```

but the `AppDelegate.m` on iOS after setting up RNN looks like this:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions];
  
//  [RNBootSplash initWithStoryboard:@"BootSplash" rootView: rootViewController.view];

//  [self.window makeKeyAndVisible];

  return YES;
}
```

I don't see (or tobe honest understand), how I can now get a rootView for passing it to RNBootSplash. 

Any guidance or help is greatly appreciated. Thank you so much!

**Comment by zoontek** [comment]
You can't use this package with RNN since it does not use `RCTRootView`. I looked a bit in the source code and see: https://github.com/wix/react-native-navigation/blob/master/lib/ios/ReactNativeNavigation.m#L73

If it's called, it will display the storyboard defined in your `info.plist`: https://github.com/wix/react-native-navigation/blob/master/lib/ios/RNNSplashScreen.m#L13

**Comment by hannojg** [comment]
Thank you so much for having looked up this information!
This behaviour is actually fine for me, as it will now open my beautiful bootsplash storyboard. I am doing all the initalization stuff before I actually load the first page with RNN (setting root). This way everything works like it should.

**Comment by Nirib13** [comment]
Hi @hannojg 
can i know how you solved?
It doesn't work for me.

**Comment by zabojad** [comment]
I'm having the same problem.

The splash storyboard is displayed but then how ti hide it? The call to `RNBootSplash.hide()` won't work...

**Comment by zoontek** [comment]
@zabojad That's not an issue with this lib, I can't do anything without RNN changes.

**Comment by zainspresso** [comment]
> Thank you so much for having looked up this information! This behaviour is actually fine for me, as it will now open my beautiful bootsplash storyboard. I am doing all the initalization stuff before I actually load the first page with RNN (setting root). This way everything works like it should.

Can you share how you managed to do this?
