### ISSUE TITLE
Pictures could not cover the whole screen

### ISSUE THREAD

**Issue by ysuMgl** [zoontek/react-native-bootsplash#82]
### 💻 My environment

- react-native-bootsplash version:2.1.0
- react-native version:0.61.5
- Platform: ios 
- OS version: 10.14
- Device: Apple + iphonex
- Simulator: yes

### 🕵️‍♂️ Reproducing the issue

I tried to generate pictures, but when I started the app, the picture was very small on the screen and could not cover the whole screen, just like the picture below. In Xcode, I opened the storeboard file and found that in the preview interface, the picture did not fill the screen. I selected scale to fill in the content mode. The preview interface is indeed full, but it is still the same when running. Sorry, I'm the first time to develop IOS. I don't know a lot of things. I haven't worked with native IOS, and I'm not familiar with Xcode. I wonder if the resolution of the generated image is too small to cover the screen. My bootsplash_logo_original.png image resolution is 1125 * 2436, and the resolution of the generated images are also in the following image. Or if I'm missing something. Hope to get your guidance, thank you!

![QQ20200327-161312.png](https://i.loli.net/2020/03/27/BQ7OXZjdm89Wnki.png)

![QQ20200327-162737.png](https://i.loli.net/2020/03/27/PKSCRU2ndpTeLO6.png)

### 🤞Solution

Not very clear. It should be a configuration problem.

**Comment by zoontek** [comment]
I suggest reading this guide: https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/WorkingwithConstraintsinInterfaceBuidler.html

Define the correct constraints, then switch devices as preview frames to check that they are set correctly.

**Comment by zoontek** [comment]
@ysuMgl Did you succeed?

**Comment by ysuMgl** [comment]
> @ysuMgl Did you succeed?

Sorry，I haven't solved it，I am new at this area and I can't make sense what you hava recommended.
May I take the liberty of asking you where can I find video tutorials about your project or have you ever put your video tutorials on youtube or other websites so that I can learn it deeply.

**Comment by zoontek** [comment]
This has nothing to do with this library in particular. I suggest to search tutorial about Storyboard layouting in general (like [this one](https://www.raywenderlich.com/1343912-adaptive-layout-tutorial-in-ios-12-getting-started)).

Depending on what you want to achieve, rules and constraints will change.

A quick example (I wanted to stuck the image to top, left, bottom and to scale to aspect fit. Then I set the background color to black). It works properly on all device sizes:

<img width="645" alt="Screenshot 2020-04-13 at 19 06 00" src="https://user-images.githubusercontent.com/1902323/79141647-88290480-7dba-11ea-94e9-c9edea25fdf8.png">

<img width="694" alt="Screenshot 2020-04-13 at 19 06 40" src="https://user-images.githubusercontent.com/1902323/79141652-8b23f500-7dba-11ea-897f-fdcd32563d76.png">

**Comment by AugustoAleGon** [comment]
@zoontek you save my day man!
