### ISSUE TITLE
Automate adding BootSplash.storyboard to Xcode

### ISSUE THREAD

**Issue by rhdeck** [zoontek/react-native-bootsplash#85]
Right now one needs to follow instructions inside xcode to activate a bootsplash launchscreen. This is a slowdown for every new app .

### 🤞Solution

Automate adding the storyboard to the project, and setting it as the launch screen as part of the CLI! Now one does not have to open Xcode at all to have their bootsplash work in a new project. 

Addressed in PR #84

**Comment by zoontek** [comment]
I replied here: https://github.com/zoontek/react-native-bootsplash/pull/84/files/6c497b7256326609bff4e996810af3d26701450d#r403085694
