### ISSUE TITLE
Automate support for dark mode in iOS

### ISSUE THREAD

**Issue by rhdeck** [zoontek/react-native-bootsplash#86]
For IOS: Storyboards use Xcode image and color assets, which as of Xcode 11 contain metadata to point to different underlying bitmaps and color codes respectively. By setting up the assets to use both light mode and dark mode we can support a seamless integration of darkmode. 

I would further suggest that we use system colors by default - instead of #fff background color, we use the systemBackground color that switches on iOS between white and black based on dark mode. Combine with a transparent PNG for super-easy bootsplash magic. 

For Android: This is even easier - just creating similar resources under values-night (for the color) and drawable-night (for the alternative icon - we should not be using mipmap!) will solve the problem. 

I can and will PR this, but since it affects the templates in generate.js, I am holding off for approval/merge of PR #84 which changes the file structure.

**Comment by zoontek** [comment]
Hi @rhdeck 

I love the idea. One small point bugs me:

> I would further suggest that we use system colors by default - instead of #fff background color, we use the systemBackground color that switches on iOS between white and black based on dark mode.

To ensure consistency across systems (iOS and Android), it might be better to ask for a light background color and a dark background color.

Maybe we could use different defaults than `#fff` and `#000` (hardcode default iOS values, apply the same colors on Android?), but it's not a priority IMHO if we can adjust the color really quickly by re-running the CLI.

**Comment by rhdeck** [comment]
The technical impact of this question is minor enough that showing in a PR is probably the best way to support that decision. Will submit when I have it working right on my end.

**Comment by rhdeck** [comment]
I made a pass at this at https://github.com/rhdeck/react-native-bootsplash/tree/dark. Addable via `yarn add rhdeck/react-native-bootsplash#dark`. I gotta say it's pretty slick to see the results. 

I have not PR'd it because I discovered an issue I'd wish discussed. In order to support a dynamic background in the launch storyboard (e.g. for light/dark mode support) we need to use a named color - a new feature in iOS 11. This is relatively easy to fix: [react-native-fix-ios-version](https://github.com/rhdeck/react-native-fix-ios-version) does this with a single command. But it would mean the bootsplash code is no longer compatible with a "vanilla" iOS app, since the `react-native init` template is for iOS 9.0. 

What do you think? Is this all hyper-different enough that I should just fork into another package, or is this still a PR?

**Comment by zoontek** [comment]
I would rather having a different package, bumping the target minimum version is a no go for us 😕

**Comment by rhdeck** [comment]
You got it. Since the prereq for this feature is incompatible with the package, will close the issue.
