### ISSUE TITLE
Can we have different storyboard per scheme/configuration?

### ISSUE THREAD

**Issue by afilp** [zoontek/react-native-bootsplash#87]
Hello, 

I create 3 different white-label apps using 3 different configurations and schemes.

I cannot find how to link to a different LaunchScreen.storyboard per scheme (configuration), so that when I run/archive the project the proper launch screen appears. So you provide for this?

Thank you.

### 💻 My environment

- react-native-bootsplash version:  2.1.0
- react-native version:  0.61.2
- Platform: both
- OS version: ?
- Device: any
- Simulator: no
- Android Studio version: ?
- Android buildToolsVersion: ?
- Xcode version: 11.3.1

### 🕵️‍♂️ Reproducing the issue

I cannot find how to link to a different LaunchScreen.storyboard per scheme (configuration).

**Comment by zoontek** [comment]
Create an Info.plist for each Scheme, then set a different `UILaunchStoryboardName` in each.
I'm closing this, it's not an issue.

<img width="918" alt="Screenshot 2020-04-02 at 00 42 59" src="https://user-images.githubusercontent.com/1902323/78193718-77ec5d80-747b-11ea-839a-10e2b41991cf.png">

<img width="748" alt="Screenshot 2020-04-02 at 00 42 25" src="https://user-images.githubusercontent.com/1902323/78193673-5ab78f00-747b-11ea-936e-3cbcc58ab7bc.png">

**Comment by afilp** [comment]
@zoontek Thank you for your prior answer.

I am not sure if this now applies with `Bootsplash.storyboard` that is selected through `AppDelegate.m`.

Any ideas on this? Maybe through a script we could rename each file `Bootsplash.myschemevariant.storyboard` to `Bootsplash.sotryboard` at building phase?

Thanks!

**Comment by zoontek** [comment]
@afilp 

1. Create multiple plist files (one per scheme)
2. Set a different value for `UILaunchStoryboardName` in each of them (mandatory)
3. Get the value in your `AppDelegate.m`, init the lib with the file name.

```objc
[RNBootSplash initWithStoryboard:[[[NSBundle mainBundle] infoDictionary] valueForKey:@"UILaunchStoryboardName"] rootView:rootView];
```

No need for specific features in this library, this is pretty standard iOS development.

**Comment by afilp** [comment]
Thanks @zoontek!

Please note that most react-native developers don't know iOS (or Android) development (just the very basics in XCode), this is why they choose to use react-native instead. Your info on such edge cases are strongly appreciated! Thanks again!

P.S. I use many other react-native packages, this will be the only one that will require me to have a different `info.plist`. From what I see, I am using a single `info.plist` and then different "User Defined Setting" variables to differentiate values among different schemes (like BundleId, DisplayName, CodePushDeploymentKey, etc.). Maybe this would be an appropriate method here too.

**Comment by zoontek** [comment]
User Defined Setting should work too, indeed

**Comment by devethan** [comment]
> User Defined Setting should work too, indeed

Yeah, I also did like this way

1. With User Defined, define LaunchScreen each of scheme
<img width="502" alt="Screenshot 2023-11-01 at 15 24 16" src="https://github.com/zoontek/react-native-bootsplash/assets/55861805/4464b098-64bb-418f-a431-275f8915180d">


2. `UILaunchStoryboardName` connect to `LAUNCH_SCREEN`
<img width="541" alt="Screenshot 2023-11-01 at 15 24 54" src="https://github.com/zoontek/react-native-bootsplash/assets/55861805/a3d36dfe-c11c-4f50-b7fc-5cd212f2e6ee">

3. Edit `AppDelegate.mm` like [this way](https://github.com/zoontek/react-native-bootsplash/issues/87#issuecomment-782099476)

**Comment by andlomonaco** [comment]
> > User Defined Setting should work too, indeed
> 
> Yeah, I also did like this way
> 
> 1. With User Defined, define `LAUNCH_SCREEN` each of scheme
> 
> <img alt="Screenshot 2023-11-01 at 15 24 16" width="502" src="https://user-images.githubusercontent.com/55861805/279593092-4464b098-64bb-418f-a431-275f8915180d.png">
> 2. `UILaunchStoryboardName` connect to `LAUNCH_SCREEN`
> 
> <img alt="Screenshot 2023-11-01 at 15 24 54" width="541" src="https://user-images.githubusercontent.com/55861805/279593209-a3d36dfe-c11c-4f50-b7fc-5cd212f2e6ee.png">
> 3. Edit `AppDelegate.mm` like [this way](https://github.com/zoontek/react-native-bootsplash/issues/87#issuecomment-782099476)

It's working for the first scheme, but not for the second one. I just pasted in AppDeleget.m and followed other steps
`[RNBootSplash initWithStoryboard:[[[NSBundle mainBundle] infoDictionary] valueForKey:@"UILaunchStoryboardName"] rootView:rootView];`

in the second scheme app crashes
