### ISSUE TITLE
LaunchScreen.xib image briefly shown at boot after upgrade to storyboard

### ISSUE THREAD

**Issue by jamesholcomb** [zoontek/react-native-bootsplash#88]
### 💻 My environment

- react-native-bootsplash version: 2.1.0
- react-native version: 0.59.10
- Platform: ios / android / both iOS
- OS version: ? 13.3
- Device: brand + model iPhone 
- Simulator: yes / no both
- Android Studio version: ?
- Android buildToolsVersion: ?
- Xcode version: 11.3.1

### 🕵️‍♂️ Reproducing the issue

My previous config used bootsplash 1.2.1 and LaunchScreen.xib file.  I upgraded to 2.1.0 following the README with CLI, removed LaunchScreen.xib file and ref in xcode, rebuilt from clean and deployed.

This works great, but on boot, the boot image briefly shows what appears to be the older xib image before being replaced by the new storyboard image.  The xib used a slightly larger app icon.  I used the default icon 100 width during upgrade (which I would like to keep).

If I delete the app on device/simulator, then redeploy, the issue goes away.

I wonder if this may be an iOS issue but wanted to see if anyone has experienced this.

Thank you for this excellent component.

**Comment by zoontek** [comment]
This is a caching issue. I already encounter it too. Follow this procedure: https://stackoverflow.com/a/35783070

(+ You can delete your `DerivedData` folder before rebuilding)

**Comment by jamesholcomb** [comment]
Thanks @zoontek
