### ISSUE TITLE
Could not find a storyboard named 'BootSplash' in bundle NSBundle 

### ISSUE THREAD

**Issue by drb1** [zoontek/react-native-bootsplash#92]
### 💻 My environment

- react-native-bootsplash version:2.2.0
- react-native version:0.61.5
- Platform: ios 
- OS version: 13.4
- Device: iphone 11 Pro Max
- Simulator: yes
- Android Studio version: ?
- Android buildToolsVersion: ?
- Xcode version: 11.4

### 🕵️‍♂️ Reproducing the issue

I followed every steps as mentioned in docs,but while launching app in ios app crashes generating the error:-

Exception	NSException *	"Could not find a storyboard named 'BootSplash' in bundle NSBundle </Users/drb/Library/Developer/CoreSimulator/Devices/1856793E-70B8-4BEC-9D34-607809F20AAC/data/Containers/Bundle/Application/A2FB88ED-27B3-4B44-A743-DACC33CECCBD/Example.app> (loaded)"	0x000060000213c8d0

**Comment by zoontek** [comment]
You didn't drag and drop the storyboard file / set it as LaunchScreen: https://github.com/zoontek/react-native-bootsplash/blob/master/README.md#ios-1

![890D21B2-4232-4A88-94D0-E5AAC86DAAC6](https://user-images.githubusercontent.com/1902323/79106347-9bb07d00-7d72-11ea-8469-cc735655e48d.jpeg)

**Comment by drb1** [comment]
i have done it 
![Screen Shot 2020-04-13 at 20 57 09](https://user-images.githubusercontent.com/14246236/79132201-9a5e6f00-7dc9-11ea-9032-840cdf342444.png)
![Screen Shot 2020-04-13 at 20 57 23](https://user-images.githubusercontent.com/14246236/79132213-a1857d00-7dc9-11ea-938f-aa996f929047.png)

**Comment by zoontek** [comment]
Your Launch Screen file is empty on the screenshot. Can you check it's correctly added to your target (it should be if you kept [this checkbox](https://raw.githubusercontent.com/zoontek/react-native-bootsplash/master/docs/xcode-2.png?raw=true) ticked)?

<img width="1229" alt="Screenshot 2020-04-13 at 17 17 28" src="https://user-images.githubusercontent.com/1902323/79132667-07aed780-7dab-11ea-8610-da0301db0f01.png">

**Comment by drb1** [comment]
Copy Bundle Resources does not exists
![Screen Shot 2020-04-13 at 21 12 54](https://user-images.githubusercontent.com/14246236/79133914-8cf6b400-7dcc-11ea-9608-89f035516c97.png)
![Screen Shot 2020-04-13 at 21 18 45](https://user-images.githubusercontent.com/14246236/79133928-92ec9500-7dcc-11ea-9205-1857628d5c30.png)

**Comment by zoontek** [comment]
It is by default when you create a React Native project. Add it back, like this, then add `BootSplash.storyboard` in the list:

<img width="845" alt="Screenshot 2020-04-13 at 18 31 42" src="https://user-images.githubusercontent.com/1902323/79138638-23b77680-7db5-11ea-8ac3-0d297ec47eb9.png">

**Comment by drb1** [comment]
Okay managed to launch storyboard but while refreshing app launch screen does not goes off .
![Screen Shot 2020-04-13 at 22 42 10](https://user-images.githubusercontent.com/14246236/79140679-12339600-7dd8-11ea-98cf-8893ae931eb7.png)

P.S I have called RNBootSplash.hide(); function in componentDidMount lifecycle.

**Comment by zoontek** [comment]
@drb1 Did you use version `2.2.0`? Update to the latest, it has been fixed.

**Comment by drb1** [comment]
Thank You So Much.Problem Has Been Solved.
