### ISSUE TITLE
Regression in 2.2.0: Splash screen not dismissed after refreshing app

### ISSUE THREAD

**Issue by kamui545** [zoontek/react-native-bootsplash#93]
Hello,

I just upgraded my package from 2.1.0 to 2.2.0 and noticed a regression.
After refreshing the app (CMD + R), the splash screen is displayed correctly but not dismissed.

### 💻 My environment

- react-native-bootsplash version: 2.2.0
- react-native version: 0.62.2
- Platform: ios
- OS version: 13.4
- Simulator: yes
- Xcode version: 11.4

### 🕵️‍♂️ Reproducing the issue

1. Launch app, splash screen is displayed then dismissed properly.
2. Hit CMD + R, see splash screen, but it is stuck and not dismissed.

I downgraded back to 2.1.0 and can confirm that it is working as intended, any idea?

**Comment by zoontek** [comment]
@kamui545 Hi! Sorry, I see what it is, and forgot to push something. I will release a fix ASAP.

**Comment by kamui545** [comment]
No worries, thanks for the blazing fast reply!

**Comment by zoontek** [comment]
@kamui545 The fix is [published](https://github.com/zoontek/react-native-bootsplash/releases/tag/2.2.1)! Enjoy 🙂

**Comment by kamui545** [comment]
Works like a charm 👌Thanks!
