### ISSUE TITLE
cannot find module prompts

### ISSUE THREAD

**Issue by R-D-P** [zoontek/react-native-bootsplash#94]
### 💻 My environment

- react-native-bootsplash version: 2.2.1
- react-native version: 0.62.0
- Platform:  both
- OS version: mac os 10.15.4
- Device: macbook pro
- Simulator: no 

### 🕵️‍♂️ Reproducing the issue

The following error occurs as soon as I run npx generate-bootsplash

Cannot find module 'prompts'
Require stack:
- /Users/russellphillips/Documents/Projects/the-memoire-app/memoire-frontend/node_modules/react-native-bootsplash/scripts/generate.js

**Comment by zoontek** [comment]
Which command did you used to install your dependencies?

**Comment by R-D-P** [comment]
I used npm install --save react-native-bootsplash
Does that answer the question, or did I have to do something more. :)

**Comment by zoontek** [comment]
Yes. For some reason, `npm` didn't install the `devDependencies`. It's supposed to happen only in production mode (`npm install --only=production`)

**Comment by zoontek** [comment]
No it's the opposite: `npm` did this without setting the --only=production flag. Did you set NODE_ENV to production? Or maybe you have a global npm config that does that?

**Comment by R-D-P** [comment]
I did no such thing intentionally i'm afraid.

**Comment by zoontek** [comment]
I will move the CLI dependencies from `devDependencies` to `dependencies` to prevent this kind of issues.

**Comment by zoontek** [comment]
Try to do this: https://stackoverflow.com/a/44655805

**Comment by R-D-P** [comment]
I unset the noe env
still seem to get the same error

**Comment by zoontek** [comment]
I made a quick release, it should fix it. https://github.com/zoontek/react-native-bootsplash/releases/tag/2.2.2

**Comment by R-D-P** [comment]
Thanks a lot, I ended up using yarn instead though. :D
