### ISSUE TITLE
App Stuck on boot screen when reloading the javascript bundle.

### ISSUE THREAD

**Issue by iWaleedibrahim** [zoontek/react-native-bootsplash#96]
### 💻 My environment

- react-native-bootsplash version: 2.2.0
- react-native version: 0.61.5
- Platform: ios 
- Simulator: yes
- Xcode version: 11.2.1

### 🕵️‍♂️ Reproducing the issue

SplashScreen hides as expected on first launch, when  reloading the js bundle app stuck on splash screen.

**Comment by zoontek** [comment]
Update to the latest version, it has been fixed
