### ISSUE TITLE
Splash Icon size change bug in iOS

### ISSUE THREAD

**Issue by AndriiBoiko** [zoontek/react-native-bootsplash#97]
Hi !! 

💻 My environment
  "react-native-bootsplash": "^2.2.2",
    "react-native": "0.62.2",
Platform: ios
OS version: 13
Simulator: yes 
Xcode version: 11.4

🕵️‍♂️ Reproducing the issue

I set size 200 (not 100)
and got the same issue  - https://github.com/zoontek/react-native-bootsplash/issues/77
PS did with a CLI
<img width="795" alt="Screenshot 2020-04-15 at 14 51 49" src="https://user-images.githubusercontent.com/50368724/79334407-ebd14000-7f28-11ea-97a5-851ccedd4f70.png">
🤞Solution
???

**Comment by zoontek** [comment]
@AndriiBoiko First, hello? Second: [issue templates](https://github.com/zoontek/react-native-bootsplash/blob/master/.github/ISSUE_TEMPLATE.md) exists for a reason.

**Comment by zoontek** [comment]
Clean your build, delete the Xcode cache (`DerivedData` etc).

**Comment by AndriiBoiko** [comment]
Sorrry )) fixed ))

**Comment by AndriiBoiko** [comment]
did all that you said - nothing
the same behaviour

**Comment by imadityadi** [comment]
how to change icon size  splash screen

**Comment by zoontek** [comment]
@imadityadi https://github.com/zoontek/react-native-bootsplash#assets-generation

`--logo-width <width>        logo width at @1x (in dp - we recommand approximately ~100) (default: 100)`

**Comment by anastely** [comment]
@zoontek At first time i set width `100` now I want to change it to let's say `400`, after running the command nothing changed! and I see the old width `100`, How can I fix this?
Thanks

**Comment by alifsis** [comment]
@anastely try this command npx react-native generate-bootsplash ./src/assets/bootsplash_logo_original.png --logo-width=230

230 or 200

**Comment by chenweigh** [comment]
Same Problem + 1

after change the bootsplash_logo ,  the last bootsplash_logo content is displayed  at each boot.

**Comment by zoontek** [comment]
@chenweigh That's an known issue with iOS cache https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update

**Comment by chanphiromsok** [comment]
I DELETE filename like below at IOS `Images.xcassets > BootSplashLogoImage > Content.json`
my problem is solved when I load screen I con size change
<img width="1156" alt="Screen Shot 2023-09-24 at 11 14 01 PM" src="https://github.com/zoontek/react-native-bootsplash/assets/65760336/0e206d42-6676-4c33-9d76-c0e57b07380e">
