### ISSUE TITLE
iOS splash devices

### ISSUE THREAD

**Issue by mezalejandro** [zoontek/react-native-bootsplash#99]
Hello,
I have images for all devices but it always shows me the first image loaded in Images.xcassets, for example I try with an ipad it does not show me the image for ipad

### 💻 My environment

- react-native-bootsplash version: 2.1.0
- react-native version: 0.61.5
- Platform: ios 
- Simulator: yes 
- Xcode version: 11.4

Thanks

**Comment by zoontek** [comment]
@mezalejandro Did you used the CLI? You need to create a storyboard file per device for that.
